"""Keras 3 training-script template (rendered by ``training.generate``)."""

KERAS_HEADER = r'''"""{{ spec.name }} — Keras 3 training script generated by AI Made Easy.

Task:   {{ task_label }}
Data:   {{ comment }}
Model:  {{ spec.name }}{% if total_params %} ({{ total_params }} trainable parameters){% endif %}

Run:    python {{ filename }}   (any Keras 3 backend: TensorFlow, JAX or PyTorch)
Needs:  {{ requirements }}
{% if spec.warnings %}

Notes:
{% for w in spec.warnings %}
  - {{ w }}
{% endfor %}
{% endif %}
"""
from __future__ import annotations

import json
import math
import time
from pathlib import Path

import keras
import numpy as np
from keras import layers
{% if uses_ops %}
from keras import ops
{% endif %}

# ================================================================ config
SEED = {{ spec.trainer.seed }}
EPOCHS = {{ spec.trainer.epochs }}
BATCH_SIZE = {{ spec.batch_size }}
EARLY_STOP = {{ spec.trainer.early_stopping_patience }}
GRAD_CLIP = {{ spec.trainer.grad_clip_norm }}
ACCUM_STEPS = {{ spec.trainer.accumulation_steps }}
MIXED_PRECISION = {{ spec.trainer.mixed_precision }}
LR0 = {{ spec.optimizer.lr }}
VAL_FRACTION = {{ spec.split.val_fraction }}
TEST_FRACTION = {{ spec.split.test_fraction }}
SPLIT_SEED = {{ spec.split.seed }}
INPUT_SHAPE = {{ input_shape_literal }}  # per sample, channels-first (as designed)
KERAS_TRANSPOSE = {{ keras_transpose }}  # channels-first -> the model's Keras layout
{% if spec.is_classification %}
NUM_CLASSES = {{ spec.num_outputs if spec.task != "binary" else 2 }}
{% endif %}
{% if timeseries %}
TARGET_SCALING = {{ target_scaling }}
{% endif %}
MODEL_FILE = "{{ spec.name }}_best.keras"
CLASS_NAMES = None
{% for helper in keras_helpers %}


{{ helper }}{% endfor %}


# ================================================================= model
def build_model() -> keras.Model:
    inputs = keras.Input(shape={{ keras_input_shape }}, dtype="{{ keras_input_dtype }}", name="input")
{% for n in nodes %}
    {{ n.keras_expr }}
{% endfor %}
    return keras.Model(inputs=inputs, outputs={{ keras_output_var }}, name="{{ spec.name }}")
'''

KERAS_TRAINING = r'''


# =============================================================== metrics
def to_scores(outputs: np.ndarray) -> np.ndarray:
{% if spec.task == "multiclass" %}
{% if loss_input == "log_probs" %}
    return np.exp(outputs)
{% elif loss_input == "probs" %}
    return outputs
{% else %}
    e = np.exp(outputs - outputs.max(axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)
{% endif %}
{% elif spec.task in ("binary", "multilabel") %}
{% if loss_input == "probs" %}
    return outputs.reshape(len(outputs), -1)
{% else %}
    return 1.0 / (1.0 + np.exp(-outputs.reshape(len(outputs), -1)))
{% endif %}
{% else %}
    return outputs
{% endif %}
{{ metrics_code }}


# ============================================================== training
def to_model_layout(x: np.ndarray) -> np.ndarray:
    return np.transpose(x, KERAS_TRANSPOSE) if KERAS_TRANSPOSE and len(x) else x


class EpochReport(keras.callbacks.Callback):
    """Prints one progress line per epoch with validation metrics."""

    def __init__(self, x_val: np.ndarray, y_val: np.ndarray) -> None:
        super().__init__()
        self.x_val, self.y_val, self.started = x_val, y_val, time.time()

    def on_epoch_begin(self, epoch, logs=None) -> None:
        self.started = time.time()

    def on_epoch_end(self, epoch, logs=None) -> None:
        logs = logs or {}
        metrics = {}
        if len(self.x_val):
            metrics = compute_metrics(self.model.predict(self.x_val, verbose=0), self.y_val)
        extra = " ".join(f"{k}={v:.4f}" for k, v in metrics.items() if isinstance(v, float))
        print(f"epoch {epoch + 1}/{EPOCHS} train_loss={logs.get('loss', float('nan')):.4f} "
              f"val_loss={logs.get('val_loss', float('nan')):.4f} {extra} "
              f"({time.time() - self.started:.1f}s)", flush=True)


def main() -> None:
    keras.utils.set_random_seed(SEED)
{% if spec.trainer.deterministic %}
    if keras.backend.backend() == "tensorflow":
        import tensorflow as tf

        tf.config.experimental.enable_op_determinism()
    elif keras.backend.backend() == "torch":
        import torch

        torch.use_deterministic_algorithms(True, warn_only=True)
{% endif %}
    if MIXED_PRECISION:
        keras.mixed_precision.set_global_policy("mixed_float16")
    arrays = make_arrays()
    (x_train, y_train), (x_val, y_val), (x_test, y_test) = (
        arrays["train"], arrays["val"], arrays["test"])
    x_train, x_val, x_test = map(to_model_layout, (x_train, x_val, x_test))
{% if balance == "oversample" %}
    counts = np.bincount(y_train.astype(int), minlength=NUM_CLASSES)
    rng = np.random.default_rng(SEED)
    picks = np.concatenate([rng.choice(np.flatnonzero(y_train == c), counts.max(), replace=True)
                            for c in range(NUM_CLASSES) if counts[c]])
    x_train, y_train = x_train[picks], y_train[picks]
{% endif %}
    print(f"samples: train={len(x_train)} val={len(x_val)} test={len(x_test)}")
{% if one_hot %}
    fit_y = keras.utils.to_categorical(y_train, NUM_CLASSES)
    val_y = keras.utils.to_categorical(y_val, NUM_CLASSES) if len(y_val) else y_val
{% else %}
    fit_y, val_y = y_train, y_val
{% endif %}

    model = build_model()
    print(f"parameters: {model.count_params():,}")
{% if augment %}
    augment = keras.Sequential([{{ augment | join(", ") }}], name="augment")
{% endif %}
{% if image_norm %}
    flat = x_train.reshape(-1, x_train.shape[-1])
    normalize = layers.Normalization(axis=-1, mean=flat.mean(axis=0), variance=flat.var(axis=0))
{% endif %}
{% if augment or image_norm %}
    raw = keras.Input(shape=x_train.shape[1:], name="image")
    head = {% if image_norm %}normalize({% endif %}{% if augment %}augment(raw){% else %}raw{% endif %}{% if image_norm %}){% endif %}

    train_model = keras.Model(raw, model(head), name="training_model")
{% if image_norm %}
    deploy_model = keras.Model(raw, model(normalize(raw)), name="{{ spec.name }}_deploy")
{% else %}
    deploy_model = model
{% endif %}
{% else %}
    train_model = deploy_model = model
{% endif %}
    optimizer = {{ optimizer_expr }}
    train_model.compile(optimizer=optimizer, loss={{ loss_expr }})
    callbacks = [EpochReport(x_val, y_val)]
    if EARLY_STOP:
        callbacks.append(keras.callbacks.EarlyStopping(
            monitor="val_loss" if len(x_val) else "loss", patience=EARLY_STOP,
            restore_best_weights=True))
{% if scheduler_callback %}
    callbacks.append({{ scheduler_callback }})
{% endif %}
{% if balance == "class weights" %}
    counts = np.bincount(y_train.astype(int), minlength=NUM_CLASSES)
    class_weight = {c: len(y_train) / (NUM_CLASSES * max(n, 1)) for c, n in enumerate(counts)}
{% endif %}
    train_model.fit(x_train, fit_y, validation_data=(x_val, val_y) if len(x_val) else None,
                    epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=callbacks, verbose=0{% if balance == "class weights" %},
                    class_weight=class_weight{% endif %})
    deploy_model.save(MODEL_FILE)
    print(f"saved model to {MODEL_FILE}")
    outputs = deploy_model.predict(x_test, verbose=0) if len(x_test) else np.zeros((0,))
    metrics = compute_metrics(outputs, y_test) if len(x_test) else {}
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items() if isinstance(v, float)))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))
{% if spec.predict %}
    print("\nprediction preview:")
    scores = to_scores(outputs)
    for i in range(min({{ spec.predict.n_samples }}, len(scores))):
{% if spec.task == "multiclass" %}
        top = np.argsort(scores[i])[::-1][:3]
        picks = ", ".join(f"{int(c)} ({scores[i][c]:.1%})" for c in top)
        print(f"  #{i}: actual {int(y_test[i])} -> {picks}")
{% else %}
        print(f"  #{i}: actual {np.round(y_test[i], 4)} -> predicted {np.round(scores[i], 4)}")
{% endif %}
{% endif %}
{% if spec.is_classification %}
    probs = to_scores(outputs)
{% if spec.task == "binary" %}
    probs = np.concatenate([1 - probs, probs], axis=1)
{% endif %}
    items = [{"index": i, "true": (y_test[i].tolist() if np.ndim(y_test[i]) else int(y_test[i])),
              "probs": [round(float(v), 4) for v in probs[i]], "file": None}
             for i in range(min(len(probs), 300))]
    Path("predictions.json").write_text(json.dumps(items, indent=1))
{% if spec.task != "multilabel" %}
    mistakes = [it for it in items if int(np.argmax(it["probs"])) != it["true"]]
    Path("mistakes.json").write_text(json.dumps(mistakes[:50], indent=1))
{% endif %}
    print(f"saved predictions.json ({len(items)} examples)")
{% endif %}


if __name__ == "__main__":
    main()
'''
