"""PyTorch training-script template (rendered by ``training.generate``)."""

TORCH_HEADER = r'''"""{{ spec.name }} — PyTorch training script generated by AI Made Easy.

Task:   {{ task_label }}
Data:   {{ comment }}
Model:  {{ spec.class_name }}{% if total_params %} ({{ total_params }} trainable parameters){% endif %}

Run:    python {{ filename }}
Needs:  {{ requirements }}
{% if spec.warnings %}

Notes:
{% for w in spec.warnings %}
  - {{ w }}
{% endfor %}
{% endif %}
"""
from __future__ import annotations

import json
import math
{% if inspect %}
import sys
{% endif %}
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
{% if uses_functional %}
import torch.nn.functional as F
{% endif %}
from torch.utils.data import DataLoader, Dataset
{% if torchvision_pipeline %}
from torchvision import datasets
from torchvision.transforms import v2
{% endif %}

# ================================================================ config
SEED = {{ spec.trainer.seed }}
DEVICE = "{{ spec.trainer.device }}"
EPOCHS = {{ spec.trainer.epochs }}
BATCH_SIZE = {{ spec.batch_size }}
EARLY_STOP = {{ spec.trainer.early_stopping_patience }}
GRAD_CLIP = {{ spec.trainer.grad_clip_norm }}
ACCUM_STEPS = {{ spec.trainer.accumulation_steps }}
MIXED_PRECISION = {{ spec.trainer.mixed_precision }}
VAL_FRACTION = {{ spec.split.val_fraction }}
TEST_FRACTION = {{ spec.split.test_fraction }}
SPLIT_SEED = {{ spec.split.seed }}
NUM_WORKERS = {{ spec.loader.num_workers }}
PIN_MEMORY = {{ spec.loader.pin_memory }}
DROP_LAST = {{ spec.loader.drop_last }}
INPUT_SHAPE = {{ input_shape_literal }}
{% if spec.is_classification %}
NUM_CLASSES = {{ spec.num_outputs if spec.task != "binary" else 2 }}
{% endif %}
{% if norm_fixed %}
NORM_MEAN = {{ norm_mean }}
NORM_STD = {{ norm_std }}
{% endif %}
{% if spec.kfold %}
K_FOLDS = {{ spec.kfold.k }}
STRATIFIED = {{ spec.kfold.stratified }}
KFOLD_SEED = {{ spec.kfold.seed }}
{% endif %}
{% if timeseries %}
TARGET_SCALING = {{ target_scaling }}
{% endif %}
CHECKPOINT = "{{ spec.name }}_best.pt"
CLASS_NAMES = None
{% for helper in torch_helpers %}


{{ helper }}{% endfor %}
{% if loss_helper == "FocalLoss" %}


class FocalLoss(nn.Module):
    """Focal cross-entropy (Lin et al., 2017)."""

    def __init__(self, gamma: float, alpha: float, weight: torch.Tensor | None = None) -> None:
        super().__init__()
        self.gamma, self.alpha, self.weight = gamma, alpha, weight

    def forward(self, logits: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        ce = F.cross_entropy(logits, target, weight=self.weight, reduction="none")
        loss = (1.0 - torch.exp(-ce)) ** self.gamma * ce
        return (self.alpha * loss if self.alpha else loss).mean()
{% endif %}


# ================================================================= model
class {{ spec.class_name }}(nn.Module):
    """(batch, {{ input_dims }}) -> (batch, {{ output_dims }})."""

    def __init__(self) -> None:
        super().__init__()
{% for m in modules %}
        {{ m.torch_module }}
{% endfor %}

    def forward(self, x: torch.Tensor) -> torch.Tensor:
{% for n in nodes %}
        {{ n.torch_expr }}
{% endfor %}
        return {{ output_var }}
'''

TORCH_IMAGE_DATA = r'''

# ================================================================== data
INFERENCE_STATE: dict = {}  # fitted preprocessing, saved with the model for serving


def build_transforms(train: bool, mean=None, std=None) -> v2.Compose:
    steps = [v2.ToImage()]
{% if image_channels_fix %}
    steps.append({{ image_channels_fix }})
{% endif %}
{% for t in image_always %}
    steps.extend([{{ t }}])
{% endfor %}
{% if image_resize_fix %}
    steps.append({{ image_resize_fix }})
{% endif %}
    if train:
{% for t in image_train %}
        steps.extend([{{ t }}])
{% endfor %}
{% if not image_train %}
        pass
{% endif %}
    steps.append(v2.ToDtype(torch.float32, scale=True))
{% for t in image_after_tensor %}
    if train:
        steps.extend([{{ t }}])
{% endfor %}
    if mean is not None:
        steps.append(v2.Normalize(mean, std))
    return v2.Compose(steps)


def image_datasets():
    """Raw (untransformed) datasets: (train pool, official test set or None)."""
{% if d.block == "data.torchvision" %}
    root = str(Path({{ d.data_dir | repr }}).expanduser())
{% if tv_split_kw == "split" %}
    return (datasets.{{ tv_class }}(root, split="train", download={{ d.download }}),
            datasets.{{ tv_class }}(root, split="test", download={{ d.download }}))
{% else %}
    return (datasets.{{ tv_class }}(root, train=True, download={{ d.download }}),
            datasets.{{ tv_class }}(root, train=False, download={{ d.download }}))
{% endif %}
{% else %}
    return datasets.ImageFolder({{ d.root | repr }}), None
{% endif %}


class TransformedSubset(Dataset):
    """A view of ``base`` restricted to ``indices`` with its own transform."""

    def __init__(self, base, indices, transform) -> None:
        self.base, self.indices, self.transform = base, list(indices), transform

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, i: int):
        image, label = self.base[self.indices[i]]
        return self.transform(image), label

    def source_file(self, i: int) -> str | None:
        samples = getattr(self.base, "samples", None)
        return samples[self.indices[i]][0] if samples else None
{% if norm_fit %}


def channel_stats(dataset, limit: int = 2000) -> tuple[list[float], list[float]]:
    """Per-channel mean/std estimated from training images (fit mode)."""
    probe = TransformedSubset(dataset.base, dataset.indices[:limit], build_transforms(train=False))
    total = squares = 0.0
    count = 0
    for xb, _ in DataLoader(probe, batch_size=256):
        total = total + xb.sum(dim=(0, 2, 3))
        squares = squares + (xb ** 2).sum(dim=(0, 2, 3))
        count += xb.numel() // xb.shape[1]
    mean = total / count
    return mean.tolist(), (squares / count - mean ** 2).clamp_min(1e-12).sqrt().tolist()
{% endif %}


def make_datasets():
    global CLASS_NAMES
    pool, official_test = image_datasets()
    CLASS_NAMES = list(getattr(pool, "classes", None) or []) or None
    idx = np.random.default_rng(SPLIT_SEED).permutation(len(pool))
    n_val = int(len(pool) * VAL_FRACTION)
{% if d.block == "data.torchvision" %}
    train_idx, val_idx, test_idx = idx[n_val:], idx[:n_val], None
{% else %}
    n_test = int(len(pool) * TEST_FRACTION)
    train_idx, val_idx, test_idx = idx[n_val + n_test:], idx[:n_val], idx[n_val:n_val + n_test]
{% endif %}
{% if norm_fixed %}
    mean, std = NORM_MEAN, NORM_STD
{% elif norm_fit %}
    mean, std = channel_stats(TransformedSubset(pool, train_idx, None))
{% else %}
    mean = std = None
{% endif %}
    INFERENCE_STATE["norm"] = (list(mean), list(std)) if mean is not None else None
    eval_tf = build_transforms(train=False, mean=mean, std=std)
    train = TransformedSubset(pool, train_idx, build_transforms(train=True, mean=mean, std=std))
    val = TransformedSubset(pool, val_idx, eval_tf)
    test = (TransformedSubset(official_test, range(len(official_test)), eval_tf)
            if official_test is not None else TransformedSubset(pool, test_idx, eval_tf))
    return train, val, test


def dataset_targets(ds: TransformedSubset) -> np.ndarray:
    targets = getattr(ds.base, "targets", None)
    if targets is None:
        targets = getattr(ds.base, "labels", None)
    if targets is None:
        targets = [ds.base[i][1] for i in range(len(ds.base))]
    return np.asarray(targets)[ds.indices]
'''

TORCH_ARRAY_LOADERS = r'''

class ArrayDataset(Dataset):
    """In-memory samples with an optional per-sample training transform."""

    def __init__(self, x: np.ndarray, y: np.ndarray, transform=None) -> None:
        self.x, self.y, self.transform = torch.from_numpy(x), torch.from_numpy(y), transform

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, i: int):
        x = self.x[i]
        return (self.transform(x) if self.transform else x), self.y[i]


def make_datasets():
    arrays = make_arrays()
{% if image_train or spec.steps.get("prep.spec_augment") %}
    train_tf = train_transform
{% else %}
    train_tf = None
{% endif %}
    return (ArrayDataset(*arrays["train"], transform=train_tf),
            ArrayDataset(*arrays["val"]), ArrayDataset(*arrays["test"]))


def dataset_targets(ds) -> np.ndarray:
    return ds.y.numpy()
{% if image_train %}


def train_transform(x: torch.Tensor) -> torch.Tensor:
    """Training augmentation applied per sample."""
    return TRAIN_AUGMENT(x)


TRAIN_AUGMENT = v2.Compose([{{ image_train | join(", ") }}])
{% elif spec.steps.get("prep.spec_augment") %}
{% set sa = spec.steps["prep.spec_augment"] %}


def train_transform(x: torch.Tensor) -> torch.Tensor:
    """SpecAugment: random frequency and time masks (training only)."""
    if torch.rand(()) > {{ sa.p }}:
        return x
    x = x.clone()
    _, n_freq, n_time = x.shape
    f = int(torch.randint(0, {{ sa.freq_mask }} + 1, ()))
    f0 = int(torch.randint(0, max(n_freq - f, 1), ()))
    x[:, f0:f0 + f, :] = 0
    t = int(torch.randint(0, {{ sa.time_mask }} + 1, ()))
    t0 = int(torch.randint(0, max(n_time - t, 1), ()))
    x[:, :, t0:t0 + t] = 0
    return x
{% endif %}
'''

TORCH_TRAINING = r'''

def make_loaders():
    train, val, test = make_datasets()
    generator = torch.Generator().manual_seed(SEED)
{% if balance == "oversample" %}
    labels = dataset_targets(train).astype(int)
    weights = 1.0 / np.bincount(labels, minlength=NUM_CLASSES).clip(min=1)
    sampler = torch.utils.data.WeightedRandomSampler(
        torch.as_tensor(weights[labels], dtype=torch.double), len(labels), generator=generator)
    train_loader = DataLoader(train, batch_size=BATCH_SIZE, sampler=sampler,
                              num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available(), drop_last=DROP_LAST)
{% else %}
    train_loader = DataLoader(train, batch_size=BATCH_SIZE, shuffle=True, generator=generator,
                              num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available(), drop_last=DROP_LAST)
{% endif %}
    eval_kw = dict(batch_size=BATCH_SIZE, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available())
    return train_loader, DataLoader(val, **eval_kw), DataLoader(test, **eval_kw)


# =============================================================== metrics
def to_scores(outputs: np.ndarray) -> np.ndarray:
    """Model outputs -> {{ "class probabilities" if spec.is_classification else "predictions" }}."""
{% if spec.task == "multiclass" %}
{% if loss_input == "log_probs" %}
    return np.exp(outputs)
{% elif loss_input == "probs" %}
    return outputs
{% else %}
    e = np.exp(outputs - outputs.max(axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)
{% endif %}
{% elif spec.task in ("binary", "multilabel") %}
{% if loss_input == "probs" %}
    return outputs.reshape(len(outputs), -1)
{% else %}
    return 1.0 / (1.0 + np.exp(-outputs.reshape(len(outputs), -1)))
{% endif %}
{% else %}
    return outputs
{% endif %}
{{ metrics_code }}


# ============================================================== training
def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def adapt(out: torch.Tensor, y: torch.Tensor):
    """Align output and target shapes for the loss."""
{% if spec.task == "binary" %}
    return out.reshape(-1), y.float().reshape(-1)
{% elif spec.task == "regression" %}
    if out.ndim == 2 and out.shape[1] == 1 and y.ndim == 1:
        out = out[:, 0]
    return out, y.float()
{% elif spec.task in ("multilabel", "distribution") %}
    return out, y.float()
{% else %}
    return out, (y if y.is_floating_point() else y.long())
{% endif %}


def make_loss(train_targets: np.ndarray | None = None):
{% if balance == "class weights" %}
    counts = np.bincount(np.asarray(train_targets).astype(int).reshape(-1), minlength=NUM_CLASSES)
    weight = torch.tensor(len(train_targets) / (NUM_CLASSES * counts.clip(min=1)), dtype=torch.float32)
{% if spec.task == "binary" %}
    return nn.BCEWithLogitsLoss(pos_weight=weight[1:2] / weight[0:1])
{% elif loss_helper == "FocalLoss" %}
    return FocalLoss(gamma={{ spec.loss.gamma }}, alpha={{ spec.loss.alpha }}, weight=weight)
{% else %}
    return nn.CrossEntropyLoss(weight=weight{% if spec.loss.label_smoothing %}, label_smoothing={{ spec.loss.label_smoothing }}{% endif %})
{% endif %}
{% else %}
    return {{ loss_expr }}
{% endif %}


@torch.no_grad()
def predict(model: nn.Module, loader: DataLoader, device: torch.device):
    model.eval()
    outs, ys = [], []
    for xb, yb in loader:
        outs.append(model(xb.to(device)).float().cpu())
        ys.append(yb)
    if not outs:
        return np.zeros((0,)), np.zeros((0,))
    return torch.cat(outs).numpy(), torch.cat(ys).numpy()


def evaluate(model: nn.Module, loss_fn, loader: DataLoader, device: torch.device):
    outputs, targets = predict(model, loader, device)
    if len(outputs) == 0:
        return float("nan"), {}
    with torch.no_grad():
        out_t, y_t = adapt(torch.from_numpy(outputs), torch.from_numpy(targets))
        loss = float(loss_fn(out_t, y_t))
    return loss, compute_metrics(outputs, targets)


def fit(model: nn.Module, train_loader, val_loader, device, log: bool = True):
    """Train with early stopping on validation loss; returns the best state."""
    loss_fn = make_loss({{ "dataset_targets(train_loader.dataset)" if balance == "class weights" else "" }})
    if hasattr(loss_fn, "to"):
        loss_fn = loss_fn.to(device)
    optimizer = {{ optimizer_expr }}
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% endif %}
{% if mixup %}
    mix = {{ mixup }}
{% endif %}
    use_amp = MIXED_PRECISION and device.type in ("cuda", "mps")
    amp_dtype = torch.float16 if device.type == "cuda" else torch.bfloat16
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp and device.type == "cuda")
    best_loss, best_state, bad_epochs = float("inf"), None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, running, seen = time.time(), 0.0, 0
        optimizer.zero_grad(set_to_none=True)
        for step, (xb, yb) in enumerate(train_loader, start=1):
            xb, yb = xb.to(device), yb.to(device)
{% if mixup %}
            xb, yb = mix(xb, yb)
{% endif %}
            with torch.autocast(device_type=device.type, dtype=amp_dtype, enabled=use_amp):
                out, target = adapt(model(xb), yb)
                loss = loss_fn(out, target)
            scaler.scale(loss / ACCUM_STEPS).backward()
            if step % ACCUM_STEPS == 0 or step == len(train_loader):
                if GRAD_CLIP > 0:
                    scaler.unscale_(optimizer)
                    nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
{% if scheduler_step == "batch" %}
                scheduler.step()
{% endif %}
            running += loss.item() * len(xb)
            seen += len(xb)
        train_loss = running / max(seen, 1)
        val_loss, val_metrics = evaluate(model, loss_fn, val_loader, device)
        monitored = val_loss if not math.isnan(val_loss) else train_loss
{% if scheduler_step == "epoch" %}
        scheduler.step()
{% elif scheduler_step == "metric" %}
        scheduler.step(monitored)
{% endif %}
        if log:
            extra = " ".join(f"{k}={v:.4f}" for k, v in val_metrics.items()
                             if isinstance(v, float))
            lr = optimizer.param_groups[0]["lr"]
            print(f"epoch {epoch}/{EPOCHS} train_loss={train_loss:.4f} val_loss={val_loss:.4f} "
                  f"{extra} lr={lr:.3g} ({time.time() - started:.1f}s)", flush=True)
        if monitored < best_loss:
            best_loss, bad_epochs = monitored, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad_epochs += 1
            if EARLY_STOP and bad_epochs >= EARLY_STOP:
                if log:
                    print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    return model, loss_fn
{% if spec.kfold %}


def cross_validate(device: torch.device) -> None:
    """K-fold cross-validation over the training and validation data."""
    arrays = make_arrays()
    x = np.concatenate([arrays["train"][0], arrays["val"][0]])
    y = np.concatenate([arrays["train"][1], arrays["val"][1]])
    rng = np.random.default_rng(KFOLD_SEED)
    fold = np.zeros(len(y), dtype=int)
    if STRATIFIED and y.ndim == 1 and len(np.unique(y)) < len(y) // 2:
        for c in np.unique(y):
            members = rng.permutation(np.flatnonzero(y == c))
            fold[members] = np.arange(len(members)) % K_FOLDS
    else:
        fold[rng.permutation(len(y))] = np.arange(len(y)) % K_FOLDS
    scores = []
    for k in range(K_FOLDS):
        tr, va = fold != k, fold == k
        train_loader = DataLoader(ArrayDataset(x[tr], y[tr]), batch_size=BATCH_SIZE, shuffle=True)
        val_loader = DataLoader(ArrayDataset(x[va], y[va]), batch_size=BATCH_SIZE)
        model, loss_fn = fit({{ spec.class_name }}().to(device), train_loader, val_loader,
                             device, log=False)
        val_loss, metrics = evaluate(model, loss_fn, val_loader, device)
        metrics = {"loss": val_loss, **metrics}
        scores.append(metrics)
        print(f"fold {k + 1}/{K_FOLDS}: " + " ".join(
            f"{m}={v:.4f}" for m, v in metrics.items() if isinstance(v, float)))
    for m in scores[0]:
        if isinstance(scores[0][m], float):
            vals = np.asarray([s[m] for s in scores])
            print(f"cv {m}: {vals.mean():.4f} ± {vals.std(ddof=1):.4f}")
{% endif %}
{% if spec.is_classification %}


def save_sample_png(t: torch.Tensor, path: str) -> None:
    from PIL import Image

    a = t.float().cpu().numpy()
    a = ((a - a.min()) / (a.max() - a.min() + 1e-9) * 255).astype("uint8")
    a = a[0] if a.shape[0] == 1 else np.transpose(a, (1, 2, 0))
    Image.fromarray(a).save(path)


def dump_test_results(model: nn.Module, loader: DataLoader, device: torch.device) -> None:
    """predictions.json / mistakes.json for error analysis (first 300 test samples)."""
    outputs, targets = predict(model, loader, device)
    probs = to_scores(outputs)
{% if spec.task == "binary" %}
    probs = np.concatenate([1 - probs, probs], axis=1)
{% endif %}
    items = []
    for i in range(min(len(probs), 300)):
        x, _ = loader.dataset[i]
        source = getattr(loader.dataset, "source_file", None)
        file = source(i) if source else None
        if file is None and x.ndim == 3 and x.shape[0] in (1, 3):
            Path("samples").mkdir(exist_ok=True)
            file = f"samples/{i}.png"
            save_sample_png(x, file)
        true = targets[i].tolist() if np.ndim(targets[i]) else int(targets[i])
        items.append({"index": i, "true": true,
                      "probs": [round(float(v), 4) for v in probs[i]], "file": file})
    Path("predictions.json").write_text(json.dumps(items, indent=1))
{% if spec.task != "multilabel" %}
    mistakes = [it for it in items if int(np.argmax(it["probs"])) != it["true"]]
    Path("mistakes.json").write_text(json.dumps(mistakes[:50], indent=1))
{% endif %}
    if CLASS_NAMES:
        Path("classes.json").write_text(json.dumps(list(CLASS_NAMES)))
    print(f"saved predictions.json ({len(items)} examples)")
{% endif %}
{% if spec.predict %}


def preview_predictions(model: nn.Module, loader: DataLoader, device: torch.device) -> None:
    outputs, targets = predict(model, loader, device)
    scores = to_scores(outputs)
    print("\nprediction preview:")
    for i in range(min({{ spec.predict.n_samples }}, len(scores))):
{% if spec.task == "multiclass" %}
        top = np.argsort(scores[i])[::-1][:3]
        name = lambda c: CLASS_NAMES[c] if CLASS_NAMES else str(c)
{% if spec.predict.show_probabilities %}
        picks = ", ".join(f"{name(int(c))} ({scores[i][c]:.1%})" for c in top)
        print(f"  #{i}: actual {name(int(targets[i]))} -> {picks}")
{% else %}
        print(f"  #{i}: actual {name(int(targets[i]))} -> predicted {name(int(top[0]))}")
{% endif %}
{% else %}
        print(f"  #{i}: actual {np.round(targets[i], 4)} -> predicted {np.round(scores[i], 4)}")
{% endif %}
{% endif %}
'''

TORCH_MAIN = r'''

def main() -> None:
    torch.manual_seed(SEED)
    np.random.seed(SEED)
{% if spec.trainer.deterministic %}
    torch.use_deterministic_algorithms(True, warn_only=True)
    torch.backends.cudnn.benchmark = False
{% endif %}
    device = pick_device()
    print(f"device: {device}")
{% if spec.kfold %}
    cross_validate(device)
    return
{% else %}
    train_loader, val_loader, test_loader = make_loaders()
    print(f"samples: train={len(train_loader.dataset)} val={len(val_loader.dataset)} "
          f"test={len(test_loader.dataset)}")
    model = {{ spec.class_name }}().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    model, loss_fn = fit(model, train_loader, val_loader, device)
    torch.save(model.state_dict(), CHECKPOINT)
    save_inference_state()
    print(f"saved best weights to {CHECKPOINT}")
    test_loss, test_metrics = evaluate(model, loss_fn, test_loader, device)
    report = {"loss": test_loss, **{k: v for k, v in test_metrics.items() if isinstance(v, float)}}
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in report.items()))
    Path("metrics.json").write_text(json.dumps(
        {k: v for k, v in {**report, **test_metrics}.items()
         if isinstance(v, (float, list))}, indent=1))
{% if spec.predict %}
    preview_predictions(model, test_loader, device)
{% endif %}
{% if spec.is_classification %}
    try:
        dump_test_results(model, test_loader, device)
    except Exception as exc:  # noqa: BLE001 — artefacts are optional
        print(f"(could not save predictions: {exc})")
{% endif %}
{% endif %}


if __name__ == "__main__":
    main()
'''
