"""scikit-learn pipeline script template."""

SKLEARN_TEMPLATE = r'''"""{{ spec.name }} — scikit-learn pipeline generated by AI Made Easy.

Task:      {{ task }}
Estimator: {{ est.name }} ({{ est.package }})
Run:       python {{ spec.name }}_train_sklearn.py
Needs:     {{ requirements }}
{% if spec.warnings %}

Notes:
{% for w in spec.warnings %}
  - {{ w }}
{% endfor %}
{% endif %}
"""
from __future__ import annotations

import json
import time
from pathlib import Path

import joblib
import numpy as np
{% if table or d.block in ("data.text_csv", "data.timeseries_csv") %}
import pandas as pd
{% endif %}
from sklearn import metrics
from sklearn.pipeline import Pipeline
{% for line in imports %}
{{ line }}
{% endfor %}

SEED = {{ spec.seed }}
TEST_FRACTION = {{ test_fraction }}
MODEL_FILE = "{{ spec.name }}_model.joblib"
{% if grid %}
PARAM_GRID = {
{% for k, values in grid.items() %}
    "{{ k }}": [{{ values | join(", ") }}],
{% endfor %}
}
{% endif %}
{% if text %}


def clean_text(text: str) -> str:
    import re

{% if clean.strip_html %}
    text = re.sub(r"<[^>]+>", " ", text)
{% endif %}
{% if clean.lowercase %}
    text = text.lower()
{% endif %}
{% if clean.strip_punctuation %}
    text = re.sub(r"[^\w\s]", " ", text)
{% endif %}
{% if clean.strip_digits %}
    text = re.sub(r"\d+", " ", text)
{% endif %}
    return re.sub(r"\s+", " ", text).strip()
{% endif %}
{% if spec.steps.get("prep.clip_outliers") %}


class OutlierClipper(TransformerMixin, BaseEstimator):
    """Clip features to bounds fitted on the training data."""

    def __init__(self, method: str = "iqr", threshold: float = 1.5) -> None:
        self.method, self.threshold = method, threshold

    def fit(self, X, y=None):
        X = np.asarray(X, dtype=float)
        if self.method == "iqr":
            q1, q3 = np.nanpercentile(X, [25, 75], axis=0)
            self.lo_, self.hi_ = q1 - self.threshold * (q3 - q1), q3 + self.threshold * (q3 - q1)
        elif self.method == "zscore":
            mu, sd = np.nanmean(X, axis=0), np.nanstd(X, axis=0)
            self.lo_, self.hi_ = mu - self.threshold * sd, mu + self.threshold * sd
        else:
            self.lo_, self.hi_ = np.nanquantile(X, [self.threshold, 1 - self.threshold], axis=0)
        return self

    def transform(self, X):
        return np.clip(np.asarray(X, dtype=float), self.lo_, self.hi_)

    def get_feature_names_out(self, input_features=None):
        return np.asarray(input_features) if input_features is not None else None
{% endif %}


def load_data():
    """Return (features, targets or None)."""
{% if d.block == "data.csv" %}
    readers = {"csv": pd.read_csv, "tsv": lambda p: pd.read_csv(p, sep="\t"),
               "parquet": pd.read_parquet, "excel": pd.read_excel,
               "json": lambda p: pd.read_json(p, lines=str(p).endswith(".jsonl"))}
    frame = readers[{{ d.format | repr }}]({{ d.path | repr }})
{% if drop_rows %}
    frame = frame.dropna()
{% endif %}
    target = {{ d.target_column | repr }}
    if target not in frame.columns:
        raise SystemExit(f"target column {target!r} not found; columns: {list(frame.columns)}")
    y = frame.pop(target)
{% if feature_columns %}
    frame = frame[{{ feature_columns | repr }}]
{% endif %}
{% if drop_columns %}
    frame = frame.drop(columns=[c for c in {{ drop_columns | repr }} if c in frame.columns])
{% endif %}
    return frame, y.to_numpy()
{% elif d.block == "data.sklearn" %}
    from sklearn import datasets

    X, y = datasets.{{ sk_loader }}(return_X_y=True, as_frame=True)
    return X, y.to_numpy()
{% elif d.block == "data.synthetic" %}
    from sklearn import datasets

{% if d.kind == "moons" %}
    return datasets.make_moons(n_samples={{ d.n_samples }}, noise={{ d.noise }}, random_state={{ d.seed }})
{% elif d.kind == "circles" %}
    return datasets.make_circles(n_samples={{ d.n_samples }}, noise={{ d.noise }}, factor=0.5,
                                 random_state={{ d.seed }})
{% elif d.kind == "regression" %}
    return datasets.make_regression(n_samples={{ d.n_samples }}, n_features={{ d.n_features }},
                                    noise={{ d.noise }} * 10, random_state={{ d.seed }})
{% elif task in ("clustering", "anomaly") %}
    return datasets.make_blobs(n_samples={{ d.n_samples }}, n_features={{ d.n_features }},
                               centers={{ d.n_classes }}, random_state={{ d.seed }})
{% else %}
    informative = min({{ d.n_features }}, max(2, int(np.ceil(np.log2({{ d.n_classes }}))) + 1))
    return datasets.make_classification(
        n_samples={{ d.n_samples }}, n_features={{ d.n_features }}, n_informative=informative,
        n_redundant=0, n_classes={{ d.n_classes }}, n_clusters_per_class=1,
        flip_y={{ d.noise }} / 10, random_state={{ d.seed }})
{% endif %}
{% elif d.block == "data.numpy" %}
    archive = np.load({{ d.path | repr }})
    X = archive[{{ d.x_key | repr }}]
    return X.reshape(len(X), -1), archive[{{ d.y_key | repr }}]
{% elif d.block == "data.json" %}
    text = Path({{ d.path | repr }}).read_text().strip()
    records = json.loads(text) if text.startswith("[") else [
        json.loads(line) for line in text.splitlines() if line.strip()]
    X = np.asarray([r[{{ d.x_field | repr }}] for r in records], dtype=float)
    return X.reshape(len(X), -1), np.asarray([r[{{ d.y_field | repr }}] for r in records])
{% elif d.block == "data.huggingface" %}
    from datasets import load_dataset

    ds = load_dataset({{ d.repo_id | repr }}, split={{ d.split | repr }})
    X = np.asarray([np.asarray(v, dtype=float).reshape(-1) for v in ds[{{ d.x_field | repr }}]])
    return X, np.asarray(ds[{{ d.y_field | repr }}])
{% elif d.block == "data.text_csv" %}
    readers = {"csv": pd.read_csv, "tsv": lambda p: pd.read_csv(p, sep="\t"),
               "parquet": pd.read_parquet, "json": lambda p: pd.read_json(p, lines=True)}
    frame = readers[{{ d.format | repr }}]({{ d.path | repr }})
    return (frame[{{ d.text_column | repr }}].fillna("").astype(str).tolist(),
            frame[{{ d.label_column | repr }}].to_numpy())
{% elif d.block == "data.text_folder" %}
    root = Path({{ d.root | repr }})
    texts, labels = [], []
    for folder in sorted(p for p in root.iterdir() if p.is_dir()):
        for file in sorted(folder.glob("*.txt")):
            texts.append(file.read_text(errors="ignore"))
            labels.append(folder.name)
    return texts, np.asarray(labels)
{% elif d.block == "data.image_folder" %}
    from PIL import Image

    root = Path({{ d.root | repr }})
    images, labels = [], []
    for folder in sorted(p for p in root.iterdir() if p.is_dir()):
        for file in sorted(folder.iterdir()):
            if file.suffix.lower() in (".png", ".jpg", ".jpeg", ".bmp", ".webp"):
                img = Image.open(file).convert("L" if {{ d.grayscale }} else "RGB")
                img = img.resize(({{ image_size }}, {{ image_size }}))
                images.append(np.asarray(img, dtype=np.float32).reshape(-1) / 255.0)
                labels.append(folder.name)
    return np.stack(images), np.asarray(labels)
{% elif d.block == "data.timeseries_csv" %}
    frame = pd.read_csv({{ d.path | repr }})
    targets = {{ ts_targets | repr }}
{% if feature_columns %}
    features = frame[{{ feature_columns | repr }}].to_numpy(float)
{% else %}
    features = frame.select_dtypes("number").to_numpy(float)
{% endif %}
    values = frame[targets].to_numpy(float)
    window, horizon, stride = {{ d.window }}, {{ d.horizon }}, {{ d.stride }}
    starts = range(0, len(frame) - window - horizon + 1, stride)
    X = np.stack([features[s:s + window].reshape(-1) for s in starts])
    y = np.stack([values[s + window:s + window + horizon].reshape(-1) for s in starts])
    return X, (y[:, 0] if y.shape[1] == 1 else y)
{% endif %}


def build_pipeline() -> Pipeline:
{% if table %}
    numeric = Pipeline([
{% for step in numeric_steps %}
        {{ step }},
{% endfor %}
    ])
    categorical = Pipeline([
        ("impute", SimpleImputer(strategy="most_frequent")),
        {{ categorical_step }},
    ])
    preprocess = ColumnTransformer([
        ("numeric", numeric, make_column_selector(dtype_include=np.number)),
        ("categorical", categorical, make_column_selector(dtype_exclude=np.number)),
    ])
{% endif %}
    return Pipeline([
{% if table %}
        ("preprocess", preprocess),
{% elif text %}
        ("vectorize", {{ vectorizer }}),
{% else %}
{% for step in numeric_steps %}
        {{ step }},
{% endfor %}
{% endif %}
{% for step in feature_steps %}
        {{ step }},
{% endfor %}
        ("model", {{ est_ctor }}),
    ])
{% if supervised %}


def predict_scores(model: Pipeline, X):
    """Class probabilities, or decision scores when probabilities are unavailable."""
{% if proba %}
    return model.predict_proba(X)
{% else %}
    scores = model.decision_function(X)
    return np.column_stack([-scores, scores]) if scores.ndim == 1 else scores
{% endif %}


def evaluate(model: Pipeline, X, y) -> dict:
    pred = model.predict(X)
    m = {}
{% if task == "classification" %}
    classes = list(model.classes_)
    binary = len(classes) == 2
    average = lambda requested: "binary" if binary else requested  # noqa: E731
    pos = {"pos_label": classes[-1]} if binary else {}
{% set needs_scores = metric_keys | select("in", ["roc_auc", "avg_precision", "log_loss", "top_k_accuracy"]) | list %}
{% if needs_scores %}
    scores = predict_scores(model, X)
{% endif %}
{% for key in metric_keys %}
{% set p = metric_params[key] %}
{% if key == "accuracy" %}
    m["accuracy"] = metrics.accuracy_score(y, pred)
{% elif key == "balanced_accuracy" %}
    m["balanced_accuracy"] = metrics.balanced_accuracy_score(y, pred)
{% elif key == "top_k_accuracy" %}
    m["top_k_accuracy"] = metrics.top_k_accuracy_score(y, scores, k=min({{ p.k }}, len(classes) - 1) or 1, labels=classes) if len(classes) > 2 else metrics.accuracy_score(y, pred)
{% elif key in ("precision", "recall", "f1") %}
    m["{{ key }}"] = metrics.{{ key }}_score(y, pred, average=average("{{ p.average }}"), zero_division=0, **pos)
{% elif key == "mcc" %}
    m["mcc"] = metrics.matthews_corrcoef(y, pred)
{% elif key == "kappa" %}
    m["kappa"] = metrics.cohen_kappa_score(y, pred)
{% elif key == "roc_auc" %}
    try:
        m["roc_auc"] = (metrics.roc_auc_score(y == classes[-1], scores[:, -1]) if binary else
                        metrics.roc_auc_score(y, scores, multi_class="ovr", labels=classes))
    except ValueError:
        m["roc_auc"] = float("nan")
{% elif key == "avg_precision" %}
    from sklearn.preprocessing import label_binarize

    m["avg_precision"] = (metrics.average_precision_score(y == classes[-1], scores[:, -1]) if binary
                          else metrics.average_precision_score(
                              label_binarize(y, classes=classes), scores, average="macro"))
{% elif key == "log_loss" %}
    m["log_loss"] = metrics.log_loss(y, scores, labels=classes)
{% elif key == "confusion" %}
    m["confusion"] = metrics.confusion_matrix(y, pred, labels=classes).tolist()
{% endif %}
{% endfor %}
{% else %}
{% for key in metric_keys %}
{% if key == "mse" %}
    m["mse"] = metrics.mean_squared_error(y, pred)
{% elif key == "rmse" %}
    m["rmse"] = metrics.root_mean_squared_error(y, pred)
{% elif key == "mae" %}
    m["mae"] = metrics.mean_absolute_error(y, pred)
{% elif key == "median_ae" %}
    m["median_ae"] = metrics.median_absolute_error(y, pred)
{% elif key == "mape" %}
    m["mape"] = metrics.mean_absolute_percentage_error(y, pred)
{% elif key == "r2" %}
    m["r2"] = metrics.r2_score(y, pred)
{% elif key == "explained_variance" %}
    m["explained_variance"] = metrics.explained_variance_score(y, pred)
{% endif %}
{% endfor %}
{% endif %}
    return {k: (float(v) if not isinstance(v, list) else v) for k, v in m.items()}


def feature_importances(model: Pipeline, top: int = 15) -> list[tuple[str, float]]:
    est = model.named_steps["model"]
    values = getattr(est, "feature_importances_", None)
    if values is None and hasattr(est, "coef_"):
        values = np.abs(np.asarray(est.coef_)).reshape(-1, np.shape(est.coef_)[-1]).mean(axis=0)
    if values is None:
        return []
    try:
        names = list(model[:-1].get_feature_names_out())
    except Exception:  # noqa: BLE001 — not every transformer names its outputs
        names = [f"feature_{i}" for i in range(len(values))]
    if len(names) != len(values):
        names = [f"feature_{i}" for i in range(len(values))]
    order = np.argsort(values)[::-1][:top]
    return [(names[i], float(values[i])) for i in order]
{% endif %}


def main() -> None:
    X, y = load_data()
    print(f"samples: {len(X)}")
    model = build_pipeline()
{% if supervised %}
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_FRACTION, random_state=SEED{% if stratify %},
        stratify=y if len(np.unique(y)) > 1 and np.min(np.unique(y, return_counts=True)[1]) > 1 else None{% endif %})
    fit_params = {}
{% if balance == "oversample" %}
    rng = np.random.default_rng(SEED)
    labels, counts = np.unique(y_train, return_counts=True)
    picks = np.concatenate([rng.choice(np.flatnonzero(y_train == c), counts.max(), replace=True)
                            for c in labels])
    X_train = X_train.iloc[picks] if hasattr(X_train, "iloc") else (
        [X_train[i] for i in picks] if isinstance(X_train, list) else X_train[picks])
    y_train = y_train[picks]
{% elif sample_weight %}
    fit_params["model__sample_weight"] = compute_sample_weight("balanced", y_train)
{% endif %}
{% if spec.kfold %}
    cv = {{ "StratifiedKFold" if task == "classification" else "KFold" }}(n_splits={{ spec.kfold.k }}, shuffle=True, random_state=SEED)
    results = cross_validate(model, X_train, y_train, cv=cv, scoring="{{ scoring }}", params=fit_params or None)
    scores = results["test_score"]
    print(f"cv {{ scoring }}: {scores.mean():.4f} ± {scores.std(ddof=1):.4f}")
{% endif %}
{% if grid %}
{% if spec.search.method == "grid" %}
    search = GridSearchCV(model, PARAM_GRID, cv={{ spec.search.cv }}, scoring="{{ scoring }}", n_jobs=-1)
{% elif spec.search.method == "halving" %}
    search = HalvingGridSearchCV(model, PARAM_GRID, cv={{ spec.search.cv }}, scoring="{{ scoring }}",
                                 random_state=SEED, n_jobs=-1)
{% else %}
    search = RandomizedSearchCV(model, PARAM_GRID, n_iter={{ spec.search.n_iter }}, cv={{ spec.search.cv }},
                                scoring="{{ scoring }}", random_state=SEED, n_jobs=-1)
{% endif %}
    started = time.time()
    search.fit(X_train, y_train, **fit_params)
    model = search.best_estimator_
    print(f"best {{ scoring }} (cv): {search.best_score_:.4f}")
    print(f"best parameters: {search.best_params_}")
{% else %}
    started = time.time()
    model.fit(X_train, y_train, **fit_params)
{% endif %}
    elapsed = time.time() - started
    train_metrics = evaluate(model, X_train, y_train)
    test_metrics = evaluate(model, X_test, y_test)
    numeric = {k: v for k, v in test_metrics.items() if isinstance(v, float)}
    print("epoch 1/1 " + " ".join(f"train_{k}={v:.4f}" for k, v in train_metrics.items()
                                  if isinstance(v, float))
          + " " + " ".join(f"{k}={v:.4f}" for k, v in numeric.items()) + f" ({elapsed:.1f}s)")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in numeric.items()))
    importances = feature_importances(model)
    if importances:
        print("top features: " + ", ".join(f"{n}={v:.3g}" for n, v in importances[:10]))
    joblib.dump(model, MODEL_FILE)
    save_inference_state(X)
    print(f"saved model to {MODEL_FILE}")
    Path("metrics.json").write_text(json.dumps(
        {**test_metrics, "train": train_metrics,
         "feature_importances": importances}, indent=1, default=str))
{% if task == "classification" %}
    classes = list(model.classes_)
    probs = predict_scores(model, X_test[:300] if not hasattr(X_test, "iloc") else X_test.iloc[:300])
{% if not proba %}
    probs = np.exp(probs - probs.max(axis=1, keepdims=True))
    probs = probs / probs.sum(axis=1, keepdims=True)
{% endif %}
    items = [{"index": i, "true": classes.index(y_test[i]), "probs": [round(float(v), 4) for v in row],
              "file": None} for i, row in enumerate(probs)]
    Path("predictions.json").write_text(json.dumps(items, indent=1))
    mistakes = [it for it in items if int(np.argmax(it["probs"])) != it["true"]]
    Path("mistakes.json").write_text(json.dumps(mistakes[:50], indent=1))
    Path("classes.json").write_text(json.dumps([str(c) for c in classes]))
    print(f"saved predictions.json ({len(items)} examples)")
{% endif %}
{% elif task == "clustering" %}
    started = time.time()
    labels = model.fit_predict(X)
    features = model[:-1].transform(X) if len(model) > 1 else np.asarray(X)
    m = {}
    found = set(labels) - {-1}
    print(f"clusters found: {len(found)} (noise points: {int((labels == -1).sum())})")
    if len(found) > 1:
{% for key in metric_keys %}
{% if key == "silhouette" %}
        m["silhouette"] = float(metrics.silhouette_score(features, labels))
{% elif key == "davies_bouldin" %}
        m["davies_bouldin"] = float(metrics.davies_bouldin_score(features, labels))
{% elif key == "calinski_harabasz" %}
        m["calinski_harabasz"] = float(metrics.calinski_harabasz_score(features, labels))
{% endif %}
{% endfor %}
{% for key in metric_keys %}
{% if key == "adjusted_rand" %}
    if y is not None:
        m["adjusted_rand"] = float(metrics.adjusted_rand_score(y, labels))
{% elif key == "nmi" %}
    if y is not None:
        m["nmi"] = float(metrics.normalized_mutual_info_score(y, labels))
{% endif %}
{% endfor %}
    print("epoch 1/1 " + " ".join(f"{k}={v:.4f}" for k, v in m.items())
          + f" ({time.time() - started:.1f}s)")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in m.items()))
    joblib.dump(model, MODEL_FILE)
    save_inference_state(X)
    Path("metrics.json").write_text(json.dumps(m, indent=1))
    Path("clusters.json").write_text(json.dumps([int(v) for v in labels]))
    print(f"saved model to {MODEL_FILE}")
{% else %}
    started = time.time()
    model.fit(X)
    flags = model.predict(X)
    rate = float((flags == -1).mean())
    print(f"epoch 1/1 anomaly_rate={rate:.4f} ({time.time() - started:.1f}s)")
    print(f"test: anomaly_rate={rate:.4f}")
    joblib.dump(model, MODEL_FILE)
    save_inference_state(X)
    Path("metrics.json").write_text(json.dumps({"anomaly_rate": rate}, indent=1))
    print(f"saved model to {MODEL_FILE}")
{% endif %}


# ============================================================= inference
INFERENCE_FILE = "inference.json"
_PREDICTOR = None
_COLUMNS = None


def save_inference_state(X) -> None:
    """Record the input columns the pipeline expects (for serving)."""
    columns = [str(c) for c in X.columns] if hasattr(X, "columns") else None
    Path(INFERENCE_FILE).write_text(json.dumps({"columns": columns}))


def load_predictor(folder: str | Path = ".", device: str = "cpu"):
    """Load the fitted pipeline from a run folder."""
    import __main__

    global _PREDICTOR, _COLUMNS
    # helper classes / functions were pickled from the training script's __main__
    for name, value in list(globals().items()):
        if callable(value) and getattr(value, "__module__", None) == __name__:
            setattr(__main__, name, value)
    _PREDICTOR = joblib.load(Path(folder) / MODEL_FILE)
    state_file = Path(folder) / INFERENCE_FILE
    _COLUMNS = json.loads(state_file.read_text()).get("columns") if state_file.exists() else None
    return _PREDICTOR


def prepare_inputs(raw: list):
    """Raw inputs -> what the pipeline's fit() received.

{% if text %}    raw: texts.
{% elif table or d.block == "data.sklearn" %}    raw: records, e.g. [{"column": value, ...}, ...].
{% elif d.block == "data.image_folder" %}    raw: images as file paths, bytes or base64 strings.
{% elif d.block == "data.timeseries_csv" %}    raw: windows of {{ d.window }} time steps x feature columns.
{% else %}    raw: feature vectors.
{% endif %}    """
{% if text %}
    return [str(t) for t in raw]
{% elif d.block == "data.image_folder" %}
    import base64
    import io

    from PIL import Image

    rows = []
    for item in raw:
        if isinstance(item, (bytes, bytearray)):
            img = Image.open(io.BytesIO(item))
        elif isinstance(item, str) and Path(item).exists():
            img = Image.open(item)
        else:
            img = Image.open(io.BytesIO(base64.b64decode(str(item).split(",")[-1])))
        img = img.convert("L" if {{ d.grayscale }} else "RGB").resize(({{ image_size }}, {{ image_size }}))
        rows.append(np.asarray(img, dtype=np.float32).reshape(-1) / 255.0)
    return np.stack(rows)
{% else %}
    if _COLUMNS is not None:
        import pandas as pd

        frame = raw if isinstance(raw, pd.DataFrame) else pd.DataFrame.from_records(raw)
        missing = [c for c in _COLUMNS if c not in frame.columns]
        if missing:
            raise ValueError(f"missing input columns: {missing}")
        return frame[_COLUMNS]
    X = np.asarray(raw, dtype=float)
    return X.reshape(len(X), -1)
{% endif %}


def infer(raw: list) -> list[dict]:
    """Predictions for a list of raw inputs (see ``prepare_inputs``)."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    X = prepare_inputs(raw)
{% if task == "classification" %}
    classes = [str(c) for c in _PREDICTOR.classes_]
    scores = np.asarray(predict_scores(_PREDICTOR, X), dtype=float)
{% if not proba %}
    scores = np.exp(scores - scores.max(axis=1, keepdims=True))
    scores = scores / scores.sum(axis=1, keepdims=True)
{% endif %}
    out = []
    for row in scores:
        best = int(np.argmax(row))
        out.append({"label": classes[best], "class_index": best,
                    "confidence": round(float(row[best]), 6),
                    "probabilities": {c: round(float(p), 6) for c, p in zip(classes, row, strict=True)}})
    return out
{% elif task == "regression" %}
    values = np.asarray(_PREDICTOR.predict(X), dtype=float)
    return [{"prediction": (float(v) if np.ndim(v) == 0 else [float(x) for x in v])}
            for v in values]
{% elif task == "clustering" %}
    if not hasattr(_PREDICTOR, "predict"):
        raise RuntimeError("this clustering model cannot assign new samples")
    return [{"cluster": int(c)} for c in _PREDICTOR.predict(X)]
{% else %}
    flags = _PREDICTOR.predict(X)
    scores = (_PREDICTOR.decision_function(X) if hasattr(_PREDICTOR, "decision_function")
              else np.zeros(len(flags)))
    return [{"anomaly": bool(f == -1), "score": float(s)} for f, s in zip(flags, scores, strict=True)]
{% endif %}


if __name__ == "__main__":
    main()
'''
