"""Curated pretrained-model catalogs (generated by scripts/build_zoo.py, no network).

Each catalog is a JSON list of entries with the measured feature width,
parameter count, accuracy, input-size limits, Keras equivalent and license.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

ZOO = Path(__file__).parent


@lru_cache(maxsize=None)
def catalog(name: str) -> tuple[dict, ...]:
    path = ZOO / f"{name}.json"
    if not path.exists():
        raise KeyError(f"no model catalog {name!r}")
    return tuple(json.loads(path.read_text()))


def entry(name: str, model: str) -> dict:
    for row in catalog(name):
        if row["name"] == model:
            return row
    raise KeyError(f"{model!r} is not in the {name} catalog")


def catalogs() -> list[str]:
    return sorted(p.stem for p in ZOO.glob("*.json"))
