"""Training scripts for reinforcement learning (Gymnasium + stable-baselines3).

The designed network becomes the policy's feature extractor; the algorithm adds its
action / value heads. A callback evaluates the deterministic policy at regular intervals,
prints the reward curve as epoch lines, draws it (``samples: <png>``) and keeps the best
policy. A random policy is the baseline.
"""
from __future__ import annotations

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.forecast.template import _strip_main
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.rl.blocks import ALGORITHMS
from ai_made_easy.core.rl.tasks import algorithm_node, env_node

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

CLASSES = {"rl.ppo": "PPO", "rl.a2c": "A2C", "rl.dqn": "DQN", "rl.sac": "SAC", "rl.td3": "TD3"}
LOOP = ("total_timesteps", "head", "evaluations", "eval_episodes", "action_noise")

TEMPLATE = r'''"""{{ title }} — reinforcement-learning script generated by AI Made Easy.

Environment: {{ env_id }} · algorithm: {{ algo }}
Usage:  python {{ filename }}          train, evaluate and save the best policy
Needs:  {{ requirements }}
"""
from __future__ import annotations

import json
import pickle
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

ENV_ID = {{ env_id | repr }}
N_ENVS = {{ n_envs }}
SEED = {{ seed }}
ALGO = "{{ algo }}"
HPARAMS = {{ hparams | repr }}
TOTAL_TIMESTEPS = {{ loop.total_timesteps }}
HEAD = {{ head | repr }}
EVALUATIONS = {{ loop.evaluations }}
EVAL_EPISODES = {{ loop.eval_episodes }}
ACTION_NOISE = {{ action_noise }}
DEVICE = "{{ device }}"
INPUT_SHAPE = {{ input_shape | repr }}
FEATURES = {{ features }}
CHECKPOINT = "{{ name }}_best.pt"            # a stable-baselines3 zip archive
INFERENCE_FILE = "inference_state.pkl"
LIVE_DIR = Path("samples")
SAMPLES_DIR = Path("eval_samples")
STATE: dict = {}
# ---------------------------------------------------------------------- model
{{ model_code }}


# ======================================================================== policy
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor  # noqa: E402


class DesignedExtractor(BaseFeaturesExtractor):
    """The network designed on the canvas: observations -> features."""

    def __init__(self, observation_space, features_dim: int = FEATURES) -> None:
        super().__init__(observation_space, features_dim)
        self.net = build_model()

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        return self.net(obs.float().reshape(len(obs), *INPUT_SHAPE))


def policy_kwargs() -> dict:
    head = list(HEAD)
    arch = head if ALGO == "DQN" else ({"pi": head, "vf": head} if ALGO in ("PPO", "A2C")
                                       else {"pi": head, "qf": head})
    return {"features_extractor_class": DesignedExtractor,
            "features_extractor_kwargs": {"features_dim": FEATURES}, "net_arch": arch}


def make_algorithm(env, device):
    import stable_baselines3 as sb3

    kwargs = dict(HPARAMS)
    if ALGO == "TD3" and ACTION_NOISE > 0:
        from stable_baselines3.common.noise import NormalActionNoise

        size = env.action_space.shape[-1]
        kwargs["action_noise"] = NormalActionNoise(np.zeros(size), ACTION_NOISE * np.ones(size))
    return getattr(sb3, ALGO)("MlpPolicy", env, policy_kwargs=policy_kwargs(), seed=SEED,
                              device=device, verbose=0, **kwargs)


def pick_device() -> str:
    if DEVICE != "auto":
        return DEVICE
    return "cuda" if torch.cuda.is_available() else "cpu"


# ======================================================================== evaluation
def random_reward(episodes: int) -> tuple[float, float]:
    import gymnasium as gym

    env = gym.make(ENV_ID)
    env.action_space.seed(SEED)
    totals = []
    for k in range(episodes):
        obs, _ = env.reset(seed=SEED + 10_000 + k)
        done, total = False, 0.0
        while not done:
            obs, reward, terminated, truncated, _ = env.step(env.action_space.sample())
            total += float(reward)
            done = terminated or truncated
        totals.append(total)
    env.close()
    return float(np.mean(totals)), float(np.std(totals))


def curve_picture(points: list, baseline: float, path: Path, live: bool = False) -> None:
    from PIL import Image, ImageDraw

    w, h = 520, 260
    img = Image.new("RGB", (w, h), (24, 26, 30))
    draw = ImageDraw.Draw(img)
    values = [p[1] for p in points] + [baseline]
    lo, hi = min(values), max(values)
    hi = hi if hi > lo else lo + 1
    steps = max(p[0] for p in points) or 1

    def xy(t, v):
        return 40 + t / steps * (w - 60), h - 30 - (v - lo) / (hi - lo) * (h - 60)

    draw.line([xy(0, baseline), xy(steps, baseline)], fill=(110, 110, 110))
    if len(points) > 1:
        draw.line([xy(t, v) for t, v in points], fill=(240, 120, 80), width=2)
    for t, v in points:
        x, y = xy(t, v)
        draw.ellipse([x - 3, y - 3, x + 3, y + 3], fill=(240, 120, 80))
    draw.text((10, 6), f"{ENV_ID} · {ALGO}: evaluation reward (grey: random policy)",
              fill=(225, 225, 225))
    draw.text((10, h - 20), f"{lo:.0f}", fill=(150, 150, 150))
    draw.text((w - 120, h - 20), f"{steps:,} steps", fill=(150, 150, 150))
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)
    if live:
        print(f"samples: {path}", flush=True)


# ======================================================================== serving
_ALGORITHM = None
_PREDICTOR = None


class ServedPolicy(nn.Module):
    """The trained policy as a plain module: observations -> action scores (discrete:
    logits or Q-values) or deterministic actions in [-1, 1] (continuous)."""

    def __init__(self, algorithm) -> None:
        super().__init__()
        self.policy = algorithm.policy

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        obs = obs.float()
        if ALGO == "DQN":
            return self.policy.q_net(obs)
        if ALGO in ("PPO", "A2C"):
            dist = self.policy.get_distribution(obs).distribution
            return dist.logits if hasattr(dist, "logits") else dist.mean
        return self.policy.actor(obs, deterministic=True) if ALGO == "SAC" \
            else self.policy.actor(obs)


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    global _ALGORITHM, _PREDICTOR
    import stable_baselines3 as sb3

    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    _ALGORITHM = getattr(sb3, ALGO).load(str(Path(folder) / CHECKPOINT), device=device)
    _PREDICTOR = ServedPolicy(_ALGORITHM).eval()
    return _PREDICTOR


def infer(raw: list) -> list[dict]:
    """An observation (list of numbers, or {"observation": [...], "deterministic": true})
    -> the action (and action probabilities / Q-values for discrete actions)."""
    if _ALGORITHM is None:
        raise RuntimeError("call load_predictor(folder) first")
    out = []
    for item in raw:
        item = item if isinstance(item, dict) else {"observation": item}
        obs = np.asarray(item["observation"], dtype=np.float32).reshape(INPUT_SHAPE)
        action, _ = _ALGORITHM.predict(obs, deterministic=bool(item.get("deterministic", True)))
        row = {"action": action.tolist() if np.ndim(action) else int(action)}
        if STATE.get("discrete"):
            with torch.no_grad():
                scores = _PREDICTOR(torch.as_tensor(obs[None]))[0]
            key = "q_values" if ALGO == "DQN" else "probabilities"
            values = scores if ALGO == "DQN" else scores.softmax(-1)
            row[key] = [round(float(v), 6) for v in values]
        out.append(row)
    return out


def main() -> None:
    from stable_baselines3.common.callbacks import BaseCallback
    from stable_baselines3.common.env_util import make_vec_env
    from stable_baselines3.common.evaluation import evaluate_policy

    import gymnasium as gym

    torch.manual_seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    env = make_vec_env(ENV_ID, n_envs=N_ENVS, seed=SEED)
    eval_env = gym.make(ENV_ID)
    discrete = hasattr(env.action_space, "n")
    obs_size = int(np.prod(env.observation_space.shape))
    if obs_size != int(np.prod(INPUT_SHAPE)):
        raise SystemExit(f"{ENV_ID} observations have {obs_size} values but the Input holds "
                         f"{int(np.prod(INPUT_SHAPE))}")
    print(f"environment: {ENV_ID} observation={env.observation_space.shape} "
          f"action={'discrete ' + str(env.action_space.n) if discrete else env.action_space.shape}")
    baseline, _ = random_reward(EVAL_EPISODES)
    print(f"random policy reward: {baseline:.2f}")
    model = make_algorithm(env, device)
    print(f"parameters: {sum(p.numel() for p in model.policy.parameters()):,}")
    every = max(1, TOTAL_TIMESTEPS // EVALUATIONS)
    points: list = []
    best = {"reward": -np.inf}

    class Progress(BaseCallback):
        def __init__(self) -> None:
            super().__init__()
            self.next, self.round, self.started = every, 0, time.time()

        def _on_step(self) -> bool:
            if self.num_timesteps < self.next:
                return True
            self.next += every
            self.round += 1
            mean, std = evaluate_policy(self.model, eval_env, n_eval_episodes=EVAL_EPISODES,
                                        deterministic=True)
            recent = [ep["r"] for ep in self.model.ep_info_buffer] or [float("nan")]
            points.append((self.num_timesteps, float(mean)))
            print(f"epoch {self.round}/{EVALUATIONS} train_reward={np.mean(recent):.4f} "
                  f"val_reward={mean:.4f} val_reward_std={std:.4f} "
                  f"timesteps={self.num_timesteps} ({time.time() - self.started:.1f}s)",
                  flush=True)
            if self.round == 1:
                print(f"resources: peak_memory_mb=0.0 step_ms="
                      f"{(time.time() - self.started) / self.num_timesteps * 1e3:.3f} "
                      f"batch_size={N_ENVS} device={device}", flush=True)
            curve_picture(points, baseline, LIVE_DIR / f"epoch_{self.round:03d}.png", live=True)
            if mean >= best["reward"]:
                best["reward"] = float(mean)
                self.model.save(CHECKPOINT)
            return True

    model.learn(total_timesteps=TOTAL_TIMESTEPS, callback=Progress())
    if not points:
        model.save(CHECKPOINT)
    import stable_baselines3 as sb3

    model = getattr(sb3, ALGO).load(CHECKPOINT, device=device)
    mean, std = evaluate_policy(model, eval_env, n_eval_episodes=max(EVAL_EPISODES, 20),
                                deterministic=True)
    STATE.update({"env_id": ENV_ID, "discrete": discrete, "algorithm": ALGO})
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    metrics = {"mean_reward": float(mean), "std_reward": float(std),
               "random_reward": baseline, "timesteps": float(TOTAL_TIMESTEPS)}
    if points:
        curve_picture(points, baseline, SAMPLES_DIR / "reward_curve.png")
    print(f"saved the best policy to {CHECKPOINT}")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))


if __name__ == "__main__":
    main()
'''


def _ints(text) -> list[int]:  # noqa: ANN001
    return [int(float(v)) for v in str(text or "").split(",") if v.strip()]


def context(graph: Graph, framework: str) -> dict:
    from ai_made_easy.core.training import catalog as cat
    from ai_made_easy.core.training.generate import own_loop_requirements

    if framework != "pytorch":
        raise CodegenError("reinforcement learning trains with PyTorch (stable-baselines3): "
                           "choose the PyTorch framework")
    env = env_node(graph)
    ep = env.resolved_params() if env is not None else {"env_id": "CartPole-v1",
                                                        "custom_id": "", "n_envs": 4, "seed": 0}
    env_id = ep["custom_id"] if ep["env_id"] == "custom" else ep["env_id"]
    algo = algorithm_node(graph)
    if algo is None:
        from ai_made_easy.core.registry import get_registry

        type_id = "rl.ppo"
        ap = {p.name: p.default for p in get_registry().get(type_id).params}
    else:
        type_id, ap = algo.type_id, dict(algo.resolved_params())
    if type_id not in ALGORITHMS:
        raise CodegenError(f"unknown algorithm {type_id}")
    trainer = next((n for n in graph.nodes.values() if n.type_id == "train.trainer"), None)
    device = cat.resolved("train.trainer", dict(trainer.params) if trainer else {})["device"]
    chain = graph.model_nodes()
    shapes = graph.infer_shapes()
    model_code = generate(graph, "pytorch")
    name = sanitize_identifier(graph.name)
    out_shape = list(shapes[chain[-1].instance_id])
    return {
        "title": graph.name, "filename": f"{name}_train_pytorch.py", "name": name,
        "env_id": env_id or "CartPole-v1", "n_envs": int(ep["n_envs"]), "seed": int(ep["seed"]),
        "algo": CLASSES[type_id],
        "hparams": {k: v for k, v in ap.items() if k not in LOOP},
        "loop": {k: ap[k] for k in ("total_timesteps", "evaluations", "eval_episodes")},
        "head": _ints(ap.get("head")), "action_noise": float(ap.get("action_noise", 0.0)),
        "device": device, "input_shape": list(shapes[chain[0].instance_id]),
        "features": int(out_shape[0]),
        "requirements": own_loop_requirements(model_code, ("gymnasium", "stable-baselines3")),
        "model_code": _strip_main(model_code),
    }


def render(graph: Graph, _spec, framework: str) -> str:
    return _env.from_string(TEMPLATE).render(**context(graph, framework))

