"""Scripts for the pipeline stages that work inside a trained PyTorch network.

A model-producing stage's run folder looks like a training run's: the model's training
script (``*_train_pytorch.py``), its weights (``*_best.pt``), the fitted preprocessing
(``inference_state.pkl``) and ``metrics.json`` — so later stages, the deploy packager and
the model registry use it like any run. Each stage writes a small ``stage_<kind>.py``
that imports the training script as a module, sets its pipeline hooks (``INIT_HOOK``,
``LOSS_HOOK``, ``LR_SCALE``, ...) and calls its own ``main()``, or evaluates it.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

HEADER = '''"""{title} — pipeline stage generated by AI Made Easy."""
import importlib.util
import json
import sys
from pathlib import Path

import numpy as np
import torch
from torch import nn


def load_module(path, name):
    """Import a training script as a module (its main() does not run)."""
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def checkpoint(folder):
    return next(Path(folder).glob("*_best.pt"))


def update_metrics(**values):
    path = Path("metrics.json")
    data = json.loads(path.read_text()) if path.exists() else {{}}
    data.update(values)
    path.write_text(json.dumps(data, indent=1))
'''


def script_of(run_dir: Path) -> Path:
    found = sorted(Path(run_dir).glob("*_train_pytorch.py"))
    if not found:
        raise FileNotFoundError(f"{run_dir} has no PyTorch training script")
    return found[0]


def _model_script(workdir: Path, source: Path | None = None, design=None) -> Path:  # noqa: ANN001
    """The stage's copy of the model's training script (or one generated for a design)."""
    if design is not None:
        from ai_made_easy.core.codegen import export_training

        return export_training(design, "pytorch", workdir)
    target = workdir / source.name
    shutil.copy2(source, target)
    return target


def _write(workdir: Path, kind: str, text: str) -> Path:
    path = workdir / f"stage_{kind}.py"
    path.write_text(text)
    return path


def finetune(workdir: Path, source: Path, params: dict, design=None) -> Path:  # noqa: ANN001
    script = _model_script(workdir, script_of(source), design)
    body = f'''
SOURCE = Path({str(source)!r})
FREEZE = {params["freeze"]!r}
UNFREEZE_AFTER = {int(params["unfreeze_after"])}
model_module = load_module({script.name!r}, "model_under_training")
state = torch.load(checkpoint(SOURCE), map_location="cpu")


def layers_with_weights(model):
    return [m for m in model.modules() if any(True for _ in m.parameters(recurse=False))]


def init(model):
    result = model.load_state_dict(state, strict=False)
    if result.missing_keys or result.unexpected_keys:
        print(f"fine-tune: {{len(result.missing_keys)}} new and "
              f"{{len(result.unexpected_keys)}} dropped weights (e.g. a new head)")
    groups = layers_with_weights(model)
    frozen = groups[:-1] if FREEZE == "all_but_last" else \\
        groups[: len(groups) // 2] if FREEZE == "first_half" else []
    for layer in frozen:
        for p in layer.parameters(recurse=False):
            p.requires_grad = False
    print(f"fine-tune: starting from {{SOURCE.name}}; {{len(frozen)}} of {{len(groups)}} "
          "layers frozen")


def unfreeze(epoch, model):
    if UNFREEZE_AFTER and epoch == UNFREEZE_AFTER:
        for p in model.parameters():
            p.requires_grad = True
        print(f"fine-tune: all layers trainable from epoch {{epoch}}")


model_module.INIT_HOOK = init
model_module.EPOCH_HOOK = unfreeze
model_module.LR_SCALE = {float(params["lr_scale"])}
model_module.EPOCHS = {int(params["epochs"])}
model_module.main()
'''
    return _write(workdir, "finetune", HEADER.format(title="Fine-tune") + body)


def distill(workdir: Path, teacher: Path, student, params: dict, task: str) -> Path:  # noqa: ANN001
    from ai_made_easy.core.codegen import class_name_for

    script = _model_script(workdir, design=student)
    teacher_script = script_of(teacher)
    teacher_graph_name = json.loads((teacher / "run.json").read_text())["graph"].get("name",
                                                                                     "model")
    epochs = int(params["epochs"])
    body = f'''
TEACHER = Path({str(teacher)!r})
TEMPERATURE = {float(params["temperature"])}
ALPHA = {float(params["alpha"])}
TASK = {task!r}
student = load_module({script.name!r}, "student_model")
teacher_module = load_module({str(teacher_script)!r}, "teacher_model")
teacher = getattr(teacher_module, {class_name_for(teacher_graph_name)!r})()
teacher.load_state_dict(torch.load(checkpoint(TEACHER), map_location="cpu"))
teacher.eval()
for p in teacher.parameters():
    p.requires_grad = False


def distillation(loss, out, xb, model):
    with torch.no_grad():
        target = teacher.to(xb.device)(xb).float()
    t = TEMPERATURE
    if TASK == "multiclass":
        soft = nn.functional.kl_div(nn.functional.log_softmax(out / t, dim=-1),
                                    nn.functional.softmax(target / t, dim=-1),
                                    reduction="batchmean") * t * t
    elif TASK in ("binary", "multilabel"):
        soft = nn.functional.binary_cross_entropy_with_logits(
            out / t, torch.sigmoid(target.reshape(out.shape) / t)) * t * t
    else:
        soft = nn.functional.mse_loss(out, target.reshape(out.shape))
    return ALPHA * loss + (1 - ALPHA) * soft


print(f"distill: teacher {{TEACHER.name}}, temperature {{TEMPERATURE}}, alpha {{ALPHA}}")
student.LOSS_HOOK = distillation
{"student.EPOCHS = %d" % epochs if epochs else ""}
student.main()
'''
    return _write(workdir, "distill", HEADER.format(title="Distill") + body)


def prune(workdir: Path, source: Path, params: dict) -> Path:
    script = _model_script(workdir, script_of(source))
    body = f'''
import torch.nn.utils.prune as prune

SOURCE = Path({str(source)!r})
AMOUNT = {float(params["amount"])}
model_module = load_module({script.name!r}, "model_under_training")
state = torch.load(checkpoint(SOURCE), map_location="cpu")
targets = []


def init(model):
    model.load_state_dict(state)
    targets.extend((m, "weight") for m in model.modules()
                   if isinstance(m, (nn.Linear, nn.Conv1d, nn.Conv2d, nn.Conv3d)))
    prune.global_unstructured(targets, pruning_method=prune.L1Unstructured, amount=AMOUNT)
    print(f"prune: {{AMOUNT:.0%}} of the weights of {{len(targets)}} layers set to zero")


def finish(model):
    for module, name in targets:
        prune.remove(module, name)            # make the zeros permanent


model_module.INIT_HOOK = init
model_module.BEFORE_SAVE = finish
model_module.LR_SCALE = {float(params["lr_scale"])}
model_module.EPOCHS = {int(params["epochs"])}
model_module.main()
weights = [m.weight for m, _ in targets]
zeros = sum(int((w == 0).sum()) for w in weights)
update_metrics(sparsity=zeros / max(sum(w.numel() for w in weights), 1))
'''
    return _write(workdir, "prune", HEADER.format(title="Prune") + body)


def _copy_model(workdir: Path, source: Path, quantize: str = "") -> Path:
    script = _model_script(workdir, script_of(source))
    if quantize:
        text = script.read_text()
        if 'QUANTIZE = ""' not in text:
            raise ValueError("the model's training script predates quantization support: "
                             "retrain it")
        script.write_text(text.replace('QUANTIZE = ""', f'QUANTIZE = "{quantize}"', 1))
    for pattern in ("*_best.pt", "inference_state.pkl", "classes.json"):
        for file in Path(source).glob(pattern):
            shutil.copy2(file, workdir / file.name)
    return script


EVALUATE_COMMON = '''
def test_outputs(module, folder, device):
    """The model's raw outputs and the targets on the test split."""
    model = module.load_predictor(folder, device=str(device))
    _train, _val, test_loader = module.make_loaders()
    outputs, targets = module.predict(model, test_loader, device)
    return model, outputs, targets


def size_mb(model):
    import io

    buffer = io.BytesIO()
    torch.save(model.state_dict(), buffer)
    return buffer.tell() / 2**20


def metrics_of(module, outputs, targets):
    values = module.compute_metrics(outputs, targets)
    return {k: v for k, v in values.items() if isinstance(v, float)}
'''


def quantize(workdir: Path, source: Path, params: dict) -> Path:
    script = _copy_model(workdir, source, quantize=params["mode"])
    body = EVALUATE_COMMON + f'''
SOURCE = Path({str(source)!r})
module = load_module({script.name!r}, "quantized_model")
device = torch.device("cpu")
module.QUANTIZE = ""
original, outputs, targets = test_outputs(module, SOURCE, device)
before = metrics_of(module, outputs, targets)
module.QUANTIZE = {params["mode"]!r}
quantized, outputs, targets = test_outputs(module, ".", device)
after = metrics_of(module, outputs, targets)
report = {{**after, "size_mb": size_mb(quantized), "size_mb_before": size_mb(original),
          **{{f"{{k}}_before": v for k, v in before.items()}}}}
print("quantize: " + " ".join(f"{{k}}={{v:.4f}}" for k, v in report.items()))
Path("metrics.json").write_text(json.dumps(report, indent=1))
'''
    return _write(workdir, "quantize", HEADER.format(title="Quantize") + body)


def evaluate(workdir: Path, source: Path, params: dict, classification: bool) -> Path:
    script = _model_script(workdir, script_of(source))
    body = EVALUATE_COMMON + f'''
SOURCE = Path({str(source)!r})
BINS = {int(params["bins"])}
module = load_module({script.name!r}, "evaluated_model")
# quantized weights only run on the CPU
device = torch.device("cpu") if getattr(module, "QUANTIZE", "") else module.pick_device()
model, outputs, targets = test_outputs(module, SOURCE, device)
report = metrics_of(module, outputs, targets)
if {classification!r} and len(targets):
    scores = module.to_scores(outputs)
    if scores.ndim == 1 or scores.shape[1] == 1:
        p1 = scores.reshape(-1)
        scores = np.stack([1 - p1, p1], axis=1)
    confidence, predicted = scores.max(axis=1), scores.argmax(axis=1)
    correct = predicted == np.asarray(targets).reshape(-1).astype(int)
    edges = np.linspace(0, 1, BINS + 1)
    table, ece = [], 0.0
    for lo, hi in zip(edges[:-1], edges[1:], strict=True):
        inside = (confidence > lo) & (confidence <= hi)
        if inside.any():
            gap = abs(correct[inside].mean() - confidence[inside].mean())
            ece += inside.mean() * gap
            table.append({{"bin": [float(lo), float(hi)], "count": int(inside.sum()),
                          "accuracy": float(correct[inside].mean()),
                          "confidence": float(confidence[inside].mean())}})
    report["ece"] = float(ece)
    Path("reliability.json").write_text(json.dumps(table, indent=1))
print("evaluate: " + " ".join(f"{{k}}={{v:.4f}}" for k, v in report.items()))
Path("metrics.json").write_text(json.dumps(report, indent=1))
'''
    return _write(workdir, "evaluate", HEADER.format(title="Evaluate") + body)


def ensemble(workdir: Path, members: list[Path], params: dict, task: str) -> Path:
    scripts = []
    for i, member in enumerate(members):
        target = workdir / f"member{i}_{script_of(member).name}"
        shutil.copy2(script_of(member), target)
        scripts.append(target.name)
    body = EVALUATE_COMMON + f'''
MEMBERS = {[str(m) for m in members]!r}
SCRIPTS = {scripts!r}
METHOD = {params["method"]!r}
TASK = {task!r}
device = torch.device("cpu")
modules, scores, report = [], [], {{}}
for i, (folder, script) in enumerate(zip(MEMBERS, SCRIPTS, strict=True)):
    module = load_module(script, f"member{{i}}")
    _model, outputs, targets = test_outputs(module, folder, device)
    modules.append(module)
    scores.append(module.to_scores(outputs) if TASK != "regression" else outputs)
    for k, v in metrics_of(module, outputs, targets).items():
        report[f"member{{i}}_{{k}}"] = v
first = modules[0]
if TASK == "regression":
    combined = np.mean(scores, axis=0)
elif METHOD == "vote" and TASK == "multiclass":
    votes = np.stack([s.argmax(axis=1) for s in scores])
    counts = np.apply_along_axis(np.bincount, 0, votes, minlength=scores[0].shape[1])
    combined = np.log(counts.T / len(scores) + 1e-9)
else:
    p = np.clip(np.mean(scores, axis=0), 1e-7, 1 - 1e-7)
    combined = np.log(p) if TASK == "multiclass" else np.log(p / (1 - p))
report.update(metrics_of(first, combined, targets))
print("ensemble: " + " ".join(f"{{k}}={{v:.4f}}" for k, v in report.items()))
Path("metrics.json").write_text(json.dumps(report, indent=1))
'''
    return _write(workdir, "ensemble", HEADER.format(title="Ensemble") + body)
