"""Scripts for probabilistic programs (PyMC).

The script builds the designed model (literal PyMC code), samples the posterior (NUTS,
ADVI, SMC or MAP), reports convergence diagnostics (R-hat, ESS, divergences), checks
posterior predictions on training and held-out rows, draws posteriors / traces /
predictive checks and saves posterior draws that ``load_predictor`` / ``infer`` use to
predict new rows.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, sanitize_identifier
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.ppl import runtime
from ai_made_easy.core.ppl.blocks import BY_ID
from ai_made_easy.core.ppl.model import ModelError, compile_design, identifier, model_code

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

DEFAULT_SAMPLER = {"method": "nuts", "draws": 1000, "tune": 1000, "chains": 4,
                   "target_accept": 0.9, "advi_iterations": 20000, "backend": "pymc",
                   "test_fraction": 0.2, "seed": 0}

TEMPLATE = r'''"""{{ title }} — Bayesian model (PyMC) generated by AI Made Easy.

Data:   {{ data_comment }}
Usage:  python {{ filename }}          sample the posterior, check it, save draws
Needs:  pymc, numpy, pandas, scipy, pillow
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import json
import math
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image, ImageDraw

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

DATASET = {{ dataset | repr }}
SAMPLER = {{ sampler | repr }}
COLUMNS = {{ columns | repr }}              # data columns the model reads
GROUPS = {{ groups | repr }}                # columns with one parameter per level
OBSERVED = {{ observed | repr }}            # variable -> (column, kind)
CATEGORICAL = {{ categorical | repr }}      # observed columns of categories
DRAWS_FILE = "{{ name }}_draws.npz"
STATE_FILE = "{{ name }}_state.json"
SAMPLES_DIR = Path("eval_samples")
STATE: dict = {}
{{ data_code }}
{{ diagnostics_code }}
{{ plot_code }}


def fix_pytensor_macos() -> None:
    """Recent Xcode linkers reject PyTensor's '-ld64' flag on macOS: drop it."""
    if sys.platform != "darwin":
        return
    try:
        from pytensor.link.c import cmodule
    except ImportError:
        return
    original = cmodule.GCC_compiler.compile_args
    if getattr(original, "_aime_patched", False):
        return

    def compile_args(*args, **kwargs):
        return [a for a in original(*args, **kwargs) if a != "-ld64"]

    compile_args._aime_patched = True
    cmodule.GCC_compiler.compile_args = staticmethod(compile_args)


fix_pytensor_macos()
import pymc as pm  # noqa: E402


# ======================================================================== data
def load_frame():
    if DATASET is None:
        raise SystemExit("this model needs a dataset: add a table or Synthetic Groups")
    if DATASET["block"] == "data.synthetic_groups":
        frame, truth = synthetic_groups(int(DATASET["n_groups"]), int(DATASET["rows_per_group"]),
                                        float(DATASET["intercept"]), float(DATASET["group_sd"]),
                                        float(DATASET["slope"]), float(DATASET["noise"]),
                                        DATASET["outcome"], int(DATASET["seed"]))
        STATE["truth"] = truth
        return frame
    path = Path(DATASET["path"]).expanduser()
    fmt = DATASET.get("format", "csv")
    if fmt == "parquet":
        return pd.read_parquet(path)
    return pd.read_csv(path, sep="\t" if fmt == "tsv" else ",")


def fit_encoders(frame) -> None:
    missing = [c for c in [*COLUMNS, *GROUPS] if c not in frame.columns]
    if missing:
        raise SystemExit(f"the data has no column(s) {missing}; columns: {list(frame.columns)}")
    STATE["levels"] = {g: sorted(frame[g].astype(str).unique().tolist()) for g in GROUPS}
    STATE["categories"] = {c: sorted(frame[c].astype(str).unique().tolist())
                           for c in CATEGORICAL}


def to_model_data(frame, observed_values: bool = True) -> dict:
    """Arrays for build_model: data columns, group codes and observed values."""
    data = {"_rows": np.arange(len(frame))}
    for col in COLUMNS:
        if col in CATEGORICAL:
            codes = {c: i for i, c in enumerate(STATE["categories"][col])}
            data[col] = frame[col].astype(str).map(codes).fillna(0).to_numpy().astype(int) \
                if col in frame else np.zeros(len(frame), int)
            continue
        kind = next((k for c, k in OBSERVED.values() if c == col), "real")
        is_observed = col in [c for c, _k in OBSERVED.values()]
        if col not in frame or (is_observed and not observed_values):
            values = np.zeros(len(frame))
        else:
            values = pd.to_numeric(frame[col], errors="coerce").to_numpy(float)
            if np.isnan(values).any():
                raise SystemExit(f"column {col!r} has missing or non-numeric values")
        data[col] = values.astype(int) if kind in ("count", "binary") else values
    for g in GROUPS:
        index = {lvl: i for i, lvl in enumerate(STATE["levels"][g])}
        codes = frame[g].astype(str).map(index)
        if codes.isna().any():
            unknown = sorted(set(frame[g].astype(str)) - set(index))[:5]
            raise ValueError(f"unknown {g} level(s) {unknown}: the model has "
                             f"{STATE['levels'][g][:10]}")
        data[g + "__code"] = codes.to_numpy(int)
    return data


def coords() -> dict:
    return {{ coord_expr }}


# ======================================================================== model
def build_model(data: dict):
    with pm.Model(coords=coords()) as model:
{% for line in model_lines %}
        {{ line }}
{% endfor %}
    return model


# ======================================================================== inference
def free_names(model) -> list[str]:
    return [rv.name for rv in model.free_RVs]


def sample(model) -> dict:
    """Posterior draws: name -> [chains, draws, ...]; plus sampler statistics."""
    cfg = SAMPLER
    stats: dict = {"divergences": 0}
    with model:
        if cfg["method"] == "map":
            point = pm.find_MAP(progressbar=False, seed=cfg["seed"])
            return {n: np.asarray(point[n])[None, None] for n in free_names(model)}, stats
        if cfg["method"] == "advi":
            approx = pm.fit(n=cfg["advi_iterations"], method="advi", random_seed=cfg["seed"],
                            progressbar=False)
            trace = approx.sample(cfg["draws"], random_seed=cfg["seed"])
        elif cfg["method"] == "smc":
            trace = pm.sample_smc(cfg["draws"], chains=cfg["chains"], random_seed=cfg["seed"],
                                  progressbar=False)
        else:
            kwargs = {"nuts_sampler": "numpyro"} if cfg["backend"] == "numpyro" else {}
            trace = pm.sample(cfg["draws"], tune=cfg["tune"], chains=cfg["chains"],
                              target_accept=cfg["target_accept"], random_seed=cfg["seed"],
                              progressbar=False, compute_convergence_checks=False, **kwargs)
            stats["divergences"] = int(np.asarray(trace["sample_stats"]["diverging"]).sum())
    posterior = trace["posterior"]
    return {n: np.asarray(posterior[n]) for n in free_names(model)}, stats


def points(draws: dict, limit: int = 400) -> list[dict]:
    """Up to ``limit`` posterior points (a single MAP point is repeated so that predictions
    still include the likelihood's noise)."""
    chains, n = next(iter(draws.values())).shape[:2]
    flat = {k: v.reshape(chains * n, *v.shape[2:]) for k, v in draws.items()}
    total = chains * n
    idx = np.linspace(0, total - 1, min(limit, total)).astype(int) if total > 1 else \
        np.zeros(limit, int)
    return [{k: v[i] for k, v in flat.items()} for i in idx]


def predict(frame, draws: dict, observed_values: bool = True) -> dict:
    """Posterior predictive draws of every observed variable for these rows."""
    data = to_model_data(frame, observed_values)
    model = build_model(data)
    with model:
        pp = pm.sample_posterior_predictive(points(draws), var_names=list(OBSERVED),
                                            random_seed=SAMPLER["seed"], progressbar=False)
    group = pp["posterior_predictive"]
    return {n: np.asarray(group[n]).reshape(-1, len(frame)) for n in OBSERVED}


def check(frame, preds: dict, prefix: str) -> dict:
    out = {}
    for name, (column, kind) in OBSERVED.items():
        sims = preds[name]
        actual = frame[column]
        if column in CATEGORICAL:
            codes = {c: i for i, c in enumerate(STATE["categories"][column])}
            actual = actual.astype(str).map(codes).to_numpy()
            mode = np.array([np.bincount(s.astype(int)).argmax() for s in sims.T])
            out[f"{prefix}_{name}_accuracy"] = float(np.mean(mode == actual))
            continue
        actual = pd.to_numeric(actual).to_numpy(float)
        lo, hi = np.quantile(sims, [0.03, 0.97], axis=0)
        mean = sims.mean(0)
        out[f"{prefix}_{name}_coverage_94"] = float(np.mean((actual >= lo) & (actual <= hi)))
        if kind == "binary":
            out[f"{prefix}_{name}_accuracy"] = float(np.mean((mean > 0.5) == (actual > 0.5)))
        else:
            out[f"{prefix}_{name}_rmse"] = float(np.sqrt(np.mean((mean - actual) ** 2)))
        if prefix == "train":
            SAMPLES_DIR.mkdir(exist_ok=True)
            ppc_plot(actual, mean, lo, hi, f"{name}: observed vs posterior predictive").save(
                SAMPLES_DIR / f"ppc_{name}.png")
    return out


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu"):
    global _PREDICTOR
    folder = Path(folder)
    STATE.update(json.loads((folder / STATE_FILE).read_text()))
    with np.load(folder / DRAWS_FILE) as npz:
        _PREDICTOR = {k: npz[k] for k in npz.files}
    return _PREDICTOR


def infer(raw: list) -> list[dict]:
    """Rows of input columns (and group levels) -> the posterior predictive of each
    observed variable: mean, sd and a 94% interval (probabilities for yes / no)."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    frame = pd.DataFrame([dict(r) for r in raw])
    preds = predict(frame, _PREDICTOR, observed_values=False)
    out = []
    for i in range(len(frame)):
        row = {}
        for name, (column, kind) in OBSERVED.items():
            sims = preds[name][:, i]
            if column in CATEGORICAL:
                counts = np.bincount(sims.astype(int), minlength=len(STATE["categories"][column]))
                row[name] = {c: round(float(p), 4) for c, p in
                             zip(STATE["categories"][column], counts / counts.sum())}
            elif kind == "binary":
                row[name] = {"probability": round(float(sims.mean()), 4)}
            else:
                lo, hi = np.quantile(sims, [0.03, 0.97])
                row[name] = {"mean": round(float(sims.mean()), 4),
                             "sd": round(float(sims.std()), 4),
                             "lower_94": round(float(lo), 4), "upper_94": round(float(hi), 4)}
        out.append(row)
    return out


# ======================================================================== main
def main() -> None:
    frame = load_frame()
    fit_encoders(frame)
    n_test = int(round(len(frame) * SAMPLER["test_fraction"])) if len(frame) >= 20 else 0
    order = np.random.default_rng(SAMPLER["seed"]).permutation(len(frame))
    test = frame.iloc[order[:n_test]].reset_index(drop=True) if n_test else None
    train = frame.iloc[order[n_test:]].reset_index(drop=True)
    print(f"rows: train={len(train)} test={n_test}; method={SAMPLER['method']}", flush=True)
    model = build_model(to_model_data(train))
    draws, stats = sample(model)
    rows = summarize(draws) if SAMPLER["method"] != "map" else [
        {"name": k, "mean": float(np.asarray(v).mean()), "sd": 0.0} for k, v in draws.items()]
    metrics: dict = {"divergences": float(stats["divergences"])}
    if SAMPLER["method"] in ("nuts", "smc"):     # chain diagnostics need real chains
        rhats = [r["r_hat"] for r in rows if not math.isnan(r["r_hat"])]
        esss = [r["ess_bulk"] for r in rows if not math.isnan(r["ess_bulk"])]
        if rhats:
            metrics["max_r_hat"] = float(max(rhats))
        if esss:
            metrics["min_ess_bulk"] = float(min(esss))
    for name, arr in draws.items():
        if arr[0, 0].size == 1:
            metrics[f"mean_{name}"] = float(np.asarray(arr).mean())
    if OBSERVED:
        metrics.update(check(train, predict(train, draws), "train"))
        if test is not None:
            metrics.update(check(test, predict(test, draws), "test"))
    if metrics.get("max_r_hat", 1.0) > 1.01:
        print(f"warning: R-hat {metrics['max_r_hat']:.3f} > 1.01: the chains disagree; "
              "sample longer or reparameterise", flush=True)
    if stats["divergences"]:
        print(f"warning: {stats['divergences']} divergent transitions: raise target_accept "
              "or reparameterise (non-centred hierarchies)", flush=True)
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()), flush=True)
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))
    SAMPLES_DIR.mkdir(exist_ok=True)
    header = f"{'variable':<22}{'mean':>10}{'sd':>9}{'3%':>10}{'97%':>10}{'ess':>8}{'r_hat':>8}"
    lines = ["Posterior summary", header]
    for r in rows:
        lines.append(f"{r['name']:<22}{r['mean']:>10.4f}{r['sd']:>9.4f}"
                     f"{r.get('lower_94', float('nan')):>10.4f}"
                     f"{r.get('upper_94', float('nan')):>10.4f}"
                     f"{r.get('ess_bulk', float('nan')):>8.0f}{r.get('r_hat', float('nan')):>8.3f}")
    if "truth" in STATE:
        lines += ["", "True values used to generate the data: " + json.dumps(STATE["truth"])]
    (SAMPLES_DIR / "report.txt").write_text("\n".join(lines) + "\n")
    Path("summary.json").write_text(json.dumps(rows, indent=1))
    if SAMPLER["method"] != "map":
        posterior_grid(draws).save(SAMPLES_DIR / "posterior.png")
        trace_plot(draws).save(SAMPLES_DIR / "trace.png")
    keep = points(draws, 1000)
    np.savez_compressed(DRAWS_FILE, **{k: np.stack([p[k] for p in keep])[None]
                                       for k in draws})
    Path(STATE_FILE).write_text(json.dumps({k: v for k, v in STATE.items() if k != "truth"}))
    print(f"saved posterior draws to {DRAWS_FILE} and a report to {SAMPLES_DIR}/")


if __name__ == "__main__":
    main()
'''


def _dataset(graph: Graph) -> dict | None:
    from ai_made_easy.core.ppl.tasks import dataset_of

    node = dataset_of(graph)
    if node is None:
        return None
    out = {"block": node.type_id, **dict(node.resolved_params())}
    raw = out.get("path")
    if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
        candidate = Path.cwd() / str(raw)
        if candidate.exists():
            out["path"] = str(candidate)
    return out


def render(graph: Graph) -> str:
    from ai_made_easy.core.ppl.rules import ppl_issues

    errors = [i for i in ppl_issues(graph) if i.severity == "error"]
    if errors:
        raise CodegenError("the probabilistic program has errors:\n"
                           + "\n".join(f"  - {e.message}" for e in errors))
    try:
        compiled = compile_design(graph)
    except ModelError as exc:
        raise CodegenError(str(exc)) from None
    vars_, info = compiled["vars"], compiled["info"]
    sampler = next((dict(n.resolved_params()) for n in graph.nodes.values()
                    if n.type_id == "ppl.sampler"), dict(DEFAULT_SAMPLER))
    notes = []
    if not info["observed"]:
        notes.append("no variable is observed: this samples the prior only")
    observed = {v.name: (v.observed, BY_ID[v.type_id].support) for v in vars_ if v.observed}
    model_lines = model_code(vars_, info)
    coord_expr = "{" + ", ".join(f"{identifier(g)!r}: STATE['levels'][{g!r}]"
                                 for g in info["groups"]) + "}"
    name = sanitize_identifier(graph.name)
    dataset = _dataset(graph)
    return _env.from_string(TEMPLATE).render(
        title=graph.name, filename=f"{name}_train_pymc.py", name=name, notes=notes,
        data_comment=_comment(dataset), dataset=dataset, sampler=sampler,
        columns=info["columns"], groups=info["groups"], observed=observed,
        categorical=compiled["categorical"], coord_expr=coord_expr, model_lines=model_lines,
        data_code=runtime.DATA_CODE, diagnostics_code=runtime.DIAGNOSTICS_CODE,
        plot_code=runtime.PLOT_CODE)


def _comment(dataset: dict | None) -> str:
    if dataset is None:
        return "none"
    if dataset["block"] == "data.synthetic_groups":
        return (f"generated: {dataset['n_groups']} groups, about {dataset['rows_per_group']} "
                f"rows each ({dataset['outcome']} outcome)")
    return str(dataset.get("path"))
