"""Training scripts for normalizing flows (density estimation).

The model maps data to standard-normal noise; training maximises the exact
log-likelihood log N(z) + sum(log|det J|). Data is standardised first and every reported
log-likelihood is converted back to the original units. A full-covariance Gaussian is
the baseline. 2-D data gets a live picture each epoch (``samples: <png>`` lines): the
data, samples from the model and the learned density.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.flows.tasks import dataset_of
from ai_made_easy.core.forecast.template import _picked, _strip_main
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.training import catalog as cat

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

TEMPLATE = r'''"""{{ title }} — normalizing-flow training script generated by AI Made Easy.

Data:   {{ data_comment }}
Usage:  python {{ filename }}          train, save weights, metrics and density plots
Needs:  {{ requirements }}
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import json
import math
import pickle
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

DATASET = {{ dataset | repr }}
INPUT_DIM = {{ input_dim }}
INPUT_SHAPE = [INPUT_DIM]
EPOCHS = {{ trainer.epochs }}
BATCH_SIZE = {{ batch_size }}
SEED = {{ trainer.seed }}
DEVICE = "{{ trainer.device }}"
EARLY_STOP = {{ trainer.early_stopping_patience }}
GRAD_CLIP = {{ trainer.grad_clip_norm or 5.0 }}
CHECKPOINT = "{{ name }}_best.pt"
INFERENCE_FILE = "inference_state.pkl"
SAMPLES_DIR = Path("eval_samples")
LIVE_DIR = Path("samples")
STATE: dict = {}
LOG_2PI = math.log(2 * math.pi)
# ---------------------------------------------------------------------- model
{{ model_code }}


# ======================================================================== data
def density_2d(kind: str, n: int, noise: float, seed: int) -> np.ndarray:
    """Points from a 2-D toy distribution."""
    rng = np.random.default_rng(seed)
    if kind == "moons":
        t = rng.uniform(0, np.pi, n)
        upper = rng.random(n) < 0.5
        x = np.where(upper[:, None], np.stack([np.cos(t), np.sin(t)], 1),
                     np.stack([1 - np.cos(t), 0.5 - np.sin(t)], 1)) - [0.5, 0.25]
    elif kind == "circles":
        t = rng.uniform(0, 2 * np.pi, n)
        r = np.where(rng.random(n) < 0.5, 2.0, 1.0)
        x = np.stack([r * np.cos(t), r * np.sin(t)], 1)
    elif kind == "eight_gaussians":
        angle = rng.integers(0, 8, n) * np.pi / 4
        x = 2 * np.stack([np.cos(angle), np.sin(angle)], 1) + rng.normal(0, 0.1, (n, 2))
    elif kind == "checkerboard":
        x1 = rng.uniform(-2, 2, n)
        x2 = rng.uniform(0, 1, n) - 2 * rng.integers(0, 2, n) + np.floor(x1) % 2
        x = np.stack([x1, x2], 1)
    elif kind == "spiral":
        t = np.sqrt(rng.random(n)) * 3 * np.pi
        sign = np.where(rng.random(n) < 0.5, 1.0, -1.0)[:, None]
        x = sign * np.stack([-np.cos(t) * t, np.sin(t) * t], 1) / 3
    elif kind == "pinwheel":
        arms, radial, tangential, rate = 5, 0.3, 0.1, 0.25
        labels = rng.integers(0, arms, n)
        feats = rng.normal(0, 1, (n, 2)) * [radial, tangential] + [1.0, 0.0]
        angles = labels * 2 * np.pi / arms + rate * np.exp(feats[:, 0])
        rot = np.stack([np.cos(angles), -np.sin(angles), np.sin(angles), np.cos(angles)], 1)
        x = 2 * np.einsum("ni,nij->nj", feats, rot.reshape(n, 2, 2))
    else:
        raise SystemExit(f"unknown 2-D density {kind!r}")
    return (x + rng.normal(0, noise, x.shape)).astype(np.float32)


def load_points(d: dict) -> tuple[np.ndarray, list[str]]:
    if d["block"] == "data.density_2d":
        return density_2d(d["kind"], int(d["n_samples"]), float(d["noise"]), int(d["seed"])), \
            ["x1", "x2"]
    import pandas as pd

    path = Path(d["path"]).expanduser()
    frame = pd.read_csv(path, sep="\t" if d.get("format") == "tsv" else ",")
    wanted = [c.strip() for c in str(d.get("feature_columns") or "").split(",") if c.strip()]
    columns = wanted or list(frame.select_dtypes("number").columns)
    missing = [c for c in columns if c not in frame.columns]
    if missing:
        raise SystemExit(f"columns {missing} are not in {path.name}")
    values = frame[columns].astype("float32").dropna().to_numpy()
    return values, columns


def split(n: int, val: float, test: float, seed: int) -> dict:
    order = np.random.default_rng(seed).permutation(n)
    n_test, n_val = int(round(n * test)), int(round(n * val))
    return {"test": order[:n_test], "val": order[n_test:n_test + n_val],
            "train": order[n_test + n_val:]}


# ======================================================================== flow
def flow_layers(model: nn.Module) -> list:
    return [m for m in model.modules() if getattr(m, "is_flow", False)]


def log_prob(model: nn.Module, x: torch.Tensor) -> torch.Tensor:
    """log p(x) of standardised data: standard-normal base plus the log-determinants."""
    z = model(x)
    logdet = sum(m.logdet for m in flow_layers(model))
    return -0.5 * (z ** 2).sum(-1) - 0.5 * z.shape[-1] * LOG_2PI + logdet


@torch.no_grad()
def sample(model: nn.Module, n: int, seed: int = 0) -> np.ndarray:
    """Points drawn from the model, in the original units."""
    device = next(model.parameters()).device
    g = torch.Generator(device="cpu").manual_seed(seed)
    z = torch.randn(n, INPUT_DIM, generator=g).to(device)
    for layer in reversed(flow_layers(model)):
        z = layer.inverse(z)
    return z.cpu().numpy() * STATE["std"] + STATE["mean"]


@torch.no_grad()
def log_density(model: nn.Module, points: np.ndarray, batch: int = 4096) -> np.ndarray:
    """log p(x) in the original units (the standardisation's Jacobian included)."""
    model.eval()
    device = next(model.parameters()).device
    xs = (np.asarray(points, dtype=np.float32) - STATE["mean"]) / STATE["std"]
    out = [log_prob(model, torch.from_numpy(xs[i:i + batch]).to(device)).float().cpu().numpy()
           for i in range(0, len(xs), batch)]
    return np.concatenate(out) - float(np.log(STATE["std"]).sum())


def gaussian_nll(train: np.ndarray, test: np.ndarray) -> float:
    """Mean negative log-likelihood of a full-covariance Gaussian fitted to train."""
    mean = train.mean(0)
    cov = np.cov(train, rowvar=False).reshape(train.shape[1], train.shape[1])
    cov += 1e-6 * np.eye(len(cov))
    diff = test - mean
    _sign, logdet = np.linalg.slogdet(cov)
    maha = np.einsum("ni,ij,nj->n", diff, np.linalg.inv(cov), diff)
    return float(np.mean(0.5 * (maha + logdet + train.shape[1] * LOG_2PI)))


# ======================================================================== pictures
def density_picture(model: nn.Module, data: np.ndarray, path: Path, title: str,
                    live: bool = False) -> None:
    """Data | model samples | learned density over the first two dimensions."""
    from PIL import Image, ImageDraw

    size, pad = 240, 10
    lo = np.percentile(data[:, :2], 0.5, axis=0)
    hi = np.percentile(data[:, :2], 99.5, axis=0)
    span = np.maximum(hi - lo, 1e-6)
    lo, hi = lo - 0.15 * span, hi + 0.15 * span
    img = Image.new("RGB", (3 * size + 4 * pad, size + 2 * pad + 36), (24, 26, 30))
    draw = ImageDraw.Draw(img)

    def to_px(points: np.ndarray, ox: int) -> np.ndarray:
        u = (points[:, :2] - lo) / (hi - lo)
        return np.stack([ox + u[:, 0] * size, pad + 18 + (1 - u[:, 1]) * size], 1)

    model.eval()
    drawn = sample(model, min(2000, max(len(data), 500)), seed=SEED)
    for k, (points, colour) in enumerate(((data[:2000], (90, 150, 240)),
                                          (drawn, (240, 120, 80)))):
        ox = pad + k * (size + pad)
        draw.rectangle([ox, pad + 18, ox + size, pad + 18 + size], outline=(70, 70, 70))
        for px, py in to_px(points, ox):
            if ox <= px <= ox + size and pad + 18 <= py <= pad + 18 + size:
                draw.rectangle([px, py, px + 1, py + 1], fill=colour)
    if INPUT_DIM == 2:
        g = 120
        gx, gy = np.meshgrid(np.linspace(lo[0], hi[0], g), np.linspace(hi[1], lo[1], g))
        dens = np.exp(log_density(model, np.stack([gx.ravel(), gy.ravel()], 1)))
        dens = (dens / max(dens.max(), 1e-12)).reshape(g, g)
        heat = (np.stack([dens * 250, dens * 200 + 30 * (1 - dens), 60 + dens * 60], -1)
                .clip(0, 255).astype(np.uint8))
        img.paste(Image.fromarray(heat).resize((size, size)), (pad + 2 * (size + pad), pad + 18))
    for k, label in enumerate(("data", "samples from the flow",
                               "learned density" if INPUT_DIM == 2 else "(density: 2-D only)")):
        draw.text((pad + k * (size + pad), 4), label, fill=(200, 200, 200))
    draw.text((pad, size + pad + 22), title, fill=(160, 160, 160))
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)
    if live:
        print(f"samples: {path}", flush=True)


def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")      # (MPS lacks some ops the splines use)


def report_resources(device: torch.device, step_seconds: float) -> None:
    peak = torch.cuda.max_memory_allocated(device) / 2**20 if device.type == "cuda" else 0.0
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


# ======================================================================== training
def mean_nll(model: nn.Module, points: np.ndarray) -> float:
    return float(-log_density(model, points).mean()) if len(points) else float("nan")


def train(model: nn.Module, train_x: np.ndarray, val_x: np.ndarray, device) -> nn.Module:
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% endif %}
    data = torch.from_numpy((train_x - STATE["mean"]) / STATE["std"]).float()
    steps = max(1, math.ceil(len(data) / BATCH_SIZE))
    best, best_state, bad = math.inf, None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, total = time.time(), 0.0
        order = torch.randperm(len(data))
        for start in range(0, len(data), BATCH_SIZE):
            xb = data[order[start:start + BATCH_SIZE]].to(device)
            if len(xb) < 2:
                continue
            loss = -log_prob(model, xb).mean()
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate or "
                                 "use fewer / smaller layers")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(params, GRAD_CLIP)
            optimizer.step()
{% if scheduler_step == "batch" %}
            scheduler.step()
{% endif %}
            total += loss.item()
        if epoch == 1:
            report_resources(device, (time.time() - started) / steps)
        val_nll = mean_nll(model, val_x if len(val_x) else train_x[:2000])
{% if scheduler_step == "epoch" %}
        scheduler.step()
{% elif scheduler_step == "metric" %}
        scheduler.step(val_nll)
{% endif %}
        train_nll = total / steps + float(np.log(STATE["std"]).sum())
        print(f"epoch {epoch}/{EPOCHS} train_loss={train_nll:.4f} val_loss={val_nll:.4f} "
              f"val_nll_per_dim={val_nll / INPUT_DIM:.4f} "
              f"lr={optimizer.param_groups[0]['lr']:.3g} ({time.time() - started:.1f}s)",
              flush=True)
        if epoch == 1 or epoch % max(1, EPOCHS // 10) == 0 or epoch == EPOCHS:
            density_picture(model, train_x, LIVE_DIR / f"epoch_{epoch:03d}.png",
                            f"epoch {epoch}: val NLL {val_nll:.3f}", live=True)
        if val_nll < best:
            best, bad = val_nll, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if EARLY_STOP and bad >= EARLY_STOP:
                print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    model.load_state_dict(best_state)
    return model


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    global _PREDICTOR
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    model = build_model()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    _PREDICTOR = model.eval().to(device)
    return _PREDICTOR


def infer(raw: list) -> list[dict]:
    """A point ([values] or {"column": value}) -> {"log_density"};
    {"sample": n, "seed": s} -> {"samples": [[values], ...]}."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    results = []
    for item in raw:
        if isinstance(item, dict) and "sample" in item:
            n = max(1, min(int(item["sample"]), 10000))
            drawn = sample(_PREDICTOR, n, int(item.get("seed", 0)))
            results.append({"samples": [[round(float(v), 6) for v in row] for row in drawn]})
            continue
        if isinstance(item, dict):
            point = [float(item[c]) for c in STATE["columns"]]
        else:
            point = [float(v) for v in item]
        if len(point) != INPUT_DIM:
            raise ValueError(f"expected {INPUT_DIM} values ({STATE['columns']}), "
                             f"got {len(point)}")
        results.append({"log_density": float(log_density(_PREDICTOR, np.array([point]))[0])})
    return results


def main() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    points, columns = load_points(DATASET)
    if points.shape[1] != INPUT_DIM:
        raise SystemExit(f"the data has {points.shape[1]} columns but the Input holds "
                         f"{INPUT_DIM} values")
    parts = split(len(points), float(DATASET.get("val_fraction", 0.1)),
                  float(DATASET.get("test_fraction", 0.1)), SEED)
    train_x, val_x, test_x = (points[parts[k]] for k in ("train", "val", "test"))
    STATE.update({"mean": train_x.mean(0).astype(np.float32),
                  "std": (train_x.std(0) + 1e-6).astype(np.float32), "columns": columns})
    print(f"points: train={len(train_x)} val={len(val_x)} test={len(test_x)} dims={INPUT_DIM}")
    model = build_model().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    model = train(model, train_x, val_x, device)
    test_x = test_x if len(test_x) else val_x
    nll = mean_nll(model, test_x)
    baseline = gaussian_nll(train_x, test_x)
    metrics = {"nll": nll, "nll_per_dim": nll / INPUT_DIM, "baseline_nll": baseline,
               "nll_gain": baseline - nll}
    torch.save(model.state_dict(), CHECKPOINT)
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    density_picture(model, test_x, SAMPLES_DIR / "density.png",
                    f"test NLL {nll:.3f} (Gaussian {baseline:.3f})")
    print(f"saved best weights to {CHECKPOINT}")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))


if __name__ == "__main__":
    main()
'''

DEFAULT_DATA = {"block": "data.density_2d", "kind": "moons", "n_samples": 5000, "noise": 0.05,
                "seed": 0, "val_fraction": 0.1, "test_fraction": 0.1}


def _dataset(graph: Graph) -> dict:
    node = dataset_of(graph)
    if node is None:
        return dict(DEFAULT_DATA)
    out = {"block": node.type_id, "val_fraction": 0.1, "test_fraction": 0.1,
           **dict(node.resolved_params())}
    raw = out.get("path")
    if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
        candidate = Path.cwd() / str(raw)
        if candidate.exists():
            out["path"] = str(candidate)
    return out


def _comment(dataset: dict) -> str:
    if dataset["block"] == "data.density_2d":
        return f"{dataset['n_samples']} points from the 2-D '{dataset['kind']}' distribution"
    return str(dataset.get("path"))


def context(graph: Graph, framework: str) -> dict:
    from ai_made_easy.core.training.generate import own_loop_requirements

    if framework != "pytorch":
        raise CodegenError("normalizing flows train with PyTorch: choose the PyTorch "
                           "framework")
    notes: list[str] = []
    dataset = _dataset(graph)
    if dataset_of(graph) is None:
        notes.append("no dataset block: training on the 2-D 'moons' distribution")
    if any(n.type_id in cat.LOSS_IDS for n in graph.nodes.values()):
        notes.append("loss blocks are ignored: flows train by maximum likelihood")
    chain = graph.model_nodes()
    shapes = graph.infer_shapes()
    _t, trainer = _picked(graph, ("train.trainer",))
    trainer = cat.resolved("train.trainer", trainer)
    _l, loader = _picked(graph, ("prep.dataloader",))
    opt, opt_params = _picked(graph, cat.OPTIMIZER_IDS)
    optimizer = ("torch.optim.Adam(params, lr=0.001)" if opt is None else
                 cat.render(opt.type_id, cat.resolved(opt.type_id, opt_params), "pytorch")
                 .replace("model.parameters()", "params"))
    sched, sched_params = _picked(graph, cat.SCHEDULER_IDS)
    model_code = generate(graph, "pytorch")
    name = sanitize_identifier(graph.name)
    extra = ("pandas",) if dataset["block"] == "data.csv" else ()
    return {
        "title": graph.name, "filename": f"{name}_train_pytorch.py", "name": name,
        "notes": notes, "requirements": own_loop_requirements(model_code, extra),
        "data_comment": _comment(dataset), "dataset": dataset,
        "input_dim": int(shapes[chain[0].instance_id][0]), "trainer": trainer,
        "batch_size": int(loader.get("batch_size") or 0) or int(trainer["batch_size"]),
        "model_code": _strip_main(model_code), "optimizer_expr": optimizer,
        "scheduler_expr": (cat.render(sched.type_id, cat.resolved(sched.type_id, sched_params),
                                      "pytorch") if sched else None),
        "scheduler_step": cat.COMPONENTS[sched.type_id].meta["step"] if sched else None,
    }


def render(graph: Graph, _spec, framework: str) -> str:
    return _env.from_string(TEMPLATE).render(**context(graph, framework))
