"""statsmodels scripts for state-space models (structural time series and SARIMAX).

The model is fitted by maximum likelihood (the Kalman filter evaluates the likelihood),
the last ``horizon`` steps are held out and forecast with intervals, and a seasonal-naive
forecast is the baseline. Serving re-runs the Kalman filter with the learned parameters
on any new history, so a deployed model forecasts series it has never seen.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, sanitize_identifier
from ai_made_easy.core.graph import Graph

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

# trend kind -> (level, stochastic level, trend, stochastic trend)
TREND_FLAGS = {"local level": (True, True, False, False),
               "local linear trend": (True, True, True, True),
               "smooth trend": (True, False, True, True),
               "random walk with drift": (True, True, True, False),
               "deterministic trend": (True, False, True, False),
               "fixed intercept": (True, False, False, False),
               "random walk": (True, True, False, False)}

TEMPLATE = r'''"""{{ title }} — state-space model script generated by AI Made Easy.

Model:  {{ model_comment }}
Data:   {{ data_comment }}
Usage:  python {{ filename }}          fit, forecast the held-out steps, save the model
Needs:  statsmodels, numpy, pandas, pillow
"""
from __future__ import annotations

import json
import math
import pickle
import time
import warnings
from pathlib import Path

import numpy as np

DATASET = {{ dataset | repr }}
KIND = "{{ kind }}"                       # structural | sarimax
SPEC = {{ spec | repr }}
TARGET = {{ target | repr }}
EXOG = {{ exog | repr }}
HORIZON = {{ horizon }}
INTERVAL = {{ interval }}
MAX_ITER = {{ max_iter }}
SEASON = {{ season }}                     # seasonal period for MASE / the naive baseline
MODEL_FILE = "{{ name }}_ssm.pkl"
SAMPLES_DIR = Path("eval_samples")
STATE: dict = {}


# ======================================================================== data
def structural_series(d: dict):
    """A series made of known parts; returns (frame, true components)."""
    import pandas as pd

    rng = np.random.default_rng(int(d["seed"]))
    n = int(d["length"])
    t = np.arange(n)
    slope = float(d["slope"]) + np.cumsum(rng.normal(0, float(d["level_drift"]), n))
    trend = 10.0 + np.cumsum(slope)
    s = int(d["season_length"])
    season = (float(d["season_amplitude"]) * (np.sin(2 * np.pi * t / s)
                                              + 0.5 * np.sin(4 * np.pi * t / s + 1.0))
              if s > 1 else np.zeros(n))
    period = max(n / 4, 8.0)
    cycle = float(d["cycle_amplitude"]) * np.sin(2 * np.pi * t / period)
    y = trend + season + cycle + rng.normal(0, float(d["noise"]), n)
    return pd.DataFrame({"t": t, "y": y}), {"trend": trend, "season": season, "cycle": cycle}


def load_data():
    import pandas as pd

    if DATASET["block"] == "data.structural_series":
        return structural_series(DATASET)
    path = Path(DATASET["path"]).expanduser()
    frame = pd.read_csv(path)
    missing = [c for c in [TARGET, *EXOG] if c not in frame.columns]
    if missing:
        raise SystemExit(f"columns {missing} are not in {path.name}")
    return frame.dropna(subset=[TARGET, *EXOG]).reset_index(drop=True), None


# ======================================================================== model
def build(endog: np.ndarray, exog: np.ndarray | None):
    if KIND == "sarimax":
        from statsmodels.tsa.statespace.sarimax import SARIMAX

        return SARIMAX(endog, exog=exog, **SPEC)
    from statsmodels.tsa.statespace.structural import UnobservedComponents

    return UnobservedComponents(endog, exog=exog, **SPEC)


def fit(endog: np.ndarray, exog: np.ndarray | None):
    model = build(endog, exog)
    started, step = time.time(), [0]

    def progress(xk) -> None:
        step[0] += 1
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            nll = -model.loglike(xk, transformed=False) / len(endog)
        print(f"epoch {step[0]}/{MAX_ITER} train_loss={nll:.4f} "
              f"({time.time() - started:.1f}s)", flush=True)

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        result = model.fit(disp=False, maxiter=MAX_ITER, callback=progress)
    if not result.mle_retvals.get("converged", True):
        print("warning: the optimiser did not converge: raise max_iterations or simplify "
              "the model", flush=True)
    return model, result


def forecast(result, steps: int, exog_future: np.ndarray | None) -> dict:
    frame = result.get_forecast(steps, exog=exog_future).summary_frame(alpha=1 - INTERVAL)
    return {"mean": frame["mean"].to_numpy(), "lower": frame["mean_ci_lower"].to_numpy(),
            "upper": frame["mean_ci_upper"].to_numpy()}


def components(result) -> dict:
    """Smoothed structural components (empty for SARIMAX)."""
    out = {}
    if KIND != "structural":
        return out
    for name in ("level", "seasonal", "cycle", "autoregressive"):
        part = getattr(result, name, None)
        if part is not None and part.get("smoothed") is not None:
            out[name] = np.asarray(part["smoothed"])
    for i, part in enumerate(getattr(result, "freq_seasonal", None) or []):
        out[f"seasonal_{i}"] = np.asarray(part["smoothed"])
    return out


# ======================================================================== metrics
def scores(actual: np.ndarray, fc: dict, history: np.ndarray) -> dict:
    err = actual - fc["mean"]
    m = SEASON if SEASON and len(history) > SEASON else 1
    scale = np.mean(np.abs(history[m:] - history[:-m])) or 1.0
    naive = np.resize(history[-m:], len(actual))
    denom = np.abs(actual) + np.abs(fc["mean"])
    return {"mae": float(np.mean(np.abs(err))), "rmse": float(np.sqrt(np.mean(err ** 2))),
            "mase": float(np.mean(np.abs(err)) / scale),
            "smape": float(np.mean(np.where(denom > 0, 2 * np.abs(err) / np.maximum(denom, 1e-12),
                                            0.0))),
            "coverage": float(np.mean((actual >= fc["lower"]) & (actual <= fc["upper"]))),
            "interval_width": float(np.mean(fc["upper"] - fc["lower"])),
            "naive_mae": float(np.mean(np.abs(actual - naive)))}


# ======================================================================== pictures
def _plot_lines(draw, box, series: list, lo: float, hi: float, n: int) -> None:
    x0, y0, x1, y1 = box
    hi = hi if hi > lo else lo + 1

    def xy(i, v):
        return x0 + i / max(n - 1, 1) * (x1 - x0), y1 - (v - lo) / (hi - lo) * (y1 - y0)

    for start, values, colour in series:
        pts = [xy(start + i, v) for i, v in enumerate(values) if np.isfinite(v)]
        if len(pts) > 1:
            draw.line(pts, fill=colour, width=2)


def forecast_picture(history: np.ndarray, actual: np.ndarray, fc: dict, path: Path,
                     title: str) -> None:
    from PIL import Image, ImageDraw

    w, h = 760, 300
    img = Image.new("RGB", (w, h), (24, 26, 30))
    draw = ImageDraw.Draw(img)
    tail = history[-max(4 * len(actual), 60):]
    n = len(tail) + len(actual)
    values = np.concatenate([tail, actual, fc["lower"], fc["upper"]])
    lo, hi = float(np.nanmin(values)), float(np.nanmax(values))
    box = (40, 30, w - 20, h - 30)
    span = (hi - lo) or 1.0
    x0, y0, x1, y1 = box
    for i in range(len(actual)):                       # interval band
        xa = x0 + (len(tail) + i) / max(n - 1, 1) * (x1 - x0)
        ya = y1 - (fc["upper"][i] - lo) / span * (y1 - y0)
        yb = y1 - (fc["lower"][i] - lo) / span * (y1 - y0)
        draw.line([xa, ya, xa, yb], fill=(60, 80, 120), width=4)
    _plot_lines(draw, box, [(0, tail, (150, 150, 150)),
                            (len(tail), actual, (90, 150, 240)),
                            (len(tail), fc["mean"], (240, 120, 80))], lo, hi, n)
    draw.text((10, 8), title, fill=(225, 225, 225))
    draw.text((w - 330, h - 20), "history (grey)  actual (blue)  forecast (orange)",
              fill=(150, 150, 150))
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)


def components_picture(y: np.ndarray, parts: dict, truth: dict | None, path: Path) -> None:
    from PIL import Image, ImageDraw

    rows = [("observed", y, None)]
    for name, values in parts.items():
        key = "trend" if name == "level" else "season" if name.startswith("seasonal") else name
        rows.append((name, values, (truth or {}).get(key)))
    w, rh = 760, 110
    img = Image.new("RGB", (w, rh * len(rows)), (24, 26, 30))
    draw = ImageDraw.Draw(img)
    for r, (name, values, true) in enumerate(rows):
        lines = [(0, values, (240, 120, 80) if r else (150, 150, 150))]
        if true is not None and np.ptp(true) > 0:
            lines.insert(0, (0, true[:len(values)], (90, 150, 240)))
        stacked = np.concatenate([v for _s, v, _c in lines])
        _plot_lines(draw, (40, r * rh + 20, w - 20, r * rh + rh - 10), lines,
                    float(np.nanmin(stacked)), float(np.nanmax(stacked)), len(values))
        draw.text((10, r * rh + 4), name + ("  (blue: true)" if len(lines) > 1 else ""),
                  fill=(225, 225, 225))
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".") -> dict:
    global _PREDICTOR
    with open(Path(folder) / MODEL_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    _PREDICTOR = STATE
    return _PREDICTOR


def infer(raw: list) -> list[dict]:
    """A history (list of values, or {"history": [...], "horizon": n,
    "past_covariates": [[...]], "future_covariates": [[...]]}) -> forecast mean and
    interval. The Kalman filter runs on the history with the learned parameters."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    out = []
    for item in raw:
        item = item if isinstance(item, dict) else {"history": item}
        history = np.asarray(item["history"], dtype=float)
        steps = max(1, min(int(item.get("horizon", HORIZON)), 10000))
        past = future = None
        if EXOG:
            if "past_covariates" not in item or "future_covariates" not in item:
                raise ValueError(f"this model uses {EXOG}: send past_covariates (one row per "
                                 "history step) and future_covariates (one row per forecast "
                                 "step)")
            past = np.asarray(item["past_covariates"], dtype=float).reshape(len(history), -1)
            future = np.asarray(item["future_covariates"], dtype=float).reshape(-1, len(EXOG))
            steps = len(future)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            result = build(history, past).smooth(np.asarray(STATE["params"]))
            fc = forecast(result, steps, future)
        out.append({"mean": [round(float(v), 6) for v in fc["mean"]],
                    "lower": [round(float(v), 6) for v in fc["lower"]],
                    "upper": [round(float(v), 6) for v in fc["upper"]],
                    "interval": INTERVAL})
    return out


def main() -> None:
    frame, truth = load_data()
    y = frame[TARGET].to_numpy(dtype=float)
    X = frame[EXOG].to_numpy(dtype=float) if EXOG else None
    if len(y) <= HORIZON + 10:
        raise SystemExit(f"the series has {len(y)} steps: too short for a {HORIZON}-step "
                         "test horizon")
    cut = len(y) - HORIZON
    print(f"series: {len(y)} steps, train={cut} test={HORIZON}; model: {KIND}")
    model, result = fit(y[:cut], X[:cut] if X is not None else None)
    print("parameters: " + ", ".join(f"{k}={v:.4g}" for k, v in
                                     zip(model.param_names, result.params)))
    fc = forecast(result, HORIZON, X[cut:] if X is not None else None)
    metrics = scores(y[cut:], fc, y[:cut])
    metrics.update({"aic": float(result.aic), "bic": float(result.bic),
                    "log_likelihood": float(result.llf)})
    parts = components(result)
    if truth is not None and "level" in parts:
        metrics["trend_rmse"] = float(np.sqrt(np.mean((parts["level"] - truth["trend"][:cut])
                                                      ** 2)))
    STATE.update({"params": [float(v) for v in result.params],
                  "param_names": list(model.param_names), "kind": KIND, "spec": SPEC,
                  "exog": EXOG})
    with open(MODEL_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    forecast_picture(y[:cut], y[cut:], fc, SAMPLES_DIR / "forecast.png",
                     f"{HORIZON}-step forecast, {INTERVAL:.0%} interval "
                     f"(MASE {metrics['mase']:.2f})")
    components_picture(y[:cut], parts, truth, SAMPLES_DIR / "components.png")
    print(f"saved the model to {MODEL_FILE}")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))


if __name__ == "__main__":
    main()
'''


def model_node(graph: Graph):  # noqa: ANN201
    return next((n for n in graph.nodes.values() if n.type_id == "ssm.model"), None)


def wired(graph: Graph) -> list:
    """Component / SARIMAX blocks wired into the model."""
    model = model_node(graph)
    if model is None:
        return []
    return [graph.nodes[e.source_id] for e in graph.incoming(model.instance_id)
            if e.source_id in graph.nodes]


def dataset_of(graph: Graph):  # noqa: ANN201
    from ai_made_easy.core.ssm.blocks import SSM_DATA

    return next((n for n in graph.nodes.values() if n.type_id in SSM_DATA), None)


def _names(value) -> list[str]:  # noqa: ANN001
    return [c.strip() for c in str(value or "").split(",") if c.strip()]


def spec_of(graph: Graph) -> tuple[str, dict, list[str], int]:
    """(kind, statsmodels keyword arguments, regression columns, seasonal period)."""
    model = model_node(graph)
    p = model.resolved_params()
    parts = {n.type_id: n for n in wired(graph)}
    exog: list[str] = []
    if "ssm.regression" in parts:
        exog = _names(parts["ssm.regression"].resolved_params()["columns"])
    if "ssm.arima" in parts:
        a = parts["ssm.arima"].resolved_params()
        season = int(a["season"])
        seasonal = ((int(a["seasonal_p"]), int(a["seasonal_d"]), int(a["seasonal_q"]), season)
                    if season > 1 else (0, 0, 0, 0))
        trend = a["trend"] if int(a["d"]) == 0 or a["trend"] in ("n", "t") else "n"
        return "sarimax", {"order": (int(a["p"]), int(a["d"]), int(a["q"])),
                           "seasonal_order": seasonal, "trend": trend}, exog, season
    trend_kind = (parts["ssm.trend"].resolved_params()["kind"] if "ssm.trend" in parts
                  else "fixed intercept")
    level, stoch_level, trend, stoch_trend = TREND_FLAGS[trend_kind]
    spec: dict = {"level": level, "stochastic_level": stoch_level, "trend": trend,
                  "stochastic_trend": stoch_trend, "irregular": bool(p["irregular"])}
    season = 0
    if "ssm.seasonal" in parts:
        s = parts["ssm.seasonal"].resolved_params()
        season = int(s["period"])
        if int(s["harmonics"]) > 0:
            spec["freq_seasonal"] = [{"period": season, "harmonics": int(s["harmonics"])}]
            spec["stochastic_freq_seasonal"] = [bool(s["stochastic"])]
        else:
            spec["seasonal"] = season
            spec["stochastic_seasonal"] = bool(s["stochastic"])
    if "ssm.cycle" in parts:
        c = parts["ssm.cycle"].resolved_params()
        spec.update({"cycle": True, "stochastic_cycle": bool(c["stochastic"]),
                     "damped_cycle": bool(c["damped"])})
        if float(c["max_period"]) > 0:
            spec["cycle_period_bounds"] = (float(c["min_period"]), float(c["max_period"]))
    if "ssm.autoregressive" in parts:
        spec["autoregressive"] = int(parts["ssm.autoregressive"].resolved_params()["order"])
    return "structural", spec, exog, season


def _dataset(graph: Graph) -> dict:
    node = dataset_of(graph)
    if node is None:
        return {"block": "data.structural_series", "length": 240, "slope": 0.05,
                "level_drift": 0.02, "season_length": 12, "season_amplitude": 2.0,
                "cycle_amplitude": 0.0, "noise": 0.4, "seed": 0}
    out = {"block": node.type_id, **dict(node.resolved_params())}
    raw = out.get("path")
    if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
        candidate = Path.cwd() / str(raw)
        if candidate.exists():
            out["path"] = str(candidate)
    return out


def target_of(graph: Graph) -> str:
    p = model_node(graph).resolved_params()
    if str(p["target_column"]).strip():
        return str(p["target_column"]).strip()
    data = dataset_of(graph)
    if data is not None and data.type_id == "data.timeseries_csv":
        names = _names(data.resolved_params()["target_columns"])
        if names:
            return names[0]
    return "y"


def render(graph: Graph) -> str:
    from ai_made_easy.core.ssm.rules import ssm_issues

    errors = [i for i in ssm_issues(graph) if i.severity == "error"]
    if errors:
        raise CodegenError("the state-space design has errors:\n"
                           + "\n".join(f"  - {e.message}" for e in errors))
    kind, spec, exog, season = spec_of(graph)
    p = model_node(graph).resolved_params()
    dataset = _dataset(graph)
    name = sanitize_identifier(graph.name)
    comment = (f"SARIMAX{spec['order']}x{spec['seasonal_order']}" if kind == "sarimax" else
               "structural: " + ", ".join(k for k in ("level", "trend", "seasonal",
                                                      "freq_seasonal", "cycle",
                                                      "autoregressive", "irregular")
                                          if spec.get(k)))
    if exog:
        comment += f" + regression on {', '.join(exog)}"
    data_comment = (f"{dataset['length']} generated steps (trend + season + noise)"
                    if dataset["block"] == "data.structural_series" else str(dataset["path"]))
    return _env.from_string(TEMPLATE).render(
        title=graph.name, filename=f"{name}_train_statsmodels.py", name=name, kind=kind,
        spec=spec, target=target_of(graph), exog=exog, horizon=int(p["horizon"]),
        interval=float(p["interval"]), max_iter=int(p["max_iterations"]), season=season,
        dataset=dataset, model_comment=comment, data_comment=data_comment)
