"""Training scripts for speech: keyword spotting, CTC speech recognition, audio tagging.

Self-contained like every generated script: the model, the audio readers and the
synthetic speech generator (``core.speech.runtime``), waveform augmentation, the
loss for the task (cross-entropy, CTC or binary cross-entropy), evaluation
(accuracy / F1, CER / WER, tag mAP), spectrogram sample images and the
``load_predictor`` / ``infer`` functions deploy packages serve.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.forecast.template import _picked, _strip_main
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.speech import runtime
from ai_made_easy.core.speech.tasks import dataset_of, speech_task
from ai_made_easy.core.training import catalog as cat

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

DEFAULT_DATA = {"block": "data.synthetic_speech", "task": "keywords", "n_clips": 600,
                "n_keywords": 6, "noise": 0.03, "seed": 0, "sample_rate": 16000,
                "duration": 1.0, "augment": True, "val_fraction": 0.1, "test_fraction": 0.1}

TEMPLATE = r'''"""{{ title }} — {{ task_label }} script generated by AI Made Easy.

Data:   {{ data_comment }}
Usage:  python {{ filename }}          train, evaluate, save weights + spectrogram samples
Needs:  {{ requirements }}
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import base64
import json
import math
import pickle
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from PIL import Image, ImageDraw

DATASET = {{ dataset | repr }}
TASK = "{{ task }}"            # keywords | transcripts | tags
SAMPLE_RATE = {{ sample_rate }}
N_SAMPLES = {{ n_samples }}
LABEL_SMOOTHING = {{ label_smoothing }}
ZERO_INFINITY = {{ zero_infinity }}
INPUT_SHAPE = {{ input_shape | repr }}
EPOCHS = {{ trainer.epochs }}
BATCH_SIZE = {{ batch_size }}
SEED = {{ trainer.seed }}
DEVICE = "{{ trainer.device }}"
EARLY_STOP = {{ trainer.early_stopping_patience }}
GRAD_CLIP = {{ trainer.grad_clip_norm }}
CHECKPOINT = "{{ name }}_best.pt"
INFERENCE_FILE = "inference_state.pkl"
SAMPLES_DIR = Path("eval_samples")
STATE: dict = {}
# ---------------------------------------------------------------------- model
{{ model_code }}
{{ data_code }}
{{ metrics_code }}
{{ plot_code }}


# ======================================================================== batches
def stack(records: list) -> torch.Tensor:
    return torch.from_numpy(np.stack([r["wave"] for r in records]).astype(np.float32))[:, None]


def targets(records: list, names: list):
    if TASK == "keywords":
        return torch.tensor([r["label"] for r in records])
    if TASK == "tags":
        y = torch.zeros(len(records), len(names))
        for i, r in enumerate(records):
            y[i, r["label"]] = 1.0
        return y
    return [r["label"] for r in records]   # transcripts


def augment(wave: torch.Tensor) -> torch.Tensor:
    """Random gain, circular time shift (±10 %) and background noise."""
    b = wave.shape[0]
    gain = torch.empty(b, 1, 1, device=wave.device).uniform_(0.7, 1.3)
    shift = int(random.uniform(-0.1, 0.1) * wave.shape[-1])
    wave = torch.roll(wave, shift, dims=-1) * gain
    return wave + 0.01 * torch.rand(b, 1, 1, device=wave.device) * torch.randn_like(wave)


def encode(text: str) -> list[int]:
    return [STATE["alphabet"].index(c) + 1 for c in text]


def task_loss(out: torch.Tensor, y) -> torch.Tensor:
    if TASK == "keywords":
        return nn.functional.cross_entropy(out, y.to(out.device),
                                           label_smoothing=LABEL_SMOOTHING)
    if TASK == "tags":
        return nn.functional.binary_cross_entropy_with_logits(out, y.to(out.device))
    if out.dim() != 3:
        raise SystemExit(f"speech recognition needs per-frame scores [T, alphabet + 1]; the "
                         f"model outputs {list(out.shape[1:])}")
    logp = out.float().log_softmax(-1).transpose(0, 1)      # [T, B, C]
    labels = [encode(t) for t in y]
    flat = torch.tensor([i for t in labels for i in t], dtype=torch.long)
    lengths = torch.tensor([len(t) for t in labels], dtype=torch.long)
    frames = torch.full((out.shape[0],), out.shape[1], dtype=torch.long)
    return nn.functional.ctc_loss(logp.cpu() if logp.device.type == "mps" else logp,
                                  flat, frames, lengths, blank=0, zero_infinity=ZERO_INFINITY)


@torch.no_grad()
def predict(model: nn.Module, waves: torch.Tensor, device: torch.device) -> list:
    """Per clip: class index + probabilities, tag probabilities, or a transcript."""
    model.eval()
    out = []
    for i in range(0, len(waves), 64):
        logits = model(waves[i:i + 64].to(device)).float()
        if TASK == "keywords":
            out += list(logits.softmax(-1).cpu().numpy())
        elif TASK == "tags":
            out += list(logits.sigmoid().cpu().numpy())
        else:
            out += [ctc_greedy(ids, STATE["alphabet"]) for ids in
                    logits.argmax(-1).cpu().numpy()]
    return out


def evaluate(model: nn.Module, records: list, names: list, device: torch.device) -> tuple:
    if not records:
        return {}, []
    preds = predict(model, stack(records), device)
    if TASK == "keywords":
        y = np.array([r["label"] for r in records])
        metrics = classification_scores(y, np.array([int(np.argmax(p)) for p in preds]),
                                        len(names))
    elif TASK == "tags":
        y = np.zeros((len(records), len(names)))
        for i, r in enumerate(records):
            y[i, r["label"]] = 1
        metrics = tagging_scores(y, np.stack(preds))
    else:
        refs = [r["label"] for r in records]
        metrics = {"cer": error_rate(refs, preds, False), "wer": error_rate(refs, preds, True),
                   "exact": float(np.mean([r == p for r, p in zip(refs, preds)]))}
    return metrics, preds


def score_of(metrics: dict) -> float:
    """Lower is better: the early-stopping / checkpoint criterion."""
    if TASK == "keywords":
        return -metrics.get("accuracy", 0.0)
    if TASK == "tags":
        return -metrics.get("map", 0.0)
    return metrics.get("cer", math.inf)


def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def report_resources(device: torch.device, step_seconds: float) -> None:
    peak = 0.0
    if device.type == "cuda":
        peak = torch.cuda.max_memory_allocated(device) / 2**20
    elif device.type == "mps":
        peak = torch.mps.driver_allocated_memory() / 2**20
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


def fit(model: nn.Module, train: list, val: list, names: list,
        device: torch.device) -> nn.Module:
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% endif %}
    waves, ys = stack(train), targets(train, names)
    best, best_state, bad = math.inf, None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, running, steps = time.time(), 0.0, 0
        order = torch.randperm(len(waves))
        for start in range(0, len(waves), BATCH_SIZE):
            idx = order[start:start + BATCH_SIZE]
            x = waves[idx].to(device)
            if DATASET.get("augment"):
                x = augment(x)
            y = [ys[int(i)] for i in idx] if TASK == "transcripts" else ys[idx]
            loss = task_loss(model(x), y)
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            if GRAD_CLIP > 0:
                nn.utils.clip_grad_norm_(params, GRAD_CLIP)
            optimizer.step()
{% if scheduler_step == "batch" %}
            scheduler.step()
{% endif %}
            running += loss.item() * len(idx)
            steps += 1
        if epoch == 1:
            report_resources(device, (time.time() - started) / max(steps, 1))
        metrics, _ = evaluate(model, val, names, device)
        score = score_of(metrics) if metrics else running / max(len(waves), 1)
{% if scheduler_step == "epoch" %}
        scheduler.step()
{% elif scheduler_step == "metric" %}
        scheduler.step(score)
{% endif %}
        shown = " ".join(f"val_{k}={v:.4f}" for k, v in metrics.items() if isinstance(v, float))
        print(f"epoch {epoch}/{EPOCHS} train_loss={running / max(len(waves), 1):.4f} {shown} "
              f"lr={optimizer.param_groups[0]['lr']:.3g} ({time.time() - started:.1f}s)",
              flush=True)
        if score < best:
            best, bad = score, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if EARLY_STOP and bad >= EARLY_STOP:
                print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    return model


def describe_label(label, names: list) -> str:
    if TASK == "keywords":
        return names[label]
    if TASK == "tags":
        return ", ".join(names[i] for i in label) or "(none)"
    return label


def describe_pred(pred, names: list) -> str:
    if TASK == "keywords":
        i = int(np.argmax(pred))
        return f"{names[i]} ({pred[i]:.0%})"
    if TASK == "tags":
        return ", ".join(f"{names[i]} {pred[i]:.0%}" for i in np.flatnonzero(pred >= 0.5)) \
            or "(none)"
    return pred or "(nothing)"


def save_samples(records: list, preds: list, names: list, keep: int = 8) -> None:
    SAMPLES_DIR.mkdir(exist_ok=True)
    for i, (r, p) in enumerate(list(zip(records, preds))[:keep]):
        spectrogram_image(r["wave"], f"true: {describe_label(r['label'], names)}",
                          f"predicted: {describe_pred(p, names)}").save(
            SAMPLES_DIR / f"sample_{i}.png")


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    global _PREDICTOR
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    model = build_model()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    _PREDICTOR = model.eval().to(device)
    return _PREDICTOR


def to_wave(item) -> np.ndarray:
    """A waveform list, {"waveform": [...], "sample_rate": n}, or WAV bytes / base64."""
    if isinstance(item, dict):
        wave = np.asarray(item["waveform"], np.float32)
        rate = int(item.get("sample_rate", SAMPLE_RATE))
    elif isinstance(item, (bytes, bytearray, str)):
        data = base64.b64decode(item) if isinstance(item, str) else bytes(item)
        wave, rate = decode_wav_bytes(data)
    else:
        wave, rate = np.asarray(item, np.float32).reshape(-1), SAMPLE_RATE
    return fit_length(resample(wave, rate, SAMPLE_RATE), N_SAMPLES)


@torch.no_grad()
def infer(raw: list) -> list[dict]:
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    names = STATE["names"]
    waves = torch.from_numpy(np.stack([to_wave(item) for item in raw]))[:, None]
    results = []
    for pred in predict(_PREDICTOR, waves, device):
        if TASK == "keywords":
            i = int(np.argmax(pred))
            results.append({"label": names[i], "score": round(float(pred[i]), 4),
                            "probabilities": {n: round(float(v), 4)
                                              for n, v in zip(names, pred)}})
        elif TASK == "tags":
            results.append({"tags": [names[i] for i in np.flatnonzero(pred >= 0.5)],
                            "scores": {n: round(float(v), 4) for n, v in zip(names, pred)}})
        else:
            results.append({"text": pred})
    return results


def main() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    records, names = load_speech(DATASET)
    if not records:
        raise SystemExit("no audio clips found")
    STATE.update(names=names, alphabet=DATASET.get("alphabet", ALPHABET))
    if TASK == "transcripts":
        longest = max(len(r["label"]) for r in records)
        print(f"longest transcript: {longest} characters")
    splits = split_records(records, float(DATASET["val_fraction"]),
                           float(DATASET["test_fraction"]), SEED)
    if not splits["train"]:
        raise SystemExit("no training clips: lower val_fraction / test_fraction")
    print(f"clips: train={len(splits['train'])} val={len(splits['val'])} "
          f"test={len(splits['test'])} classes={len(names)}")
    val = splits["val"] or splits["train"]
    model = build_model().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    model = fit(model, splits["train"], val, names, device)
    torch.save(model.state_dict(), CHECKPOINT)
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    print(f"saved best weights to {CHECKPOINT}")
    test = splits["test"] or val
    metrics, preds = evaluate(model, test, names, device)
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()
                              if isinstance(v, float)))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))
    Path("classes.json").write_text(json.dumps(names))
    save_samples(test, preds, names)
    print(f"saved spectrogram samples to {SAMPLES_DIR}/")


if __name__ == "__main__":
    main()
'''


def _dataset(graph: Graph) -> dict:
    node = dataset_of(graph)
    if node is None:
        return dict(DEFAULT_DATA)
    out = {"block": node.type_id, **dict(node.resolved_params())}
    raw = out.get("path")
    if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
        candidate = Path.cwd() / str(raw)
        if candidate.exists():
            out["path"] = str(candidate)
    return out


TASK_LABELS = {"keywords": "keyword spotting", "transcripts": "speech recognition (CTC)",
               "tags": "audio tagging"}
OWN_LOSS = {"keywords": "train.loss_cross_entropy", "transcripts": "speech.loss_ctc",
            "tags": "train.loss_bce_logits"}


def context(graph: Graph, framework: str) -> dict:
    if framework != "pytorch":
        raise CodegenError("speech tasks train with PyTorch: choose the PyTorch framework")
    if speech_task(graph) is None:
        raise CodegenError("not a speech design")
    dataset = _dataset(graph)
    if dataset_of(graph) is None:
        dataset["task"] = "transcripts"   # only a CTC loss marks this design as speech
    task = dataset["task"]
    notes: list[str] = []
    if dataset_of(graph) is None:
        notes.append("no dataset block: training on generated tone-coded speech")
    losses = [n for n in graph.nodes.values() if n.type_id in cat.LOSS_IDS
              or n.type_id == "speech.loss_ctc"]
    for node in losses:
        if node.type_id != OWN_LOSS[task]:
            notes.append(f"{node.definition().display_name} is ignored: {TASK_LABELS[task]} "
                         "trains with its own loss")
    ce = next((dict(n.resolved_params()) for n in losses
               if n.type_id == "train.loss_cross_entropy"), {})
    ctc = next((dict(n.resolved_params()) for n in losses if n.type_id == "speech.loss_ctc"),
               {"zero_infinity": True})
    chain = graph.model_nodes()
    input_shape = list(graph.infer_shapes()[chain[0].instance_id])
    _t, trainer = _picked(graph, ("train.trainer",))
    trainer = cat.resolved("train.trainer", trainer)
    _l, loader = _picked(graph, ("prep.dataloader",))
    opt, opt_params = _picked(graph, cat.OPTIMIZER_IDS)
    optimizer = ("torch.optim.AdamW(params, lr=0.001)" if opt is None else
                 cat.render(opt.type_id, cat.resolved(opt.type_id, opt_params), "pytorch")
                 .replace("model.parameters()", "params"))
    sched, sched_params = _picked(graph, cat.SCHEDULER_IDS)
    name = sanitize_identifier(graph.name)
    rate = int(dataset["sample_rate"])
    model_code = generate(graph, "pytorch")
    from ai_made_easy.core.training.generate import own_loop_requirements

    return {
        "requirements": own_loop_requirements(model_code),
        "title": graph.name, "filename": f"{name}_train_pytorch.py", "name": name,
        "notes": notes, "data_comment": _data_comment(dataset), "task": task,
        "task_label": TASK_LABELS[task], "dataset": dataset, "sample_rate": rate,
        "n_samples": int(round(float(dataset["duration"]) * rate)),
        "label_smoothing": float(ce.get("label_smoothing", 0.0)),
        "zero_infinity": bool(ctc.get("zero_infinity", True)),
        "input_shape": input_shape, "trainer": trainer,
        "batch_size": int(loader.get("batch_size") or 0) or int(trainer["batch_size"]),
        "model_code": _strip_main(model_code),
        "data_code": runtime.DATA_CODE, "metrics_code": runtime.METRICS_CODE,
        "plot_code": runtime.PLOT_CODE, "optimizer_expr": optimizer,
        "scheduler_expr": (cat.render(sched.type_id, cat.resolved(sched.type_id, sched_params),
                                      "pytorch") if sched else None),
        "scheduler_step": cat.COMPONENTS[sched.type_id].meta["step"] if sched else None,
    }


def _data_comment(dataset: dict) -> str:
    if dataset["block"] == "data.synthetic_speech":
        return (f"{dataset['n_clips']} generated {dataset['task']} clips of "
                f"{dataset['duration']} s at {dataset['sample_rate']} Hz")
    return f"{dataset['path']} ({dataset['task']}, {dataset['sample_rate']} Hz)"


def render(graph: Graph, _spec, framework: str) -> str:
    return _env.from_string(TEMPLATE).render(**context(graph, framework))


def register() -> None:
    from ai_made_easy.core.training.generate import register_trainer

    register_trainer("speech", render, needs_spec=False)
