"""Training scripts for graph neural networks (PyTorch Geometric).

Node classification trains full-batch on one graph with node masks; graph classification
batches whole graphs (PyG ``DataLoader``); link prediction hides validation / test edges
from message passing, samples non-edges and trains the network as a node encoder with
the Link Predictor's decoder.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.forecast.template import _picked, _strip_main
from ai_made_easy.core.gnn import runtime
from ai_made_easy.core.gnn.tasks import dataset_of, graph_kind
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.training import catalog as cat

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

TEMPLATE = r'''"""{{ title }} — graph neural network training script generated by AI Made Easy.

Task:   {{ task_label }}
Data:   {{ data_comment }}
Usage:  python {{ filename }}          train, save weights and metrics
Needs:  {{ requirements }}
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import json
import math
import pickle
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

DATASET = {{ dataset | repr }}
KIND = "{{ kind }}"            # node_classification | graph_classification | link_prediction
LINK = {{ link | repr }}
INPUT_SHAPE = {{ input_shape | repr }}
EPOCHS = {{ trainer.epochs }}
BATCH_SIZE = {{ batch_size }}
SEED = {{ trainer.seed }}
DEVICE = "{{ trainer.device }}"
EARLY_STOP = {{ trainer.early_stopping_patience }}
GRAD_CLIP = {{ trainer.grad_clip_norm or 0 }}
CHECKPOINT = "{{ name }}_best.pt"
INFERENCE_FILE = "inference_state.pkl"
STATE: dict = {}
# ---------------------------------------------------------------------- model
{{ model_code }}
{{ data_code }}
{{ metrics_code }}


def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")        # (MPS lacks scatter ops some layers use)


def report_resources(device: torch.device, step_seconds: float) -> None:
    peak = torch.cuda.max_memory_allocated(device) / 2**20 if device.type == "cuda" else 0.0
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


def tensors(g: dict, device) -> tuple:
    return (torch.from_numpy(np.asarray(g["x"], np.float32)).to(device),
            torch.from_numpy(np.asarray(g["edge_index"], np.int64)).to(device))


class LinkModel(nn.Module):
    """The designed network as a node encoder plus the Link Predictor's decoder."""

    def __init__(self) -> None:
        super().__init__()
        self.encoder = build_model()
        self.decoder = None
        if LINK and LINK["decoder"] == "mlp":
            width = OUTPUT_DIM
            self.decoder = nn.Sequential(nn.Linear(width, LINK["hidden"]), nn.ReLU(),
                                         nn.Linear(LINK["hidden"], 1))

    def forward(self, x, edge_index=None, batch=None):
        return self.encoder(x, edge_index, batch)

    def score(self, z: torch.Tensor, pairs: torch.Tensor) -> torch.Tensor:
        h = z[pairs[0]] * z[pairs[1]]
        return h.sum(-1) if self.decoder is None else self.decoder(h).squeeze(-1)


OUTPUT_DIM = {{ output_dim }}


def make_model() -> nn.Module:
    return LinkModel() if KIND == "link_prediction" else build_model()


# ======================================================================== training loops
def _optimizer(model):
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% else %}
    scheduler = None
{% endif %}
    return params, optimizer, scheduler


def _step(loss, params, optimizer, scheduler) -> None:
    if not torch.isfinite(loss):
        raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    if GRAD_CLIP:
        nn.utils.clip_grad_norm_(params, GRAD_CLIP)
    optimizer.step()
{% if scheduler_step == "batch" %}
    scheduler.step()
{% endif %}


def _epoch_end(scheduler, metric: float) -> None:
{% if scheduler_step == "epoch" %}
    scheduler.step()
{% elif scheduler_step == "metric" %}
    scheduler.step(metric)
{% else %}
    return None
{% endif %}


def _log(epoch: int, train_loss: float, val: dict, optimizer, started: float) -> None:
    shown = " ".join(f"val_{k}={v:.4f}" for k, v in val.items())
    print(f"epoch {epoch}/{EPOCHS} train_loss={train_loss:.4f} {shown} "
          f"lr={optimizer.param_groups[0]['lr']:.3g} ({time.time() - started:.2f}s)",
          flush=True)


def train_loop(model, run_epoch, evaluate_val, key: str, larger_is_better: bool, device):
    params, optimizer, scheduler = _optimizer(model)
    best, best_state, bad = -math.inf, None, 0
    for epoch in range(1, EPOCHS + 1):
        started = time.time()
        model.train()
        train_loss = run_epoch(params, optimizer, scheduler)
        if epoch == 1:
            report_resources(device, time.time() - started)
        model.eval()
        with torch.no_grad():
            val = evaluate_val()
        score = val[key] if larger_is_better else -val[key]
        _epoch_end(scheduler, -score)
        _log(epoch, train_loss, val, optimizer, started)
        if score > best or best_state is None:
            best, bad = score, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if EARLY_STOP and bad >= EARLY_STOP:
                print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    model.load_state_dict(best_state)
    return model


# ---------------------------------------------------------------- node classification
def node_task(g: dict, device) -> dict:
    x, ei = tensors(g, device)
    y = torch.from_numpy(np.asarray(g["y"], np.int64)).to(device)
    if "masks" in g:
        parts = {k: np.flatnonzero(v) for k, v in g["masks"].items()}
    else:
        parts = split_ids(len(g["x"]), float(DATASET.get("val_fraction", 0.1)),
                          float(DATASET.get("test_fraction", 0.2)), SEED)
    idx = {k: torch.from_numpy(v).to(device) for k, v in parts.items()}
    n_classes = len(g["classes"])
    print(f"nodes: train={len(parts['train'])} val={len(parts['val'])} "
          f"test={len(parts['test'])} classes={n_classes}")
    model = make_model().to(device)
    loss_fn = nn.CrossEntropyLoss()

    def run_epoch(params, optimizer, scheduler):
        out = model(x, ei)
        loss = loss_fn(out[idx["train"]], y[idx["train"]])
        _step(loss, params, optimizer, scheduler)
        return loss.item()

    def scores(part: str) -> dict:
        out = model(x, ei)
        pred = out[idx[part]].argmax(-1).cpu().numpy()
        m = accuracy_f1(pred, y[idx[part]].cpu().numpy(), n_classes)
        m["loss"] = float(loss_fn(out[idx[part]], y[idx[part]]))
        return m

    model = train_loop(model, run_epoch, lambda: scores("val" if len(parts["val"]) else "train"),
                       "accuracy", True, device)
    model.eval()
    with torch.no_grad():
        metrics = scores("test" if len(parts["test"]) else "val")
    STATE.update({"classes": g["classes"], "x": np.asarray(g["x"], np.float32),
                  "edge_index": np.asarray(g["edge_index"], np.int64), "ids": g.get("ids")})
    return model, metrics


# ---------------------------------------------------------------- graph classification
def to_data(g: dict):
    from torch_geometric.data import Data

    return Data(x=torch.from_numpy(np.asarray(g["x"], np.float32)),
                edge_index=torch.from_numpy(np.asarray(g["edge_index"], np.int64)),
                y=torch.tensor([int(g["y"])]))


def graph_task(graphs: list, classes: list, device) -> dict:
    from torch_geometric.loader import DataLoader

    parts = split_ids(len(graphs), float(DATASET.get("val_fraction", 0.1)),
                      float(DATASET.get("test_fraction", 0.2)), SEED)
    sets = {k: [to_data(graphs[i]) for i in v] for k, v in parts.items()}
    print(f"graphs: train={len(sets['train'])} val={len(sets['val'])} "
          f"test={len(sets['test'])} classes={len(classes)}")
    train_loader = DataLoader(sets["train"], batch_size=BATCH_SIZE, shuffle=True)
    model = make_model().to(device)
    loss_fn = nn.CrossEntropyLoss()

    def run_epoch(params, optimizer, scheduler):
        total, count = 0.0, 0
        for batch in train_loader:
            batch = batch.to(device)
            loss = loss_fn(model(batch.x, batch.edge_index, batch.batch), batch.y)
            _step(loss, params, optimizer, scheduler)
            total += loss.item() * batch.num_graphs
            count += batch.num_graphs
        return total / max(count, 1)

    def scores(items: list) -> dict:
        preds, ys, loss = [], [], 0.0
        for batch in DataLoader(items, batch_size=256):
            batch = batch.to(device)
            out = model(batch.x, batch.edge_index, batch.batch)
            loss += float(loss_fn(out, batch.y)) * batch.num_graphs
            preds.append(out.argmax(-1).cpu().numpy())
            ys.append(batch.y.cpu().numpy())
        m = accuracy_f1(np.concatenate(preds), np.concatenate(ys), len(classes))
        m["loss"] = loss / max(len(items), 1)
        return m

    model = train_loop(model, run_epoch, lambda: scores(sets["val"] or sets["train"]),
                       "accuracy", True, device)
    model.eval()
    with torch.no_grad():
        metrics = scores(sets["test"] or sets["val"])
    counts = np.bincount([int(graphs[i]["y"]) for i in parts["train"]], minlength=len(classes))
    metrics["baseline_accuracy"] = float(counts.max() / max(counts.sum(), 1))
    STATE.update({"classes": classes})
    return model, metrics


# ---------------------------------------------------------------- link prediction
def edge_split(edge_index: np.ndarray, n_nodes: int) -> dict:
    """Unique undirected edges split into train / val / test; message passing sees only
    the training edges (both directions)."""
    pairs = edge_index[:, edge_index[0] < edge_index[1]]
    parts = split_ids(pairs.shape[1], float(DATASET.get("val_fraction", 0.1)),
                      float(DATASET.get("test_fraction", 0.2)), SEED)
    out = {k: pairs[:, v] for k, v in parts.items()}
    rng = np.random.default_rng(SEED + 1)
    existing = set(map(tuple, pairs.T.tolist()))
    for k in ("val", "test"):                       # fixed non-edges for evaluation
        neg = []
        while len(neg) < out[k].shape[1]:
            u, v = sorted(rng.integers(0, n_nodes, 2).tolist())
            if u != v and (u, v) not in existing:
                neg.append((u, v))
        out[k + "_neg"] = np.array(neg, np.int64).T.reshape(2, -1)
    out["message"] = _undirected(out["train"])
    return out


def link_task(g: dict, device) -> dict:
    from torch_geometric.utils import negative_sampling

    n = len(g["x"])
    split = edge_split(np.asarray(g["edge_index"], np.int64), n)
    print(f"edges: train={split['train'].shape[1]} val={split['val'].shape[1]} "
          f"test={split['test'].shape[1]} nodes={n}")
    x = torch.from_numpy(np.asarray(g["x"], np.float32)).to(device)
    mp = torch.from_numpy(split["message"]).to(device)
    pos = torch.from_numpy(split["train"]).to(device)
    model = make_model().to(device)
    bce = nn.BCEWithLogitsLoss()
    n_neg = max(1, int(round(pos.shape[1] * LINK["negatives"])))

    def run_epoch(params, optimizer, scheduler):
        z = model(x, mp)
        neg = negative_sampling(mp, num_nodes=n, num_neg_samples=n_neg)
        logits = torch.cat([model.score(z, pos), model.score(z, neg)])
        labels = torch.cat([torch.ones(pos.shape[1]), torch.zeros(neg.shape[1])]).to(device)
        loss = bce(logits, labels)
        _step(loss, params, optimizer, scheduler)
        return loss.item()

    def scores(part: str) -> dict:
        z = model(x, mp)
        p = torch.from_numpy(split[part]).to(device)
        q = torch.from_numpy(split[part + "_neg"]).to(device)
        s = torch.cat([model.score(z, p), model.score(z, q)]).cpu().numpy()
        labels = np.concatenate([np.ones(p.shape[1]), np.zeros(q.shape[1])])
        return {"roc_auc": roc_auc(s, labels), "average_precision": average_precision(s, labels)}

    part = "val" if split["val"].shape[1] else "train"
    if part == "train":
        split["train_neg"] = split.get("val_neg", np.zeros((2, 0), np.int64))
    model = train_loop(model, run_epoch, lambda: scores(part), "roc_auc", True, device)
    model.eval()
    with torch.no_grad():
        metrics = scores("test" if split["test"].shape[1] else part)
    STATE.update({"x": np.asarray(g["x"], np.float32), "edge_index": split["message"],
                  "ids": g.get("ids")})
    return model, metrics


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    global _PREDICTOR
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    model = make_model()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    _PREDICTOR = model.eval().to(device)
    return _PREDICTOR


def _graph_from(item: dict) -> tuple:
    """A request graph: {"x": [[...]], "edges": [[u, v], ...]} (undirected), or the
    training graph when x is missing."""
    if "x" not in item:
        if "x" not in STATE:
            raise ValueError("send a graph: {\"x\": [[features]], \"edges\": [[u, v], ...]}")
        return STATE["x"], STATE["edge_index"]
    x = np.asarray(item["x"], np.float32).reshape(len(item["x"]), -1)
    edges = np.asarray(item.get("edges") or [], np.int64).reshape(-1, 2).T
    return x, _undirected(edges)


def _labels(logits: torch.Tensor) -> list:
    probs = logits.softmax(-1).cpu().numpy()
    classes = STATE["classes"]
    return [{"label": classes[int(p.argmax())], "confidence": round(float(p.max()), 6),
             "probabilities": {c: round(float(v), 6) for c, v in zip(classes, p)}}
            for p in probs]


@torch.no_grad()
def infer(raw: list) -> list:
    """node_classification: a graph {"x", "edges"} -> one prediction per node, or
    {"nodes": [index, ...]} for nodes of the training graph. graph_classification: a graph
    -> its class. link_prediction: {"pairs": [[u, v], ...]} (optionally with "x" and
    "edges") -> edge probabilities."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    out = []
    for item in raw:
        item = item if isinstance(item, dict) else {"nodes": [int(item)]}
        x, ei = _graph_from(item)
        xt = torch.from_numpy(x).to(device)
        et = torch.from_numpy(ei).to(device)
        if KIND == "graph_classification":
            out.append(_labels(_PREDICTOR(xt, et))[0])
        elif KIND == "node_classification":
            rows = _labels(_PREDICTOR(xt, et))
            wanted = item.get("nodes")
            out.append({"nodes": [dict(r, node=i) for i, r in enumerate(rows)
                                  if wanted is None or i in set(wanted)]})
        else:
            pairs = torch.as_tensor(np.asarray(item["pairs"], np.int64).reshape(-1, 2).T,
                                    device=device)
            z = _PREDICTOR(xt, et)
            p = torch.sigmoid(_PREDICTOR.score(z, pairs)).cpu().numpy()
            out.append({"pairs": [[int(u), int(v), round(float(s), 6)]
                                  for (u, v), s in zip(pairs.T.tolist(), p)]})
    return out


def main() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    data = load_graph_data(DATASET)
    if KIND == "graph_classification":
        graphs, classes = data
        width = graphs[0]["x"].shape[1]
    else:
        width = data["x"].shape[1]
        print("graph: " + " ".join(f"{k}={v}" for k, v in graph_stats(data).items()))
        if KIND == "node_classification" and "y" not in data:
            raise SystemExit("the node table has no label column: set label_column, or add a "
                             "Link Predictor for link prediction")
    if width != INPUT_SHAPE[0]:
        raise SystemExit(f"nodes have {width} features but the Input holds {INPUT_SHAPE[0]}")
    if KIND == "graph_classification":
        model, metrics = graph_task(graphs, classes, device)
    elif KIND == "node_classification":
        model, metrics = node_task(data, device)
    else:
        model, metrics = link_task(data, device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    torch.save(model.state_dict(), CHECKPOINT)
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    if "classes" in STATE:
        Path("classes.json").write_text(json.dumps(STATE["classes"]))
    print(f"saved best weights to {CHECKPOINT}")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))


if __name__ == "__main__":
    main()
'''

TASK_LABELS = {"node_classification": "node classification",
               "graph_classification": "graph classification",
               "link_prediction": "link prediction"}


def _dataset(graph: Graph) -> dict:
    node = dataset_of(graph)
    if node is None and graph_kind(graph) == "graph_classification":
        return {"block": "data.synthetic_graphs", "n_graphs": 600, "min_nodes": 12,
                "max_nodes": 24, "feature_dim": 8, "seed": 0, "val_fraction": 0.1,
                "test_fraction": 0.2}
    if node is None:
        return {"block": "data.synthetic_graph", "n_nodes": 600, "communities": 4,
                "p_in": 0.05, "p_out": 0.005, "feature_dim": 16, "feature_signal": 0.5,
                "seed": 0, "val_fraction": 0.1, "test_fraction": 0.2}
    out = {"block": node.type_id, **dict(node.resolved_params())}
    for key in ("nodes_path", "edges_path"):
        raw = out.get(key)
        if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
            candidate = Path.cwd() / str(raw)
            if candidate.exists():
                out[key] = str(candidate)
    return out


def _comment(d: dict) -> str:
    block = d["block"]
    if block == "data.synthetic_graph":
        return f"{d['n_nodes']} nodes in {d['communities']} communities (generated)"
    if block == "data.synthetic_graphs":
        return f"{d['n_graphs']} generated graphs with a planted motif"
    if block in ("data.planetoid", "data.tudataset"):
        return f"{d['name']} benchmark"
    return f"{d['nodes_path']} + {d['edges_path']}"


def context(graph: Graph, framework: str) -> dict:
    from ai_made_easy.core.training.generate import own_loop_requirements

    if framework != "pytorch":
        raise CodegenError("graph neural networks train with PyTorch Geometric: choose the "
                           "PyTorch framework")
    kind = graph_kind(graph)
    notes: list[str] = []
    dataset = _dataset(graph)
    if dataset_of(graph) is None:
        notes.append("no dataset block: training on generated "
                     + ("motif graphs" if kind == "graph_classification"
                        else "community graph"))
    loss = next((n for n in graph.nodes.values() if n.type_id in cat.LOSS_IDS), None)
    if loss is not None and (kind == "link_prediction"
                             or loss.type_id != "train.loss_cross_entropy"):
        notes.append(f"the {loss.definition().display_name} block is ignored: "
                     + ("link prediction trains with binary cross-entropy on edges"
                        if kind == "link_prediction" else "classification uses cross-entropy"))
    link = None
    decoder = next((n for n in graph.nodes.values() if n.type_id == "graph.link_decoder"), None)
    if decoder is not None:
        p = decoder.resolved_params()
        link = {"decoder": p["decoder"], "hidden": int(p["hidden"]),
                "negatives": float(p["negatives"])}
    chain = graph.model_nodes()
    shapes = graph.infer_shapes()
    _t, trainer = _picked(graph, ("train.trainer",))
    trainer = cat.resolved("train.trainer", trainer)
    _l, loader = _picked(graph, ("prep.dataloader",))
    opt, opt_params = _picked(graph, cat.OPTIMIZER_IDS)
    optimizer = ("torch.optim.Adam(params, lr=0.01, weight_decay=5e-4)" if opt is None else
                 cat.render(opt.type_id, cat.resolved(opt.type_id, opt_params), "pytorch")
                 .replace("model.parameters()", "params"))
    sched, sched_params = _picked(graph, cat.SCHEDULER_IDS)
    model_code = generate(graph, "pytorch")
    name = sanitize_identifier(graph.name)
    extra = ("pandas",) if dataset["block"] == "data.graph_csv" else ()
    return {
        "title": graph.name, "filename": f"{name}_train_pytorch.py", "name": name,
        "kind": kind, "task_label": TASK_LABELS[kind], "notes": notes, "link": link,
        "requirements": own_loop_requirements(model_code, ("torch_geometric", "scipy",
                                                           *extra)),
        "data_comment": _comment(dataset), "dataset": dataset,
        "input_shape": list(shapes[chain[0].instance_id]),
        "output_dim": int(shapes[chain[-1].instance_id][-1]), "trainer": trainer,
        "batch_size": int(loader.get("batch_size") or 0) or int(trainer["batch_size"]),
        "model_code": _strip_main(model_code), "data_code": runtime.DATA_CODE,
        "metrics_code": runtime.METRICS_CODE, "optimizer_expr": optimizer,
        "scheduler_expr": (cat.render(sched.type_id, cat.resolved(sched.type_id, sched_params),
                                      "pytorch") if sched else None),
        "scheduler_step": cat.COMPONENTS[sched.type_id].meta["step"] if sched else None,
    }


def render(graph: Graph, _spec, framework: str) -> str:
    return _env.from_string(TEMPLATE).render(**context(graph, framework))
