"""Training scripts for recommenders.

Every user's interactions are split into train / validation / test. Implicit feedback
trains with BPR (a seen item must outscore a sampled unseen one) or binary cross-entropy
against sampled negatives; ratings train with MSE. Evaluation ranks every item for each
user (training items excluded) and reports Recall@K, NDCG@K and MRR next to a
most-popular baseline.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.forecast.template import _picked, _strip_main
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.recsys import runtime
from ai_made_easy.core.recsys.tasks import dataset_of
from ai_made_easy.core.training import catalog as cat

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

TEMPLATE = r'''"""{{ title }} — recommender training script generated by AI Made Easy.

Data:   {{ data_comment }}
Usage:  python {{ filename }}          train, save weights and ranking metrics
Needs:  {{ requirements }}
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import json
import math
import pickle
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

DATASET = {{ dataset | repr }}
OBJECTIVE = {{ objective | repr }}           # auto | bpr | bce | mse
NEGATIVES = {{ negatives }}
TOP_K = {{ top_k }}
INPUT_SHAPE = {{ input_shape | repr }}
EPOCHS = {{ trainer.epochs }}
BATCH_SIZE = {{ batch_size }}
SEED = {{ trainer.seed }}
DEVICE = "{{ trainer.device }}"
EARLY_STOP = {{ trainer.early_stopping_patience }}
EVAL_USERS = 500                             # users ranked per validation pass
CHECKPOINT = "{{ name }}_best.pt"
INFERENCE_FILE = "inference_state.pkl"
STATE: dict = {}
# ---------------------------------------------------------------------- model
{{ model_code }}
{{ data_code }}
{{ metrics_code }}


def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def report_resources(device: torch.device, step_seconds: float) -> None:
    peak = torch.cuda.max_memory_allocated(device) / 2**20 if device.type == "cuda" else 0.0
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


# ======================================================================== rows
class Rows:
    """Builds model inputs [user, item, *user features, *item features]."""

    def __init__(self, data: dict, device) -> None:
        self.device = device
        uf, itf = data["user_features"], data["item_features"]
        extra = INPUT_SHAPE[0] - 2
        if extra not in (0, uf.shape[1] + itf.shape[1]):
            raise SystemExit(f"the Input holds {INPUT_SHAPE[0]} values but rows are 2 ids + "
                             f"{uf.shape[1] + itf.shape[1]} features")
        self.uf = torch.from_numpy(uf).to(device) if extra else None
        self.itf = torch.from_numpy(itf).to(device) if extra else None

    def __call__(self, users: torch.Tensor, items: torch.Tensor) -> torch.Tensor:
        parts = [users.float().unsqueeze(1), items.float().unsqueeze(1)]
        if self.uf is not None:
            parts += [self.uf[users], self.itf[items]]
        return torch.cat(parts, dim=1)


@torch.no_grad()
def score_matrix(model, rows: Rows, users: np.ndarray, n_items: int, device) -> np.ndarray:
    model.eval()
    items = torch.arange(n_items, device=device)
    out = np.zeros((len(users), n_items), np.float32)
    per = max(1, 200_000 // n_items)
    for start in range(0, len(users), per):
        chunk = torch.as_tensor(users[start:start + per], device=device)
        u = chunk.repeat_interleave(n_items)
        i = items.repeat(len(chunk))
        out[start:start + len(chunk)] = model(rows(u, i)).reshape(len(chunk), n_items).cpu()
    return out


def evaluate(model, rows, data, seen: list, held: list, users: np.ndarray, device,
             relevant_rating: float | None) -> dict:
    scores = score_matrix(model, rows, users, data["n_items"], device)
    for r, u in enumerate(users):
        scores[r, list(seen[u])] = -np.inf
    return ranking_metrics(scores, [held[u] for u in users], TOP_K)


def item_sets(data: dict, idx: np.ndarray, min_rating: float | None = None) -> list:
    sets = [set() for _ in range(data["n_users"])]
    for k in idx:
        if min_rating is None or data["ratings"] is None or data["ratings"][k] >= min_rating:
            sets[data["users"][k]].add(int(data["items"][k]))
    return sets


# ======================================================================== training
def train(model, data, parts, rows, device):
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% endif %}
    objective = OBJECTIVE if OBJECTIVE != "auto" else ("mse" if data["ratings"] is not None
                                                       else "bpr")
    print(f"objective: {objective}")
    tr = parts["train"]
    users = torch.as_tensor(data["users"][tr], device=device)
    items = torch.as_tensor(data["items"][tr], device=device)
    ratings = (torch.as_tensor(data["ratings"][tr], dtype=torch.float32, device=device)
               if data["ratings"] is not None else None)
    seen_train = item_sets(data, tr)
    relevant = 4.0 if data["ratings"] is not None else None
    held_val = item_sets(data, parts["val"], relevant)
    val_users = np.array([u for u in range(data["n_users"]) if held_val[u]])
    val_users = np.random.default_rng(SEED).permutation(val_users)[:EVAL_USERS]
    best, best_state, bad = -math.inf, None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, total, steps = time.time(), 0.0, 0
        order = torch.randperm(len(tr), device=device)
        for start in range(0, len(tr), BATCH_SIZE):
            b = order[start:start + BATCH_SIZE]
            u, i = users[b], items[b]
            if objective == "mse":
                loss = nn.functional.mse_loss(model(rows(u, i)).squeeze(-1), ratings[b])
            elif objective == "bpr":
                j = torch.randint(0, data["n_items"], (len(b),), device=device)
                diff = model(rows(u, i)).squeeze(-1) - model(rows(u, j)).squeeze(-1)
                loss = -nn.functional.logsigmoid(diff).mean()
            else:
                uu = u.repeat_interleave(NEGATIVES)
                j = torch.randint(0, data["n_items"], (len(uu),), device=device)
                logits = torch.cat([model(rows(u, i)), model(rows(uu, j))]).squeeze(-1)
                labels = torch.cat([torch.ones(len(u)), torch.zeros(len(uu))]).to(device)
                loss = nn.functional.binary_cross_entropy_with_logits(logits, labels)
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()
{% if scheduler_step == "batch" %}
            scheduler.step()
{% endif %}
            total += loss.item()
            steps += 1
        if epoch == 1:
            report_resources(device, (time.time() - started) / max(steps, 1))
        val = (evaluate(model, rows, data, seen_train, held_val, val_users, device, relevant)
               if len(val_users) else {f"ndcg_at_{TOP_K}": -total})
        key = val[f"ndcg_at_{TOP_K}"]
{% if scheduler_step == "epoch" %}
        scheduler.step()
{% elif scheduler_step == "metric" %}
        scheduler.step(-key)
{% endif %}
        shown = " ".join(f"val_{k}={v:.4f}" for k, v in val.items())
        print(f"epoch {epoch}/{EPOCHS} train_loss={total / max(steps, 1):.4f} {shown} "
              f"lr={optimizer.param_groups[0]['lr']:.3g} ({time.time() - started:.1f}s)",
              flush=True)
        if key > best:
            best, bad = key, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if EARLY_STOP and bad >= EARLY_STOP:
                print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    model.load_state_dict(best_state)
    return model


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    global _PREDICTOR
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    model = build_model()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    _PREDICTOR = model.eval().to(device)
    return _PREDICTOR


@torch.no_grad()
def infer(raw: list) -> list[dict]:
    """{"user": id, "k": 10, "exclude_seen": true} -> the top-k items; {"user": id,
    "items": [ids]} -> their scores. Unknown users get the most popular items."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    users, items = STATE["user_index"], STATE["item_ids"]
    rows = Rows({"user_features": STATE["user_features"],
                 "item_features": STATE["item_features"]}, device)
    out = []
    for item in raw:
        item = item if isinstance(item, dict) else {"user": item}
        uid = str(item["user"])
        k = max(1, min(int(item.get("k", TOP_K)), len(items)))
        if uid not in users:
            out.append({"user": uid, "known": False,
                        "items": [{"item": items[i], "score": None}
                                  for i in STATE["popular"][:k]]})
            continue
        u = users[uid]
        if "items" in item:
            lookup = {v: i for i, v in enumerate(items)}
            wanted = [lookup[str(v)] for v in item["items"] if str(v) in lookup]
            scores = _PREDICTOR(rows(torch.full((len(wanted),), u, device=device),
                                     torch.as_tensor(wanted, device=device))).squeeze(-1)
            out.append({"user": uid, "known": True,
                        "items": [{"item": items[i], "score": round(float(s), 6)}
                                  for i, s in zip(wanted, scores.cpu().tolist())]})
            continue
        scores = score_matrix(_PREDICTOR, rows, np.array([u]), len(items), device)[0]
        if item.get("exclude_seen", True):
            scores[list(STATE["seen"][u])] = -np.inf
        top = np.argsort(-scores)[:k]
        out.append({"user": uid, "known": True,
                    "items": [{"item": items[i], "score": round(float(scores[i]), 6)}
                              for i in top if np.isfinite(scores[i])]})
    return out


def main() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    data = load_interactions(DATASET)
    parts = split_per_user(data["users"], float(DATASET.get("val_fraction", 0.1)),
                           float(DATASET.get("test_fraction", 0.2)), SEED)
    print(f"users={data['n_users']} items={data['n_items']} interactions="
          f"{len(data['users'])} (train={len(parts['train'])} val={len(parts['val'])} "
          f"test={len(parts['test'])})")
    model = build_model().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    rows = Rows(data, device)
    model = train(model, data, parts, rows, device)
    relevant = 4.0 if data["ratings"] is not None else None
    seen = item_sets(data, np.concatenate([parts["train"], parts["val"]]))
    held = item_sets(data, parts["test"], relevant)
    test_users = np.array([u for u in range(data["n_users"]) if held[u]])
    metrics = evaluate(model, rows, data, seen, held, test_users, device, relevant)
    counts = np.bincount(data["items"][parts["train"]], minlength=data["n_items"])
    popular = np.tile(counts.astype(np.float32), (len(test_users), 1))
    for r, u in enumerate(test_users):
        popular[r, list(seen[u])] = -np.inf
    base = ranking_metrics(popular, [held[u] for u in test_users], TOP_K)
    metrics.update({f"popular_{k}": v for k, v in base.items()})
    if data["ratings"] is not None and len(parts["test"]):
        te = parts["test"]
        with torch.no_grad():
            pred = model(rows(torch.as_tensor(data["users"][te], device=device),
                              torch.as_tensor(data["items"][te], device=device)))
        err = pred.squeeze(-1).cpu().numpy() - data["ratings"][te]
        metrics.update({"rmse": float(np.sqrt(np.mean(err ** 2))),
                        "mae": float(np.mean(np.abs(err)))})
    all_seen = item_sets(data, np.arange(len(data["users"])))
    STATE.update({"user_index": {v: i for i, v in enumerate(data["user_ids"])},
                  "item_ids": data["item_ids"], "seen": [sorted(s) for s in all_seen],
                  "popular": np.argsort(-counts).tolist(),
                  "user_features": data["user_features"],
                  "item_features": data["item_features"]})
    torch.save(model.state_dict(), CHECKPOINT)
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    print(f"saved best weights to {CHECKPOINT}")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))


if __name__ == "__main__":
    main()
'''


def _dataset(graph: Graph) -> dict:
    node = dataset_of(graph)
    if node is None:
        return {"block": "data.synthetic_interactions", "n_users": 600, "n_items": 400,
                "per_user": 30, "feedback": "implicit", "features": 4, "seed": 0,
                "val_fraction": 0.1, "test_fraction": 0.2}
    out = {"block": node.type_id, **dict(node.resolved_params())}
    raw = out.get("path")
    if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
        candidate = Path.cwd() / str(raw)
        if candidate.exists():
            out["path"] = str(candidate)
    return out


def _comment(d: dict) -> str:
    if d["block"] == "data.synthetic_interactions":
        return (f"{d['n_users']} generated users x {d['n_items']} items "
                f"({d['feedback']} feedback)")
    return str(d["path"])


def context(graph: Graph, framework: str) -> dict:
    from ai_made_easy.core.training.generate import own_loop_requirements

    if framework != "pytorch":
        raise CodegenError("recommenders train with PyTorch: choose the PyTorch framework")
    notes: list[str] = []
    dataset = _dataset(graph)
    if dataset_of(graph) is None:
        notes.append("no dataset block: training on generated interactions")
    loss = next((n for n in graph.nodes.values() if n.type_id in cat.LOSS_IDS), None)
    if loss is not None:
        notes.append(f"the {loss.definition().display_name} block is ignored: the "
                     "Recommender Objective sets the loss")
    _o, objective = _picked(graph, ("rec.objective",))
    chain = graph.model_nodes()
    shapes = graph.infer_shapes()
    _t, trainer = _picked(graph, ("train.trainer",))
    trainer = cat.resolved("train.trainer", trainer)
    _l, loader = _picked(graph, ("prep.dataloader",))
    opt, opt_params = _picked(graph, cat.OPTIMIZER_IDS)
    optimizer = ("torch.optim.Adam(params, lr=0.01)" if opt is None else
                 cat.render(opt.type_id, cat.resolved(opt.type_id, opt_params), "pytorch")
                 .replace("model.parameters()", "params"))
    sched, sched_params = _picked(graph, cat.SCHEDULER_IDS)
    model_code = generate(graph, "pytorch")
    name = sanitize_identifier(graph.name)
    extra = ("pandas",) if dataset["block"] == "data.interactions_csv" else ()
    return {
        "title": graph.name, "filename": f"{name}_train_pytorch.py", "name": name,
        "notes": notes, "requirements": own_loop_requirements(model_code, extra),
        "data_comment": _comment(dataset), "dataset": dataset,
        "objective": objective.get("objective", "auto"),
        "negatives": int(objective.get("negatives", 4)),
        "top_k": int(objective.get("top_k", 10)),
        "input_shape": list(shapes[chain[0].instance_id]), "trainer": trainer,
        "batch_size": int(loader.get("batch_size") or 0) or int(trainer["batch_size"]),
        "model_code": _strip_main(model_code), "data_code": runtime.DATA_CODE,
        "metrics_code": runtime.METRICS_CODE, "optimizer_expr": optimizer,
        "scheduler_expr": (cat.render(sched.type_id, cat.resolved(sched.type_id, sched_params),
                                      "pytorch") if sched else None),
        "scheduler_step": cat.COMPONENTS[sched.type_id].meta["step"] if sched else None,
    }


def render(graph: Graph, _spec, framework: str) -> str:
    return _env.from_string(TEMPLATE).render(**context(graph, framework))
