"""Vision-task blocks: detectors, segmenters, U-Nets, backbones, datasets, losses, metrics.

Heads live in the "Vision Tasks" category and declare their task in
``meta["task"]``; the task decides the training loop (``core.vision.template``).
Pretrained catalogs come from ``core/zoo`` (generated by scripts/build_zoo.py).
"""
from __future__ import annotations

from ai_made_easy.core.blocks._dsl import P, ShapeError, nn_block
from ai_made_easy.core.palette import family_color
from ai_made_easy.core.registry import get_registry
from ai_made_easy.core.spec import BlockDefinition, PortSpec
from ai_made_easy.core.vision.helpers import unet_cost
from ai_made_easy.core.zoo import catalog

CATEGORY = "Vision Tasks"

DETECTORS = tuple(r["name"] for r in catalog("torchvision_detection")
                  if r["task"] == "detection")
INSTANCE_SEGMENTERS = tuple(r["name"] for r in catalog("torchvision_detection")
                            if r["task"] == "instance_segmentation")
KEYPOINT_DETECTORS = tuple(r["name"] for r in catalog("torchvision_detection")
                           if r["task"] == "keypoints")
SEGMENTERS = tuple(r["name"] for r in catalog("torchvision_segmentation"))
HF_DETECTORS = ("detr", "conditional_detr", "rt_detr")
HF_SEGMENTERS = ("segformer_b0", "segformer_b1", "segformer_b2")
UNET_VARIANTS = ("unet", "unet_plus_plus", "attention_unet", "resunet")
TIMM_MODELS = {r["name"]: r for r in catalog("timm_image")}
HF_ENCODERS = {  # model id: (feature width, patch multiple or 0, fixed side or 0)
    "facebook/dinov2-small": (384, 14, 0), "facebook/dinov2-base": (768, 14, 0),
    "openai/clip-vit-base-patch32": (768, 0, 224),
    "google/siglip-base-patch16-224": (768, 0, 224),
}
SSD_SIDES = {"ssd300_vgg16": 300, "ssdlite320_mobilenet_v3_large": 320}

# task-head block -> task id (core.vision.tasks resolves designs through this)
TASK_BLOCKS: dict[str, str] = {}


# ------------------------------------------------------------------ shapes

def _rgb(shape: list[int], name: str) -> None:
    if len(shape) != 3:
        raise ShapeError(f"{name} expects an image [C, H, W], got {shape}")
    if shape[0] not in (1, 3):
        raise ShapeError(f"{name} expects 1 or 3 channels (grayscale is repeated to RGB), "
                         f"got {shape[0]}")


def _detections(name: str):
    def fn(in_shapes, params):
        _rgb(in_shapes[0], name)
        if in_shapes[0][0] != 3:
            raise ShapeError(f"{name} detectors need RGB input: add a Grayscale(3) transform "
                             "or set the Input to 3 channels")
        return [int(params["max_detections"]), 6]
    return fn


def _class_map(name: str):
    def fn(in_shapes, params):
        _rgb(in_shapes[0], name)
        return [int(params["num_classes"]), *in_shapes[0][1:]]
    return fn


def _segformer_shape(in_shapes, params):
    return _class_map("SegFormer")(in_shapes, params)


def _unet_shape(in_shapes, params):
    s = in_shapes[0]
    if len(s) != 3:
        raise ShapeError(f"U-Net expects an image [C, H, W], got {s}")
    step = 2 ** int(params["depth"])
    if s[1] % step or s[2] % step:
        near = max(step, round(s[1] / step) * step)
        raise ShapeError(f"U-Net with depth {params['depth']} halves the image "
                         f"{params['depth']} times: height and width must be multiples of "
                         f"{step} (got {s[1]}×{s[2]}); resize to {near}×{near}")
    return [int(params["num_classes"]), s[1], s[2]]


def _unet_cost(in_shapes, params) -> tuple[int, int]:
    s = in_shapes[0]
    return unet_cost(s[0], int(params["num_classes"]), int(params["depth"]),
                     int(params["base_channels"]), params["variant"], params["norm"],
                     params["upsample"], s[1], s[2])


def _timm_shape(in_shapes, params):
    s = in_shapes[0]
    _rgb(s, params["model"])
    row = TIMM_MODELS[params["model"]]
    fixed = row.get("fixed_side")
    if fixed and (s[1] != fixed or s[2] != fixed):
        raise ShapeError(f"{params['model']} needs {fixed}×{fixed} inputs, got {s[1]}×{s[2]}")
    if min(s[1], s[2]) < row.get("min_side", 32):
        raise ShapeError(f"{params['model']} needs images of at least 32×32")
    return [int(row["feature_dim"])]


def _hf_encoder_shape(in_shapes, params):
    s = in_shapes[0]
    _rgb(s, params["model_id"])
    width, patch, fixed = HF_ENCODERS[params["model_id"]]
    if fixed and (s[1] != fixed or s[2] != fixed):
        raise ShapeError(f"{params['model_id']} needs {fixed}×{fixed} inputs, got "
                         f"{s[1]}×{s[2]}")
    if patch and (s[1] % patch or s[2] % patch):
        raise ShapeError(f"{params['model_id']} splits images into {patch}×{patch} patches: "
                         f"height and width must be multiples of {patch} (got {s[1]}×{s[2]})")
    return [width]


# ------------------------------------------------------------------ cost hooks
# meta["cost"](in_shapes, params) -> (parameters, forward FLOPs); used by the summary and
# core.budget for blocks whose cost does not follow a single-layer formula.

def _zoo_cost(name: str, scale_by_input: bool):
    rows = {r["name"]: r for r in catalog(name)}

    def fn(in_shapes, params):
        row = rows[params["arch"]]
        count = int(float(row["params_m"]) * 1e6)
        side = row.get("gmacs_side") or 224
        s = in_shapes[0]
        if params["arch"] in SSD_SIDES:
            pixels = SSD_SIDES[params["arch"]] ** 2
        elif scale_by_input:
            pixels = s[1] * s[2]
        else:  # R-CNN / RetinaNet / FCOS resize the short side to min_size
            short = int(params.get("min_size") or 0) or min(s[1], s[2])
            pixels = short * short * max(s[1], s[2]) / max(min(s[1], s[2]), 1)
        flops = int(2 * float(row.get("gmacs") or 0) * 1e9 * pixels / (side * side))
        return count, flops
    return fn


# Hugging Face models: (parameters in M, GMACs, side the GMACs refer to) from the model cards
HF_COSTS = {
    "detr": (41.3, 43.0, 800), "conditional_detr": (43.2, 45.0, 800),
    "rt_detr": (20.2, 30.0, 640), "segformer_b0": (3.8, 4.2, 512),
    "segformer_b1": (13.7, 8.0, 512), "segformer_b2": (27.5, 31.2, 512),
    "facebook/dinov2-small": (22.1, 5.5, 224), "facebook/dinov2-base": (86.6, 21.9, 224),
    "openai/clip-vit-base-patch32": (87.8, 4.4, 224),
    "google/siglip-base-patch16-224": (92.9, 17.5, 224),
}


def _hf_cost(key: str, fixed_side: bool = False):
    def fn(in_shapes, params):
        params_m, gmacs, side = HF_COSTS[params[key]]
        s = in_shapes[0]
        pixels = side * side if fixed_side else s[1] * s[2]
        return int(params_m * 1e6), int(2 * gmacs * 1e9 * pixels / (side * side))
    return fn


def _unet_flops(in_shapes, params):
    count, macs = _unet_cost(in_shapes, params)
    return count, 2 * macs


def _timm_cost(in_shapes, params):
    return int(float(TIMM_MODELS[params["model"]]["params_m"]) * 1e6), 0


# ------------------------------------------------------------------ registration

_WEIGHTS_HELP = ("none: random init (no download); imagenet: pretrained backbone; "
                 "coco: the whole detector pretrained on COCO")


def _head(type_id: str, name: str, *, task: str, params: tuple, shape, torch,
          helpers: tuple, desc: str, cost=None, requires=(), extra="", role="boxes"):
    defn = nn_block(type_id, name, CATEGORY, family="model", params=params, shape=shape,
                    torch=torch, torch_helpers=helpers, desc=desc,
                    param_fn=(lambda s, p: cost(s, p)[0]) if cost else None)
    meta = {"task": task, "cost": cost}
    defn = _replace(defn, meta=meta, requires=tuple(requires), extra=extra,
                    outputs=(PortSpec("out", role=role),), library="PyTorch")
    TASK_BLOCKS[type_id] = task
    return defn


def _replace(defn: BlockDefinition, **changes) -> BlockDefinition:
    from dataclasses import replace

    return replace(defn, **changes)


def _tv_detector(c: dict) -> str:
    min_size = int(c["min_size"]) or min(c["input_shape"][1:])
    max_size = int(c.get("max_size") or 0) or max(c["input_shape"][1:])
    keypoints = f", num_keypoints={int(c['num_keypoints'])}" if "num_keypoints" in c else ""
    return (f"TVDetector(\"{c['arch']}\", num_classes={int(c['num_classes'])}, "
            f"weights=\"{c['weights']}\", min_size={min_size}, max_size={max_size}, "
            f"max_detections={int(c['max_detections'])}, "
            f"score_threshold={float(c['score_threshold'])}, "
            f"trainable_layers={int(c['trainable_layers'])}{keypoints})")


def _detector_params(archs: tuple, default: str, classes: int, extra: tuple = ()) -> tuple:
    return (P("arch", "enum", default, options=archs),
            P("num_classes", "int", classes, lo=1,
              help="Object classes in the dataset (background is added automatically)"),
            *extra,
            P("weights", "enum", "imagenet", options=("none", "imagenet", "coco"),
              help=_WEIGHTS_HELP),
            P("min_size", "int", 0, lo=0,
              help="Short side images are resized to inside the model; 0 = the Input height"),
            P("max_size", "int", 0, lo=0, help="Cap on the long side; 0 = the Input width"),
            P("max_detections", "int", 100, lo=1, hi=1000),
            P("score_threshold", "float", 0.05, lo=0.0, hi=1.0,
              help="Detections below this confidence are dropped"),
            P("trainable_layers", "int", 3, lo=0, hi=5,
              help="Backbone stages fine-tuned when pretrained (0 = frozen backbone)"))


def _blocks() -> list[BlockDefinition]:
    det_cost = _zoo_cost("torchvision_detection", scale_by_input=False)
    seg_cost = _zoo_cost("torchvision_segmentation", scale_by_input=True)
    return [
        _head("vision.detector", "Object Detector", task="detection",
              params=_detector_params(DETECTORS, "fasterrcnn_mobilenet_v3_large_fpn", 3),
              shape=_detections("Object Detector"), torch=_tv_detector,
              helpers=("skip_pretrained", "pad_detections", "TVDetector"), cost=det_cost,
              desc="torchvision Faster R-CNN, RetinaNet, FCOS or SSD → boxes, labels, scores "
                   "(padded to [max_detections, 6])."),
        _head("vision.instance_segmenter", "Instance Segmenter", task="instance_segmentation",
              params=_detector_params(INSTANCE_SEGMENTERS, "maskrcnn_resnet50_fpn", 3),
              shape=_detections("Instance Segmenter"), torch=_tv_detector,
              helpers=("skip_pretrained", "pad_detections", "TVDetector"), cost=det_cost, role="masks",
              desc="Mask R-CNN: a box, label, score and pixel mask for every object."),
        _head("vision.keypoint_detector", "Keypoint Detector", task="keypoints",
              params=_detector_params(KEYPOINT_DETECTORS, "keypointrcnn_resnet50_fpn", 1,
                                      (P("num_keypoints", "int", 17, lo=1,
                                         help="Keypoints per object (COCO people: 17)"),)),
              shape=_detections("Keypoint Detector"), torch=_tv_detector,
              helpers=("skip_pretrained", "pad_detections", "TVDetector"), cost=det_cost, role="keypoints",
              desc="Keypoint R-CNN: boxes plus keypoints (e.g. human pose) per object."),
        _head("vision.hf_detector", "Transformer Detector (DETR)", task="detection",
              params=(P("arch", "enum", "detr", options=HF_DETECTORS),
                      P("num_classes", "int", 3, lo=1, help="Object classes in the dataset"),
                      P("weights", "enum", "none", options=("none", "coco"),
                        help="coco: Hugging Face checkpoint fine-tuned on COCO"),
                      P("max_detections", "int", 100, lo=1, hi=300),
                      P("score_threshold", "float", 0.05, lo=0.0, hi=1.0)),
              shape=_detections("Transformer Detector"), cost=_hf_cost("arch", fixed_side=True),
              torch=lambda c: (f"HFDetr(\"{c['arch']}\", num_classes={int(c['num_classes'])}, "
                               f"weights=\"{c['weights']}\", "
                               f"max_detections={int(c['max_detections'])}, "
                               f"score_threshold={float(c['score_threshold'])})"),
              helpers=("imagenet_normalize", "pad_detections", "HFDetr"),
              requires=("transformers",), extra="vision-tasks",
              desc="Hugging Face DETR, Conditional DETR or RT-DETR: set prediction with "
                   "transformers, no anchors or NMS."),
        _head("vision.segmenter", "Semantic Segmenter", task="semantic_segmentation",
              params=(P("arch", "enum", "deeplabv3_mobilenet_v3_large", options=SEGMENTERS),
                      P("num_classes", "int", 21, lo=2,
                        help="Classes per pixel, including background"),
                      P("weights", "enum", "imagenet", options=("none", "imagenet", "coco"),
                        help="coco: pretrained on COCO with the 21 Pascal VOC classes")),
              shape=_class_map("Semantic Segmenter"), cost=seg_cost, role="masks",
              torch=lambda c: (f"TVSegmenter(\"{c['arch']}\", "
                               f"num_classes={int(c['num_classes'])}, "
                               f"weights=\"{c['weights']}\")"),
              helpers=("skip_pretrained", "imagenet_normalize", "TVSegmenter"),
              desc="torchvision DeepLabV3, FCN or LR-ASPP → per-pixel class logits [C, H, W]."),
        _head("vision.hf_segmenter", "SegFormer", task="semantic_segmentation",
              params=(P("arch", "enum", "segformer_b0", options=HF_SEGMENTERS),
                      P("num_classes", "int", 21, lo=2,
                        help="Classes per pixel, including background"),
                      P("weights", "enum", "none", options=("none", "imagenet", "ade"))),
              shape=_segformer_shape, role="masks", cost=_hf_cost("arch"),
              torch=lambda c: (f"HFSegformer(\"{c['arch']}\", "
                               f"num_classes={int(c['num_classes'])}, "
                               f"weights=\"{c['weights']}\")"),
              helpers=("imagenet_normalize", "HFSegformer"),
              requires=("transformers",), extra="vision-tasks",
              desc="Hugging Face SegFormer (MiT-B0..B2): efficient transformer segmentation."),
        _head("vision.unet", "U-Net", task="semantic_segmentation",
              params=(P("variant", "enum", "unet", options=UNET_VARIANTS,
                        help="unet_plus_plus: nested skips; attention_unet: gated skips; "
                             "resunet: residual blocks"),
                      P("num_classes", "int", 2, lo=1,
                        help="Classes per pixel, including background"),
                      P("depth", "int", 4, lo=1, hi=6, help="Down-sampling steps"),
                      P("base_channels", "int", 32, lo=4, help="Width of the first level"),
                      P("norm", "enum", "batch", options=("batch", "group")),
                      P("upsample", "enum", "transpose", options=("transpose", "bilinear"))),
              shape=_unet_shape, cost=_unet_flops, role="masks",
              torch=lambda c: (f"UNet({c['input_shape'][0]}, {int(c['num_classes'])}, "
                               f"depth={int(c['depth'])}, base={int(c['base_channels'])}, "
                               f"variant=\"{c['variant']}\", norm=\"{c['norm']}\", "
                               f"upsample=\"{c['upsample']}\")"),
              helpers=("UNet",),
              desc="U-Net family trained from scratch: encoder-decoder with skip connections "
                   "→ [C, H, W]."),
        _replace(nn_block(
            "vision.timm_backbone", "timm Image Backbone", "Pretrained Models", family="model",
            params=(P("model", "enum", "convnext_atto", options=tuple(TIMM_MODELS)),
                    P("weights", "enum", "imagenet", options=("imagenet", "none")),
                    P("freeze", "bool", True)),
            shape=_timm_shape, param_fn=lambda s, p: _timm_cost(s, p)[0],
            torch=lambda c: (f"TimmBackbone(\"{c['model']}\", "
                             f"pretrained={c['weights'] == 'imagenet'}, "
                             f"freeze={bool(c['freeze'])})"),
            torch_helpers=("skip_pretrained", "imagenet_normalize", "TimmBackbone"),
            desc="87 curated timm models (ConvNeXt V2, EfficientNetV2, RegNet, Swin, ViT, "
                 "DeiT, MaxViT, MobileNetV4, EVA-02, ...) → pooled features [F]."),
            requires=("timm",), extra="vision-tasks", meta={"zoo": "timm_image"}),
        _replace(nn_block(
            "vision.hf_image_encoder", "Hugging Face Image Encoder", "Pretrained Models",
            family="model",
            params=(P("model_id", "enum", "facebook/dinov2-small", options=tuple(HF_ENCODERS)),
                    P("weights", "enum", "pretrained", options=("pretrained", "none")),
                    P("freeze", "bool", True)),
            shape=_hf_encoder_shape,
            torch=lambda c: (f"HFImageEncoder(\"{c['model_id']}\", "
                             f"pretrained={c['weights'] == 'pretrained'}, "
                             f"freeze={bool(c['freeze'])})"),
            torch_helpers=("imagenet_normalize", "HFImageEncoder"),
            desc="DINOv2, CLIP or SigLIP image tower → pooled features [F]."),
            requires=("transformers",), extra="vision-tasks"),
    ]


# ------------------------------------------------------------------ datasets

VISION_DATA: dict[str, dict] = {}


def _data(type_id: str, name: str, params: tuple, desc: str, *, formats: str,
          checks=None) -> BlockDefinition:
    VISION_DATA[type_id] = {"formats": formats}
    return BlockDefinition(
        type_id=type_id, display_name=name, category="Data", color=family_color("data"),
        params=params, description=desc, library="PyTorch", checks_fn=checks,
        meta={"modality": "image", "vision": True, "annotations": formats})


def _dataset_blocks() -> list[BlockDefinition]:
    return [
        _data("data.coco", "COCO Dataset",
              (P("images_dir", "str", "images/"),
               P("annotations", "str", "annotations.json",
                 help="COCO JSON: boxes, polygon / RLE masks and keypoints")),
              "Images with a COCO-format annotation file (boxes, masks, keypoints).",
              formats="boxes,masks,keypoints"),
        _data("data.yolo", "YOLO Dataset",
              (P("images_dir", "str", "images/"),
               P("labels_dir", "str", "labels/",
                 help="One .txt per image: class cx cy w h (normalized 0-1); polygons and "
                      "pose keypoints are read too"),
               P("classes", "str", "",
                 help="Class names, comma-separated, or a data.yaml / classes.txt path")),
              "Images with YOLO-format label files (boxes, segmentation polygons, pose).",
              formats="boxes,masks,keypoints"),
        _data("data.voc", "Pascal VOC Dataset",
              (P("root", "str", "VOCdevkit/VOC2012",
                 help="Folder with Annotations/, JPEGImages/ and optional SegmentationClass/"),
               P("classes", "str", "", help="Comma-separated; empty = found in the XML files")),
              "Pascal VOC XML boxes (and SegmentationClass masks when present).",
              formats="boxes,semantic"),
        _data("data.mask_folder", "Segmentation Mask Folder",
              (P("images_dir", "str", "images/"),
               P("masks_dir", "str", "masks/",
                 help="One PNG per image (same file stem): pixel value = class index"),
               P("num_classes", "int", 2, lo=2, help="Including background (class 0)"),
               P("class_names", "str", "", help="Optional, comma-separated"),
               P("ignore_index", "int", 255, lo=0, hi=255,
                 help="Pixel value that is not scored (borders, unlabeled)")),
              "Images with per-pixel class masks for semantic segmentation.",
              formats="semantic"),
        _data("data.synthetic_shapes", "Synthetic Shapes",
              (P("n_images", "int", 240, lo=8),
               P("image_size", "int", 128, lo=32, hi=1024),
               P("max_objects", "int", 3, lo=1, hi=20),
               P("seed", "int", 0, lo=0)),
              "Generated squares, circles and triangles with boxes, masks and keypoints: "
              "try any vision task without downloading data.",
              formats="boxes,masks,keypoints,semantic"),
    ]


SYNTHETIC_CLASSES = ("square", "circle", "triangle")


# ------------------------------------------------------------------ losses / metrics

VISION_LOSSES: dict[str, dict] = {}
VISION_METRICS: dict[str, dict] = {}


def _loss(type_id: str, name: str, params: tuple, desc: str) -> BlockDefinition:
    VISION_LOSSES[type_id] = {}
    return BlockDefinition(
        type_id=type_id, display_name=name, category="Loss", color=family_color("training"),
        params=(*params, P("weight", "float", 1.0, lo=0.0,
                           help="Weight when several losses are combined")),
        description=desc, library="PyTorch",
        meta={"kind": "loss", "task": "semantic_segmentation", "vision": True})


def _metric(type_id: str, name: str, key: str, tasks: tuple, desc: str,
            params: tuple = ()) -> BlockDefinition:
    VISION_METRICS[type_id] = {"key": key, "tasks": tasks}
    return BlockDefinition(
        type_id=type_id, display_name=name, category="Metrics",
        color=family_color("evaluation"), params=params, description=desc, library="PyTorch",
        meta={"kind": "metrics", "key": key, "tasks": list(tasks), "vision": True})


BOX_TASKS = ("detection", "instance_segmentation", "keypoints")


def _loss_metric_blocks() -> list[BlockDefinition]:
    return [
        _loss("vision.loss_dice", "Dice Loss", (P("smooth", "float", 1.0, lo=0.0),),
              "1 − Dice overlap per class: robust to class imbalance in segmentation."),
        _loss("vision.loss_tversky", "Tversky Loss",
              (P("alpha", "float", 0.3, lo=0.0, hi=1.0, help="False-positive weight"),
               P("beta", "float", 0.7, lo=0.0, hi=1.0, help="False-negative weight")),
              "Dice generalisation that trades false positives against false negatives."),
        _loss("vision.loss_lovasz", "Lovász-Softmax Loss", (),
              "Directly optimises the mean IoU (Berman et al., 2018)."),
        _loss("vision.loss_focal_pixel", "Pixel Focal Loss",
              (P("gamma", "float", 2.0, lo=0.0),),
              "Cross-entropy that down-weights easy pixels (rare classes, thin structures)."),
        _metric("eval.map", "mAP@[.5:.95]", "map", BOX_TASKS,
                "COCO mean average precision over IoU 0.50–0.95."),
        _metric("eval.map50", "mAP@.5", "map50", BOX_TASKS,
                "Average precision at IoU 0.50 (Pascal VOC style)."),
        _metric("eval.mask_map", "Mask mAP", "mask_map", ("instance_segmentation",),
                "COCO mAP computed on mask IoU."),
        _metric("eval.pck", "PCK", "pck", ("keypoints",),
                "Percentage of correct keypoints within a fraction of the object size.",
                (P("threshold", "float", 0.2, lo=0.01, hi=1.0,
                   help="Fraction of the box diagonal"),)),
        _metric("eval.miou", "Mean IoU", "miou", ("semantic_segmentation",),
                "Intersection over union averaged over classes."),
        _metric("eval.dice", "Dice Score", "dice", ("semantic_segmentation",),
                "Mean Dice (F1) overlap over classes."),
        _metric("eval.pixel_accuracy", "Pixel Accuracy", "pixel_accuracy",
                ("semantic_segmentation",), "Share of correctly classified pixels."),
    ]


def register_all() -> None:
    reg = get_registry()
    for defn in (*_blocks(), *_dataset_blocks(), *_loss_metric_blocks()):
        reg.register(defn)
