"""Training scripts for vision tasks (detection, instance / semantic segmentation, keypoints).

The script is self-contained like every generated script: the model file, the
dataset readers and metrics (``core.vision.runtime``), a box / mask aware
``transforms.v2`` pipeline, the training loop for the task's trainer kind,
COCO-style evaluation, overlay images of test predictions, and the
``load_predictor`` / ``infer`` functions the deploy package serves.
"""
from __future__ import annotations

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.tasks import get_task, task_of
from ai_made_easy.core.training import catalog as cat
from ai_made_easy.core.training import data_catalog as dcat
from ai_made_easy.core.vision import runtime
from ai_made_easy.core.vision.blocks import (
    SYNTHETIC_CLASSES,
    VISION_DATA,
    VISION_LOSSES,
    VISION_METRICS,
)
from ai_made_easy.core.vision.tasks import dataset_of, head_of

# image transforms that do not support boxes / masks / keypoints in transforms.v2
UNSUPPORTED_AUGMENT = {
    "prep.auto_augment": "AutoAugment", "prep.rand_augment": "RandAugment",
    "prep.trivial_augment": "TrivialAugment", "prep.augmix": "AugMix",
    "prep.mixup_cutmix": "MixUp / CutMix", "prep.random_erasing": "Random Erasing",
}
IGNORED_PREP = {
    "prep.normalize": "vision models normalize their input themselves",
    "prep.class_balance": "class balancing applies to image classification",
}

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

TEMPLATE = r'''"""{{ title }} — {{ task_label | lower }} training script generated by AI Made Easy.

Data:   {{ data_comment }}
Model:  {{ head_label }}
Usage:  python {{ filename }}                      train, test, save weights + overlays
        python {{ filename }} --predict IMG ...    predictions (JSON) for image files
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import json
import math
import pickle
import random
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image, ImageDraw
from torch.utils.data import DataLoader, Dataset
from torchvision import tv_tensors
from torchvision.transforms import v2

TASK = "{{ task }}"
DATASET = {{ dataset | repr }}
INPUT_SHAPE = {{ input_shape | repr }}          # [C, H, W] the model sees
NUM_CLASSES = {{ num_classes }}{{ "  # including background" if task == "semantic_segmentation" else "  # object classes" }}

CLASS_NAMES: list = {{ class_names | repr }}
EPOCHS = {{ trainer.epochs }}
BATCH_SIZE = {{ batch_size }}
SEED = {{ trainer.seed }}
DEVICE = "{{ trainer.device }}"
EARLY_STOP = {{ trainer.early_stopping_patience }}
GRAD_CLIP = {{ trainer.grad_clip_norm }}
ACCUM_STEPS = {{ trainer.accumulation_steps }}
MIXED_PRECISION = {{ trainer.mixed_precision }}
NUM_WORKERS = {{ num_workers }}
SPLIT = {{ split | repr }}
PRIMARY = "{{ primary }}"                       # validation metric that picks the best epoch
IGNORE_INDEX = {{ ignore_index }}
PCK_THRESHOLD = {{ pck_threshold }}
CHECKPOINT = "{{ name }}_best.pt"
INFERENCE_FILE = "inference_state.pkl"
SAMPLES_DIR = Path("eval_samples")
# ---------------------------------------------------------------------- model
{{ model_code }}
{{ data_code }}
{{ metrics_code }}
{{ encode_code }}

# ======================================================================== pipeline
ALWAYS = [{% for t in always %}{{ t }}, {% endfor %}]
AUGMENT = [{% for t in augment %}{{ t }}, {% endfor %}]


def to_channels(image: torch.Tensor) -> torch.Tensor:
    if INPUT_SHAPE[0] == 1 and image.shape[0] == 3:
        return image.mean(0, keepdim=True)
    return image


def keypoint_array(rec: dict) -> np.ndarray:
    kps = rec.get("keypoints") or []
    if not kps:
        return np.zeros((len(rec["boxes"]), 0, 3), np.float32)
    return np.stack([np.asarray(k, np.float32) for k in kps])


def sanitize(target: dict) -> dict:
    """Clamp boxes to the image, drop degenerate ones, hide keypoints outside the image."""
    h, w = target["boxes"].canvas_size
    boxes = target["boxes"].as_subclass(torch.Tensor).clone()
    boxes[:, 0::2] = boxes[:, 0::2].clamp(0, w)
    boxes[:, 1::2] = boxes[:, 1::2].clamp(0, h)
    keep = ((boxes[:, 2] - boxes[:, 0]) > 1) & ((boxes[:, 3] - boxes[:, 1]) > 1)
    out = {"boxes": boxes[keep], "labels": target["labels"][keep]}
    if "masks" in target:
        out["masks"] = target["masks"].as_subclass(torch.Tensor)[keep].to(torch.uint8)
    if "keypoints" in target:
        pts = target["keypoints"].as_subclass(torch.Tensor)[keep]
        vis = target["visibility"][keep].clone()
        inside = (pts[..., 0] >= 0) & (pts[..., 0] < w) & (pts[..., 1] >= 0) & (pts[..., 1] < h)
        vis[~inside] = 0
        out["keypoints"] = torch.cat([pts, vis.unsqueeze(-1)], dim=-1)
    return out


class VisionDataset(Dataset):
    def __init__(self, records: list, train: bool) -> None:
        self.records = records
        self.transform = v2.Compose([*ALWAYS, *(AUGMENT if train else []),
                                     v2.Resize(INPUT_SHAPE[1:], antialias=True),
                                     v2.ToDtype(torch.float32, scale=True)])

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, index: int):
        rec = self.records[index]
        arr = load_image(rec)
        h, w = arr.shape[:2]
        image = tv_tensors.Image(torch.from_numpy(np.array(arr, copy=True)).permute(2, 0, 1))
        if TASK == "semantic_segmentation":
            mask = tv_tensors.Mask(torch.from_numpy(semantic_mask(rec, h, w)))
            image, mask = self.transform(image, mask)
            return to_channels(image), mask.as_subclass(torch.Tensor).long()
        target = {
            "boxes": tv_tensors.BoundingBoxes(
                torch.tensor(rec["boxes"], dtype=torch.float32).reshape(-1, 4),
                format="XYXY", canvas_size=(h, w)),
            "labels": torch.tensor(rec["labels"], dtype=torch.int64),
        }
        if TASK == "instance_segmentation":
            target["masks"] = tv_tensors.Mask(
                torch.from_numpy(instance_masks(rec, h, w)).to(torch.uint8))
        if TASK == "keypoints":
            kp = keypoint_array(rec)
            target["keypoints"] = tv_tensors.KeyPoints(torch.from_numpy(kp[..., :2]),
                                                       canvas_size=(h, w))
            target["visibility"] = torch.from_numpy(kp[..., 2])
        image, target = self.transform(image, target)
        return to_channels(image), sanitize(target)


def collate(batch: list):
    images = torch.stack([b[0] for b in batch])
    if TASK == "semantic_segmentation":
        return images, torch.stack([b[1] for b in batch])
    return images, [b[1] for b in batch]


def make_loaders() -> tuple:
    global CLASS_NAMES
    records, names = load_records(DATASET, keypoints=TASK == "keypoints")
    if not records:
        raise SystemExit(f"no images found for {DATASET}")
    if not CLASS_NAMES:
        CLASS_NAMES = (names if TASK != "semantic_segmentation" or DATASET["block"] in (
            "data.mask_folder",) else ["background", *names])
    train, val, test = split_records(records, SPLIT["val_fraction"], SPLIT["test_fraction"],
                                     SPLIT["seed"], SPLIT["shuffle"])
    val = val or train[: max(1, len(train) // 10)]
    test = test or val

    def loader(rows: list, training: bool) -> DataLoader:
        return DataLoader(VisionDataset(rows, training), batch_size=BATCH_SIZE,
                          shuffle=training, num_workers=NUM_WORKERS, collate_fn=collate)

    return loader(train, True), loader(val, False), loader(test, False)


def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def report_resources(device: torch.device, step_seconds: float) -> None:
    """Measured first-epoch cost; calibrates the designer's budget estimates."""
    peak = 0.0
    if device.type == "cuda":
        peak = torch.cuda.max_memory_allocated(device) / 2**20
    elif device.type == "mps":
        peak = torch.mps.driver_allocated_memory() / 2**20
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)
{% if task == "semantic_segmentation" %}


# ======================================================================== losses
def _valid(target: torch.Tensor) -> torch.Tensor:
    return target != IGNORE_INDEX


def _one_hot(logits: torch.Tensor, target: torch.Tensor):
    valid = _valid(target)
    probs = logits.float().softmax(1) * valid.unsqueeze(1)
    onehot = F.one_hot(target.clamp(0, logits.shape[1] - 1), logits.shape[1])
    onehot = onehot.permute(0, 3, 1, 2).float() * valid.unsqueeze(1)
    return probs, onehot


def dice_loss(logits, target, smooth: float = 1.0):
    probs, onehot = _one_hot(logits, target)
    inter = (probs * onehot).sum((0, 2, 3))
    total = probs.sum((0, 2, 3)) + onehot.sum((0, 2, 3))
    return 1 - ((2 * inter + smooth) / (total + smooth)).mean()


def tversky_loss(logits, target, alpha: float = 0.3, beta: float = 0.7):
    probs, onehot = _one_hot(logits, target)
    tp = (probs * onehot).sum((0, 2, 3))
    fp = (probs * (1 - onehot)).sum((0, 2, 3))
    fn = ((1 - probs) * onehot).sum((0, 2, 3))
    return 1 - ((tp + 1) / (tp + alpha * fp + beta * fn + 1)).mean()


def _lovasz_grad(gt_sorted: torch.Tensor) -> torch.Tensor:
    gts = gt_sorted.sum()
    inter = gts - gt_sorted.cumsum(0)
    union = gts + (1 - gt_sorted).cumsum(0)
    jaccard = 1 - inter / union
    if len(gt_sorted) > 1:
        jaccard[1:] = jaccard[1:] - jaccard[:-1]
    return jaccard


def lovasz_loss(logits, target):
    """Lovász-Softmax (Berman et al., 2018) over the classes present in the batch."""
    probs = logits.float().softmax(1).permute(0, 2, 3, 1).reshape(-1, logits.shape[1])
    labels = target.reshape(-1)
    keep = labels != IGNORE_INDEX
    probs, labels = probs[keep], labels[keep]
    losses = []
    for c in labels.unique():
        fg = (labels == c).float()
        errors = (fg - probs[:, c]).abs()
        order = errors.argsort(descending=True)
        losses.append(torch.dot(errors[order], _lovasz_grad(fg[order])))
    return torch.stack(losses).mean() if losses else logits.sum() * 0


def focal_pixel_loss(logits, target, gamma: float = 2.0):
    ce = F.cross_entropy(logits.float(), target, ignore_index=IGNORE_INDEX, reduction="none")
    pt = torch.exp(-ce)
    valid = _valid(target)
    return (((1 - pt) ** gamma) * ce)[valid].mean()


def cross_entropy(logits, target, label_smoothing: float = 0.0):
    return F.cross_entropy(logits.float(), target, ignore_index=IGNORE_INDEX,
                           label_smoothing=label_smoothing)


LOSSES = [{% for fn, args, weight in losses %}({{ fn }}, {{ args | repr }}, {{ weight }}), {% endfor %}]


def compute_loss(logits: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    return sum(weight * fn(logits, target, **args) for fn, args, weight in LOSSES)
{% endif %}


# ======================================================================== train / evaluate
def task_head(model: nn.Module) -> nn.Module:
{% if box_task %}
    return next(m for m in model.modules() if hasattr(m, "losses") and hasattr(m, "detect"))
{% else %}
    return model
{% endif %}


@torch.no_grad()
def evaluate(model: nn.Module, loader: DataLoader, device: torch.device,
             keep: int = 0) -> tuple:
    """Metrics on a split; with keep > 0 also the first predictions for overlays."""
    model.eval()
    kept = []
{% if box_task %}
    head = task_head(model)
    preds, trues = [], []
    for images, targets in loader:
        for image, out, t in zip(images, head.detect(images.to(device)), targets):
            p = {k: out[k].float().cpu().numpy() for k in ("boxes", "scores")}
            p["labels"] = out["labels"].cpu().numpy()
            if "masks" in out:
                p["masks"] = (out["masks"][:, 0] > 0.5).cpu().numpy()
            if "keypoints" in out:
                p["keypoints"] = out["keypoints"].float().cpu().numpy()
            true = {k: v.numpy() for k, v in t.items()}
            if "masks" in true:
                true["masks"] = true["masks"].astype(bool)
            preds.append(p)
            trues.append(true)
            if len(kept) < keep:
                kept.append((image, p, true))
    ap = average_precision(preds, trues)
    metrics = {"map": ap["map"], "map50": ap["map50"], "map75": ap["map75"]}
{% if task == "instance_segmentation" %}
    metrics["mask_map"] = average_precision(preds, trues, "masks")["map"]
{% endif %}
{% if task == "keypoints" %}
    metrics["pck"] = keypoint_pck(preds, trues, PCK_THRESHOLD)
{% endif %}
    metrics["per_class_ap"] = [ap["per_class"].get(c) for c in range(NUM_CLASSES)]
    return metrics, kept
{% else %}
    conf = np.zeros((NUM_CLASSES, NUM_CLASSES), np.int64)
    total, count = 0.0, 0
    for images, masks in loader:
        logits = model(images.to(device)).float()
        total += float(compute_loss(logits, masks.to(device))) * len(images)
        count += len(images)
        pred = logits.argmax(1).cpu().numpy()
        conf += confusion(pred, masks.numpy(), NUM_CLASSES, IGNORE_INDEX)
        for image, p, t in zip(images, pred, masks.numpy()):
            if len(kept) < keep:
                kept.append((image, p, t))
    metrics = segmentation_scores(conf)
    metrics["loss"] = total / max(count, 1)
    return metrics, kept
{% endif %}


def train_step_loss(model: nn.Module, images: torch.Tensor, targets, device):
{% if box_task %}
    targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
    losses = task_head(model).losses(images, targets)
    return sum(losses.values())
{% else %}
    return compute_loss(model(images), targets.to(device))
{% endif %}


def fit(model: nn.Module, train_loader, val_loader, device) -> nn.Module:
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% endif %}
    use_amp = MIXED_PRECISION and device.type in ("cuda", "mps")
    amp_dtype = torch.float16 if device.type == "cuda" else torch.bfloat16
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp and device.type == "cuda")
    best, best_state, bad = -math.inf, None, 0
    if device.type == "cuda":
        torch.cuda.reset_peak_memory_stats(device)
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, running, seen, step = time.time(), 0.0, 0, 0
        optimizer.zero_grad(set_to_none=True)
        for step, (images, targets) in enumerate(train_loader, start=1):
            images = images.to(device)
            with torch.autocast(device_type=device.type, dtype=amp_dtype, enabled=use_amp):
                loss = train_step_loss(model, images, targets, device)
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
            scaler.scale(loss / ACCUM_STEPS).backward()
            if step % ACCUM_STEPS == 0 or step == len(train_loader):
                if GRAD_CLIP > 0:
                    scaler.unscale_(optimizer)
                    nn.utils.clip_grad_norm_(params, GRAD_CLIP)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
{% if scheduler_step == "batch" %}
                scheduler.step()
{% endif %}
            running += loss.item() * len(images)
            seen += len(images)
        if epoch == 1:
            report_resources(device, (time.time() - started) / max(step, 1))
        metrics, _ = evaluate(model, val_loader, device)
        score = metrics[PRIMARY]
{% if scheduler_step == "epoch" %}
        scheduler.step()
{% elif scheduler_step == "metric" %}
        scheduler.step(-score)  # ReduceLROnPlateau minimizes: pass the negated score
{% endif %}
        shown = " ".join(f"val_{k}={v:.4f}" for k, v in metrics.items() if isinstance(v, float))
        print(f"epoch {epoch}/{EPOCHS} train_loss={running / max(seen, 1):.4f} {shown} "
              f"lr={optimizer.param_groups[0]['lr']:.3g} ({time.time() - started:.1f}s)",
              flush=True)
        if score > best:
            best, bad = score, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if EARLY_STOP and bad >= EARLY_STOP:
                print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    return model


def save_overlays(kept: list) -> None:
    SAMPLES_DIR.mkdir(exist_ok=True)
    for i, (image, pred, true) in enumerate(kept):
        arr = (image.permute(1, 2, 0).numpy() * 255).clip(0, 255).astype(np.uint8)
        if arr.shape[2] == 1:
            arr = np.repeat(arr, 3, axis=2)
{% if box_task %}
        overlay(arr, pred, true, CLASS_NAMES).save(SAMPLES_DIR / f"sample_{i}.png")
{% else %}
        both = np.concatenate([np.asarray(overlay(arr, mask=true)),
                               np.asarray(overlay(arr, mask=pred))], axis=1)
        Image.fromarray(both).save(SAMPLES_DIR / f"sample_{i}.png")  # truth | prediction
{% endif %}


# ======================================================================== serving
_PREDICTOR = None


def save_inference_state() -> None:
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump({"task": TASK, "class_names": CLASS_NAMES, "input_shape": INPUT_SHAPE}, fh)


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    """Load trained weights (pretrained weights are not downloaded again)."""
    import os

    global _PREDICTOR, CLASS_NAMES
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        CLASS_NAMES = pickle.load(fh)["class_names"]
    os.environ["AIME_SKIP_PRETRAINED"] = "1"
    try:
        model = build_model()
    finally:
        os.environ.pop("AIME_SKIP_PRETRAINED", None)
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    _PREDICTOR = model.eval().to(device)
    return _PREDICTOR


def _name(c: int) -> str:
    return CLASS_NAMES[c] if 0 <= c < len(CLASS_NAMES) else str(c)


@torch.no_grad()
def infer(raw: list) -> list[dict]:
    """Predictions for images (bytes, base64 strings or HxWxC arrays), in pixel coordinates
    of each original image."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    results = []
    for item in raw:
        img = decode_image(item)
        w, h = img.size
        x = v2.functional.to_dtype(v2.functional.pil_to_tensor(
            img.resize((INPUT_SHAPE[2], INPUT_SHAPE[1]))), torch.float32, scale=True)
        x = to_channels(x).unsqueeze(0).to(device)
{% if box_task %}
        out = task_head(_PREDICTOR).detect(x)[0]
        scale = torch.tensor([w / INPUT_SHAPE[2], h / INPUT_SHAPE[1]] * 2, device=device)
        boxes = (out["boxes"] * scale).cpu().numpy().astype(np.float64)
        item_out = {"boxes": boxes.round(2).tolist(),
                    "scores": out["scores"].cpu().numpy().astype(np.float64).round(4).tolist(),
                    "labels": out["labels"].cpu().tolist(),
                    "label_names": [_name(int(c)) for c in out["labels"].cpu().tolist()]}
        if "masks" in out:
            masks = F.interpolate(out["masks"].float(), size=(h, w), mode="bilinear",
                                  align_corners=False)[:, 0] > 0.5
            item_out["masks"] = [mask_to_rle(m) for m in masks.cpu().numpy()]
        if "keypoints" in out:
            kp = out["keypoints"].cpu().numpy().astype(np.float64)
            kp[..., 0] *= w / INPUT_SHAPE[2]
            kp[..., 1] *= h / INPUT_SHAPE[1]
            item_out["keypoints"] = kp.round(2).tolist()
{% else %}
        logits = _PREDICTOR(x).float()
        logits = F.interpolate(logits, size=(h, w), mode="bilinear", align_corners=False)
        pred = logits.argmax(1)[0].cpu().numpy()
        counts = np.bincount(pred.reshape(-1), minlength=NUM_CLASSES)
        item_out = {"mask": mask_to_rle(pred > 0) if NUM_CLASSES == 2 else None,
                    "class_masks": {_name(c): mask_to_rle(pred == c)
                                    for c in range(1, NUM_CLASSES) if counts[c]},
                    "class_fractions": {_name(c): round(float(counts[c] / pred.size), 4)
                                        for c in range(NUM_CLASSES) if counts[c]}}
{% endif %}
        results.append(item_out)
    return results


def main() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
{% if trainer.deterministic %}
    torch.use_deterministic_algorithms(True, warn_only=True)
{% endif %}
    if len(sys.argv) > 2 and sys.argv[1] == "--predict":
        load_predictor(".")
        print(json.dumps(infer([Path(p).read_bytes() for p in sys.argv[2:]]), indent=1))
        return
    device = pick_device()
    print(f"device: {device}")
    train_loader, val_loader, test_loader = make_loaders()
    print(f"images: train={len(train_loader.dataset)} val={len(val_loader.dataset)} "
          f"test={len(test_loader.dataset)} classes={len(CLASS_NAMES)}")
    model = build_model().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    model = fit(model, train_loader, val_loader, device)
    torch.save(model.state_dict(), CHECKPOINT)
    save_inference_state()
    Path("classes.json").write_text(json.dumps(CLASS_NAMES))
    print(f"saved best weights to {CHECKPOINT}")
    metrics, kept = evaluate(model, test_loader, device, keep=8)
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()
                              if isinstance(v, float)))
    Path("metrics.json").write_text(json.dumps(
        {k: v for k, v in metrics.items() if isinstance(v, (float, list))}, indent=1))
    try:
        save_overlays(kept)
        print(f"saved {len(kept)} prediction overlays to {SAMPLES_DIR}/")
    except Exception as exc:  # noqa: BLE001 — overlays are optional
        print(f"(could not save overlays: {exc})")


if __name__ == "__main__":
    main()
'''


# ------------------------------------------------------------------ context

def _strip_main(code: str) -> str:
    head, _sep, _tail = code.partition('\n\nif __name__ == "__main__":')
    body = head.split('\nfrom __future__ import annotations\n', 1)[-1]
    lines = [ln for ln in body.splitlines()
             if not ln.startswith(("import torch", "import torch.nn as nn",
                                   "import torch.nn.functional as F"))]
    return "\n".join(lines).strip("\n") + "\n"


def _resolved_node(graph: Graph, ids) -> tuple:
    found = [n for n in graph.nodes.values() if n.type_id in ids]
    return (found[0], dict(found[0].resolved_params())) if found else (None, {})


def _dataset(graph: Graph) -> dict:
    node = dataset_of(graph)
    if node is None:
        params = {"block": "data.synthetic_shapes", "n_images": 240, "image_size": 128,
                  "max_objects": 3, "seed": 0}
        return params
    out = {"block": node.type_id, **dict(node.resolved_params())}
    from pathlib import Path

    for key in ("images_dir", "annotations", "labels_dir", "root", "masks_dir", "classes"):
        raw = out.get(key)
        if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
            candidate = Path.cwd() / str(raw)
            if candidate.exists():
                out[key] = str(candidate)
    return out


def _class_names(dataset: dict, task: str) -> list:
    if dataset["block"] == "data.synthetic_shapes":
        names = list(SYNTHETIC_CLASSES)
        return ["background", *names] if task == "semantic_segmentation" else names
    return []  # read from the data at training time


def _num_classes(graph: Graph, task: str, dataset: dict) -> int:
    head = head_of(graph)
    if head is not None:
        return int(head.resolved_params()["num_classes"])
    chain = graph.model_nodes()
    return int(graph.infer_shapes()[chain[-1].instance_id][0])


def _augmentations(graph: Graph, notes: list) -> tuple[list, list]:
    always, augment = [], []
    order = {pid: i for i, pid in enumerate(dcat.PREP_IDS)}
    preps = sorted((n for n in graph.nodes.values() if n.type_id in order),
                   key=lambda n: order[n.type_id])
    for node in preps:
        blk = dcat.BLOCKS[node.type_id]
        if node.type_id in UNSUPPORTED_AUGMENT:
            notes.append(f"{UNSUPPORTED_AUGMENT[node.type_id]} is skipped: it does not move "
                         "boxes, masks or keypoints with the image")
            continue
        if node.type_id in IGNORED_PREP:
            notes.append(f"{blk.name} is skipped: {IGNORED_PREP[node.type_id]}")
            continue
        if blk.torch is None or "image" not in blk.applies_to:
            continue
        expr = blk.torch(dict(node.resolved_params()))
        (always if blk.stage == "always" else augment).append(expr)
    return always, augment


def _losses(graph: Graph) -> list:
    out = []
    names = {"vision.loss_dice": "dice_loss", "vision.loss_tversky": "tversky_loss",
             "vision.loss_lovasz": "lovasz_loss", "vision.loss_focal_pixel": "focal_pixel_loss"}
    for node in graph.nodes.values():
        p = dict(node.resolved_params())
        if node.type_id in VISION_LOSSES:
            weight = float(p.pop("weight", 1.0))
            out.append((names[node.type_id], p, weight))
        elif node.type_id == "train.loss_cross_entropy":
            out.append(("cross_entropy",
                        {"label_smoothing": float(p.get("label_smoothing", 0.0) or 0.0)}, 1.0))
    return sorted(out) or [("cross_entropy", {"label_smoothing": 0.0}, 1.0)]


def _optimizer(graph: Graph, box_task: bool) -> str:
    node, params = _resolved_node(graph, cat.OPTIMIZER_IDS)
    if node is None:
        return ("torch.optim.AdamW(params, lr=0.0001, weight_decay=0.0001)" if box_task
                else "torch.optim.AdamW(params, lr=0.001, weight_decay=0.0001)")
    expr = cat.render(node.type_id, cat.resolved(node.type_id, params), "pytorch")
    return expr.replace("model.parameters()", "params")


def _scheduler(graph: Graph) -> tuple:
    node, params = _resolved_node(graph, cat.SCHEDULER_IDS)
    if node is None:
        return None, None
    expr = cat.render(node.type_id, cat.resolved(node.type_id, params), "pytorch")
    return expr, cat.COMPONENTS[node.type_id].meta["step"]


def context(graph: Graph, framework: str) -> dict:
    if framework != "pytorch":
        raise CodegenError("vision tasks train with PyTorch: choose the PyTorch framework")
    task = task_of(graph)
    if task is None:
        raise CodegenError("this design is not a vision task")
    box_task = task.trainer_kind == "detection"
    notes: list[str] = []
    dataset = _dataset(graph)
    if dataset_of(graph) is None:
        notes.append("no dataset block: training on generated shapes (Synthetic Shapes)")
    head = head_of(graph)
    chain = graph.model_nodes()
    shapes = graph.infer_shapes()
    _tnode, trainer = _resolved_node(graph, ("train.trainer",))
    trainer = cat.resolved("train.trainer", trainer)
    _lnode, loader = _resolved_node(graph, ("prep.dataloader",))
    _snode, split = _resolved_node(graph, ("prep.split",))
    split = {**{p.name: p.default for p in dcat.BLOCKS["prep.split"].params}, **split}
    always, augment = _augmentations(graph, notes)
    if box_task and any(n.type_id in (*VISION_LOSSES, *cat.LOSS_IDS)
                        for n in graph.nodes.values()):
        notes.append("loss blocks are ignored: detectors compute their own losses")
    metric_nodes = [n for n in graph.nodes.values() if n.type_id in VISION_METRICS]
    pck = next((float(n.resolved_params()["threshold"]) for n in metric_nodes
                if n.type_id == "eval.pck"), 0.2)
    sched_expr, sched_step = _scheduler(graph)
    primary = "map" if box_task else "miou"
    if task.id == "instance_segmentation" and any(n.type_id == "eval.mask_map"
                                                  for n in metric_nodes):
        primary = "mask_map"
    name = sanitize_identifier(graph.name)
    head_label = (head.definition().display_name + f" ({head.resolved_params().get('arch') or head.resolved_params().get('variant', '')})"
                  if head is not None else "custom layers")
    batch = int(loader.get("batch_size") or 0) or int(trainer["batch_size"])
    return {
        "title": graph.name, "task": task.id, "task_label": task.label,
        "filename": f"{name}_train_pytorch.py", "name": name,
        "data_comment": _data_comment(dataset), "head_label": head_label, "notes": notes,
        "dataset": dataset, "input_shape": list(shapes[chain[0].instance_id]),
        "num_classes": _num_classes(graph, task.id, dataset),
        "class_names": _class_names(dataset, task.id),
        "trainer": trainer, "batch_size": batch,
        "num_workers": int(loader.get("num_workers") or 0),
        "split": {k: split[k] for k in ("val_fraction", "test_fraction", "seed", "shuffle")},
        "primary": primary, "ignore_index": int(dataset.get("ignore_index", 255)),
        "pck_threshold": pck, "box_task": box_task,
        "model_code": _strip_main(generate(graph, "pytorch")),
        "data_code": runtime.DATA_CODE, "metrics_code": runtime.METRICS_CODE,
        "encode_code": runtime.ENCODE_CODE,
        "always": always, "augment": augment, "losses": _losses(graph),
        "optimizer_expr": _optimizer(graph, box_task),
        "scheduler_expr": sched_expr, "scheduler_step": sched_step,
    }


def _data_comment(dataset: dict) -> str:
    block = dataset["block"]
    if block == "data.synthetic_shapes":
        return (f"{dataset['n_images']} generated {dataset['image_size']}px images of squares, "
                "circles and triangles")
    if block == "data.coco":
        return f"COCO annotations {dataset['annotations']} (images in {dataset['images_dir']})"
    if block == "data.yolo":
        return f"YOLO labels in {dataset['labels_dir']} (images in {dataset['images_dir']})"
    if block == "data.voc":
        return f"Pascal VOC at {dataset['root']}"
    return f"masks in {dataset['masks_dir']} (images in {dataset['images_dir']})"


def render(graph: Graph, _spec, framework: str) -> str:
    code = _env.from_string(TEMPLATE).render(**context(graph, framework))
    return code


def register() -> None:
    from ai_made_easy.core.training.generate import register_trainer

    register_trainer("detection", render, needs_spec=False)
    register_trainer("segmentation", render, needs_spec=False)


__all__ = ["render", "register", "context", "VISION_DATA", "get_task"]
