"""Scripts for graphical models: Bayesian / Markov / naive Bayes / dynamic networks (pgmpy),
linear-Gaussian networks and hidden Markov models (hmmlearn).

The script learns structure and parameters when asked, answers the design's queries,
scores the model on held-out rows, draws the network and saves a model that
``load_predictor`` / ``infer`` serve (posteriors for posted evidence).
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, sanitize_identifier
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.pgm import network, runtime
from ai_made_easy.core.pgm.blocks import PGM_DATA, _names

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

TEMPLATE = r'''"""{{ title }} — {{ label }} script generated by AI Made Easy.

Data:   {{ data_comment }}
Usage:  python {{ filename }}          learn, query, score and save the model
Needs:  {{ requirements }}
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import json
import math
import pickle
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image, ImageDraw

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

DESIGN = {{ design | repr }}
DATASET = {{ dataset | repr }}
SEED = {{ seed }}
MODEL_FILE = "{{ name }}_model.pkl"
SAMPLES_DIR = Path("eval_samples")
{{ data_code }}
{{ scores_code }}
{{ plot_code }}


def quiet() -> None:
    try:
        from pgmpy.global_vars import config

        config.set_show_progress(False)
    except ImportError:
        pass


# ======================================================================== data
def read_frame(dataset: dict):
    path = Path(dataset["path"]).expanduser()
    fmt = dataset.get("format", "csv")
    if fmt == "parquet":
        return pd.read_parquet(path)
    if fmt in ("xlsx", "excel"):
        return pd.read_excel(path)
    if fmt == "json":
        return pd.read_json(path)
    return pd.read_csv(path, sep="\t" if fmt == "tsv" else ",")


def load_data():
    if DATASET is None:
        return None
    block = DATASET["block"]
    if block == "data.network_sample":
        return forward_sample(DESIGN["variables"], int(DATASET["n_rows"]), int(DATASET["seed"]))
    if block == "data.regime_series":
        return regime_series(int(DATASET["n_steps"]), int(DATASET["n_regimes"]),
                             float(DATASET["stickiness"]), int(DATASET["seed"]))
    return read_frame(DATASET)


def as_state(value) -> str:
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def prepare(frame):
    """The modelled columns: discrete values as state strings (declared order kept),
    Gaussian columns as floats."""
    out = {}
    for name, var in DESIGN["variables"].items():
        if var["latent"]:
            continue
        if name not in frame.columns:
            raise SystemExit(f"the data has no column '{name}' (columns: {list(frame.columns)})")
        if var["kind"] == "gaussian":
            out[name] = pd.to_numeric(frame[name], errors="coerce")
            continue
        column = frame[name].map(lambda v: None if pd.isna(v) else as_state(v))
        seen = sorted({v for v in column if v is not None})
        if var["states"]:
            unknown = [s for s in seen if s not in var["states"]]
            if unknown:
                raise SystemExit(f"{name} has values {unknown[:5]} that are not among its "
                                 f"states {var['states']}")
        else:
            var["states"] = seen
        out[name] = column
    frame = pd.DataFrame(out)
    dropped = int(frame.isna().any(axis=1).sum())
    if dropped and DESIGN["parameters"]["estimator"] != "em":
        print(f"note: {dropped} row(s) with missing values dropped (use the EM estimator to "
              "keep them)")
        frame = frame.dropna()
    return frame


def split(frame):
    if frame is None or DESIGN["test_fraction"] <= 0 or len(frame) < 10:
        return frame, None
    n_test = int(round(len(frame) * DESIGN["test_fraction"]))
    if DESIGN["kind"] in ("dynamic_bn",) or DESIGN["hmm"]:
        return frame.iloc[:-n_test], frame.iloc[-n_test:]      # keep time order
    order = np.random.default_rng(SEED).permutation(len(frame))
    return frame.iloc[order[n_test:]], frame.iloc[order[:n_test]]


# ======================================================================== structure
def learn_structure(train) -> list:
    cfg = DESIGN["structure"]
    method = cfg["method"]
    score = {"bic": "bic-d", "aic": "aic-d", "bdeu": "bdeu", "k2": "k2", "bds": "bds"}[cfg["score"]]
    if DESIGN["gaussian"]:
        score = {"bic": "bic-g", "aic": "aic-g"}.get(cfg["score"], "bic-g")
    if method == "tree":
        from pgmpy.estimators import TreeSearch

        dag = TreeSearch(train).estimate(show_progress=False)
    else:
        from pgmpy import causal_discovery as cd

        if method == "pc":
            est = cd.PC(return_type="dag", significance_level=cfg["significance"],
                        show_progress=False)
        elif method == "ges":
            est = cd.GES(scoring_method=score, return_type="dag")
        else:
            start = None
            if cfg["start_from_design"] and DESIGN["edges"]:
                from pgmpy.base import DAG

                start = DAG(DESIGN["edges"])
                start.add_nodes_from(train.columns)
            est = cd.HillClimbSearch(scoring_method=score, start_dag=start, return_type="dag",
                                     max_indegree=cfg["max_indegree"] or None,
                                     show_progress=False)
        dag = est.fit(train).causal_graph_
    return sorted([list(e) for e in dag.edges()])


# ======================================================================== models
def estimator():
    from pgmpy import parameter_estimator as pe

    cfg = DESIGN["parameters"]
    names = {n: v["states"] for n, v in DESIGN["variables"].items() if not v["latent"]}
    if cfg["estimator"] == "bayesian":
        return pe.DiscreteBayesianEstimator(state_names=names, prior_type=cfg["prior"],
                                            equivalent_sample_size=cfg["equivalent_sample_size"])
    if cfg["estimator"] == "em":
        latent = {n: len(v["states"]) for n, v in DESIGN["variables"].items() if v["latent"]}
        return pe.DiscreteEM(state_names=names, latent_card=latent or None,
                             max_iter=cfg["iterations"], seed=SEED, show_progress=False)
    return pe.DiscreteMLE(state_names=names)


def tabular(name: str):
    from pgmpy.factors.discrete import TabularCPD

    var = DESIGN["variables"][name]
    parents = var["parents"]
    cards = [len(DESIGN["variables"][p]["states"]) for p in parents]
    names = {name: var["states"], **{p: DESIGN["variables"][p]["states"] for p in parents}}
    return TabularCPD(name, len(var["states"]), var["table"], evidence=parents or None,
                      evidence_card=cards or None, state_names=names)


def rename_latents(model) -> None:
    """EM numbers hidden states 0..k-1: show the designed state names instead."""
    from pgmpy.factors.discrete import TabularCPD

    for name, var in DESIGN["variables"].items():
        if not var["latent"]:
            continue
        for cpd in list(model.get_cpds()):
            if name in cpd.state_names:
                names = dict(cpd.state_names)
                names[name] = var["states"]
                evidence = cpd.variables[1:]
                new = TabularCPD(cpd.variable, cpd.variable_card, cpd.get_values(),
                                 evidence=evidence or None,
                                 evidence_card=[cpd.cardinality[i + 1]
                                                for i in range(len(evidence))] or None,
                                 state_names=names)
                model.remove_cpds(cpd)
                model.add_cpds(new)


def discrete_network(edges: list, train):
    from pgmpy.models import DiscreteBayesianNetwork

    latents = {n for n, v in DESIGN["variables"].items() if v["latent"]}
    model = DiscreteBayesianNetwork([tuple(e) for e in edges], latents=latents)
    model.add_nodes_from(DESIGN["variables"])
    if train is not None:
        model = model.fit(train, estimator=estimator()) or model
        rename_latents(model)
    for name, var in DESIGN["variables"].items():
        if var["table"] is not None:
            if train is not None:
                model.remove_cpds(model.get_cpds(name))
            model.add_cpds(tabular(name))
    model.check_model()
    return model


def naive_bayes(train):
    """Naive Bayes as the equivalent star-shaped Bayesian network (class -> every feature)."""
    target = DESIGN["class_variable"]
    edges = [[target, n] for n in DESIGN["variables"] if n != target]
    DESIGN["edges"] = edges
    for name, var in DESIGN["variables"].items():
        var["parents"] = [target] if name != target else []
        var["table"] = None
    return discrete_network(edges, train)


def markov_network(edges: list, train):
    """Pairwise factors P(u, v) / (P(u) P(v)) with unary marginals: exact for tree-shaped
    networks (the Chow-Liu factorisation), an approximation when the network has loops."""
    from pgmpy.factors.discrete import DiscreteFactor
    from pgmpy.models import DiscreteMarkovNetwork

    if train is None:
        raise SystemExit("a Markov network learns its factors from data: add a dataset")
    model = DiscreteMarkovNetwork([tuple(e) for e in edges])
    model.add_nodes_from(DESIGN["variables"])
    V = DESIGN["variables"]

    def marginal(n):
        counts = train[n].value_counts().reindex(V[n]["states"], fill_value=0).to_numpy() + 1.0
        return counts / counts.sum()

    factors = [DiscreteFactor([n], [len(V[n]["states"])], marginal(n),
                              state_names={n: V[n]["states"]}) for n in V]
    for u, v in edges:
        joint = pd.crosstab(train[u], train[v]).reindex(index=V[u]["states"],
                                                         columns=V[v]["states"],
                                                         fill_value=0).to_numpy() + 1.0
        joint /= joint.sum()
        ratio = joint / np.outer(marginal(u), marginal(v))
        factors.append(DiscreteFactor([u, v], [len(V[u]["states"]), len(V[v]["states"])],
                                      ratio.ravel(), state_names={u: V[u]["states"],
                                                                  v: V[v]["states"]}))
    model.add_factors(*factors)
    model.check_model()
    return model


def markov_log_potential(model, rows) -> np.ndarray:
    """Per-row sum of log factor values (the unnormalised log-probability)."""
    total = np.zeros(len(rows))
    for factor in model.get_factors():
        index = np.zeros(len(rows), int)
        for var, card in zip(factor.variables, factor.cardinality):
            states = factor.state_names[var]
            index = index * card + rows[var].map({s: i for i, s in enumerate(states)}).to_numpy()
        total += np.log(np.clip(factor.values.ravel()[index], 1e-300, None))
    return total


def two_slice(frame):
    """Rows (t-1, t) for a dynamic network: columns 'X[t-1]' and 'X[t]'."""
    prev = frame.iloc[:-1].reset_index(drop=True).add_suffix("[t-1]")
    now = frame.iloc[1:].reset_index(drop=True).add_suffix("[t]")
    return pd.concat([prev, now], axis=1)


def dynamic_network(train):
    """A two-slice network: within-step edges in both slices plus lagged edges."""
    V = DESIGN["variables"]
    edges = [[f"{u}[t-1]", f"{v}[t-1]"] for u, v in DESIGN["edges"]]
    edges += [[f"{u}[t]", f"{v}[t]"] for u, v in DESIGN["edges"]]
    edges += [[f"{p}[t-1]", f"{n}[t]"] for n, v in V.items() for p in v["lagged"]]
    unrolled = {}
    for n, v in V.items():
        for suffix in ("[t-1]", "[t]"):
            unrolled[n + suffix] = {**v, "table": None, "latent": False, "lagged": [],
                                    "parents": sorted(u for u, w in edges if w == n + suffix)}
    DESIGN["variables"] = unrolled
    DESIGN["edges"] = sorted(edges)
    return discrete_network(DESIGN["edges"], two_slice(train) if train is not None else None)


def gaussian_network(edges: list, train) -> dict:
    """name -> (intercept, weights, std, parents) for a linear-Gaussian network."""
    V = DESIGN["variables"]
    cpds = {}
    for name, var in V.items():
        parents = sorted(u for u, v in edges if v == name)
        if train is not None:
            X = np.column_stack([np.ones(len(train))] + [train[p].to_numpy() for p in parents])
            beta, *_ = np.linalg.lstsq(X, train[name].to_numpy(), rcond=None)
            resid = train[name].to_numpy() - X @ beta
            cpds[name] = (float(beta[0]), [float(b) for b in beta[1:]],
                          float(max(resid.std(), 1e-9)), parents)
        else:
            coefs = var["coefficients"] or [0.0] * len(parents)
            cpds[name] = (var["intercept"], coefs, math.sqrt(var["variance"]), parents)
    return cpds


def joint_gaussian(cpds: dict) -> tuple:
    names = list(cpds)
    idx = {n: i for i, n in enumerate(names)}
    k = len(names)
    B, c, D = np.zeros((k, k)), np.zeros(k), np.zeros(k)
    for n, (b0, weights, std, parents) in cpds.items():
        c[idx[n]], D[idx[n]] = b0, std ** 2
        for w, p in zip(weights, parents):
            B[idx[n], idx[p]] = w
    inv = np.linalg.inv(np.eye(k) - B)
    return names, inv @ c, inv @ np.diag(D) @ inv.T


def gaussian_query(cpds: dict, variables: list, evidence: dict) -> dict:
    names, mean, cov = joint_gaussian(cpds)
    obs = [names.index(n) for n in evidence]
    out = {}
    for n in variables:
        i = names.index(n)
        if obs:
            s12 = cov[i, obs]
            s22 = cov[np.ix_(obs, obs)]
            gain = np.linalg.solve(s22, s12)
            diff = np.array([float(evidence[o]) for o in evidence]) - mean[obs]
            m, v = mean[i] + gain @ diff, cov[i, i] - gain @ s12
        else:
            m, v = mean[i], cov[i, i]
        out[n] = {"mean": round(float(m), 6), "std": round(float(math.sqrt(max(v, 0))), 6)}
    return out


# ======================================================================== queries
def predict_class(model, rows, target: str) -> np.ndarray:
    """Most probable class for each row given its other columns (MAP query; repeated
    feature combinations are answered once)."""
    eng = engine(model)
    cache: dict = {}
    out = []
    for record in rows.drop(columns=[target]).to_dict("records"):
        evidence = {k: v for k, v in record.items() if v is not None and not pd.isna(v)}
        key = tuple(sorted(evidence.items()))
        if key not in cache:
            cache[key] = answer(model, [target], evidence, "map")["map"][target]
        out.append(cache[key])
    return np.asarray(out, dtype=object).astype(str)


def engine(model):
    method = DESIGN["inference"]["method"]
    from pgmpy.inference import ApproxInference, BeliefPropagation, VariableElimination

    if DESIGN["kind"] == "markov_network" or method == "belief_propagation":
        return BeliefPropagation(model)
    if method == "sampling":
        return ApproxInference(model)
    return VariableElimination(model)


def answer(model, variables: list, evidence: dict, kind: str) -> dict:
    eng = engine(model)
    approx = type(eng).__name__ == "ApproxInference"
    if kind == "map":
        if approx:
            joint = eng.query(variables, evidence=evidence or None, joint=True,
                              n_samples=DESIGN["inference"]["samples"], seed=SEED,
                              show_progress=False)
            best = np.unravel_index(int(np.argmax(joint.values)), joint.values.shape)
            return {"map": {v: joint.state_names[v][i] for v, i in zip(joint.variables, best)}}
        return {"map": dict(eng.map_query(variables, evidence=evidence or None,
                                          show_progress=False))}
    kwargs = {"n_samples": DESIGN["inference"]["samples"], "seed": SEED} if approx else {}
    result = eng.query(variables, evidence=evidence or None, joint=False,
                       show_progress=False, **kwargs)
    return {"posteriors": {v: {s: round(float(p), 6) for s, p in
                               zip(f.state_names[v], f.values)} for v, f in result.items()}}


def run_queries(model, gaussian_cpds) -> list:
    queries = DESIGN["queries"] or [{"variables": [n for n, v in DESIGN["variables"].items()],
                                     "evidence": {}, "kind": "marginal", "name": "marginals"}]
    results = []
    for q in queries:
        if gaussian_cpds is not None:
            res = {"posteriors": gaussian_query(gaussian_cpds, q["variables"], q["evidence"])}
        else:
            res = answer(model, q["variables"], q["evidence"], q["kind"])
        results.append({**q, **res})
    return results


# ======================================================================== HMM
def hmm_model(seed: int):
    from hmmlearn import hmm

    cfg = DESIGN["hmm"]
    common = {"n_components": cfg["n_states"], "n_iter": cfg["iterations"],
              "random_state": seed}
    if cfg["emission"] == "categorical":
        return hmm.CategoricalHMM(**common)
    if cfg["emission"] == "poisson":
        return hmm.PoissonHMM(**common)
    if cfg["emission"] == "gmm":
        return hmm.GMMHMM(n_mix=cfg["mixtures"], covariance_type=cfg["covariance"], **common)
    return hmm.GaussianHMM(covariance_type=cfg["covariance"], **common)


def hmm_arrays(frame) -> tuple:
    cfg = DESIGN["hmm"]
    cols = cfg["observations"]
    missing = [c for c in cols if c not in frame.columns]
    if missing:
        raise SystemExit(f"observation columns {missing} not found (columns: {list(frame.columns)})")
    X = frame[cols].to_numpy()
    if cfg["emission"] in ("categorical", "poisson"):
        X = X.astype(int)
    lengths = (frame.groupby(cfg["sequence_column"], sort=False).size().tolist()
               if cfg["sequence_column"] else [len(frame)])
    return X, lengths


def run_hmm(frame) -> dict:
    cfg = DESIGN["hmm"]
    train, test = split(frame)
    X, lengths = hmm_arrays(train)
    model, ll = None, -math.inf
    for r in range(cfg.get("restarts", 1)):      # EM finds local optima: keep the best start
        candidate = hmm_model(cfg["seed"] + r)
        candidate.fit(X, lengths)
        score = candidate.score(X, lengths)
        print(f"restart {r + 1}: log-likelihood {score:.2f}")
        if score > ll:
            model, ll = candidate, score
    n = len(X)
    metrics = {"train_log_likelihood": ll / n, "bic": float(model.bic(X, lengths)),
               "converged": float(model.monitor_.converged),
               "iterations": float(len(model.monitor_.history))}
    if test is not None and len(test):
        Xt, lt = hmm_arrays(test)
        metrics["test_log_likelihood"] = model.score(Xt, lt) / len(Xt)
    Xa, la = hmm_arrays(frame)
    states = model.predict(Xa, la)
    if "regime" in frame.columns:
        metrics["state_accuracy"] = best_label_accuracy(frame["regime"].to_numpy(), states,
                                                       cfg["n_states"])
    occupancy = np.bincount(states, minlength=cfg["n_states"]) / len(states)
    lines = ["Transition matrix (row: from, column: to):"]
    lines += ["  " + " ".join(f"{p:6.3f}" for p in row) for row in model.transmat_]
    if hasattr(model, "means_"):
        lines += ["", "State means:"] + [f"  state {i}: {np.round(m, 4).tolist()}  "
                                         f"(share {occupancy[i]:.1%})"
                                         for i, m in enumerate(model.means_)]
    SAMPLES_DIR.mkdir(exist_ok=True)
    (SAMPLES_DIR / "report.txt").write_text("\n".join(lines) + "\n")
    draw_regimes(Xa[:, 0].astype(float)[:800], states[:800],
                 "observed series coloured by decoded state").save(SAMPLES_DIR / "regimes.png")
    with open(MODEL_FILE, "wb") as fh:
        pickle.dump({"kind": "hmm", "model": model, "design": DESIGN}, fh)
    return metrics


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu"):
    global _PREDICTOR
    quiet()
    with open(Path(folder) / MODEL_FILE, "rb") as fh:
        _PREDICTOR = pickle.load(fh)
    DESIGN.update(_PREDICTOR["design"])
    return _PREDICTOR


def infer(raw: list) -> list[dict]:
    """Networks: evidence {"G": "C"} or {"evidence": {...}, "variables": [...], "kind":
    "marginal" | "map"} -> posteriors (Gaussian: mean / std). HMMs: a sequence of
    observations -> the decoded state of every step."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    out = []
    for item in raw:
        if _PREDICTOR["kind"] == "hmm":
            X = np.asarray(item.get("observations", item) if isinstance(item, dict) else item)
            X = X.reshape(len(X), -1)
            if DESIGN["hmm"]["emission"] in ("categorical", "poisson"):
                X = X.astype(int)
            model = _PREDICTOR["model"]
            out.append({"states": model.predict(X).tolist(),
                        "probabilities": np.round(model.predict_proba(X), 6).tolist(),
                        "log_likelihood": float(model.score(X))})
            continue
        item = dict(item)
        evidence = item.pop("evidence", None)
        if evidence is None:
            evidence, item = item, {}
        evidence = {k: v if _PREDICTOR["kind"] == "gaussian" else as_state(v)
                    for k, v in evidence.items()}
        variables = item.get("variables") or [n for n in DESIGN["variables"] if n not in evidence]
        for name, value in evidence.items():
            var = DESIGN["variables"].get(name)
            if var is None:
                raise ValueError(f"unknown variable {name!r}")
            if _PREDICTOR["kind"] != "gaussian" and value not in var["states"]:
                raise ValueError(f"{name} has no state {value!r}; states: {var['states']}")
        if _PREDICTOR["kind"] == "gaussian":
            out.append({"posteriors": gaussian_query(_PREDICTOR["cpds"], variables, evidence)})
        else:
            out.append(answer(_PREDICTOR["model"], variables, evidence,
                              item.get("kind", "marginal")))
    return out


# ======================================================================== main
def format_cpd(cpd) -> list[str]:
    """P(variable | parents) as rows of states × parent combinations (4 decimals)."""
    import itertools

    names = cpd.state_names
    variable, parents = cpd.variable, list(cpd.variables[1:])
    values = cpd.get_values()
    combos = list(itertools.product(*[names[p] for p in parents])) or [()]
    labels = [", ".join(f"{p}={s}" for p, s in zip(parents, c)) or "P" for c in combos]
    width = max(8, *(len(x) for x in labels))
    lines = [f"P({variable}{' | ' + ', '.join(parents) if parents else ''})"]
    lines.append(" " * 12 + " ".join(f"{x:>{width}}" for x in labels))
    for i, state in enumerate(names[variable]):
        lines.append(f"  {str(state)[:10]:<10}" + " ".join(f"{v:>{width}.4f}" for v in values[i]))
    return lines


def report(model, gaussian_cpds, results: list) -> list:
    lines = []
    if gaussian_cpds is not None:
        lines.append("Linear-Gaussian CPDs:")
        for n, (b0, w, std, parents) in gaussian_cpds.items():
            terms = " + ".join(f"{wi:.4g}·{p}" for wi, p in zip(w, parents))
            lines.append(f"  {n} = {b0:.4g}{' + ' + terms if terms else ''} + N(0, {std:.4g}²)")
    elif DESIGN["kind"] != "markov_network":
        lines.append("Conditional probability tables:")
        for cpd in sorted(model.get_cpds(), key=lambda c: c.variable):
            lines += format_cpd(cpd) + [""]
    lines.append("")
    for r in results:
        evidence = ", ".join(f"{k}={v}" for k, v in r["evidence"].items()) or "no evidence"
        lines.append(f"Query {r.get('name') or ', '.join(r['variables'])} | {evidence}")
        if "map" in r:
            lines.append("  most probable: " + ", ".join(f"{k}={v}" for k, v in r["map"].items()))
        for var, dist in r.get("posteriors", {}).items():
            lines.append(f"  {var}: " + ", ".join(f"{s} {p:.4f}" if isinstance(p, float)
                                                   else f"{s} {p}" for s, p in dist.items()))
    return lines


def main() -> None:
    quiet()
    frame = load_data()
    if DESIGN["hmm"]:
        if frame is None:
            raise SystemExit("a hidden Markov model learns from data: add a dataset")
        metrics = run_hmm(frame)
        print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
        Path("metrics.json").write_text(json.dumps(metrics, indent=1))
        return
    data = prepare(frame) if frame is not None else None
    train, test = split(data)
    edges = DESIGN["edges"]
    metrics: dict = {}
    learned = None
    if DESIGN["structure"] and train is not None:
        learned = learn_structure(train)
        if DESIGN["edges"]:
            metrics["shd"] = float(shd(DESIGN["edges"], learned))
            metrics["skeleton_errors"] = float(skeleton_errors(DESIGN["edges"], learned))
        print(f"learned {len(learned)} edge(s): " + ", ".join(f"{u}->{v}" for u, v in learned))
        Path("learned_edges.json").write_text(json.dumps(learned))
        edges = learned
        for var in DESIGN["variables"].values():
            var["table"] = None      # learned structure: every table is learned from data
    gaussian_cpds, model = None, None
    kind = DESIGN["kind"]
    if DESIGN["gaussian"]:
        gaussian_cpds = gaussian_network(edges, train)
        kind = "gaussian"
    elif kind == "naive_bayes":
        model = naive_bayes(train)
        edges = DESIGN["edges"]
    elif kind == "markov_network":
        model = markov_network(edges, train)
    elif kind == "dynamic_bn":
        model = dynamic_network(train)
        edges = DESIGN["edges"]
        if test is not None:
            test = two_slice(test)
        if train is not None:
            train = two_slice(train)
    else:
        DESIGN["edges"] = edges
        for name, var in DESIGN["variables"].items():
            var["parents"] = sorted(u for u, v in edges if v == name)
        model = discrete_network(edges, train)
    metrics["edges"] = float(len(edges))
    if gaussian_cpds is not None:
        if train is not None:
            metrics["train_log_likelihood"] = float(gaussian_log_likelihood(gaussian_cpds,
                                                                            train).mean())
        if test is not None:
            metrics["test_log_likelihood"] = float(gaussian_log_likelihood(gaussian_cpds,
                                                                           test).mean())
    elif kind == "markov_network":
        log_z = math.log(model.get_partition_function())
        for split_name, rows in (("train", train), ("test", test)):
            if rows is not None:
                metrics[f"{split_name}_log_likelihood"] = float(
                    (markov_log_potential(model, rows) - log_z).mean())
    elif not any(v["latent"] for v in DESIGN["variables"].values()):
        arrays = cpd_arrays(model, DESIGN["variables"])
        k = free_parameters(arrays)
        metrics["parameters"] = float(k)
        if train is not None:
            ll = log_likelihood(arrays, DESIGN["variables"], train)
            metrics["train_log_likelihood"] = float(ll.mean())
            metrics["bic"] = float(ll.sum() - 0.5 * k * math.log(len(train)))
        if test is not None:
            metrics["test_log_likelihood"] = float(log_likelihood(arrays, DESIGN["variables"],
                                                                  test).mean())
    target = DESIGN["class_variable"]
    if target and test is not None and model is not None and target in test.columns:
        predicted = predict_class(model, test, target)
        actual = test[target].astype(str).to_numpy()
        metrics["accuracy"] = float(np.mean(predicted == actual))
        majority = test[target].astype(str).value_counts().iloc[0] / len(test)
        metrics["majority_baseline"] = float(majority)
    results = run_queries(model, gaussian_cpds)
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))
    Path("posteriors.json").write_text(json.dumps(results, indent=1))
    SAMPLES_DIR.mkdir(exist_ok=True)
    (SAMPLES_DIR / "report.txt").write_text("\n".join(report(model, gaussian_cpds, results))
                                            + "\n")
    notes = {}
    first = results[0] if results else {}
    for var, dist in first.get("posteriors", {}).items():
        if "mean" in dist:
            notes[var] = f"mean {dist['mean']:.3g}"
        elif dist:
            state, p = max(dist.items(), key=lambda kv: kv[1])
            notes[var] = f"{state} {p:.0%}"
    design = [tuple(e) for e in {{ design_edges | repr }}]
    final = [tuple(e) for e in edges]
    if learned is not None:
        kept = [e for e in final if e in design]
        flipped = [e for e in final if e not in design and (e[1], e[0]) in design]
        added = [e for e in final if e not in design and e not in flipped]
        removed = [e for e in design if e not in final and (e[1], e[0]) not in final]
        draw_network(list(DESIGN["variables"]), kept, added, removed,
                     "learned structure (green: added, red: removed, orange: reversed)",
                     notes, reversed_=flipped).save(SAMPLES_DIR / "network.png")
    else:
        draw_network(list(DESIGN["variables"]), final, title="network",
                     notes=notes).save(SAMPLES_DIR / "network.png")
    with open(MODEL_FILE, "wb") as fh:
        pickle.dump({"kind": "gaussian" if gaussian_cpds is not None else "discrete",
                     "model": model, "cpds": gaussian_cpds, "design": DESIGN}, fh)
    print(f"saved the model to {MODEL_FILE} and a report to {SAMPLES_DIR}/")


if __name__ == "__main__":
    main()
'''

LABELS = {"bayesian_network": "Bayesian network", "markov_network": "Markov network",
          "naive_bayes": "naive Bayes", "dynamic_bn": "dynamic Bayesian network"}


def _picked(graph: Graph, type_id: str) -> dict | None:
    node = next((n for n in graph.nodes.values() if n.type_id == type_id), None)
    return dict(node.resolved_params()) if node is not None else None


def _evidence(text: str) -> dict:
    out = {}
    for part in _names(text):
        if "=" not in part:
            raise CodegenError(f"evidence '{part}' must look like Variable=state")
        k, v = part.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _dataset(graph: Graph) -> dict | None:
    from ai_made_easy.core.pgm.tasks import dataset_of

    node = dataset_of(graph)
    if node is None:
        return None
    out = {"block": node.type_id, **dict(node.resolved_params())}
    raw = out.get("path")
    if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
        candidate = Path.cwd() / str(raw)
        if candidate.exists():
            out["path"] = str(candidate)
    return out


def design(graph: Graph) -> dict:
    """Everything the script needs, as plain data."""
    variables = network.variables(graph)
    model = _picked(graph, "pgm.model") or {"kind": "bayesian_network", "class_variable": "",
                                            "test_fraction": 0.2}
    hmm = _picked(graph, "pgm.hmm")
    structure = _picked(graph, "pgm.structure_learning")
    params = _picked(graph, "pgm.parameter_learning") or {
        "estimator": "em" if any(v.latent for v in variables.values()) else "mle",
        "prior": "BDeu", "equivalent_sample_size": 5.0, "iterations": 100}
    inference = _picked(graph, "pgm.inference") or {"method": "variable_elimination",
                                                    "samples": 5000}
    queries = []
    for node in graph.nodes.values():
        if node.type_id == "pgm.query":
            p = node.resolved_params()
            queries.append({"name": node.instance_id, "variables": _names(p["variables"]),
                            "evidence": _evidence(p["evidence"]), "kind": p["kind"]})
    out_vars = {}
    for name, var in variables.items():
        try:
            table = network.parse_table(var.table)
        except ValueError as exc:
            raise CodegenError(f"{name}: {exc}") from None
        coefficients = [float(c) for c in _names(var.params.get("coefficients", ""))] \
            if var.kind == "gaussian" else []
        out_vars[name] = {"kind": var.kind, "states": var.states, "parents": var.parents,
                          "table": table, "latent": var.latent, "lagged": var.lagged,
                          "intercept": float(var.params.get("intercept", 0.0)),
                          "coefficients": coefficients,
                          "variance": float(var.params.get("variance", 1.0))}
    return {
        "kind": model["kind"], "class_variable": str(model.get("class_variable") or ""),
        "test_fraction": float(hmm["test_fraction"] if hmm else model["test_fraction"]),
        "variables": out_vars, "edges": [list(e) for e in network.edges(graph)],
        "gaussian": any(v.kind == "gaussian" for v in variables.values()),
        "structure": structure, "parameters": params, "inference": inference,
        "queries": queries,
        "hmm": ({**hmm, "observations": _names(hmm["observations"])} if hmm else None),
    }


def render(graph: Graph) -> str:
    from ai_made_easy.core.pgm.rules import pgm_issues

    errors = [i for i in pgm_issues(graph) if i.severity == "error"]
    if errors:
        raise CodegenError("the graphical model has errors:\n"
                           + "\n".join(f"  - {e.message}" for e in errors))
    spec = design(graph)
    dataset = _dataset(graph)
    notes = []
    if spec["kind"] == "markov_network":
        notes.append("Markov factors are pairwise empirical ratios: exact for tree-shaped "
                     "networks, approximate with loops")
    label = "hidden Markov model" if spec["hmm"] else (
        "linear-Gaussian network" if spec["gaussian"] else LABELS[spec["kind"]])
    reqs = "hmmlearn, numpy, pandas, scipy, pillow" if spec["hmm"] else \
        "pgmpy, numpy, pandas, pillow"
    name = sanitize_identifier(graph.name)
    return _env.from_string(TEMPLATE).render(
        title=graph.name, label=label, filename=f"{name}_train_pgmpy.py", name=name,
        notes=notes, requirements=reqs, data_comment=_comment(dataset), design=spec,
        design_edges=spec["edges"], dataset=dataset, seed=0,
        data_code=runtime.DATA_CODE, scores_code=runtime.SCORES_CODE,
        plot_code=runtime.PLOT_CODE)


def _comment(dataset: dict | None) -> str:
    if dataset is None:
        return "none: the probability tables come from the design"
    if dataset["block"] == "data.network_sample":
        return f"{dataset['n_rows']} rows sampled from the designed network"
    if dataset["block"] == "data.regime_series":
        return f"{dataset['n_steps']} generated steps with {dataset['n_regimes']} regimes"
    return str(dataset.get("path"))


def is_pgm_data(type_id: str) -> bool:
    return type_id in PGM_DATA
