"""cifar10_cnn - training script generated by AI Made Easy."""
import time

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# ------------------------------------------------------------------ config
SEED = 42
DEVICE = "auto"
EPOCHS = 30
BATCH_SIZE = 64
EARLY_STOP = 5
VAL_FRACTION = 0.1
TEST_FRACTION = 0.1
NUM_WORKERS = 0
PIN_MEMORY = True
CHECKPOINT = "cifar10_cnn_best.pt"
INPUT_SHAPE = (3, 32, 32)

def pick_device() -> str:
    if DEVICE != "auto":
        return DEVICE
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


# ------------------------------------------------------------------- model
class Cifar10Cnn(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv2d_1 = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, stride=1, padding=1, dilation=1)
        self.batch_norm2d_1 = nn.BatchNorm2d(num_features=32, eps=1e-05, momentum=0.1)
        self.relu_1 = nn.ReLU()
        self.maxpool2d_1 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)
        self.conv2d_2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=1, padding=1, dilation=1)
        self.batch_norm2d_2 = nn.BatchNorm2d(num_features=64, eps=1e-05, momentum=0.1)
        self.relu_2 = nn.ReLU()
        self.dropout_1 = nn.Dropout(p=0.3)
        self.dense_1 = nn.Linear(in_features=64, out_features=10, bias=True)

    def forward(self, x):
        v_conv2d_1 = self.conv2d_1(x)
        v_batch_norm2d_1 = self.batch_norm2d_1(v_conv2d_1)
        v_relu_1 = self.relu_1(v_batch_norm2d_1)
        v_maxpool2d_1 = self.maxpool2d_1(v_relu_1)
        v_conv2d_2 = self.conv2d_2(v_maxpool2d_1)
        v_batch_norm2d_2 = self.batch_norm2d_2(v_conv2d_2)
        v_relu_2 = self.relu_2(v_batch_norm2d_2)
        v_global_avgpool2d_1 = torch.mean(v_relu_2, dim=(2, 3))
        v_dropout_1 = self.dropout_1(v_global_avgpool2d_1)
        v_dense_1 = self.dense_1(v_dropout_1)
        return v_dense_1


# ----------------------------------------------------------------- dataset
from torchvision import datasets, transforms as tv_transforms


def make_loaders(device_hint: str):
    tf = []
    tf.append(tv_transforms.RandomHorizontalFlip())
    tf.append(tv_transforms.RandomRotation(15.0))
    tf.append(tv_transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05))
    tf.append(tv_transforms.ToTensor())
    transform = tv_transforms.Compose(tf)
    train_full = datasets.CIFAR10(root="~/.aime/data", train=True,
                                               download=True, transform=transform)
    test = datasets.CIFAR10(root="~/.aime/data", train=False,
                                        download=True, transform=transform)
    n_val = int(len(train_full) * VAL_FRACTION)
    n_train = len(train_full) - n_val
    gen = torch.Generator().manual_seed(SEED)
    train, val = torch.utils.data.random_split(train_full, [n_train, n_val], generator=gen)
    mk = lambda ds: DataLoader(ds, batch_size=BATCH_SIZE, shuffle=True,
                               num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)
    return mk(train), mk(val), mk(test)


N_CLASSES = 10


def class_metrics(preds: torch.Tensor, targets: torch.Tensor):
    """Confusion-matrix based macro precision/recall/F1."""
    cm = torch.bincount(targets * N_CLASSES + preds, minlength=N_CLASSES ** 2)
    cm = cm.reshape(N_CLASSES, N_CLASSES).float()
    tp = cm.diag()
    precision = tp / (cm.sum(0) + 1e-12)
    recall = tp / (cm.sum(1) + 1e-12)
    f1 = 2 * precision * recall / (precision + recall + 1e-12)
    return precision.mean().item(), recall.mean().item(), f1.mean().item(), cm.long()



@torch.no_grad()
def evaluate(model, loss_fn, loader, device):
    model.eval()
    total, n_seen = 0.0, 0
    all_p, all_t = [], []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        out = model(xb)
        total += loss_fn(out, yb).item() * len(yb)
        n_seen += len(yb)
        all_p.append(out.argmax(1).cpu())
        all_t.append(yb.cpu())
    metrics = {}
    p, t = torch.cat(all_p), torch.cat(all_t)
    metrics["accuracy"] = (p == t).float().mean().item()
    prec, rec, f1, cm = class_metrics(p, t)
    metrics["precision"] = prec
    metrics["recall"] = rec
    metrics["f1"] = f1
    _, _, _, cm = class_metrics(p, t)
    metrics["confusion"] = cm
    return total / max(n_seen, 1), metrics




def main():
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    device = torch.device(pick_device())
    print(f"device: {device}")
    train_loader, val_loader, test_loader = make_loaders(str(device))
    model = Cifar10Cnn().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters()):,}")
    loss_fn = nn.CrossEntropyLoss(label_smoothing=0.0)
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=3)
    best_val, best_state, bad_epochs = float("inf"), None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        t0, running = time.time(), 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad()
            loss = loss_fn(model(xb), yb)
            loss.backward()
            optimizer.step()
            running += loss.item() * len(xb)
        train_loss = running / len(train_loader.dataset)
        val_loss, val_metrics = evaluate(model, loss_fn, val_loader, device)
        scheduler.step(val_loss)
        extra = " ".join(f"{k}={v:.4f}" if isinstance(v, float) else f"{k}={v}"
                         for k, v in val_metrics.items())
        print(f"epoch {epoch}/{EPOCHS} train_loss={train_loss:.4f} "
              f"val_loss={val_loss:.4f} {extra} ({time.time() - t0:.1f}s)")
        if val_loss < best_val:
            best_val, bad_epochs = val_loss, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad_epochs += 1
            if EARLY_STOP and bad_epochs >= EARLY_STOP:
                print(f"early stopping after {epoch} epochs without improvement")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    test_loss, test_metrics = evaluate(model, loss_fn, test_loader, device)
    print("test:", {**test_metrics, "loss": round(test_loss, 4)})
    torch.save(model.state_dict(), CHECKPOINT)
    print(f"saved best weights to {CHECKPOINT}")


if __name__ == "__main__":
    main()
