"""mnist_mlp - training script generated by AI Made Easy."""
import json as _json
import os as _os
import sys
import time

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# ------------------------------------------------------------------ config
SEED = 42
DEVICE = "auto"
EPOCHS = 10
BATCH_SIZE = 32
EARLY_STOP = 3
VAL_FRACTION = 0.1
TEST_FRACTION = 0.1
NUM_WORKERS = 0
PIN_MEMORY = True
CHECKPOINT = "mnist_mlp_best.pt"
INPUT_SHAPE = (784,)

def pick_device() -> str:
    if DEVICE != "auto":
        return DEVICE
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


# ------------------------------------------------------------------- model
class MnistMlp(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense_1 = nn.Linear(in_features=784, out_features=128, bias=True)
        self.relu_1 = nn.ReLU()
        self.dropout_1 = nn.Dropout(p=0.2)
        self.dense_2 = nn.Linear(in_features=128, out_features=10, bias=True)

    def forward(self, x):
        v_dense_1 = self.dense_1(x)
        v_relu_1 = self.relu_1(v_dense_1)
        v_dropout_1 = self.dropout_1(v_relu_1)
        v_dense_2 = self.dense_2(v_dropout_1)
        return v_dense_2


# ----------------------------------------------------------------- dataset

def make_arrays():
    """Synthetic classification data"""
    rng = np.random.default_rng(SEED)
    n, d, k = 1000, 784, 10
    centers = rng.normal(scale=2.0, size=(k, d))
    y = rng.integers(0, k, size=n)
    x = (centers[y] + rng.normal(scale=0.5, size=(n, d))).astype(np.float32)
    return x, y


def make_loaders(device_hint: str):
    x, y = make_arrays()
    x = x.astype(np.float32)
    y = y.astype(np.int64)
    n = len(x)
    idx = np.random.default_rng(SEED).permutation(n)
    n_val = int(n * VAL_FRACTION)
    n_test = int(n * TEST_FRACTION)
    val_i = idx[:n_val]
    test_i = idx[n_val:n_val + n_test]
    train_i = idx[n_val + n_test:]
    mk = lambda ids: DataLoader(
        TensorDataset(torch.from_numpy(x[ids]), torch.from_numpy(y[ids])),
        batch_size=BATCH_SIZE, shuffle=True,
        num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)
    return mk(train_i), mk(val_i), mk(test_i)


N_CLASSES = 10


def class_metrics(preds: torch.Tensor, targets: torch.Tensor):
    """Confusion-matrix based macro precision/recall/F1."""
    cm = torch.bincount(targets * N_CLASSES + preds, minlength=N_CLASSES ** 2)
    cm = cm.reshape(N_CLASSES, N_CLASSES).float()
    tp = cm.diag()
    precision = tp / (cm.sum(0) + 1e-12)
    recall = tp / (cm.sum(1) + 1e-12)
    f1 = 2 * precision * recall / (precision + recall + 1e-12)
    return precision.mean().item(), recall.mean().item(), f1.mean().item(), cm.long()




def _sample_file(loader, idx: int):
    """Original file path for image datasets (for the Mistake Museum)."""
    ds = loader.dataset
    base = getattr(ds, "dataset", ds)
    samples = getattr(base, "samples", None)
    if samples is None:
        return None
    indices = getattr(ds, "indices", None)
    real = indices[idx] if indices is not None else idx
    try:
        return samples[real][0]
    except (IndexError, TypeError):
        return None


def _save_sample_png(t, path):
    """Save a (C,H,W) float tensor as a normalized PNG."""
    from PIL import Image

    a = t.float().cpu().numpy()
    lo, hi = float(a.min()), float(a.max())
    a = ((a - lo) / (hi - lo + 1e-9) * 255).astype("uint8")
    if a.shape[0] == 1:
        a = a[0]
    elif a.shape[0] == 3:
        a = np.transpose(a, (1, 2, 0))
    Image.fromarray(a).save(path)


def dump_test_results(model, loader, device):
    """predictions.json + mistakes.json — the Mistake Museum's raw data."""
    model.eval()
    items, idx = [], 0
    with torch.no_grad():
        for xb, yb in loader:
            out = model(xb.to(device)).cpu()
            probs = (out if out.shape[1] == 1 else torch.softmax(out, dim=1))
            for i in range(len(yb)):
                file = _sample_file(loader, idx)
                if file is None and xb.ndim == 4 and xb.shape[1] in (1, 3):
                    _os.makedirs("samples", exist_ok=True)
                    cand = _os.path.join("samples", f"{idx}.png")
                    try:
                        _save_sample_png(xb[i], cand)
                        file = cand
                    except Exception:
                        file = None
                items.append({
                    "index": idx,
                    "true": int(yb[i]),
                    "probs": [round(float(v), 4) for v in probs[i]],
                    "file": file,
                })
                idx += 1
            if idx >= 300:
                break
    with open("predictions.json", "w") as fh:
        _json.dump(items[:300], fh, indent=1)
    if items and len(items[0]["probs"]) > 1:
        mistakes = [it for it in items
                    if it["probs"].index(max(it["probs"])) != it["true"]]
        with open("mistakes.json", "w") as fh:
            _json.dump(mistakes[:50], fh, indent=1)
    print(f"saved predictions.json ({len(items)} examples)")


@torch.no_grad()
def evaluate(model, loss_fn, loader, device):
    model.eval()
    total, n_seen = 0.0, 0
    all_p, all_t = [], []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        out = model(xb)
        total += loss_fn(out, yb).item() * len(yb)
        n_seen += len(yb)
        all_p.append(out.argmax(1).cpu())
        all_t.append(yb.cpu())
    metrics = {}
    p, t = torch.cat(all_p), torch.cat(all_t)
    metrics["accuracy"] = (p == t).float().mean().item()
    return total / max(n_seen, 1), metrics




def main():
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    device = torch.device(pick_device())
    print(f"device: {device}")
    train_loader, val_loader, test_loader = make_loaders(str(device))
    model = MnistMlp().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters()):,}")
    loss_fn = nn.CrossEntropyLoss(label_smoothing=0.0)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999), eps=1e-08)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50, eta_min=1e-06)
    best_val, best_state, bad_epochs = float("inf"), None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        t0, running = time.time(), 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad()
            loss = loss_fn(model(xb), yb)
            loss.backward()
            optimizer.step()
            running += loss.item() * len(xb)
        train_loss = running / len(train_loader.dataset)
        val_loss, val_metrics = evaluate(model, loss_fn, val_loader, device)
        scheduler.step()
        extra = " ".join(f"{k}={v:.4f}" if isinstance(v, float) else f"{k}={v}"
                         for k, v in val_metrics.items())
        print(f"epoch {epoch}/{EPOCHS} train_loss={train_loss:.4f} "
              f"val_loss={val_loss:.4f} {extra} ({time.time() - t0:.1f}s)")
        if val_loss < best_val:
            best_val, bad_epochs = val_loss, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad_epochs += 1
            if EARLY_STOP and bad_epochs >= EARLY_STOP:
                print(f"early stopping after {epoch} epochs without improvement")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    test_loss, test_metrics = evaluate(model, loss_fn, test_loader, device)
    print("test:", {**test_metrics, "loss": round(test_loss, 4)})
    torch.save(model.state_dict(), CHECKPOINT)
    print(f"saved best weights to {CHECKPOINT}")
    try:
        dump_test_results(model, test_loader, device)
    except Exception as exc:
        print(f"(could not save predictions: {exc})")


if __name__ == "__main__":
    main()
