"""mnist_mlp — PyTorch model generated by AI Made Easy.

Input shape:  (batch, 1, 28, 28)
Output shape: (batch, 10)
Trainable parameters: 101,770
"""
from __future__ import annotations

import torch
import torch.nn as nn


class MnistMlp(nn.Module):
    """mnist_mlp: (batch, 1, 28, 28) -> (batch, 10)."""

    def __init__(self) -> None:
        super().__init__()
        self.flatten_1 = nn.Flatten()
        self.dense_1 = nn.Linear(in_features=784, out_features=128, bias=True)
        self.relu_1 = nn.ReLU()
        self.dropout_1 = nn.Dropout(p=0.2)
        self.dense_2 = nn.Linear(in_features=128, out_features=10, bias=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.flatten_1(x)
        x = self.dense_1(x)
        x = self.relu_1(x)
        x = self.dropout_1(x)
        x = self.dense_2(x)
        return x


def build_model() -> MnistMlp:
    """Construct a freshly initialised model."""
    return MnistMlp()


if __name__ == "__main__":
    model = build_model()
    print(model)
    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"trainable parameters: {n_params:,}")
    x = torch.randn(2, 1, 28, 28)
    model.eval()
    with torch.no_grad():
        y = model(x)
    print("input shape: ", tuple(x.shape))
    print("output shape:", tuple(y.shape))
