"""mnist_mlp — PyTorch training script generated by AI Made Easy.

Task:   multi-class classification (10 classes)
Data:   Torchvision mnist
Model:  MnistMlp (101,770 trainable parameters)
Run:    python mnist_mlp_train_pytorch.py
Needs:  torch, numpy, torchvision, pillow
"""
from __future__ import annotations

import json
import math
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from torchvision import datasets
from torchvision.transforms import v2

# ================================================================ config
SEED = 42
DEVICE = "auto"
EPOCHS = 10
BATCH_SIZE = 32
EARLY_STOP = 3
GRAD_CLIP = 0.0
ACCUM_STEPS = 1
MIXED_PRECISION = False
VAL_FRACTION = 0.1
TEST_FRACTION = 0.1
SPLIT_SEED = 42
NUM_WORKERS = 0
PIN_MEMORY = True
DROP_LAST = False
INPUT_SHAPE = (1, 28, 28)
NUM_CLASSES = 10
NORM_MEAN = [0.1307]
NORM_STD = [0.3081]
CHECKPOINT = "mnist_mlp_best.pt"
CLASS_NAMES = None
# pipeline hooks (fine-tune, distill, prune and quantize stages set these)
LR_SCALE = 1.0          # multiplies the optimizer's learning rates
INIT_HOOK = None        # f(model): load weights / freeze layers before training
EPOCH_HOOK = None       # f(epoch, model): e.g. unfreeze after some epochs
LOSS_HOOK = None        # f(loss, out, xb, model) -> loss: e.g. knowledge distillation
BEFORE_SAVE = None      # f(model): e.g. make pruning permanent
QUANTIZE = ""           # "dynamic_int8": quantize Linear layers when serving


# ================================================================= model
class MnistMlp(nn.Module):
    """(batch, 1, 28, 28) -> (batch, 10)."""

    def __init__(self) -> None:
        super().__init__()
        self.flatten_1 = nn.Flatten()
        self.dense_1 = nn.Linear(in_features=784, out_features=128, bias=True)
        self.relu_1 = nn.ReLU()
        self.dropout_1 = nn.Dropout(p=0.2)
        self.dense_2 = nn.Linear(in_features=128, out_features=10, bias=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.flatten_1(x)
        x = self.dense_1(x)
        x = self.relu_1(x)
        x = self.dropout_1(x)
        x = self.dense_2(x)
        return x


# ================================================================== data
INFERENCE_STATE: dict = {}  # fitted preprocessing, saved with the model for serving


def build_transforms(train: bool, mean=None, std=None) -> v2.Compose:
    steps = [v2.ToImage()]
    if train:
        pass
    steps.append(v2.ToDtype(torch.float32, scale=True))
    if mean is not None:
        steps.append(v2.Normalize(mean, std))
    return v2.Compose(steps)


def image_datasets():
    """Raw (untransformed) datasets: (train pool, official test set or None)."""
    root = str(Path('~/.aime/data').expanduser())
    return (datasets.MNIST(root, train=True, download=True),
            datasets.MNIST(root, train=False, download=True))


class TransformedSubset(Dataset):
    """A view of ``base`` restricted to ``indices`` with its own transform."""

    def __init__(self, base, indices, transform) -> None:
        self.base, self.indices, self.transform = base, list(indices), transform

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, i: int):
        image, label = self.base[self.indices[i]]
        return self.transform(image), label

    def source_file(self, i: int) -> str | None:
        samples = getattr(self.base, "samples", None)
        return samples[self.indices[i]][0] if samples else None


def make_datasets():
    global CLASS_NAMES
    pool, official_test = image_datasets()
    CLASS_NAMES = list(getattr(pool, "classes", None) or []) or None
    idx = np.random.default_rng(SPLIT_SEED).permutation(len(pool))
    n_val = int(len(pool) * VAL_FRACTION)
    train_idx, val_idx, test_idx = idx[n_val:], idx[:n_val], None
    mean, std = NORM_MEAN, NORM_STD
    INFERENCE_STATE["norm"] = (list(mean), list(std)) if mean is not None else None
    eval_tf = build_transforms(train=False, mean=mean, std=std)
    train = TransformedSubset(pool, train_idx, build_transforms(train=True, mean=mean, std=std))
    val = TransformedSubset(pool, val_idx, eval_tf)
    test = (TransformedSubset(official_test, range(len(official_test)), eval_tf)
            if official_test is not None else TransformedSubset(pool, test_idx, eval_tf))
    return train, val, test


def dataset_targets(ds: TransformedSubset) -> np.ndarray:
    targets = getattr(ds.base, "targets", None)
    if targets is None:
        targets = getattr(ds.base, "labels", None)
    if targets is None:
        targets = [ds.base[i][1] for i in range(len(ds.base))]
    return np.asarray(targets)[ds.indices]


def make_loaders():
    train, val, test = make_datasets()
    generator = torch.Generator().manual_seed(SEED)
    train_loader = DataLoader(train, batch_size=BATCH_SIZE, shuffle=True, generator=generator,
                              num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available(), drop_last=DROP_LAST)
    eval_kw = dict(batch_size=BATCH_SIZE, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available())
    return train_loader, DataLoader(val, **eval_kw), DataLoader(test, **eval_kw)


# =============================================================== metrics
def to_scores(outputs: np.ndarray) -> np.ndarray:
    """Model outputs -> class probabilities."""
    e = np.exp(outputs - outputs.max(axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)


def compute_metrics(outputs: np.ndarray, targets: np.ndarray) -> dict:
    """Validation / test metrics from raw model outputs."""
    m = {}
    scores = to_scores(outputs)
    y = (targets.argmax(axis=1) if targets.ndim > 1 else targets).astype(int)
    pred = scores.argmax(axis=1)
    k = scores.shape[1]
    m["accuracy"] = float((pred == y).mean())
    return m


# ============================================================== training
def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def adapt(out: torch.Tensor, y: torch.Tensor):
    """Align output and target shapes for the loss."""
    return out, (y if y.is_floating_point() else y.long())


def make_loss(train_targets: np.ndarray | None = None):
    return nn.CrossEntropyLoss(label_smoothing=0.0)


@torch.no_grad()
def predict(model: nn.Module, loader: DataLoader, device: torch.device):
    model.eval()
    outs, ys = [], []
    for xb, yb in loader:
        outs.append(model(xb.to(device)).float().cpu())
        ys.append(yb)
    if not outs:
        return np.zeros((0,)), np.zeros((0,))
    return torch.cat(outs).numpy(), torch.cat(ys).numpy()


def evaluate(model: nn.Module, loss_fn, loader: DataLoader, device: torch.device):
    outputs, targets = predict(model, loader, device)
    if len(outputs) == 0:
        return float("nan"), {}
    with torch.no_grad():
        out_t, y_t = adapt(torch.from_numpy(outputs), torch.from_numpy(targets))
        loss = float(loss_fn(out_t, y_t))
    return loss, compute_metrics(outputs, targets)


def reset_peak_memory(device: torch.device) -> None:
    if device.type == "cuda":
        torch.cuda.reset_peak_memory_stats(device)


def report_resources(device: torch.device, step_seconds: float) -> None:
    """Measured first-epoch cost; calibrates the designer's budget estimates."""
    peak = 0.0
    if device.type == "cuda":
        peak = torch.cuda.max_memory_allocated(device) / 2**20
    elif device.type == "mps":
        peak = torch.mps.driver_allocated_memory() / 2**20
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


def fit(model: nn.Module, train_loader, val_loader, device, log: bool = True):
    """Train with early stopping on validation loss; returns the best state."""
    loss_fn = make_loss()
    if hasattr(loss_fn, "to"):
        loss_fn = loss_fn.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999), eps=1e-08)
    for group in optimizer.param_groups:
        group["lr"] *= LR_SCALE
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50, eta_min=1e-06)
    use_amp = MIXED_PRECISION and device.type in ("cuda", "mps")
    amp_dtype = torch.float16 if device.type == "cuda" else torch.bfloat16
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp and device.type == "cuda")
    best_loss, best_state, bad_epochs = float("inf"), None, 0
    reset_peak_memory(device)
    for epoch in range(1, EPOCHS + 1):
        if EPOCH_HOOK is not None:
            EPOCH_HOOK(epoch, model)
        model.train()
        started, running, seen = time.time(), 0.0, 0
        optimizer.zero_grad(set_to_none=True)
        step = 0
        for step, (xb, yb) in enumerate(train_loader, start=1):
            xb, yb = xb.to(device), yb.to(device)
            with torch.autocast(device_type=device.type, dtype=amp_dtype, enabled=use_amp):
                out, target = adapt(model(xb), yb)
                loss = loss_fn(out, target)
                if LOSS_HOOK is not None:
                    loss = LOSS_HOOK(loss, out, xb, model)
            scaler.scale(loss / ACCUM_STEPS).backward()
            if step % ACCUM_STEPS == 0 or step == len(train_loader):
                if GRAD_CLIP > 0:
                    scaler.unscale_(optimizer)
                    nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
            running += loss.item() * len(xb)
            seen += len(xb)
        if epoch == 1 and log:
            report_resources(device, (time.time() - started) / max(step, 1))
        train_loss = running / max(seen, 1)
        val_loss, val_metrics = evaluate(model, loss_fn, val_loader, device)
        monitored = val_loss if not math.isnan(val_loss) else train_loss
        scheduler.step()
        if log:
            extra = " ".join(f"{k}={v:.4f}" for k, v in val_metrics.items()
                             if isinstance(v, float))
            lr = optimizer.param_groups[0]["lr"]
            print(f"epoch {epoch}/{EPOCHS} train_loss={train_loss:.4f} val_loss={val_loss:.4f} "
                  f"{extra} lr={lr:.3g} ({time.time() - started:.1f}s)", flush=True)
        if monitored < best_loss:
            best_loss, bad_epochs = monitored, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad_epochs += 1
            if EARLY_STOP and bad_epochs >= EARLY_STOP:
                if log:
                    print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    return model, loss_fn


def save_sample_png(t: torch.Tensor, path: str) -> None:
    from PIL import Image

    a = t.float().cpu().numpy()
    a = ((a - a.min()) / (a.max() - a.min() + 1e-9) * 255).astype("uint8")
    a = a[0] if a.shape[0] == 1 else np.transpose(a, (1, 2, 0))
    Image.fromarray(a).save(path)


def dump_test_results(model: nn.Module, loader: DataLoader, device: torch.device) -> None:
    """predictions.json / mistakes.json for error analysis (first 300 test samples)."""
    outputs, targets = predict(model, loader, device)
    probs = to_scores(outputs)
    items = []
    for i in range(min(len(probs), 300)):
        x, _ = loader.dataset[i]
        source = getattr(loader.dataset, "source_file", None)
        file = source(i) if source else None
        if file is None and x.ndim == 3 and x.shape[0] in (1, 3):
            Path("samples").mkdir(exist_ok=True)
            file = f"samples/{i}.png"
            save_sample_png(x, file)
        true = targets[i].tolist() if np.ndim(targets[i]) else int(targets[i])
        items.append({"index": i, "true": true,
                      "probs": [round(float(v), 4) for v in probs[i]], "file": file})
    Path("predictions.json").write_text(json.dumps(items, indent=1))
    mistakes = [it for it in items if int(np.argmax(it["probs"])) != it["true"]]
    Path("mistakes.json").write_text(json.dumps(mistakes[:50], indent=1))
    if CLASS_NAMES:
        Path("classes.json").write_text(json.dumps(list(CLASS_NAMES)))
    print(f"saved predictions.json ({len(items)} examples)")


# ============================================================= inference
INFERENCE_FILE = "inference_state.pkl"


def save_inference_state() -> None:
    """Persist the fitted preprocessing and class names for serving."""
    import pickle

    INFERENCE_STATE["classes"] = CLASS_NAMES
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(INFERENCE_STATE, fh)


def load_inference_state(folder: str | Path = ".") -> None:
    """Restore the state saved by a training run (trusted files only: pickle)."""
    import pickle

    global CLASS_NAMES
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        INFERENCE_STATE.update(pickle.load(fh))
    CLASS_NAMES = INFERENCE_STATE.get("classes")


def open_image(item):
    """Path, raw bytes, base64 / data-URL string or PIL image -> PIL image."""
    import base64
    import io

    from PIL import Image

    if isinstance(item, Image.Image):
        return item
    if isinstance(item, (bytes, bytearray)):
        return Image.open(io.BytesIO(item))
    if isinstance(item, str):
        if item.startswith("data:"):
            item = item.split(",", 1)[1]
        elif len(item) < 1024 and _is_file(item):
            return Image.open(item)
        return Image.open(io.BytesIO(base64.b64decode(item)))
    arr = np.asarray(item)
    if arr.dtype != np.uint8:
        arr = (np.clip(arr, 0, 1) * 255).astype(np.uint8) if arr.max() <= 1 else arr.astype(np.uint8)
    return Image.fromarray(arr)


def _is_file(text: str) -> bool:
    try:
        return Path(text).is_file()
    except (OSError, ValueError):  # e.g. base64 strings longer than a file name may be
        return False


def class_name(index: int) -> str:
    return str(CLASS_NAMES[index]) if CLASS_NAMES and index < len(CLASS_NAMES) else str(index)


def describe(outputs: np.ndarray) -> list[dict]:
    """Model outputs -> JSON-friendly predictions."""
    scores = to_scores(np.asarray(outputs, dtype=np.float32))
    results = []
    for row in scores:
        best = int(np.argmax(row))
        results.append({"label": class_name(best), "class_index": best,
                        "confidence": round(float(row[best]), 6),
                        "probabilities": {class_name(i): round(float(p), 6)
                                          for i, p in enumerate(row)}})
    return results



def prepare_inputs(raw: list) -> np.ndarray:
    """Images (paths, bytes, base64 strings or PIL images) -> a normalised batch."""
    mean, std = INFERENCE_STATE.get("norm") or (None, None)
    transform = build_transforms(train=False, mean=mean, std=std)
    mode = "L" if INPUT_SHAPE[0] == 1 else "RGB"
    batch = []
    for item in raw:
        img = open_image(item).convert(mode)
        img = img.resize((INPUT_SHAPE[2], INPUT_SHAPE[1]))
        batch.append(transform(img))
    x = torch.stack(batch).numpy()
    if tuple(x.shape[1:]) != tuple(INPUT_SHAPE):
        raise ValueError(f"images become {tuple(x.shape[1:])}; the model expects "
                         f"{tuple(INPUT_SHAPE)}")
    return x


_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    """Load the trained weights and preprocessing state from a run folder."""
    global _PREDICTOR
    load_inference_state(folder)
    model = MnistMlp()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    model.eval()
    if QUANTIZE == "dynamic_int8":       # set by a pipeline's Quantize stage (CPU serving)
        engines = torch.backends.quantized.supported_engines
        if torch.backends.quantized.engine == "none" or torch.backends.quantized.engine \
                not in engines:
            torch.backends.quantized.engine = next(e for e in ("fbgemm", "x86", "qnnpack")
                                                   if e in engines)
        model = torch.ao.quantization.quantize_dynamic(model, {nn.Linear}, dtype=torch.qint8)
    _PREDICTOR = model.to(device)
    return _PREDICTOR


@torch.no_grad()
def infer(raw: list) -> list[dict]:
    """Predictions for a list of raw inputs (see ``prepare_inputs``)."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    x = torch.from_numpy(np.ascontiguousarray(prepare_inputs(raw))).to(device)
    return describe(_PREDICTOR(x).float().cpu().numpy())


def main() -> None:
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    train_loader, val_loader, test_loader = make_loaders()
    print(f"samples: train={len(train_loader.dataset)} val={len(val_loader.dataset)} "
          f"test={len(test_loader.dataset)}")
    model = MnistMlp().to(device)
    if INIT_HOOK is not None:
        INIT_HOOK(model)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    model, loss_fn = fit(model, train_loader, val_loader, device)
    if BEFORE_SAVE is not None:
        BEFORE_SAVE(model)
    torch.save(model.state_dict(), CHECKPOINT)
    save_inference_state()
    print(f"saved best weights to {CHECKPOINT}")
    test_loss, test_metrics = evaluate(model, loss_fn, test_loader, device)
    report = {"loss": test_loss, **{k: v for k, v in test_metrics.items() if isinstance(v, float)}}
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in report.items()))
    Path("metrics.json").write_text(json.dumps(
        {k: v for k, v in {**report, **test_metrics}.items()
         if isinstance(v, (float, list))}, indent=1))
    try:
        dump_test_results(model, test_loader, device)
    except Exception as exc:  # noqa: BLE001 — artefacts are optional
        print(f"(could not save predictions: {exc})")


if __name__ == "__main__":
    main()
