"""mnist_mlp - generated by AI Made Easy."""
import torch
import torch.nn as nn


class MnistMlp(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense_1 = nn.Linear(in_features=784, out_features=128, bias=True)
        self.relu_1 = nn.ReLU()
        self.dropout_1 = nn.Dropout(p=0.2)
        self.dense_2 = nn.Linear(in_features=128, out_features=10, bias=True)

    def forward(self, x):
        v_dense_1 = self.dense_1(x)
        v_relu_1 = self.relu_1(v_dense_1)
        v_dropout_1 = self.dropout_1(v_relu_1)
        v_dense_2 = self.dense_2(v_dropout_1)
        return v_dense_2


if __name__ == "__main__":
    model = MnistMlp()
    print(model)
    x = torch.randn(1, 784)
    out = model(x)
    print("input shape: ", tuple(x.shape))
    print("output shape:", tuple(out.shape))
