"""mnist_mlp — Keras 3 training script generated by AI Made Easy.

Task:   multi-class classification (10 classes)
Data:   Torchvision mnist
Model:  mnist_mlp (101,770 trainable parameters)
Run:    python mnist_mlp_train_keras.py   (any Keras 3 backend: TensorFlow, JAX or PyTorch)
Needs:  keras>=3, numpy
"""
from __future__ import annotations

import json
import math
import time
from pathlib import Path

import keras
import numpy as np
from keras import layers

# ================================================================ config
SEED = 42
EPOCHS = 10
BATCH_SIZE = 32
EARLY_STOP = 3
GRAD_CLIP = 0.0
ACCUM_STEPS = 1
MIXED_PRECISION = False
LR0 = 0.001
VAL_FRACTION = 0.1
TEST_FRACTION = 0.1
SPLIT_SEED = 42
INPUT_SHAPE = (1, 28, 28)  # per sample, channels-first (as designed)
KERAS_TRANSPOSE = (0, 2, 3, 1)  # channels-first -> the model's Keras layout
NUM_CLASSES = 10
MODEL_FILE = "mnist_mlp_best.keras"
CLASS_NAMES = None


# ================================================================= model
def build_model() -> keras.Model:
    inputs = keras.Input(shape=(28, 28, 1), dtype="float32", name="input")
    x = layers.Flatten()(inputs)
    x = layers.Dense(units=128, use_bias=True)(x)
    x = layers.ReLU()(x)
    x = layers.Dropout(rate=0.2)(x)
    x = layers.Dense(units=10, use_bias=True)(x)
    return keras.Model(inputs=inputs, outputs=x, name="mnist_mlp")

# ================================================================== data
INFERENCE_STATE: dict = {}  # fitted preprocessing, saved with the model for serving


def load_raw():
    """Load Torchvision mnist. Returns (features, targets, class names or None)."""
    (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
    x = np.concatenate([x_train, x_test]).astype(np.float32) / 255.0
    x = x[:, None] if x.ndim == 3 else x.transpose(0, 3, 1, 2)
    return x, np.concatenate([y_train, y_test]).reshape(-1), None


def split_indices(n: int, y) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Train / validation / test indices."""
    n_val, n_test = int(n * VAL_FRACTION), int(n * TEST_FRACTION)
    rng = np.random.default_rng(SPLIT_SEED)
    if y is not None and np.ndim(y) == 1 and len(np.unique(y)) < max(n // 5, 2):
        train, val, test = [], [], []
        for c in np.unique(y):
            members = np.flatnonzero(y == c)
            rng.shuffle(members)
            cv, ct = int(round(len(members) * VAL_FRACTION)), int(round(len(members) * TEST_FRACTION))
            val += list(members[:cv])
            test += list(members[cv:cv + ct])
            train += list(members[cv + ct:])
        return (rng.permutation(train), rng.permutation(val).astype(int),
                rng.permutation(test).astype(int))
    idx = rng.permutation(n)
    return idx[n_val + n_test:], idx[:n_val], idx[n_val:n_val + n_test]


class NumericPipeline:
    """Feature transforms fitted on training data only."""

    def fit(self, x: np.ndarray) -> "NumericPipeline":
        flat = x.reshape(len(x), -1)
        axes = (0,) + tuple(range(2, x.ndim))
        return self

    def _scale(self, x: np.ndarray) -> np.ndarray:
        shape = x.shape
        flat = x.reshape(len(x), -1).astype(np.float32)
        return flat.reshape(shape)

    def transform(self, x: np.ndarray) -> np.ndarray:
        x = self._scale(x)
        return x.astype(np.float32)


def make_arrays() -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Load, split and preprocess the data. Statistics come from the training split."""
    x, y, classes = load_raw()
    global CLASS_NAMES
    CLASS_NAMES = classes
    train_i, val_i, test_i = split_indices(len(y), y)
    parts = {"train": train_i, "val": val_i, "test": test_i}
    feats = {k: x[v] for k, v in parts.items()}
    targets = {k: np.asarray(y)[v] for k, v in parts.items()}
    pipeline = NumericPipeline().fit(feats["train"])
    INFERENCE_STATE["numeric"] = dict(vars(pipeline))
    feats = {k: pipeline.transform(v) for k, v in feats.items()}
    out = {}
    for k in parts:
        xs = feats[k]
        if xs.ndim == 2 and len(INPUT_SHAPE) > 1 and xs.shape[1] == int(np.prod(INPUT_SHAPE)):
            xs = xs.reshape(len(xs), *INPUT_SHAPE)
        if xs.shape[1:] != tuple(INPUT_SHAPE):
            raise SystemExit(f"data samples have shape {xs.shape[1:]} but the model expects "
                             f"{tuple(INPUT_SHAPE)}")
        out[k] = (xs, targets[k].astype(np.int64))
    return out


def prepare_inputs(raw: list) -> np.ndarray:
    """Raw inputs -> a model-ready batch, preprocessed exactly as during training.

    raw: images as file paths, bytes, base64 strings or PIL images.
    """
    x = np.stack([image_array(item) for item in raw])
    pipeline = NumericPipeline.__new__(NumericPipeline)
    vars(pipeline).update(INFERENCE_STATE.get("numeric") or {})
    x = pipeline.transform(x)
    if x.ndim == 2 and len(INPUT_SHAPE) > 1 and x.shape[1] == int(np.prod(INPUT_SHAPE)):
        x = x.reshape(len(x), *INPUT_SHAPE)
    if tuple(x.shape[1:]) != tuple(INPUT_SHAPE):
        raise ValueError(f"inputs have shape {tuple(x.shape[1:])}; the model expects "
                         f"{tuple(INPUT_SHAPE)}")
    return x


def image_array(item) -> np.ndarray:
    """An image (path, bytes, base64 string or PIL image) as a [C, H, W] array in [0, 1]."""
    img = open_image(item).convert("L" if INPUT_SHAPE[0] == 1 else "RGB")
    arr = np.asarray(img.resize((INPUT_SHAPE[2], INPUT_SHAPE[1])), dtype=np.float32) / 255.0
    return arr[None] if arr.ndim == 2 else arr.transpose(2, 0, 1)



# =============================================================== metrics
def to_scores(outputs: np.ndarray) -> np.ndarray:
    e = np.exp(outputs - outputs.max(axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)


def compute_metrics(outputs: np.ndarray, targets: np.ndarray) -> dict:
    """Validation / test metrics from raw model outputs."""
    m = {}
    scores = to_scores(outputs)
    y = (targets.argmax(axis=1) if targets.ndim > 1 else targets).astype(int)
    pred = scores.argmax(axis=1)
    k = scores.shape[1]
    m["accuracy"] = float((pred == y).mean())
    return m


# ============================================================== training
def to_model_layout(x: np.ndarray) -> np.ndarray:
    return np.transpose(x, KERAS_TRANSPOSE) if KERAS_TRANSPOSE and len(x) else x


class EpochReport(keras.callbacks.Callback):
    """Prints one progress line per epoch with validation metrics."""

    def __init__(self, x_val: np.ndarray, y_val: np.ndarray) -> None:
        super().__init__()
        self.x_val, self.y_val, self.started = x_val, y_val, time.time()

    def on_epoch_begin(self, epoch, logs=None) -> None:
        self.started = time.time()

    def on_epoch_end(self, epoch, logs=None) -> None:
        logs = logs or {}
        metrics = {}
        if len(self.x_val):
            metrics = compute_metrics(self.model.predict(self.x_val, verbose=0), self.y_val)
        extra = " ".join(f"{k}={v:.4f}" for k, v in metrics.items() if isinstance(v, float))
        print(f"epoch {epoch + 1}/{EPOCHS} train_loss={logs.get('loss', float('nan')):.4f} "
              f"val_loss={logs.get('val_loss', float('nan')):.4f} {extra} "
              f"({time.time() - self.started:.1f}s)", flush=True)


def main() -> None:
    keras.utils.set_random_seed(SEED)
    if MIXED_PRECISION:
        keras.mixed_precision.set_global_policy("mixed_float16")
    arrays = make_arrays()
    (x_train, y_train), (x_val, y_val), (x_test, y_test) = (
        arrays["train"], arrays["val"], arrays["test"])
    x_train, x_val, x_test = map(to_model_layout, (x_train, x_val, x_test))
    print(f"samples: train={len(x_train)} val={len(x_val)} test={len(x_test)}")
    fit_y, val_y = y_train, y_val

    model = build_model()
    print(f"parameters: {model.count_params():,}")
    flat = x_train.reshape(-1, x_train.shape[-1])
    normalize = layers.Normalization(axis=-1, mean=[0.1307], variance=[0.09492561])
    raw = keras.Input(shape=x_train.shape[1:], name="image")
    head = normalize(raw)
    train_model = keras.Model(raw, model(head), name="training_model")
    deploy_model = keras.Model(raw, model(normalize(raw)), name="mnist_mlp_deploy")
    optimizer = keras.optimizers.Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
    train_model.compile(optimizer=optimizer, loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True))
    callbacks = [EpochReport(x_val, y_val)]
    if EARLY_STOP:
        callbacks.append(keras.callbacks.EarlyStopping(
            monitor="val_loss" if len(x_val) else "loss", patience=EARLY_STOP,
            restore_best_weights=True))
    callbacks.append(keras.callbacks.LearningRateScheduler(lambda epoch, lr: 1e-06 + (LR0 - 1e-06) * (1 + math.cos(math.pi * min(epoch, 50) / 50)) / 2))
    train_model.fit(x_train, fit_y, validation_data=(x_val, val_y) if len(x_val) else None,
                    epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=callbacks, verbose=0)
    deploy_model.save(MODEL_FILE)
    save_inference_state()
    print(f"saved model to {MODEL_FILE}")
    outputs = deploy_model.predict(x_test, verbose=0) if len(x_test) else np.zeros((0,))
    metrics = compute_metrics(outputs, y_test) if len(x_test) else {}
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items() if isinstance(v, float)))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))
    probs = to_scores(outputs)
    items = [{"index": i, "true": (y_test[i].tolist() if np.ndim(y_test[i]) else int(y_test[i])),
              "probs": [round(float(v), 4) for v in probs[i]], "file": None}
             for i in range(min(len(probs), 300))]
    Path("predictions.json").write_text(json.dumps(items, indent=1))
    mistakes = [it for it in items if int(np.argmax(it["probs"])) != it["true"]]
    Path("mistakes.json").write_text(json.dumps(mistakes[:50], indent=1))
    print(f"saved predictions.json ({len(items)} examples)")


# ============================================================= inference
INFERENCE_FILE = "inference_state.pkl"


def save_inference_state() -> None:
    """Persist the fitted preprocessing and class names for serving."""
    import pickle

    INFERENCE_STATE["classes"] = CLASS_NAMES
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(INFERENCE_STATE, fh)


def load_inference_state(folder: str | Path = ".") -> None:
    """Restore the state saved by a training run (trusted files only: pickle)."""
    import pickle

    global CLASS_NAMES
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        INFERENCE_STATE.update(pickle.load(fh))
    CLASS_NAMES = INFERENCE_STATE.get("classes")


def open_image(item):
    """Path, raw bytes, base64 / data-URL string or PIL image -> PIL image."""
    import base64
    import io

    from PIL import Image

    if isinstance(item, Image.Image):
        return item
    if isinstance(item, (bytes, bytearray)):
        return Image.open(io.BytesIO(item))
    if isinstance(item, str):
        if item.startswith("data:"):
            item = item.split(",", 1)[1]
        elif len(item) < 1024 and _is_file(item):
            return Image.open(item)
        return Image.open(io.BytesIO(base64.b64decode(item)))
    arr = np.asarray(item)
    if arr.dtype != np.uint8:
        arr = (np.clip(arr, 0, 1) * 255).astype(np.uint8) if arr.max() <= 1 else arr.astype(np.uint8)
    return Image.fromarray(arr)


def _is_file(text: str) -> bool:
    try:
        return Path(text).is_file()
    except (OSError, ValueError):  # e.g. base64 strings longer than a file name may be
        return False


def class_name(index: int) -> str:
    return str(CLASS_NAMES[index]) if CLASS_NAMES and index < len(CLASS_NAMES) else str(index)


def describe(outputs: np.ndarray) -> list[dict]:
    """Model outputs -> JSON-friendly predictions."""
    scores = to_scores(np.asarray(outputs, dtype=np.float32))
    results = []
    for row in scores:
        best = int(np.argmax(row))
        results.append({"label": class_name(best), "class_index": best,
                        "confidence": round(float(row[best]), 6),
                        "probabilities": {class_name(i): round(float(p), 6)
                                          for i, p in enumerate(row)}})
    return results


_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu"):
    """Load the trained model and preprocessing state from a run folder."""
    global _PREDICTOR
    load_inference_state(folder)
    _PREDICTOR = keras.models.load_model(Path(folder) / MODEL_FILE)
    return _PREDICTOR


def infer(raw: list) -> list[dict]:
    """Predictions for a list of raw inputs (see ``prepare_inputs``)."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    x = to_model_layout(prepare_inputs(raw))
    return describe(np.asarray(_PREDICTOR.predict(x, verbose=0)))


if __name__ == "__main__":
    main()
