"""mnist_mlp - Keras training script generated by AI Made Easy."""
import numpy as np
import keras
from keras import layers

# ------------------------------------------------------------------ config
SEED = 42
EPOCHS = 10
INPUT_SHAPE = (784,)  # per-sample, channels-first (as designed)
KERAS_TRANSPOSE = None  # channels-first -> the model's Keras layout
BATCH_SIZE = 32
EARLY_STOP = 3
VAL_FRACTION = 0.1
TEST_FRACTION = 0.1


# ------------------------------------------------------------------- model
def build_model() -> keras.Model:
    inputs = keras.Input(shape=(784,), dtype="float32")
    x = layers.Dense(units=128, use_bias=True)(inputs)
    x = layers.ReLU()(x)
    x = layers.Dropout(rate=0.2)(x)
    x = layers.Dense(units=10, use_bias=True)(x)
    return keras.Model(inputs=inputs, outputs=x)


# ----------------------------------------------------------------- dataset
def make_arrays():
    """Synthetic classification data"""
    rng = np.random.default_rng(SEED)
    n, d, k = 1000, 784, 10
    centers = rng.normal(scale=2.0, size=(k, d))
    y = rng.integers(0, k, size=n)
    x = (centers[y] + rng.normal(scale=0.5, size=(n, d))).astype(np.float32)
    return x, y.astype(np.int64)


def to_model_layout(x):
    """Reshape samples to the designed shape, then to the model's Keras layout."""
    x = x.reshape(len(x), *INPUT_SHAPE)
    return np.transpose(x, KERAS_TRANSPOSE) if KERAS_TRANSPOSE else x


def main():
    keras.utils.set_random_seed(SEED)
    x, y = make_arrays()
    x = to_model_layout(x)
    n = len(x)
    idx = np.random.default_rng(SEED).permutation(n)
    n_val = int(n * VAL_FRACTION)
    n_test = int(n * TEST_FRACTION)
    x_train, y_train = x[idx[n_val + n_test:]], y[idx[n_val + n_test:]]
    x_val, y_val = x[idx[:n_val]], y[idx[:n_val]]
    x_test, y_test = x[idx[n_val:n_val + n_test]], y[idx[n_val:n_val + n_test]]

    model = build_model()
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),
        loss="sparse_categorical_crossentropy",
        metrics=['accuracy'],
    )
    callbacks = []
    if EARLY_STOP:
        callbacks.append(keras.callbacks.EarlyStopping(
            patience=EARLY_STOP, restore_best_weights=True))
    callbacks.append(keras.callbacks.LearningRateScheduler(lambda epoch, lr: 1e-06 + (0.001 - 1e-06) * (1 + np.cos(np.pi * epoch / 50)) / 2))
    model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=EPOCHS,
              batch_size=BATCH_SIZE, callbacks=callbacks, verbose=2)
    results = model.evaluate(x_test, y_test, verbose=0)
    print("test:", dict(zip(model.metrics_names, results)))
    try:
        probs_all = model.predict(x_test[:300], verbose=0)
        items = [{"index": i, "true": int(y_test[i]),
                  "probs": [round(float(v), 4) for v in probs_all[i]],
                  "file": None}
                 for i in range(len(probs_all))]
        with open("predictions.json", "w") as fh:
            import json as _json
            _json.dump(items, fh, indent=1)
        if len(items[0]["probs"]) > 1:
            mistakes = [it for it in items
                        if it["probs"].index(max(it["probs"])) != it["true"]]
            with open("mistakes.json", "w") as fh:
                _json.dump(mistakes[:50], fh, indent=1)
        print(f"saved predictions.json ({len(items)} examples)")
    except Exception as exc:
        print(f"(could not save predictions: {exc})")
    model.save("mnist_mlp_best.keras")
    print("saved model to mnist_mlp_best.keras")


if __name__ == "__main__":
    main()
