"""mnist_mlp — Keras 3 model generated by AI Made Easy.

Input shape:  (batch, 784)
Output shape: (batch, 10)
Trainable parameters: 101,770
Runs on any Keras 3 backend (TensorFlow, JAX or PyTorch).
"""
from __future__ import annotations

import keras
from keras import layers


def build_model() -> keras.Model:
    """Construct a freshly initialised model."""
    inputs = keras.Input(shape=(784,), dtype="float32", name="input")
    x = layers.Dense(units=128, use_bias=True)(inputs)
    x = layers.ReLU()(x)
    x = layers.Dropout(rate=0.2)(x)
    x = layers.Dense(units=10, use_bias=True)(x)
    return keras.Model(inputs=inputs, outputs=x, name="mnist_mlp")


if __name__ == "__main__":
    import numpy as np

    model = build_model()
    model.summary()
    x = np.random.rand(2, 784).astype("float32")
    print("output shape:", tuple(model(x).shape))
