"""mnist_cnn — PyTorch training script generated by AI Made Easy.

Task:   multi-class classification (10 classes)
Data:   Synthetic classification data
Model:  MnistCnn (5,130 trainable parameters)
Run:    python mnist_cnn_train_pytorch.py
Needs:  torch, numpy

Notes:
  - no dataset block: training on synthetic data shaped like the model's input and output
"""
from __future__ import annotations

import json
import math
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

# ================================================================ config
SEED = 42
DEVICE = "auto"
EPOCHS = 10
BATCH_SIZE = 32
EARLY_STOP = 0
GRAD_CLIP = 0.0
ACCUM_STEPS = 1
MIXED_PRECISION = False
VAL_FRACTION = 0.1
TEST_FRACTION = 0.1
SPLIT_SEED = 42
NUM_WORKERS = 0
PIN_MEMORY = True
DROP_LAST = False
INPUT_SHAPE = (1, 28, 28)
NUM_CLASSES = 10
CHECKPOINT = "mnist_cnn_best.pt"
CLASS_NAMES = None


# ================================================================= model
class MnistCnn(nn.Module):
    """(batch, 1, 28, 28) -> (batch, 10)."""

    def __init__(self) -> None:
        super().__init__()
        self.conv2d_1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, stride=1, padding=1)
        self.relu_1 = nn.ReLU()
        self.maxpool2d_1 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)
        self.conv2d_2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=1, padding=1)
        self.relu_2 = nn.ReLU()
        self.dense_1 = nn.Linear(in_features=32, out_features=10, bias=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.conv2d_1(x)
        x = self.relu_1(x)
        x = self.maxpool2d_1(x)
        x = self.conv2d_2(x)
        x = self.relu_2(x)
        x = torch.mean(x, dim=(2, 3))
        x = self.dense_1(x)
        return x

# ================================================================== data
def load_raw():
    """Load Synthetic classification data. Returns (features, targets, class names or None)."""
    rng = np.random.default_rng(42)
    n = 1000
    d, k = 784, 10
    centers = rng.normal(scale=2.0, size=(k, d))
    y = rng.integers(0, k, size=n)
    x = centers[y] + rng.normal(scale=0.5 + 0.3, size=(n, d))
    return x.astype(np.float32), y, [str(i) for i in range(k)]


def split_indices(n: int, y) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Train / validation / test indices."""
    n_val, n_test = int(n * VAL_FRACTION), int(n * TEST_FRACTION)
    rng = np.random.default_rng(SPLIT_SEED)
    if y is not None and np.ndim(y) == 1 and len(np.unique(y)) < max(n // 5, 2):
        train, val, test = [], [], []
        for c in np.unique(y):
            members = np.flatnonzero(y == c)
            rng.shuffle(members)
            cv, ct = int(round(len(members) * VAL_FRACTION)), int(round(len(members) * TEST_FRACTION))
            val += list(members[:cv])
            test += list(members[cv:cv + ct])
            train += list(members[cv + ct:])
        return (rng.permutation(train), rng.permutation(val).astype(int),
                rng.permutation(test).astype(int))
    idx = rng.permutation(n)
    return idx[n_val + n_test:], idx[:n_val], idx[n_val:n_val + n_test]


class NumericPipeline:
    """Feature transforms fitted on training data only."""

    def fit(self, x: np.ndarray) -> "NumericPipeline":
        flat = x.reshape(len(x), -1)
        return self

    def _scale(self, x: np.ndarray) -> np.ndarray:
        shape = x.shape
        flat = x.reshape(len(x), -1).astype(np.float32)
        return flat.reshape(shape)

    def transform(self, x: np.ndarray) -> np.ndarray:
        x = self._scale(x)
        return x.astype(np.float32)


def make_arrays() -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Load, split and preprocess the data. Statistics come from the training split."""
    x, y, classes = load_raw()
    global CLASS_NAMES
    CLASS_NAMES = classes
    train_i, val_i, test_i = split_indices(len(y), y)
    parts = {"train": train_i, "val": val_i, "test": test_i}
    feats = {k: x[v] for k, v in parts.items()}
    targets = {k: np.asarray(y)[v] for k, v in parts.items()}
    pipeline = NumericPipeline().fit(feats["train"])
    feats = {k: pipeline.transform(v) for k, v in feats.items()}
    out = {}
    for k in parts:
        xs = feats[k]
        if xs.ndim == 2 and len(INPUT_SHAPE) > 1 and xs.shape[1] == int(np.prod(INPUT_SHAPE)):
            xs = xs.reshape(len(xs), *INPUT_SHAPE)
        if xs.shape[1:] != tuple(INPUT_SHAPE):
            raise SystemExit(f"data samples have shape {xs.shape[1:]} but the model expects "
                             f"{tuple(INPUT_SHAPE)}")
        out[k] = (xs, targets[k].astype(np.int64))
    return out


class ArrayDataset(Dataset):
    """In-memory samples with an optional per-sample training transform."""

    def __init__(self, x: np.ndarray, y: np.ndarray, transform=None) -> None:
        self.x, self.y, self.transform = torch.from_numpy(x), torch.from_numpy(y), transform

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, i: int):
        x = self.x[i]
        return (self.transform(x) if self.transform else x), self.y[i]


def make_datasets():
    arrays = make_arrays()
    train_tf = None
    return (ArrayDataset(*arrays["train"], transform=train_tf),
            ArrayDataset(*arrays["val"]), ArrayDataset(*arrays["test"]))


def dataset_targets(ds) -> np.ndarray:
    return ds.y.numpy()


def make_loaders():
    train, val, test = make_datasets()
    generator = torch.Generator().manual_seed(SEED)
    train_loader = DataLoader(train, batch_size=BATCH_SIZE, shuffle=True, generator=generator,
                              num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available(), drop_last=DROP_LAST)
    eval_kw = dict(batch_size=BATCH_SIZE, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available())
    return train_loader, DataLoader(val, **eval_kw), DataLoader(test, **eval_kw)


# =============================================================== metrics
def to_scores(outputs: np.ndarray) -> np.ndarray:
    """Model outputs -> class probabilities."""
    e = np.exp(outputs - outputs.max(axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)


def compute_metrics(outputs: np.ndarray, targets: np.ndarray) -> dict:
    """Validation / test metrics from raw model outputs."""
    m = {}
    scores = to_scores(outputs)
    y = (targets.argmax(axis=1) if targets.ndim > 1 else targets).astype(int)
    pred = scores.argmax(axis=1)
    k = scores.shape[1]
    m["accuracy"] = float((pred == y).mean())
    return m


# ============================================================== training
def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def adapt(out: torch.Tensor, y: torch.Tensor):
    """Align output and target shapes for the loss."""
    return out, (y if y.is_floating_point() else y.long())


def make_loss(train_targets: np.ndarray | None = None):
    return nn.CrossEntropyLoss(label_smoothing=0.0)


@torch.no_grad()
def predict(model: nn.Module, loader: DataLoader, device: torch.device):
    model.eval()
    outs, ys = [], []
    for xb, yb in loader:
        outs.append(model(xb.to(device)).float().cpu())
        ys.append(yb)
    if not outs:
        return np.zeros((0,)), np.zeros((0,))
    return torch.cat(outs).numpy(), torch.cat(ys).numpy()


def evaluate(model: nn.Module, loss_fn, loader: DataLoader, device: torch.device):
    outputs, targets = predict(model, loader, device)
    if len(outputs) == 0:
        return float("nan"), {}
    with torch.no_grad():
        out_t, y_t = adapt(torch.from_numpy(outputs), torch.from_numpy(targets))
        loss = float(loss_fn(out_t, y_t))
    return loss, compute_metrics(outputs, targets)


def fit(model: nn.Module, train_loader, val_loader, device, log: bool = True):
    """Train with early stopping on validation loss; returns the best state."""
    loss_fn = make_loss()
    if hasattr(loss_fn, "to"):
        loss_fn = loss_fn.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999), eps=1e-05)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50, eta_min=1e-06)
    use_amp = MIXED_PRECISION and device.type in ("cuda", "mps")
    amp_dtype = torch.float16 if device.type == "cuda" else torch.bfloat16
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp and device.type == "cuda")
    best_loss, best_state, bad_epochs = float("inf"), None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, running, seen = time.time(), 0.0, 0
        optimizer.zero_grad(set_to_none=True)
        for step, (xb, yb) in enumerate(train_loader, start=1):
            xb, yb = xb.to(device), yb.to(device)
            with torch.autocast(device_type=device.type, dtype=amp_dtype, enabled=use_amp):
                out, target = adapt(model(xb), yb)
                loss = loss_fn(out, target)
            scaler.scale(loss / ACCUM_STEPS).backward()
            if step % ACCUM_STEPS == 0 or step == len(train_loader):
                if GRAD_CLIP > 0:
                    scaler.unscale_(optimizer)
                    nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
            running += loss.item() * len(xb)
            seen += len(xb)
        train_loss = running / max(seen, 1)
        val_loss, val_metrics = evaluate(model, loss_fn, val_loader, device)
        monitored = val_loss if not math.isnan(val_loss) else train_loss
        scheduler.step()
        if log:
            extra = " ".join(f"{k}={v:.4f}" for k, v in val_metrics.items()
                             if isinstance(v, float))
            lr = optimizer.param_groups[0]["lr"]
            print(f"epoch {epoch}/{EPOCHS} train_loss={train_loss:.4f} val_loss={val_loss:.4f} "
                  f"{extra} lr={lr:.3g} ({time.time() - started:.1f}s)", flush=True)
        if monitored < best_loss:
            best_loss, bad_epochs = monitored, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad_epochs += 1
            if EARLY_STOP and bad_epochs >= EARLY_STOP:
                if log:
                    print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    return model, loss_fn


def save_sample_png(t: torch.Tensor, path: str) -> None:
    from PIL import Image

    a = t.float().cpu().numpy()
    a = ((a - a.min()) / (a.max() - a.min() + 1e-9) * 255).astype("uint8")
    a = a[0] if a.shape[0] == 1 else np.transpose(a, (1, 2, 0))
    Image.fromarray(a).save(path)


def dump_test_results(model: nn.Module, loader: DataLoader, device: torch.device) -> None:
    """predictions.json / mistakes.json for error analysis (first 300 test samples)."""
    outputs, targets = predict(model, loader, device)
    probs = to_scores(outputs)
    items = []
    for i in range(min(len(probs), 300)):
        x, _ = loader.dataset[i]
        source = getattr(loader.dataset, "source_file", None)
        file = source(i) if source else None
        if file is None and x.ndim == 3 and x.shape[0] in (1, 3):
            Path("samples").mkdir(exist_ok=True)
            file = f"samples/{i}.png"
            save_sample_png(x, file)
        true = targets[i].tolist() if np.ndim(targets[i]) else int(targets[i])
        items.append({"index": i, "true": true,
                      "probs": [round(float(v), 4) for v in probs[i]], "file": file})
    Path("predictions.json").write_text(json.dumps(items, indent=1))
    mistakes = [it for it in items if int(np.argmax(it["probs"])) != it["true"]]
    Path("mistakes.json").write_text(json.dumps(mistakes[:50], indent=1))
    if CLASS_NAMES:
        Path("classes.json").write_text(json.dumps(list(CLASS_NAMES)))
    print(f"saved predictions.json ({len(items)} examples)")


def main() -> None:
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    train_loader, val_loader, test_loader = make_loaders()
    print(f"samples: train={len(train_loader.dataset)} val={len(val_loader.dataset)} "
          f"test={len(test_loader.dataset)}")
    model = MnistCnn().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    model, loss_fn = fit(model, train_loader, val_loader, device)
    torch.save(model.state_dict(), CHECKPOINT)
    print(f"saved best weights to {CHECKPOINT}")
    test_loss, test_metrics = evaluate(model, loss_fn, test_loader, device)
    report = {"loss": test_loss, **{k: v for k, v in test_metrics.items() if isinstance(v, float)}}
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in report.items()))
    Path("metrics.json").write_text(json.dumps(
        {k: v for k, v in {**report, **test_metrics}.items()
         if isinstance(v, (float, list))}, indent=1))
    try:
        dump_test_results(model, test_loader, device)
    except Exception as exc:  # noqa: BLE001 — artefacts are optional
        print(f"(could not save predictions: {exc})")


if __name__ == "__main__":
    main()
