"""mnist_cnn — Keras 3 model generated by AI Made Easy.

Input shape:  (batch, 28, 28, 1) channels-last
Output shape: (batch, 10)
Trainable parameters: 5,130
Runs on any Keras 3 backend (TensorFlow, JAX or PyTorch).
"""
from __future__ import annotations

import keras
from keras import layers


def build_model() -> keras.Model:
    """Construct a freshly initialised model."""
    inputs = keras.Input(shape=(28, 28, 1), dtype="float32", name="input")
    x = layers.Conv2D(filters=16, kernel_size=3, strides=1, padding="same")(inputs)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D(pool_size=2, strides=2, padding="valid")(x)
    x = layers.Conv2D(filters=32, kernel_size=3, strides=1, padding="same")(x)
    x = layers.ReLU()(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(units=10, use_bias=True)(x)
    return keras.Model(inputs=inputs, outputs=x, name="mnist_cnn")


if __name__ == "__main__":
    import numpy as np

    model = build_model()
    model.summary()
    x = np.random.rand(2, 28, 28, 1).astype("float32")
    print("output shape:", tuple(model(x).shape))
