"""regression_mlp — PyTorch training script generated by AI Made Easy.

Task:   regression (1 output)
Data:   Synthetic regression data
Model:  RegressionMlp (3,585 trainable parameters)
Run:    python regression_mlp_train_pytorch.py
Needs:  torch, numpy
"""
from __future__ import annotations

import json
import math
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

# ================================================================ config
SEED = 42
DEVICE = "auto"
EPOCHS = 25
BATCH_SIZE = 32
EARLY_STOP = 5
GRAD_CLIP = 0.0
ACCUM_STEPS = 1
MIXED_PRECISION = False
VAL_FRACTION = 0.1
TEST_FRACTION = 0.1
SPLIT_SEED = 42
NUM_WORKERS = 0
PIN_MEMORY = True
DROP_LAST = False
INPUT_SHAPE = (20,)
CHECKPOINT = "regression_mlp_best.pt"
CLASS_NAMES = None


# ================================================================= model
class RegressionMlp(nn.Module):
    """(batch, 20) -> (batch, 1)."""

    def __init__(self) -> None:
        super().__init__()
        self.dense_1 = nn.Linear(in_features=20, out_features=64, bias=True)
        self.layer_norm_1 = nn.LayerNorm(normalized_shape=[64], eps=1e-05)
        self.relu_1 = nn.ReLU()
        self.dense_2 = nn.Linear(in_features=64, out_features=32, bias=True)
        self.relu_2 = nn.ReLU()
        self.dense_3 = nn.Linear(in_features=32, out_features=1, bias=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.dense_1(x)
        x = self.layer_norm_1(x)
        x = self.relu_1(x)
        x = self.dense_2(x)
        x = self.relu_2(x)
        x = self.dense_3(x)
        return x

# ================================================================== data
INFERENCE_STATE: dict = {}  # fitted preprocessing, saved with the model for serving


def load_raw():
    """Load Synthetic regression data. Returns (features, targets, class names or None)."""
    rng = np.random.default_rng(42)
    n = 2000
    d = 20
    w = rng.normal(size=(d, 1))
    x = rng.normal(size=(n, d)).astype(np.float32)
    y = (x @ w + rng.normal(0, 0.1, (n, 1))).astype(np.float32)
    return x, (y[:, 0] if 1 == 1 else y), None


def split_indices(n: int, y) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Train / validation / test indices."""
    n_val, n_test = int(n * VAL_FRACTION), int(n * TEST_FRACTION)
    rng = np.random.default_rng(SPLIT_SEED)
    idx = rng.permutation(n)
    return idx[n_val + n_test:], idx[:n_val], idx[n_val:n_val + n_test]


class NumericPipeline:
    """Feature transforms fitted on training data only."""

    def fit(self, x: np.ndarray) -> "NumericPipeline":
        flat = x.reshape(len(x), -1)
        scaled = self._scale(x)
        flat_s = scaled.reshape(len(scaled), -1)
        self.min, self.max = flat_s.min(axis=0), flat_s.max(axis=0)
        return self

    def _scale(self, x: np.ndarray) -> np.ndarray:
        shape = x.shape
        flat = x.reshape(len(x), -1).astype(np.float32)
        return flat.reshape(shape)

    def transform(self, x: np.ndarray) -> np.ndarray:
        x = self._scale(x)
        shape = x.shape
        flat = x.reshape(len(x), -1)
        span = np.where(self.max - self.min > 0, self.max - self.min, 1.0)
        flat = ((flat - self.min) / span * (1.0 - -1.0)
                + -1.0)
        x = flat.reshape(shape)
        return x.astype(np.float32)


def make_arrays() -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Load, split and preprocess the data. Statistics come from the training split."""
    x, y, classes = load_raw()
    global CLASS_NAMES
    CLASS_NAMES = classes
    train_i, val_i, test_i = split_indices(len(y), y)
    parts = {"train": train_i, "val": val_i, "test": test_i}
    feats = {k: x[v] for k, v in parts.items()}
    targets = {k: np.asarray(y)[v] for k, v in parts.items()}
    pipeline = NumericPipeline().fit(feats["train"])
    INFERENCE_STATE["numeric"] = dict(vars(pipeline))
    feats = {k: pipeline.transform(v) for k, v in feats.items()}
    out = {}
    for k in parts:
        xs = feats[k]
        if xs.ndim == 2 and len(INPUT_SHAPE) > 1 and xs.shape[1] == int(np.prod(INPUT_SHAPE)):
            xs = xs.reshape(len(xs), *INPUT_SHAPE)
        if xs.shape[1:] != tuple(INPUT_SHAPE):
            raise SystemExit(f"data samples have shape {xs.shape[1:]} but the model expects "
                             f"{tuple(INPUT_SHAPE)}")
        out[k] = (xs, targets[k].astype(np.float32))
    return out


def prepare_inputs(raw: list) -> np.ndarray:
    """Raw inputs -> a model-ready batch, preprocessed exactly as during training.

    raw: samples shaped like INPUT_SHAPE (or flattened).
    """
    x = np.asarray(raw, dtype=np.float32)
    if x.ndim == 1:
        x = x[None]
    pipeline = NumericPipeline.__new__(NumericPipeline)
    vars(pipeline).update(INFERENCE_STATE.get("numeric") or {})
    x = pipeline.transform(x)
    if x.ndim == 2 and len(INPUT_SHAPE) > 1 and x.shape[1] == int(np.prod(INPUT_SHAPE)):
        x = x.reshape(len(x), *INPUT_SHAPE)
    if tuple(x.shape[1:]) != tuple(INPUT_SHAPE):
        raise ValueError(f"inputs have shape {tuple(x.shape[1:])}; the model expects "
                         f"{tuple(INPUT_SHAPE)}")
    return x


class ArrayDataset(Dataset):
    """In-memory samples with an optional per-sample training transform."""

    def __init__(self, x: np.ndarray, y: np.ndarray, transform=None) -> None:
        self.x, self.y, self.transform = torch.from_numpy(x), torch.from_numpy(y), transform

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, i: int):
        x = self.x[i]
        return (self.transform(x) if self.transform else x), self.y[i]


def make_datasets():
    arrays = make_arrays()
    train_tf = None
    return (ArrayDataset(*arrays["train"], transform=train_tf),
            ArrayDataset(*arrays["val"]), ArrayDataset(*arrays["test"]))


def dataset_targets(ds) -> np.ndarray:
    return ds.y.numpy()


def make_loaders():
    train, val, test = make_datasets()
    generator = torch.Generator().manual_seed(SEED)
    train_loader = DataLoader(train, batch_size=BATCH_SIZE, shuffle=True, generator=generator,
                              num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available(), drop_last=DROP_LAST)
    eval_kw = dict(batch_size=BATCH_SIZE, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY and torch.cuda.is_available())
    return train_loader, DataLoader(val, **eval_kw), DataLoader(test, **eval_kw)


# =============================================================== metrics
def to_scores(outputs: np.ndarray) -> np.ndarray:
    """Model outputs -> predictions."""
    return outputs


def compute_metrics(outputs: np.ndarray, targets: np.ndarray) -> dict:
    """Validation / test metrics from raw model outputs."""
    m = {}
    pred = outputs.reshape(targets.shape) if outputs.size == targets.size else outputs
    err = pred - targets
    m["mae"] = float(np.mean(np.abs(err)))
    return m


# ============================================================== training
def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def adapt(out: torch.Tensor, y: torch.Tensor):
    """Align output and target shapes for the loss."""
    if out.ndim == 2 and out.shape[1] == 1 and y.ndim == 1:
        out = out[:, 0]
    return out, y.float()


def make_loss(train_targets: np.ndarray | None = None):
    return nn.SmoothL1Loss(beta=1.0)


@torch.no_grad()
def predict(model: nn.Module, loader: DataLoader, device: torch.device):
    model.eval()
    outs, ys = [], []
    for xb, yb in loader:
        outs.append(model(xb.to(device)).float().cpu())
        ys.append(yb)
    if not outs:
        return np.zeros((0,)), np.zeros((0,))
    return torch.cat(outs).numpy(), torch.cat(ys).numpy()


def evaluate(model: nn.Module, loss_fn, loader: DataLoader, device: torch.device):
    outputs, targets = predict(model, loader, device)
    if len(outputs) == 0:
        return float("nan"), {}
    with torch.no_grad():
        out_t, y_t = adapt(torch.from_numpy(outputs), torch.from_numpy(targets))
        loss = float(loss_fn(out_t, y_t))
    return loss, compute_metrics(outputs, targets)


def reset_peak_memory(device: torch.device) -> None:
    if device.type == "cuda":
        torch.cuda.reset_peak_memory_stats(device)


def report_resources(device: torch.device, step_seconds: float) -> None:
    """Measured first-epoch cost; calibrates the designer's budget estimates."""
    peak = 0.0
    if device.type == "cuda":
        peak = torch.cuda.max_memory_allocated(device) / 2**20
    elif device.type == "mps":
        peak = torch.mps.driver_allocated_memory() / 2**20
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


def fit(model: nn.Module, train_loader, val_loader, device, log: bool = True):
    """Train with early stopping on validation loss; returns the best state."""
    loss_fn = make_loss()
    if hasattr(loss_fn, "to"):
        loss_fn = loss_fn.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999), eps=1e-08)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50, eta_min=1e-06)
    use_amp = MIXED_PRECISION and device.type in ("cuda", "mps")
    amp_dtype = torch.float16 if device.type == "cuda" else torch.bfloat16
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp and device.type == "cuda")
    best_loss, best_state, bad_epochs = float("inf"), None, 0
    reset_peak_memory(device)
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, running, seen = time.time(), 0.0, 0
        optimizer.zero_grad(set_to_none=True)
        step = 0
        for step, (xb, yb) in enumerate(train_loader, start=1):
            xb, yb = xb.to(device), yb.to(device)
            with torch.autocast(device_type=device.type, dtype=amp_dtype, enabled=use_amp):
                out, target = adapt(model(xb), yb)
                loss = loss_fn(out, target)
            scaler.scale(loss / ACCUM_STEPS).backward()
            if step % ACCUM_STEPS == 0 or step == len(train_loader):
                if GRAD_CLIP > 0:
                    scaler.unscale_(optimizer)
                    nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
            running += loss.item() * len(xb)
            seen += len(xb)
        if epoch == 1 and log:
            report_resources(device, (time.time() - started) / max(step, 1))
        train_loss = running / max(seen, 1)
        val_loss, val_metrics = evaluate(model, loss_fn, val_loader, device)
        monitored = val_loss if not math.isnan(val_loss) else train_loss
        scheduler.step()
        if log:
            extra = " ".join(f"{k}={v:.4f}" for k, v in val_metrics.items()
                             if isinstance(v, float))
            lr = optimizer.param_groups[0]["lr"]
            print(f"epoch {epoch}/{EPOCHS} train_loss={train_loss:.4f} val_loss={val_loss:.4f} "
                  f"{extra} lr={lr:.3g} ({time.time() - started:.1f}s)", flush=True)
        if monitored < best_loss:
            best_loss, bad_epochs = monitored, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad_epochs += 1
            if EARLY_STOP and bad_epochs >= EARLY_STOP:
                if log:
                    print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    return model, loss_fn


# ============================================================= inference
INFERENCE_FILE = "inference_state.pkl"


def save_inference_state() -> None:
    """Persist the fitted preprocessing and class names for serving."""
    import pickle

    INFERENCE_STATE["classes"] = CLASS_NAMES
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(INFERENCE_STATE, fh)


def load_inference_state(folder: str | Path = ".") -> None:
    """Restore the state saved by a training run (trusted files only: pickle)."""
    import pickle

    global CLASS_NAMES
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        INFERENCE_STATE.update(pickle.load(fh))
    CLASS_NAMES = INFERENCE_STATE.get("classes")


def class_name(index: int) -> str:
    return str(CLASS_NAMES[index]) if CLASS_NAMES and index < len(CLASS_NAMES) else str(index)


def describe(outputs: np.ndarray) -> list[dict]:
    """Model outputs -> JSON-friendly predictions."""
    scores = to_scores(np.asarray(outputs, dtype=np.float32))
    results = []
    values = scores.reshape(len(scores), -1)
    for row in values:
        results.append({"prediction": float(row[0]) if len(row) == 1
                        else [float(v) for v in row]})
    return results


_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    """Load the trained weights and preprocessing state from a run folder."""
    global _PREDICTOR
    load_inference_state(folder)
    model = RegressionMlp()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    model.eval()
    _PREDICTOR = model.to(device)
    return _PREDICTOR


@torch.no_grad()
def infer(raw: list) -> list[dict]:
    """Predictions for a list of raw inputs (see ``prepare_inputs``)."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    x = torch.from_numpy(np.ascontiguousarray(prepare_inputs(raw))).to(device)
    return describe(_PREDICTOR(x).float().cpu().numpy())


def main() -> None:
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    train_loader, val_loader, test_loader = make_loaders()
    print(f"samples: train={len(train_loader.dataset)} val={len(val_loader.dataset)} "
          f"test={len(test_loader.dataset)}")
    model = RegressionMlp().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    model, loss_fn = fit(model, train_loader, val_loader, device)
    torch.save(model.state_dict(), CHECKPOINT)
    save_inference_state()
    print(f"saved best weights to {CHECKPOINT}")
    test_loss, test_metrics = evaluate(model, loss_fn, test_loader, device)
    report = {"loss": test_loss, **{k: v for k, v in test_metrics.items() if isinstance(v, float)}}
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in report.items()))
    Path("metrics.json").write_text(json.dumps(
        {k: v for k, v in {**report, **test_metrics}.items()
         if isinstance(v, (float, list))}, indent=1))


if __name__ == "__main__":
    main()
