"""skip_mlp - generated by AI Made Easy."""
import torch
import torch.nn as nn


class SkipMlp(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense_1 = nn.Linear(in_features=64, out_features=64, bias=True)
        self.layer_norm_1 = nn.LayerNorm(normalized_shape=[64], eps=1e-05)
        self.relu_1 = nn.ReLU()
        self.dense_2 = nn.Linear(in_features=64, out_features=10, bias=True)

    def forward(self, x):
        v_dense_1 = self.dense_1(x)
        v_layer_norm_1 = self.layer_norm_1(v_dense_1)
        v_relu_1 = self.relu_1(v_layer_norm_1)
        v_add_1 = v_relu_1 + x
        v_dense_2 = self.dense_2(v_add_1)
        return v_dense_2


if __name__ == "__main__":
    model = SkipMlp()
    print(model)
    x = torch.randn(1, 64)
    out = model(x)
    print("input shape: ", tuple(x.shape))
    print("output shape:", tuple(out.shape))
