"""skip_mlp - generated by AI Made Easy."""
import keras
from keras import layers


def build_model() -> keras.Model:
    inputs = keras.Input(shape=(64,))
    x_dense_1 = layers.Dense(units=64, use_bias=True)(inputs)
    x_layer_norm_1 = layers.LayerNormalization(axis=None, epsilon=1e-05)(x_dense_1)
    x_relu_1 = layers.ReLU()(x_layer_norm_1)
    x_add_1 = layers.Add()([x_relu_1, inputs])
    x_dense_2 = layers.Dense(units=10, use_bias=True)(x_add_1)
    return keras.Model(inputs=inputs, outputs=x_dense_2)


if __name__ == "__main__":
    model = build_model()
    model.summary()
