"""skip_mlp — PyTorch model generated by AI Made Easy.

Input shape:  (batch, 64)
Output shape: (batch, 10)
Trainable parameters: 4,938
"""
from __future__ import annotations

import torch
import torch.nn as nn


class SkipMlp(nn.Module):
    """skip_mlp: (batch, 64) -> (batch, 10)."""

    def __init__(self) -> None:
        super().__init__()
        self.dense_1 = nn.Linear(in_features=64, out_features=64, bias=True)
        self.layer_norm_1 = nn.LayerNorm(normalized_shape=[64], eps=1e-05)
        self.relu_1 = nn.ReLU()
        self.dense_2 = nn.Linear(in_features=64, out_features=10, bias=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        dense_1 = self.dense_1(x)
        layer_norm_1 = self.layer_norm_1(dense_1)
        relu_1 = self.relu_1(layer_norm_1)
        x = relu_1 + x
        x = self.dense_2(x)
        return x


def build_model() -> SkipMlp:
    """Construct a freshly initialised model."""
    return SkipMlp()


if __name__ == "__main__":
    model = build_model()
    print(model)
    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"trainable parameters: {n_params:,}")
    x = torch.randn(2, 64)
    model.eval()
    with torch.no_grad():
        y = model(x)
    print("input shape: ", tuple(x.shape))
    print("output shape:", tuple(y.shape))
