"""skip_mlp — Keras 3 model generated by AI Made Easy.

Input shape:  (batch, 64)
Output shape: (batch, 10)
Trainable parameters: 4,938
Runs on any Keras 3 backend (TensorFlow, JAX or PyTorch).
"""
from __future__ import annotations

import keras
from keras import layers


def build_model() -> keras.Model:
    """Construct a freshly initialised model."""
    inputs = keras.Input(shape=(64,), dtype="float32", name="input")
    x = layers.Dense(units=64, use_bias=True)(inputs)
    x = layers.LayerNormalization(axis=-1, epsilon=1e-05)(x)
    x = layers.ReLU()(x)
    x = layers.Add()([x, inputs])
    x = layers.Dense(units=10, use_bias=True)(x)
    return keras.Model(inputs=inputs, outputs=x, name="skip_mlp")


if __name__ == "__main__":
    import numpy as np

    model = build_model()
    model.summary()
    x = np.random.rand(2, 64).astype("float32")
    print("output shape:", tuple(model(x).shape))
