"""Training scripts for image generation: VAE, GAN (adversarial) and diffusion.

Self-contained like every generated script: the model, the image readers and
metrics (``core.generative.runtime``), the training loop for the trainer kind,
sample grids every epoch (printed as ``samples: <png>`` lines the app shows live),
FID / KID against held-out images and ``load_predictor`` / ``infer`` for serving.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.forecast.template import _picked, _strip_main
from ai_made_easy.core.generative import runtime
from ai_made_easy.core.generative.blocks import GENERATIVE_METRICS
from ai_made_easy.core.generative.tasks import dataset_of, generative_kind
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.training import catalog as cat

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

DEFAULT_SCHEDULER = {"timesteps": 1000, "schedule": "cosine", "sampler": "ddim",
                     "sample_steps": 50, "guidance": 2.0, "cond_dropout": 0.1, "ema": 0.999,
                     "sample_every": 5}
KIND_LABELS = {"vae": "variational autoencoder", "adversarial": "GAN",
               "diffusion": "diffusion model"}
DEFAULT_OPTIMIZERS = {"vae": "torch.optim.Adam(params, lr=0.001)",
                      "adversarial": "torch.optim.Adam(params, lr=0.0002, betas=(0.5, 0.999))",
                      "diffusion": "torch.optim.AdamW(params, lr=0.0002)"}

TEMPLATE = r'''"""{{ title }} — {{ kind_label }} training script generated by AI Made Easy.

Data:   {{ data_comment }}
Usage:  python {{ filename }}          train, save weights, sample grids and FID
Needs:  {{ requirements }}
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import base64
import copy
import io
import json
import math
import pickle
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from PIL import Image, ImageDraw

DATASET = {{ dataset | repr }}
KIND = "{{ kind }}"
INPUT_SHAPE = {{ input_shape | repr }}
IMAGE_SHAPE = {{ image_shape | repr }}
EPOCHS = {{ trainer.epochs }}
BATCH_SIZE = {{ batch_size }}
SEED = {{ trainer.seed }}
DEVICE = "{{ trainer.device }}"
GRAD_CLIP = {{ trainer.grad_clip_norm }}
METRICS = {{ metrics | repr }}           # final metrics: name -> feature kind
METRIC_SAMPLES = {{ metric_samples }}
VAE = {{ vae | repr }}
GAN = {{ gan | repr }}
DIFFUSION = {{ diffusion | repr }}
CHECKPOINT = "{{ name }}_best.pt"
INFERENCE_FILE = "inference_state.pkl"
SAMPLES_DIR = Path("eval_samples")
LIVE_DIR = Path("samples")
STATE: dict = {}
# ---------------------------------------------------------------------- model
{{ model_code }}
{{ disc_code }}
{{ data_code }}
{{ metrics_code }}
{{ plot_code }}


# ======================================================================== shared
def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def report_resources(device: torch.device, step_seconds: float) -> None:
    peak = 0.0
    if device.type == "cuda":
        peak = torch.cuda.max_memory_allocated(device) / 2**20
    elif device.type == "mps":
        peak = torch.mps.driver_allocated_memory() / 2**20
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


def to_model_range(x: torch.Tensor) -> torch.Tensor:
    """VAEs work in [0, 1]; GANs and diffusion in [-1, 1]."""
    return x if KIND == "vae" else x * 2 - 1


def to_unit(x: torch.Tensor) -> np.ndarray:
    x = x if KIND == "vae" else (x + 1) / 2
    return x.clamp(0, 1).float().cpu().numpy()


_INCEPTION = None


def inception_features(images: np.ndarray) -> np.ndarray:
    """Pool features [N, 2048] of torchvision's Inception-v3 (downloads its weights)."""
    global _INCEPTION
    import torchvision

    if _INCEPTION is None:
        net = torchvision.models.inception_v3(weights="DEFAULT", aux_logits=True)
        net.fc = nn.Identity()
        _INCEPTION = net.eval()
    out = []
    mean = torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1)
    with torch.no_grad():
        for i in range(0, len(images), 64):
            x = torch.from_numpy(images[i:i + 64])
            x = x.repeat(1, 3, 1, 1) if x.shape[1] == 1 else x[:, :3]
            x = nn.functional.interpolate(x, size=(299, 299), mode="bilinear")
            out.append(_INCEPTION((x - mean) / std).numpy())
    return np.concatenate(out)


def features(images: np.ndarray, kind: str) -> np.ndarray:
    return inception_features(images) if kind == "inception" else pixel_features(images)


def image_scores(fake: np.ndarray, real: np.ndarray, wanted: dict) -> dict:
    out, cache = {}, {}
    for name, kind in wanted.items():
        if kind not in cache:
            cache[kind] = (features(fake, kind), features(real, kind))
        f, r = cache[kind]
        out[name] = frechet_distance(f, r) if name.startswith("fid") else \
            kernel_distance(f, r)
    return out


def save_grid(images: np.ndarray, path: Path, live: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image_grid(images).save(path)
    if live:
        print(f"samples: {path}", flush=True)


def encode_png(image: np.ndarray) -> str:
    arr = (np.clip(image, 0, 1) * 255).astype(np.uint8)
    img = Image.fromarray(arr[0], "L") if arr.shape[0] == 1 else \
        Image.fromarray(arr[:3].transpose(1, 2, 0), "RGB")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode()


# ======================================================================== VAE
def bottleneck(model: nn.Module):
    return next(m for m in model.modules() if hasattr(m, "prior_z"))


def vae_losses(model: nn.Module, x: torch.Tensor) -> tuple:
    out = model(x)
    if out.shape != x.shape:
        raise SystemExit(f"the decoder outputs {list(out.shape[1:])} but images are "
                         f"{list(x.shape[1:])}: the VAE must reconstruct its input")
    if VAE["recon"] == "bce":
        recon = nn.functional.binary_cross_entropy(out.clamp(1e-6, 1 - 1e-6), x,
                                                   reduction="none")
    else:
        recon = nn.functional.mse_loss(out, x, reduction="none")
    return recon.flatten(1).sum(1).mean(), bottleneck(model).kl, out


@torch.no_grad()
def vae_generate(model: nn.Module, n: int, seed: int, device: torch.device) -> np.ndarray:
    model.eval()
    rep = bottleneck(model)
    gen = torch.Generator(device="cpu").manual_seed(seed)
    rep.prior_z = torch.randn((n, *STATE["latent_shape"]), generator=gen).to(device)
    try:
        out = model(torch.zeros((n, *INPUT_SHAPE), device=device))
    finally:
        rep.prior_z = None
    return to_unit(out)


def train_vae(model, train_x, val_x, device):
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
    best, best_state = math.inf, None
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, totals, n = time.time(), np.zeros(2), 0
        weight = VAE["beta"] * (min(1.0, epoch / VAE["kl_warmup"]) if VAE["kl_warmup"] else 1.0)
        order = torch.randperm(len(train_x))
        for start in range(0, len(train_x), BATCH_SIZE):
            x = train_x[order[start:start + BATCH_SIZE]].to(device)
            recon, kl, _ = vae_losses(model, x)
            loss = recon + weight * kl
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            if GRAD_CLIP > 0:
                nn.utils.clip_grad_norm_(params, GRAD_CLIP)
            optimizer.step()
            totals += np.array([recon.item(), kl.item()]) * len(x)
            n += len(x)
            if epoch == 1 and start == 0:
                STATE["latent_shape"] = list(bottleneck(model).latent_shape)
        if epoch == 1:
            report_resources(device, (time.time() - started) / max(1, -(-n // BATCH_SIZE)))
        val = vae_validate(model, val_x, device)
        fake = vae_generate(model, 64, SEED, device)
        save_grid(fake, LIVE_DIR / f"epoch_{epoch:03d}.png", live=True)
        val["fid_pixels"] = image_scores(vae_generate(model, min(METRIC_SAMPLES, 500), SEED + 1,
                                                       device), STATE["real"],
                                         {"fid_pixels": "pixels"})["fid_pixels"]
        shown = " ".join(f"val_{k}={v:.4f}" for k, v in val.items())
        print(f"epoch {epoch}/{EPOCHS} train_loss={totals.sum() / n:.4f} "
              f"train_recon={totals[0] / n:.4f} train_kl={totals[1] / n:.4f} {shown} "
              f"kl_weight={weight:.3g} ({time.time() - started:.1f}s)", flush=True)
        if val["elbo"] < best:
            best = val["elbo"]
            best_state = copy.deepcopy(model.state_dict())
    model.load_state_dict(best_state)
    return model


@torch.no_grad()
def vae_validate(model, val_x, device) -> dict:
    model.eval()
    totals, n = np.zeros(2), 0
    for start in range(0, len(val_x), 256):
        x = val_x[start:start + 256].to(device)
        recon, kl, _ = vae_losses(model, x)
        totals += np.array([recon.item(), kl.item()]) * len(x)
        n += len(x)
    return {"recon": totals[0] / n, "kl": totals[1] / n, "elbo": totals.sum() / n}


# ======================================================================== GAN
def d_loss(disc, real, fake) -> torch.Tensor:
    real_score, fake_score = disc(real), disc(fake)
    if GAN["loss"] == "hinge":
        return nn.functional.relu(1 - real_score).mean() + nn.functional.relu(1 + fake_score).mean()
    if GAN["loss"] == "wgan_gp":
        eps = torch.rand(real.shape[0], 1, 1, 1, device=real.device)
        mixed = (eps * real + (1 - eps) * fake).requires_grad_(True)
        grad = torch.autograd.grad(disc(mixed).sum(), mixed, create_graph=True)[0]
        penalty = ((grad.flatten(1).norm(dim=1) - 1) ** 2).mean()
        return fake_score.mean() - real_score.mean() + GAN["gp_weight"] * penalty
    return nn.functional.softplus(-real_score).mean() + nn.functional.softplus(fake_score).mean()


def g_loss(disc, fake) -> torch.Tensor:
    score = disc(fake)
    return nn.functional.softplus(-score).mean() if GAN["loss"] == "bce" else -score.mean()


@torch.no_grad()
def gan_generate(gen_model: nn.Module, n: int, seed: int, device: torch.device) -> np.ndarray:
    gen_model.eval()
    g = torch.Generator(device="cpu").manual_seed(seed)
    out = [gen_model(torch.randn((min(256, n - i), *INPUT_SHAPE), generator=g).to(device))
           for i in range(0, n, 256)]
    return to_unit(torch.cat(out))


def train_gan(model, train_x, val_x, device):
    disc = Discriminator(IMAGE_SHAPE[0], IMAGE_SHAPE[1], IMAGE_SHAPE[2], GAN["width"],
                         GAN["norm"], GAN["spectral_norm"]).to(device)
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
    d_opt = torch.optim.Adam(disc.parameters(), lr=GAN["lr"], betas=(GAN["beta1"], 0.999))
    best, best_state = math.inf, None
    for epoch in range(1, EPOCHS + 1):
        model.train()
        disc.train()
        started, totals, steps = time.time(), np.zeros(2), 0
        order = torch.randperm(len(train_x))
        for start in range(0, len(train_x), BATCH_SIZE):
            real = to_model_range(train_x[order[start:start + BATCH_SIZE]].to(device))
            for _ in range(GAN["d_steps"]):
                fake = model(torch.randn((len(real), *INPUT_SHAPE), device=device)).detach()
                loss_d = d_loss(disc, real, fake)
                d_opt.zero_grad(set_to_none=True)
                loss_d.backward()
                d_opt.step()
            fake = model(torch.randn((len(real), *INPUT_SHAPE), device=device))
            if fake.shape[1:] != real.shape[1:]:
                raise SystemExit(f"the generator outputs {list(fake.shape[1:])} but images are "
                                 f"{list(real.shape[1:])}")
            loss_g = g_loss(disc, fake)
            optimizer.zero_grad(set_to_none=True)
            loss_g.backward()
            if GRAD_CLIP > 0:
                nn.utils.clip_grad_norm_(params, GRAD_CLIP)
            optimizer.step()
            if not (torch.isfinite(loss_d) and torch.isfinite(loss_g)):
                raise SystemExit("the GAN losses diverged: lower the learning rates")
            totals += np.array([loss_d.item(), loss_g.item()])
            steps += 1
        if epoch == 1:
            report_resources(device, (time.time() - started) / max(steps, 1))
        save_grid(gan_generate(model, 64, SEED, device), LIVE_DIR / f"epoch_{epoch:03d}.png",
                  live=True)
        fid = image_scores(gan_generate(model, min(METRIC_SAMPLES, 500), SEED + 1, device),
                           STATE["real"], {"fid_pixels": "pixels"})["fid_pixels"]
        print(f"epoch {epoch}/{EPOCHS} d_loss={totals[0] / steps:.4f} "
              f"g_loss={totals[1] / steps:.4f} val_fid_pixels={fid:.4f} "
              f"({time.time() - started:.1f}s)", flush=True)
        if fid < best:
            best = fid
            best_state = copy.deepcopy(model.state_dict())
    model.load_state_dict(best_state)
    torch.save(disc.state_dict(), CHECKPOINT.replace("_best.pt", "_discriminator.pt"))
    return model


# ======================================================================== diffusion
def schedule(device) -> dict:
    t = DIFFUSION["timesteps"]
    if DIFFUSION["schedule"] == "linear":
        betas = torch.linspace(1e-4, 0.02, t, dtype=torch.float64)
    else:
        s = 0.008
        steps = torch.linspace(0, t, t + 1, dtype=torch.float64) / t
        cum = torch.cos((steps + s) / (1 + s) * math.pi / 2) ** 2
        betas = (1 - cum[1:] / cum[:-1]).clamp(0, 0.999)
    cum = torch.cumprod(1 - betas, 0)
    return {"betas": betas.float().to(device), "cum": cum.float().to(device)}


def denoiser(model: nn.Module):
    return next(m for m in model.modules() if getattr(m, "is_denoiser", False))


def diffusion_loss(unet, x0, labels, sched) -> torch.Tensor:
    t = torch.randint(0, DIFFUSION["timesteps"], (len(x0),), device=x0.device)
    noise = torch.randn_like(x0)
    a = sched["cum"][t].view(-1, 1, 1, 1)
    xt = a.sqrt() * x0 + (1 - a).sqrt() * noise
    y = None
    if unet.num_classes:
        y = labels.clone()
        y[torch.rand(len(y), device=y.device) < DIFFUSION["cond_dropout"]] = unet.num_classes
    return nn.functional.mse_loss(unet(xt, t, y), noise)


def guided_eps(unet, x, t, y, guidance) -> torch.Tensor:
    tt = torch.full((len(x),), int(t), device=x.device, dtype=torch.long)
    if not unet.num_classes or y is None or guidance == 1.0:
        return unet(x, tt, y)
    null = torch.full_like(y, unet.num_classes)
    both = unet(torch.cat([x, x]), torch.cat([tt, tt]), torch.cat([y, null]))
    cond, uncond = both.chunk(2)
    return uncond + guidance * (cond - uncond)


@torch.no_grad()
def diffusion_sample(unet, n: int, seed: int, device, labels=None, steps=None,
                     guidance=None, sampler=None) -> np.ndarray:
    unet.eval()
    sched = schedule(device)
    steps = int(steps or DIFFUSION["sample_steps"])
    guidance = float(DIFFUSION["guidance"] if guidance is None else guidance)
    sampler = sampler or DIFFUSION["sampler"]
    g = torch.Generator(device="cpu").manual_seed(seed)
    out = []
    for start in range(0, n, 128):
        m = min(128, n - start)
        x = torch.randn((m, *IMAGE_SHAPE), generator=g).to(device)
        y = None if labels is None else labels[start:start + m].to(device)
        if sampler == "ddpm":
            for t in range(DIFFUSION["timesteps"] - 1, -1, -1):
                eps = guided_eps(unet, x, t, y, guidance)
                beta, cum = sched["betas"][t], sched["cum"][t]
                prev = sched["cum"][t - 1] if t > 0 else torch.tensor(1.0, device=device)
                mean = (x - beta / (1 - cum).sqrt() * eps) / (1 - beta).sqrt()
                if t > 0:
                    var = beta * (1 - prev) / (1 - cum)
                    mean = mean + var.sqrt() * torch.randn(x.shape, generator=g).to(device)
                x = mean
        else:
            times = np.linspace(DIFFUSION["timesteps"] - 1, 0, steps).round().astype(int)
            for i, t in enumerate(times):
                eps = guided_eps(unet, x, t, y, guidance)
                a = sched["cum"][t]
                prev = sched["cum"][times[i + 1]] if i + 1 < len(times) else \
                    torch.tensor(1.0, device=device)
                x0 = ((x - (1 - a).sqrt() * eps) / a.sqrt()).clamp(-1, 1)
                x = prev.sqrt() * x0 + (1 - prev).sqrt() * eps
        out.append(x)
    return to_unit(torch.cat(out))


def sample_labels(unet, n: int):
    if not unet.num_classes:
        return None
    return torch.arange(n) % unet.num_classes


@torch.no_grad()
def diffusion_val_loss(unet, val_x, val_y, sched, device) -> float:
    unet.eval()
    torch.manual_seed(SEED)    # the same timesteps and noise every epoch
    total, n = 0.0, 0
    for start in range(0, len(val_x), 256):
        x0 = to_model_range(val_x[start:start + 256].to(device))
        total += diffusion_loss(unet, x0, val_y[start:start + 256].to(device), sched).item() \
            * len(x0)
        n += len(x0)
    return total / max(n, 1)


def train_diffusion(model, train_x, val_x, train_y, val_y, device):
    unet = denoiser(model)
    ema = copy.deepcopy(unet).eval() if DIFFUSION["ema"] > 0 else unet
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
    sched = schedule(device)
    best, best_state, updates = math.inf, None, 0
    for epoch in range(1, EPOCHS + 1):
        unet.train()
        started, total, n = time.time(), 0.0, 0
        order = torch.randperm(len(train_x))
        for start in range(0, len(train_x), BATCH_SIZE):
            idx = order[start:start + BATCH_SIZE]
            x0 = to_model_range(train_x[idx].to(device))
            loss = diffusion_loss(unet, x0, train_y[idx].to(device), sched)
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            if GRAD_CLIP > 0:
                nn.utils.clip_grad_norm_(params, GRAD_CLIP)
            optimizer.step()
            if ema is not unet:   # EMA with warm-up: early averages follow the weights
                updates += 1
                decay = min(DIFFUSION["ema"], (1 + updates) / (10 + updates))
                with torch.no_grad():
                    for e, p in zip(ema.parameters(), unet.parameters()):
                        e.lerp_(p, 1 - decay)
                    for e, b in zip(ema.buffers(), unet.buffers()):
                        e.copy_(b)
            total += loss.item() * len(x0)
            n += len(x0)
        if epoch == 1:
            report_resources(device, (time.time() - started) / max(1, -(-n // BATCH_SIZE)))
        val_loss = diffusion_val_loss(ema, val_x, val_y, sched, device)
        extra = ""
        if epoch % DIFFUSION["sample_every"] == 0 or epoch == EPOCHS:
            grid = diffusion_sample(ema, 32, SEED, device, sample_labels(ema, 32))
            save_grid(grid, LIVE_DIR / f"epoch_{epoch:03d}.png", live=True)
            k = min(METRIC_SAMPLES, 200)
            fake = diffusion_sample(ema, k, SEED + 1, device, sample_labels(ema, k))
            fid = image_scores(fake, STATE["real"], {"fid_pixels": "pixels"})["fid_pixels"]
            extra = f" val_fid_pixels={fid:.4f}"
        print(f"epoch {epoch}/{EPOCHS} train_loss={total / n:.4f} val_loss={val_loss:.4f}"
              f"{extra} ({time.time() - started:.1f}s)", flush=True)
        if val_loss < best:
            best = val_loss
            best_state = copy.deepcopy(ema.state_dict())
    unet.load_state_dict(best_state)
    return model


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    global _PREDICTOR
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    model = build_model()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    _PREDICTOR = model.eval().to(device)
    return _PREDICTOR


def generate_images(model, n: int, seed: int, device, label=None, steps=None,
                    guidance=None) -> np.ndarray:
    if KIND == "vae":
        return vae_generate(model, n, seed, device)
    if KIND == "adversarial":
        return gan_generate(model, n, seed, device)
    unet = denoiser(model)
    labels = None
    if unet.num_classes:
        labels = sample_labels(unet, n) if label is None else torch.full((n,), int(label))
    return diffusion_sample(unet, n, seed, device, labels, steps, guidance)


@torch.no_grad()
def infer(raw: list) -> list[dict]:
    """Each request: a count, or {"n", "seed", "class" (name or index), "steps",
    "guidance"} -> {"images": [base64 PNG, ...]}."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    results = []
    for item in raw:
        item = item if isinstance(item, dict) else {"n": int(item or 1)}
        n = max(1, min(int(item.get("n", 1)), 64))
        label = item.get("class")
        if isinstance(label, str):
            names = STATE.get("names", [])
            if label not in names:
                raise ValueError(f"unknown class {label!r}; classes: {names}")
            label = names.index(label)
        images = generate_images(_PREDICTOR, n, int(item.get("seed", 0)), device, label,
                                 item.get("steps"), item.get("guidance"))
        results.append({"images": [encode_png(img) for img in images]})
    return results


def main() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    images, labels, names = load_images(DATASET, IMAGE_SHAPE)
    if list(images.shape[1:]) != IMAGE_SHAPE:
        raise SystemExit(f"the dataset gives {list(images.shape[1:])} images but the design "
                         f"makes {IMAGE_SHAPE}")
    split = split_indices(len(images), float(DATASET.get("val_fraction", 0.1)), 0.0, SEED)
    if not len(split["val"]):
        split["val"] = split["train"][: max(1, len(split["train"]) // 10)]
    x = torch.from_numpy(images)
    y = torch.from_numpy(labels)
    STATE.update(names=names, image_shape=IMAGE_SHAPE)
    STATE["real"] = images[split["val"]][:METRIC_SAMPLES] if len(split["val"]) >= 50 else \
        images[split["train"]][:METRIC_SAMPLES]
    print(f"images: train={len(split['train'])} val={len(split['val'])} classes={len(names)}")
    model = build_model().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    train_x, val_x = x[split["train"]], x[split["val"]]
    if KIND == "vae":
        model = train_vae(model, train_x, val_x, device)
    elif KIND == "adversarial":
        model = train_gan(model, train_x, val_x, device)
    else:
        model = train_diffusion(model, train_x, val_x, y[split["train"]], y[split["val"]],
                                device)
    torch.save(model.state_dict(), CHECKPOINT)
    real = STATE.pop("real")
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    print(f"saved best weights to {CHECKPOINT}")
    fake = generate_images(model, len(real), SEED + 2, device)
    metrics = image_scores(fake, real, METRICS)
    if KIND == "vae":
        metrics.update(vae_validate(model, val_x, device))
        with torch.no_grad():
            recon = vae_losses(model.eval(), val_x[:8].to(device))[2]
        save_grid(np.concatenate([val_x[:8].numpy(), recon.clamp(0, 1).cpu().numpy()]),
                  SAMPLES_DIR / "reconstructions.png")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))
    Path("classes.json").write_text(json.dumps(names))
    save_grid(generate_images(model, 64, SEED, device), SAMPLES_DIR / "samples.png")
    print(f"saved sample grids to {SAMPLES_DIR}/")


if __name__ == "__main__":
    main()
'''


def _dataset(graph: Graph) -> dict:
    node = dataset_of(graph)
    if node is None:
        return {"block": "data.synthetic_images", "kind": "shapes", "n_images": 2000,
                "image_size": 32, "channels": 1, "seed": 0, "val_fraction": 0.1}
    out = {"block": node.type_id, **dict(node.resolved_params())}
    for key in ("root", "path"):
        raw = out.get(key)
        if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
            candidate = Path.cwd() / str(raw)
            if candidate.exists():
                out[key] = str(candidate)
    return out


def _metrics(graph: Graph) -> tuple[dict, int]:
    nodes = [n for n in graph.nodes.values() if n.type_id in ("eval.fid", "eval.kid")]
    if not nodes:
        return {"fid": "pixels"}, 500
    wanted = {GENERATIVE_METRICS[n.type_id]["key"]: n.resolved_params()["features"]
              for n in nodes}
    return wanted, max(int(n.resolved_params()["samples"]) for n in nodes)


def context(graph: Graph, framework: str) -> dict:
    from ai_made_easy.core.generative.helpers import DCGAN_INIT, DISCRIMINATOR
    from ai_made_easy.core.training.generate import own_loop_requirements

    if framework != "pytorch":
        raise CodegenError("generative models train with PyTorch: choose the PyTorch "
                           "framework")
    kind = generative_kind(graph)
    if kind not in KIND_LABELS:
        raise CodegenError("not an image-generation design")
    notes: list[str] = []
    dataset = _dataset(graph)
    if dataset_of(graph) is None:
        notes.append("no dataset block: training on generated shapes (Synthetic Images)")
    chain = graph.model_nodes()
    shapes = graph.infer_shapes()
    input_shape = list(shapes[chain[0].instance_id])
    image_shape = list(shapes[chain[-1].instance_id]) if kind == "adversarial" else input_shape
    _t, trainer = _picked(graph, ("train.trainer",))
    trainer = cat.resolved("train.trainer", trainer)
    _l, loader = _picked(graph, ("prep.dataloader",))
    opt, opt_params = _picked(graph, cat.OPTIMIZER_IDS)
    optimizer = (DEFAULT_OPTIMIZERS[kind] if opt is None else
                 cat.render(opt.type_id, cat.resolved(opt.type_id, opt_params), "pytorch")
                 .replace("model.parameters()", "params"))
    losses = [n for n in graph.nodes.values() if n.type_id in cat.LOSS_IDS]
    recon = "bce" if any(n.type_id == "train.loss_bce" for n in losses) else "mse"
    if kind != "vae" and losses:
        notes.append("loss blocks are ignored: GANs and diffusion models use their own losses")
    _r, rep = _picked(graph, ("gen.reparameterize",))
    _d, disc = _picked(graph, ("gen.discriminator",))
    _s, sched = _picked(graph, ("gen.noise_scheduler",))
    if kind == "diffusion" and _s is None:
        sched = dict(DEFAULT_SCHEDULER)
        notes.append("no Noise Scheduler block: cosine schedule, 1000 steps, DDIM sampling")
    metrics, samples = _metrics(graph)
    model_code = generate(graph, "pytorch")
    name = sanitize_identifier(graph.name)
    extra = ("torchvision",) if "inception" in metrics.values() or \
        dataset["block"] == "data.torchvision" else ()
    return {
        "title": graph.name, "filename": f"{name}_train_pytorch.py", "name": name,
        "kind": kind, "kind_label": KIND_LABELS[kind], "notes": notes,
        "requirements": own_loop_requirements(model_code, extra),
        "data_comment": _data_comment(dataset), "dataset": dataset,
        "input_shape": input_shape, "image_shape": image_shape, "trainer": trainer,
        "batch_size": int(loader.get("batch_size") or 0) or int(trainer["batch_size"]),
        "metrics": metrics, "metric_samples": samples,
        "vae": {"beta": float(rep.get("beta", 1.0)), "kl_warmup": int(rep.get("kl_warmup", 0)),
                "recon": recon},
        "gan": {k: disc[k] for k in ("width", "norm", "spectral_norm", "loss", "gp_weight",
                                     "d_steps", "lr", "beta1")} if disc else {},
        "diffusion": {k: sched[k] for k in ("timesteps", "schedule", "sampler",
                                            "sample_steps", "guidance", "cond_dropout",
                                            "ema", "sample_every")} if sched else {},
        "model_code": _strip_main(model_code),
        "disc_code": ("" if kind != "adversarial" else DISCRIMINATOR
                      if "def dcgan_init" in model_code else DCGAN_INIT + "\n\n" + DISCRIMINATOR),
        "data_code": runtime.DATA_CODE, "metrics_code": runtime.METRICS_CODE,
        "plot_code": runtime.PLOT_CODE, "optimizer_expr": optimizer,
    }


def _data_comment(dataset: dict) -> str:
    if dataset["block"] == "data.synthetic_images":
        return (f"{dataset['n_images']} generated {dataset['kind']} images "
                f"({dataset['image_size']} px)")
    if dataset["block"] == "data.torchvision":
        return f"torchvision {dataset['dataset']}"
    return f"images under {dataset.get('root')}"


def render(graph: Graph, _spec, framework: str) -> str:
    return _env.from_string(TEMPLATE).render(**context(graph, framework))
