"""Training scripts for text generation: language models and sequence-to-sequence models.

Byte-level tokens (any language, no tokenizer files): a language model predicts the
next byte; a seq2seq model maps source bytes to target bytes with PAD / BOS / EOS
after the 256 byte values. Samples are printed as ``samples: <txt>`` lines the app
shows live.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.forecast.template import _picked, _strip_main
from ai_made_easy.core.generative import runtime
from ai_made_easy.core.generative.tasks import dataset_of, generative_kind
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.training import catalog as cat

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

DEFAULT_OPTIMIZERS = {"language_model": "torch.optim.AdamW(params, lr=0.0003)",
                      "seq2seq": "torch.optim.AdamW(params, lr=0.0005)"}

TEMPLATE = r'''"""{{ title }} — {{ kind_label }} training script generated by AI Made Easy.

Data:   {{ data_comment }}
Usage:  python {{ filename }}          train, save weights and text samples
Needs:  {{ requirements }}
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import json
import math
import pickle
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

DATASET = {{ dataset | repr }}
KIND = "{{ kind }}"                 # language_model | seq2seq
INPUT_SHAPE = {{ input_shape | repr }}
OUTPUT_SHAPE = {{ output_shape | repr }}
EPOCHS = {{ trainer.epochs }}
BATCH_SIZE = {{ batch_size }}
SEED = {{ trainer.seed }}
DEVICE = "{{ trainer.device }}"
EARLY_STOP = {{ trainer.early_stopping_patience }}
GRAD_CLIP = {{ trainer.grad_clip_norm or 1.0 }}
SAMPLE_TOKENS = 200
CHECKPOINT = "{{ name }}_best.pt"
INFERENCE_FILE = "inference_state.pkl"
SAMPLES_DIR = Path("eval_samples")
LIVE_DIR = Path("samples")
STATE: dict = {}
Image = None    # (the runtime's image helpers are unused here)
# ---------------------------------------------------------------------- model
{{ model_code }}
{{ data_code }}
{{ metrics_code }}


def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def report_resources(device: torch.device, step_seconds: float) -> None:
    peak = 0.0
    if device.type == "cuda":
        peak = torch.cuda.max_memory_allocated(device) / 2**20
    elif device.type == "mps":
        peak = torch.mps.driver_allocated_memory() / 2**20
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


def write_samples(lines: list, path: Path, live: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n\n".join(lines) + "\n", encoding="utf-8")
    if live:
        print(f"samples: {path}", flush=True)


# ======================================================================== language model
CONTEXT = INPUT_SHAPE[0]


def lm_batch(data: torch.Tensor, n: int, device) -> tuple:
    starts = torch.randint(0, len(data) - CONTEXT - 1, (n,))
    x = torch.stack([data[s:s + CONTEXT] for s in starts])
    y = torch.stack([data[s + 1:s + CONTEXT + 1] for s in starts])
    return x.to(device), y.to(device)


@torch.no_grad()
def lm_loss(model, data: torch.Tensor, device) -> float:
    """Mean next-byte cross-entropy over non-overlapping windows."""
    model.eval()
    total, count = 0.0, 0
    windows = (len(data) - 1) // CONTEXT
    for start in range(0, windows, 64):
        idx = torch.arange(start, min(windows, start + 64)) * CONTEXT
        x = torch.stack([data[s:s + CONTEXT] for s in idx]).to(device)
        y = torch.stack([data[s + 1:s + CONTEXT + 1] for s in idx]).to(device)
        logits = model(x)
        total += nn.functional.cross_entropy(logits.reshape(-1, logits.shape[-1]),
                                             y.reshape(-1), reduction="sum").item()
        count += y.numel()
    return total / max(count, 1)


@torch.no_grad()
def lm_generate(model, prompt: str, tokens: int, temperature: float = 0.8, top_k: int = 40,
                seed: int = 0) -> str:
    model.eval()
    device = next(model.parameters()).device
    g = torch.Generator(device="cpu").manual_seed(seed)
    ids = list(encode_bytes(prompt)) or [10]
    for _ in range(tokens):
        window = ids[-CONTEXT:]
        window = [10] * (CONTEXT - len(window)) + window   # left-pad with newlines
        logits = model(torch.tensor([window], device=device))[0, -1].float().cpu()
        logits = logits / max(temperature, 1e-4)
        if top_k:
            kth = torch.topk(logits, min(top_k, logits.numel())).values[-1]
            logits[logits < kth] = -math.inf
        ids.append(int(torch.multinomial(logits.softmax(-1), 1, generator=g)))
    return decode_bytes(ids[len(encode_bytes(prompt)):])


def lm_prompts(text: str) -> list[str]:
    lines = [ln for ln in text.splitlines() if len(ln) > 8]
    return [ln[: max(4, len(ln) // 4)] for ln in lines[:3]] or ["The "]


def train_lm(model, train: torch.Tensor, val: torch.Tensor, prompts: list, device):
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
    steps_per_epoch = max(1, len(train) // (CONTEXT * BATCH_SIZE))
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% endif %}
    best, best_state, bad = math.inf, None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, total = time.time(), 0.0
        for _ in range(steps_per_epoch):
            x, y = lm_batch(train, BATCH_SIZE, device)
            logits = model(x)
            loss = nn.functional.cross_entropy(logits.reshape(-1, logits.shape[-1]),
                                               y.reshape(-1))
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(params, GRAD_CLIP)
            optimizer.step()
{% if scheduler_step == "batch" %}
            scheduler.step()
{% endif %}
            total += loss.item()
        if epoch == 1:
            report_resources(device, (time.time() - started) / steps_per_epoch)
        val_loss = lm_loss(model, val, device)
{% if scheduler_step == "epoch" %}
        scheduler.step()
{% elif scheduler_step == "metric" %}
        scheduler.step(val_loss)
{% endif %}
        write_samples([p + lm_generate(model, p, SAMPLE_TOKENS, seed=SEED) for p in prompts],
                      LIVE_DIR / f"epoch_{epoch:03d}.txt", live=True)
        print(f"epoch {epoch}/{EPOCHS} train_loss={total / steps_per_epoch:.4f} "
              f"val_loss={val_loss:.4f} val_perplexity={math.exp(min(val_loss, 50)):.4f} "
              f"val_bits_per_byte={val_loss / math.log(2):.4f} "
              f"lr={optimizer.param_groups[0]['lr']:.3g} ({time.time() - started:.1f}s)",
              flush=True)
        if val_loss < best:
            best, bad = val_loss, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if EARLY_STOP and bad >= EARLY_STOP:
                print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    model.load_state_dict(best_state)
    return model


# ======================================================================== seq2seq
TARGET_LEN = OUTPUT_SHAPE[0]


def seq2seq_module(model):
    return next(m for m in model.modules() if getattr(m, "is_seq2seq", False))


def encode_split(pairs: list) -> tuple:
    src = torch.from_numpy(np.stack([encode_pair(s, INPUT_SHAPE[0], False) for s, _ in pairs]))
    tgt = torch.from_numpy(np.stack([encode_pair(t, TARGET_LEN + 1, True) for _, t in pairs]))
    return src, tgt


@torch.no_grad()
def translate(model, sources: list, device) -> list[str]:
    s2s = seq2seq_module(model).eval()
    out = []
    for i in range(0, len(sources), 128):
        src = torch.from_numpy(np.stack([encode_pair(s, INPUT_SHAPE[0], False)
                                         for s in sources[i:i + 128]])).to(device)
        for row in s2s.generate(src).cpu().tolist():
            ids = row[: row.index(EOS)] if EOS in row else row
            out.append(decode_bytes(ids))
    return out


def text_scores(refs: list, hyps: list) -> dict:
    return {"bleu": bleu(refs, hyps), "chrf": chrf(refs, hyps), "rouge_l": rouge_l(refs, hyps),
            "exact": float(np.mean([r == h for r, h in zip(refs, hyps)])) if refs else 0.0}


def train_seq2seq(model, train_pairs: list, val_pairs: list, device):
    s2s = seq2seq_module(model)
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% endif %}
    src, tgt = encode_split(train_pairs)
    probe = val_pairs[:200]
    best, best_state, bad = -math.inf, None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, total, steps = time.time(), 0.0, 0
        order = torch.randperm(len(src))
        for start in range(0, len(src), BATCH_SIZE):
            idx = order[start:start + BATCH_SIZE]
            s, t = src[idx].to(device), tgt[idx].to(device)
            logits = s2s(s, t[:, :-1])
            loss = nn.functional.cross_entropy(logits.reshape(-1, logits.shape[-1]),
                                               t[:, 1:].reshape(-1), ignore_index=PAD)
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(params, GRAD_CLIP)
            optimizer.step()
{% if scheduler_step == "batch" %}
            scheduler.step()
{% endif %}
            total += loss.item()
            steps += 1
        if epoch == 1:
            report_resources(device, (time.time() - started) / max(steps, 1))
        hyps = translate(model, [s for s, _ in probe], device)
        scores = text_scores([t for _, t in probe], hyps)
{% if scheduler_step == "epoch" %}
        scheduler.step()
{% elif scheduler_step == "metric" %}
        scheduler.step(-scores["chrf"])
{% endif %}
        write_samples([f"{s}  →  {h}   (reference: {t})" for (s, t), h in
                       list(zip(probe, hyps))[:8]], LIVE_DIR / f"epoch_{epoch:03d}.txt",
                      live=True)
        shown = " ".join(f"val_{k}={v:.4f}" for k, v in scores.items())
        print(f"epoch {epoch}/{EPOCHS} train_loss={total / max(steps, 1):.4f} {shown} "
              f"lr={optimizer.param_groups[0]['lr']:.3g} ({time.time() - started:.1f}s)",
              flush=True)
        if scores["chrf"] > best:
            best, bad = scores["chrf"], 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if EARLY_STOP and bad >= EARLY_STOP:
                print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    model.load_state_dict(best_state)
    return model


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    global _PREDICTOR
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    model = build_model()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    _PREDICTOR = model.eval().to(device)
    return _PREDICTOR


@torch.no_grad()
def infer(raw: list) -> list[dict]:
    """Language model: a prompt, or {"prompt", "max_new_tokens", "temperature", "top_k",
    "seed"} -> {"text"}. Seq2seq: a source text (or {"source"}) -> {"text"}."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    if KIND == "seq2seq":
        sources = [str(item["source"]) if isinstance(item, dict) else str(item) for item in raw]
        return [{"text": t} for t in translate(_PREDICTOR, sources, device)]
    results = []
    for item in raw:
        item = item if isinstance(item, dict) else {"prompt": str(item)}
        tokens = max(1, min(int(item.get("max_new_tokens", SAMPLE_TOKENS)), 2000))
        results.append({"text": lm_generate(_PREDICTOR, str(item.get("prompt", "")), tokens,
                                            float(item.get("temperature", 0.8)),
                                            int(item.get("top_k", 40)),
                                            int(item.get("seed", 0)))})
    return results


def main() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    model = build_model().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    if KIND == "language_model":
        text = load_text(DATASET)
        data = torch.from_numpy(encode_bytes(text))
        cut = int(len(data) * (1 - float(DATASET.get("val_fraction", 0.1))))
        train, val = data[:cut], data[cut:]
        if len(train) <= CONTEXT + 1 or len(val) <= CONTEXT + 1:
            raise SystemExit(f"the text ({len(data):,} bytes) is too short for a {CONTEXT}-byte "
                             "context: add text or shorten the Input")
        print(f"bytes: train={len(train):,} val={len(val):,} context={CONTEXT}")
        prompts = lm_prompts(text[cut:])
        model = train_lm(model, train, val, prompts, device)
        loss = lm_loss(model, val, device)
        metrics = {"loss": loss, "perplexity": math.exp(min(loss, 50)),
                   "bits_per_byte": loss / math.log(2)}
        write_samples([p + lm_generate(model, p, 400, seed=SEED) for p in prompts],
                      SAMPLES_DIR / "samples.txt")
    else:
        pairs = load_pairs(DATASET)
        split = split_indices(len(pairs), float(DATASET.get("val_fraction", 0.1)),
                              float(DATASET.get("test_fraction", 0.1)), SEED)
        parts = {k: [pairs[i] for i in v] for k, v in split.items()}
        long_src = sum(len(encode_bytes(s)) > INPUT_SHAPE[0] for s, _ in pairs)
        long_tgt = sum(len(encode_bytes(t)) > TARGET_LEN - 1 for _, t in pairs)
        print(f"pairs: train={len(parts['train'])} val={len(parts['val'])} "
              f"test={len(parts['test'])}; truncated sources={long_src} targets={long_tgt}")
        val = parts["val"] or parts["train"][:200]
        model = train_seq2seq(model, parts["train"], val, device)
        test = parts["test"] or val
        hyps = translate(model, [s for s, _ in test], device)
        metrics = text_scores([t for _, t in test], hyps)
        write_samples([f"{s}  →  {h}   (reference: {t})" for (s, t), h in
                       list(zip(test, hyps))[:20]], SAMPLES_DIR / "samples.txt")
    torch.save(model.state_dict(), CHECKPOINT)
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    print(f"saved best weights to {CHECKPOINT}")
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))
    print(f"saved text samples to {SAMPLES_DIR}/")


if __name__ == "__main__":
    main()
'''

DEFAULT_DATA = {
    "language_model": {"block": "data.synthetic_text", "n_sentences": 4000, "seed": 0,
                       "val_fraction": 0.1},
    "seq2seq": {"block": "data.synthetic_pairs", "task": "reverse", "n_pairs": 4000,
                "max_length": 8, "seed": 0, "val_fraction": 0.1, "test_fraction": 0.1},
}


def _dataset(graph: Graph, kind: str) -> dict:
    node = dataset_of(graph)
    if node is None:
        return dict(DEFAULT_DATA[kind])
    out = {"block": node.type_id, **dict(node.resolved_params())}
    raw = out.get("path")
    if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
        candidate = Path.cwd() / str(raw)
        if candidate.exists():
            out["path"] = str(candidate)
    return out


def context(graph: Graph, framework: str) -> dict:
    from ai_made_easy.core.training.generate import own_loop_requirements

    if framework != "pytorch":
        raise CodegenError("generative models train with PyTorch: choose the PyTorch "
                           "framework")
    kind = generative_kind(graph)
    if kind not in DEFAULT_OPTIMIZERS:
        raise CodegenError("not a text-generation design")
    notes: list[str] = []
    dataset = _dataset(graph, kind)
    if dataset_of(graph) is None:
        notes.append("no dataset block: training on generated "
                     + ("sentences" if kind == "language_model" else "reverse-the-word pairs"))
    if any(n.type_id in cat.LOSS_IDS for n in graph.nodes.values()):
        notes.append("loss blocks are ignored: text generation trains with cross-entropy")
    chain = graph.model_nodes()
    shapes = graph.infer_shapes()
    _t, trainer = _picked(graph, ("train.trainer",))
    trainer = cat.resolved("train.trainer", trainer)
    _l, loader = _picked(graph, ("prep.dataloader",))
    opt, opt_params = _picked(graph, cat.OPTIMIZER_IDS)
    optimizer = (DEFAULT_OPTIMIZERS[kind] if opt is None else
                 cat.render(opt.type_id, cat.resolved(opt.type_id, opt_params), "pytorch")
                 .replace("model.parameters()", "params"))
    sched, sched_params = _picked(graph, cat.SCHEDULER_IDS)
    model_code = generate(graph, "pytorch")
    name = sanitize_identifier(graph.name)
    return {
        "title": graph.name, "filename": f"{name}_train_pytorch.py", "name": name,
        "kind": kind, "notes": notes,
        "kind_label": "language model" if kind == "language_model" else "sequence-to-sequence",
        "requirements": own_loop_requirements(model_code), "data_comment": _comment(dataset),
        "dataset": dataset, "input_shape": list(shapes[chain[0].instance_id]),
        "output_shape": list(shapes[chain[-1].instance_id]), "trainer": trainer,
        "batch_size": int(loader.get("batch_size") or 0) or int(trainer["batch_size"]),
        "model_code": _strip_main(model_code), "data_code": runtime.DATA_CODE,
        "metrics_code": runtime.METRICS_CODE, "optimizer_expr": optimizer,
        "scheduler_expr": (cat.render(sched.type_id, cat.resolved(sched.type_id, sched_params),
                                      "pytorch") if sched else None),
        "scheduler_step": cat.COMPONENTS[sched.type_id].meta["step"] if sched else None,
    }


def _comment(dataset: dict) -> str:
    block = dataset["block"]
    if block == "data.synthetic_text":
        return f"{dataset['n_sentences']} generated sentences (bytes)"
    if block == "data.synthetic_pairs":
        return f"{dataset['n_pairs']} generated '{dataset['task']}' pairs"
    return str(dataset.get("path"))


def render(graph: Graph, _spec, framework: str) -> str:
    return _env.from_string(TEMPLATE).render(**context(graph, framework))
