"""Keras 3 model-file template (functional API — required for merge blocks).

The IR is channels-first; Keras convention is channels-last. The emitter
tracks the layout of every tensor (see ``core.codegen``) so the generated
model is channels-last wherever convolutions are involved.
"""

KERAS_TEMPLATE = '''\
"""{{ graph_name }} — Keras 3 model generated by AI Made Easy.

Input shape:  (batch, {{ keras_input_dims }}){% if keras_channels_last %} channels-last{% endif %}{% if int_input %} integer indices{% endif %}

Output shape: (batch, {{ keras_output_dims }})
{% if total_params %}
Trainable parameters: {{ total_params }}
{% endif %}
Runs on any Keras 3 backend (TensorFlow, JAX or PyTorch).
"""
from __future__ import annotations

import keras
from keras import layers
{% if uses_ops %}
from keras import ops
{% endif %}
{% for helper in keras_helpers %}


{{ helper }}{% endfor %}


def build_model() -> keras.Model:
    """Construct a freshly initialised model."""
    inputs = keras.Input(shape={{ keras_input_shape }}, dtype="{{ keras_input_dtype }}", name="input")
{% for n in nodes %}
    {{ n.keras_expr }}
{% endfor %}
    return keras.Model(inputs=inputs, outputs={{ keras_output_var }}, name="{{ model_name }}")


if __name__ == "__main__":
    import numpy as np

    model = build_model()
    model.summary()
{% if int_input %}
    x = np.random.randint(0, 2, size=(2, {{ keras_input_dims }}))
{% else %}
    x = np.random.rand(2, {{ keras_input_dims }}).astype("float32")
{% endif %}
    print("output shape:", tuple(model(x).shape))
'''
