"""LLM script generation: fold the LLM config blocks into one runnable
script for exactly one detected workflow — text generation, LoRA/QLoRA
fine-tuning, or RAG.

The generated scripts import transformers/peft/datasets only at runtime
(optional extras); generation itself is dependency-free.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from jinja2 import Environment

from ai_made_easy.core.codegen import CodegenError, sanitize_identifier

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True)

_LLM_BLOCKS = ("llm.model", "llm.tokenizer", "llm.prompt", "llm.generation",
               "llm.lora", "llm.dataset", "llm.sft", "llm.embedding_model",
               "llm.vector_store", "llm.retriever", "llm.rag")


@dataclass
class LLMSpec:
    workflow: str = ""  # "generate" | "finetune" | "rag"
    name: str = "llm"
    model: dict = field(default_factory=dict)
    tokenizer: dict = field(default_factory=dict)
    prompt: dict = field(default_factory=dict)
    generation: dict = field(default_factory=dict)
    lora: dict | None = None
    dataset: dict | None = None
    sft: dict | None = None
    embedding: dict | None = None
    store: dict | None = None
    retriever: dict | None = None
    rag: dict | None = None
    # audit additions (Langflow): doc loading, chunking, chat state, typed out
    loader: dict | None = None
    splitter: dict | None = None
    memory: dict | None = None
    parser: dict | None = None


def collect_llm_spec(graph) -> LLMSpec:
    from ai_made_easy.core.blocks.llm_blocks import WORKFLOW_OF

    spec = LLMSpec(name=sanitize_identifier(graph.name))

    def one(type_id: str) -> dict | None:
        found = [n for n in graph.nodes.values() if n.type_id == type_id]
        if len(found) > 1:
            raise CodegenError(f"expected at most one {type_id} block, found {len(found)}")
        return dict(found[0].resolved_params()) if found else None

    active: set[str] = set()
    for n in graph.nodes.values():
        wf = WORKFLOW_OF.get(n.type_id)
        if wf:
            active.add(wf)
    if len(active) > 1:
        raise CodegenError(
            "LLM canvas mixes workflows " + " + ".join(sorted(active))
            + " — keep one per project (generation, fine-tuning, or RAG)"
        )
    if active:
        spec.workflow = active.pop()

    spec.model = one("llm.model")
    spec.tokenizer = one("llm.tokenizer") or {}
    spec.prompt = one("llm.prompt") or {}
    spec.generation = one("llm.generation") or {}
    spec.lora = one("llm.lora")
    spec.dataset = one("llm.dataset")
    spec.sft = one("llm.sft")
    spec.embedding = one("llm.embedding_model")
    spec.store = one("llm.vector_store")
    spec.retriever = one("llm.retriever")
    spec.rag = one("llm.rag")
    spec.loader = one("llm.doc_loader")
    spec.splitter = one("llm.text_splitter")
    spec.memory = one("llm.chat_memory")
    spec.parser = one("llm.output_parser")

    if not spec.model:
        raise CodegenError("add an 'HF Model' block first — every LLM workflow needs one")
    if not spec.workflow:
        spec.workflow = "generate"
    if spec.workflow == "finetune":
        if not spec.dataset:
            raise CodegenError("fine-tuning needs an 'SFT Dataset' block")
        if not spec.lora:
            raise CodegenError("fine-tuning needs a 'LoRA / QLoRA Config' block")
        if not spec.sft:
            raise CodegenError("fine-tuning needs a 'Fine-tune (SFT)' block")
    if spec.workflow == "rag":
        for missing in ("embedding", "store", "retriever", "rag"):
            if getattr(spec, missing) is None:
                names = {"embedding": "Embedding Model", "store": "Vector Store",
                         "retriever": "Retriever", "rag": "RAG Pipeline"}
                raise CodegenError(f"RAG workflow needs a '{names[missing]}' block")
    if not spec.tokenizer.get("repo_id"):
        spec.tokenizer["repo_id"] = spec.model["repo_id"]
    if not spec.prompt:
        spec.prompt = {"template": "{input}"}
    if not spec.generation:
        spec.generation = {"max_new_tokens": 128, "do_sample": True,
                           "temperature": 0.7, "top_p": 0.9, "top_k": 50,
                           "repetition_penalty": 1.1}
    return spec


def _py(v) -> str:
    return repr(v)


GENERATE_TEMPLATE = '''\
"""{{ spec.name }} - LLM generation script generated by AI Made Easy.

Requires: pip install transformers
Usage:   python {{ spec.name }}_llm_generate.py ["your prompt"]
"""
import json
import sys

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

MODEL_ID = {{ model_id }}
DTYPE = "{{ spec.model.dtype }}"
PROMPT_TEMPLATE = {{ prompt_template }}
MAX_NEW_TOKENS = {{ spec.generation.max_new_tokens }}
DO_SAMPLE = {{ do_sample_lit }}
TEMPERATURE = {{ spec.generation.temperature }}
TOP_P = {{ spec.generation.top_p }}
TOP_K = {{ spec.generation.top_k }}
REPETITION_PENALTY = {{ spec.generation.repetition_penalty }}
TRUST_REMOTE_CODE = {{ trust_rc_lit }}
MEMORY_TURNS = {{ spec.memory.n_messages if spec.memory else 0 }}
OUTPUT_SCHEMA = {{ output_schema }}
STRICT_JSON = {{ "True" if spec.parser and spec.parser.strict else "False" }}


def pick_device() -> str:
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


def main() -> None:
    device = pick_device()
    print(f"loading {MODEL_ID} on {device}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=TRUST_REMOTE_CODE)
    dtype = {"float32": torch.float32, "float16": torch.float16,
             "bfloat16": torch.bfloat16}[DTYPE]
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID, torch_dtype=dtype, trust_remote_code=TRUST_REMOTE_CODE
    ).to(device)
    model.eval()

    history: list[tuple[str, str]] = []

    def build_prompt(user_text: str) -> str:
        parts = []
        if MEMORY_TURNS:
            for prev_user, prev_answer in history[-MEMORY_TURNS:]:
                parts.append(f"User: {prev_user}\\nAssistant: {prev_answer}")
        parts.append(user_text)
        filled = PROMPT_TEMPLATE.replace("{input}", "\\n".join(parts))
        if OUTPUT_SCHEMA:
            filled += f"\\nRespond ONLY with JSON shaped like: {OUTPUT_SCHEMA}"
        return filled

    def generate(user_text: str) -> str:
        prompt = build_prompt(user_text)
        inputs = tokenizer(prompt, return_tensors="pt").to(device)
        with torch.no_grad():
            output = model.generate(
                **inputs,
                max_new_tokens=MAX_NEW_TOKENS,
                do_sample=DO_SAMPLE,
                temperature=TEMPERATURE if DO_SAMPLE else None,
                top_p=TOP_P if DO_SAMPLE else None,
                top_k=int(TOP_K) if DO_SAMPLE else None,
                repetition_penalty=REPETITION_PENALTY,
                pad_token_id=tokenizer.eos_token_id,
            )
        new_tokens = output[0][inputs["input_ids"].shape[1]:]
        return tokenizer.decode(new_tokens, skip_special_tokens=True)

    def show(answer: str) -> None:
        print(f"Assistant: {answer}")
        if OUTPUT_SCHEMA:
            try:
                start, end = answer.index("{"), answer.rindex("}") + 1
                print("parsed:", json.dumps(json.loads(answer[start:end]),
                                            indent=2)[:500])
            except (ValueError, json.JSONDecodeError) as exc:
                if STRICT_JSON:
                    raise SystemExit(f"model did not return valid JSON: {exc}")
                print("could not parse JSON:", exc)

{% if spec.memory %}
    print(f"Chat ready (remembers the last {MEMORY_TURNS} message(s)) — "
          "type your message, Ctrl-D or Ctrl-C to quit.")
    while True:
        try:
            user_text = input("\\nYou: ")
        except (EOFError, KeyboardInterrupt):
            break
        answer = generate(user_text)
        show(answer)
        history.append((user_text, answer))
{% else %}
    user_text = sys.argv[1] if len(sys.argv) > 1 else "Hello!"
    show(generate(user_text))
{% endif %}


if __name__ == "__main__":
    main()
'''

FINETUNE_TEMPLATE = '''\
"""{{ spec.name }} - LoRA fine-tuning script generated by AI Made Easy.

Requires: pip install transformers peft datasets accelerate
QLoRA mode additionally requires bitsandbytes + a CUDA GPU.
Usage:   python {{ spec.name }}_llm_finetune.py
"""
import math
import time

import torch
from peft import LoraConfig, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer

MODEL_ID = {{ model_id }}
TOKENIZER_ID = {{ tokenizer_id }}
MAX_LENGTH = {{ spec.tokenizer.max_length }}
LORA_MODE = "{{ spec.lora.mode }}"
LORA_R = {{ spec.lora.r }}
LORA_ALPHA = {{ spec.lora.alpha }}
LORA_DROPOUT = {{ spec.lora.dropout }}
TARGET_MODULES = {{ target_modules }}
EPOCHS = {{ spec.sft.epochs }}
BATCH_SIZE = {{ spec.sft.batch_size }}
LR = {{ spec.sft.lr }}
GRAD_ACCUM = {{ spec.sft.gradient_accumulation }}
WARMUP_RATIO = {{ spec.sft.warmup_ratio }}
SEED = {{ spec.sft.seed }}
OUTPUT_DIR = "{{ spec.name }}_lora_adapter"
TRUST_REMOTE_CODE = {{ trust_rc_lit }}


def pick_device() -> str:
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


def load_texts():
{% if spec.dataset.source == "hf_hub" %}
    from datasets import load_dataset

    ds = load_dataset("{{ spec.dataset.dataset_id }}", split="{{ spec.dataset.split }}")
    return [str(x) for x in ds["{{ spec.dataset.text_field }}"]]
{% else %}
    with open("{{ spec.dataset.file_path }}") as fh:
        return [line.strip() for line in fh if line.strip()]
{% endif %}

def main() -> None:
    torch.manual_seed(SEED)
    device = pick_device()
    print(f"loading {MODEL_ID} on {device}...")
    tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_ID, trust_remote_code=TRUST_REMOTE_CODE)
    tokenizer.pad_token = tokenizer.pad_token or tokenizer.eos_token

    model_kwargs = dict(torch_dtype=torch.float32, trust_remote_code=TRUST_REMOTE_CODE)
    if LORA_MODE == "qlora":
        if not torch.cuda.is_available():
            raise SystemExit("QLoRA (4-bit) requires bitsandbytes + a CUDA GPU; "
                             "switch the LoRA block mode to 'lora' for CPU/MPS")
        from transformers import BitsAndBytesConfig

        model_kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16)
    model = AutoModelForCausalLM.from_pretrained(MODEL_ID, **model_kwargs)
    if LORA_MODE == "qlora":
        from peft import prepare_model_for_kbit_training

        model = prepare_model_for_kbit_training(model)

    lora = LoraConfig(r=LORA_R, lora_alpha=LORA_ALPHA, lora_dropout=LORA_DROPOUT,
                      target_modules=TARGET_MODULES, task_type="CAUSAL_LM")
    model = get_peft_model(model, lora)
    model.print_trainable_parameters()
    model.to(device)

    texts = load_texts()
    print(f"{len(texts)} training examples")
    tokens = tokenizer(texts, truncation=True, max_length=MAX_LENGTH,
                       return_tensors="pt", padding=True)
    input_ids = tokens["input_ids"]
    attention_mask = tokens["attention_mask"]

    trainable = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.AdamW(trainable, lr=LR)
    steps_total = math.ceil(len(input_ids) * EPOCHS / (BATCH_SIZE * GRAD_ACCUM))
    warmup = int(steps_total * WARMUP_RATIO)

    def lr_at(step: int) -> float:
        if step < warmup:
            return LR * step / max(warmup, 1)
        progress = (step - warmup) / max(steps_total - warmup, 1)
        return 0.1 * LR + 0.9 * LR * 0.5 * (1 + math.cos(math.pi * progress))

    step = 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        t0, running = time.time(), 0.0
        perm = torch.randperm(len(input_ids))
        for start in range(0, len(input_ids), BATCH_SIZE):
            idx = perm[start:start + BATCH_SIZE]
            out = model(input_ids=input_ids[idx].to(device),
                        attention_mask=attention_mask[idx].to(device),
                        labels=input_ids[idx].to(device))
            (out.loss / GRAD_ACCUM).backward()
            running += out.loss.item()
            if (start // BATCH_SIZE + 1) % GRAD_ACCUM == 0 or start + BATCH_SIZE >= len(input_ids):
                for g in optimizer.param_groups:
                    g["lr"] = lr_at(step)
                optimizer.step()
                optimizer.zero_grad()
                step += 1
        print(f"epoch {epoch}/{EPOCHS} train_loss={running / math.ceil(len(input_ids) / BATCH_SIZE):.4f} "
              f"({time.time() - t0:.1f}s)")

    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"saved LoRA adapter to {OUTPUT_DIR}/")


if __name__ == "__main__":
    main()
'''

RAG_TEMPLATE = '''\
"""{{ spec.name }} - RAG script generated by AI Made Easy.

Requires: pip install transformers
Usage:   python {{ spec.name }}_llm_rag.py ["your question"]
"""
import glob
import sys

import numpy as np
import torch
from transformers import AutoModel, AutoModelForCausalLM, AutoTokenizer

GENERATOR_ID = {{ model_id }}
EMBEDDER_ID = {{ embedder_id }}
DOCS_GLOB = {{ docs_glob }}
DOCS_ENCODING = {{ docs_encoding }}
CHUNK_SIZE = {{ chunk_size }}
CHUNK_OVERLAP = {{ chunk_overlap }}
CHUNK_SEPARATOR = {{ chunk_separator }}
TOP_K = {{ spec.retriever.top_k }}
POOLING = "{{ spec.embedding.pooling }}"
EMBED_BATCH = {{ spec.embedding.batch_size }}
STORE_BACKEND = "{{ spec.store.backend }}"
PROMPT_TEMPLATE = {{ prompt_template }}
MAX_NEW_TOKENS = {{ spec.generation.max_new_tokens }}
DO_SAMPLE = {{ do_sample_lit }}
TEMPERATURE = {{ spec.generation.temperature }}
TOP_P = {{ spec.generation.top_p }}
TRUST_REMOTE_CODE = {{ trust_rc_lit }}


def pick_device() -> str:
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


def chunk_documents():
    """(path, text) chunks — paragraph-aware when a separator splits text,
    fixed windows as the fallback."""
    chunks = []
    for path in sorted(glob.glob(DOCS_GLOB)):
        with open(path, encoding=DOCS_ENCODING) as fh:
            text = fh.read()
        step = max(CHUNK_SIZE - CHUNK_OVERLAP, 1)
        pieces = [p.strip() for p in text.split(CHUNK_SEPARATOR) if p.strip()]
        made = []
        buf = ""
        for piece in pieces:
            candidate = (buf + "\\n" + piece) if buf else piece
            if len(candidate) > CHUNK_SIZE and buf:
                made.append(buf[:CHUNK_SIZE])
                buf = (buf[-CHUNK_OVERLAP:] + " " + piece
                       if CHUNK_OVERLAP else piece)
            else:
                buf = candidate
            while len(buf) > CHUNK_SIZE:  # one paragraph longer than a chunk
                made.append(buf[:CHUNK_SIZE])
                buf = buf[step:]
        if buf.strip():
            made.append(buf[:CHUNK_SIZE])
        if not made:  # separator produced nothing: fixed windows
            made = [text[i:i + CHUNK_SIZE].strip()
                    for i in range(0, len(text), step)]
        chunks.extend((path, piece) for piece in made if piece)
    return chunks


@torch.no_grad()
def embed(texts, tok, enc, device):
    vectors = []
    enc.eval()
    for i in range(0, len(texts), EMBED_BATCH):
        batch = texts[i:i + EMBED_BATCH]
        tokens = tok(batch, padding=True, truncation=True,
                     max_length=512, return_tensors="pt").to(device)
        hidden = enc(**tokens).last_hidden_state
        if POOLING == "cls":
            vec = hidden[:, 0]
        else:  # masked mean
            mask = tokens["attention_mask"].unsqueeze(-1).float()
            vec = (hidden * mask).sum(1) / mask.sum(1).clamp(min=1)
        vectors.append(torch.nn.functional.normalize(vec, dim=-1).cpu().numpy())
    return np.concatenate(vectors).astype("float32")


class NumpyStore:
    """Zero-dependency cosine-similarity vector store."""

    def __init__(self, matrix, chunks):
        self.matrix, self.chunks = matrix, chunks

    def query(self, q_vec, k):
        scores = (self.matrix @ q_vec.reshape(-1, 1)).ravel()
        order = np.argsort(scores)[::-1][:k]
        return [(self.chunks[i][1], float(scores[i])) for i in order]


def build_store(device):
    tok = AutoTokenizer.from_pretrained(EMBEDDER_ID)
    enc = AutoModel.from_pretrained(EMBEDDER_ID).to(device)
    chunks = chunk_documents()
    if not chunks:
        raise SystemExit(f"no documents matched {DOCS_GLOB}")
    print(f"embedding {len(chunks)} chunks from {len({c[0] for c in chunks})} file(s)...")
    matrix = embed([c[1] for c in chunks], tok, enc, device)
{% if spec.store.backend == "faiss" %}
    import faiss

    index = faiss.IndexFlatIP(matrix.shape[1])
    index.add(matrix)

    class FaissStore(NumpyStore):
        def __init__(self):
            self.matrix, self.chunks, self.index = matrix, chunks, index

        def query(self, q_vec, k):
            scores, ids = self.index.search(q_vec.reshape(1, -1), k)
            return [(self.chunks[i][1], float(s))
                    for s, i in zip(scores[0], ids[0])]

    return FaissStore(), tok, enc
{% else %}
    return NumpyStore(matrix, chunks), tok, enc
{% endif %}

def main() -> None:
    device = pick_device()
    store, embed_tok, embed_enc = build_store(device)

    print(f"loading generator {GENERATOR_ID}...")
    gen_tok = AutoTokenizer.from_pretrained(GENERATOR_ID, trust_remote_code=TRUST_REMOTE_CODE)
    generator = AutoModelForCausalLM.from_pretrained(
        GENERATOR_ID, trust_remote_code=TRUST_REMOTE_CODE).to(device)
    generator.eval()

    question = sys.argv[1] if len(sys.argv) > 1 else input("question > ").strip()
    q_vec = embed([question], embed_tok, embed_enc, device)
    hits = store.query(q_vec, TOP_K)
    context = "\\n\\n".join(h[0] for h in hits)
    print(f"\\n--- top {TOP_K} chunk(s) ---")
    for text, score in hits:
        print(f"[{score:.3f}] {text[:120].replace(chr(10), ' ')}...")

    prompt = PROMPT_TEMPLATE.replace("{context}", context).replace("{input}", question)
    inputs = gen_tok(prompt, return_tensors="pt").to(device)
    with torch.no_grad():
        output = generator.generate(
            **inputs, max_new_tokens=MAX_NEW_TOKENS, do_sample=DO_SAMPLE,
            temperature=TEMPERATURE if DO_SAMPLE else None,
            top_p=TOP_P if DO_SAMPLE else None,
            pad_token_id=gen_tok.eos_token_id,
        )
    print("\\n--- answer ---")
    print(gen_tok.decode(output[0][inputs["input_ids"].shape[1]:],
                         skip_special_tokens=True))


if __name__ == "__main__":
    main()
'''


def _str_literal(s: str) -> str:
    return repr(str(s))


def _bool_lit(v) -> str:
    return "True" if v else "False"


def _list_literal(csv: str) -> str:
    items = [p.strip() for p in str(csv).split(",") if p.strip()]
    return "[" + ", ".join(repr(i) for i in items) + "]"


def generate_llm_script(graph) -> str:
    spec = collect_llm_spec(graph)
    ctx = {
        "spec": spec,
        "do_sample_lit": _bool_lit(spec.generation.get("do_sample")),
        "trust_rc_lit": _bool_lit(spec.model.get("trust_remote_code")),
        "model_id": _str_literal(spec.model["repo_id"]),
        "tokenizer_id": _str_literal(spec.tokenizer["repo_id"]),
        "prompt_template": _str_literal(spec.prompt.get("template", "{input}")),
        "embedder_id": _str_literal(spec.embedding["repo_id"] if spec.embedding else ""),
        "docs_glob": _str_literal(
            (spec.loader or spec.rag or {}).get("docs_path", "docs/*.txt")),
        "docs_encoding": _str_literal(
            (spec.loader or {}).get("encoding", "utf-8")),
        "chunk_size": (spec.splitter or spec.rag or {}).get("chunk_size", 500),
        "chunk_overlap": (spec.splitter or spec.rag or {}).get("chunk_overlap", 50),
        "chunk_separator": _str_literal(
            (spec.splitter or {}).get("separator", "\n\n")),
        "output_schema": _str_literal(
            spec.parser["schema"] if spec.parser else ""),
        "target_modules": _list_literal(spec.lora["target_modules"] if spec.lora else ""),
    }
    # the RAG template expects {context} in the prompt template
    if spec.workflow == "rag":
        template = spec.prompt.get("template", "{input}")
        if "{context}" not in template:
            template = "Context:\\n{context}\\n\\nQuestion: {input}\\nAnswer:"
            ctx["prompt_template"] = _str_literal(template)
    templates = {
        "generate": GENERATE_TEMPLATE,
        "finetune": FINETUNE_TEMPLATE,
        "rag": RAG_TEMPLATE,
    }
    return _env.from_string(templates[spec.workflow]).render(**ctx)
