"""PyTorch model-file template."""

PYTORCH_TEMPLATE = '''\
"""{{ graph_name }} — PyTorch model generated by AI Made Easy.

Input shape:  (batch, {{ input_dims }}){% if int_input %} integer indices{% endif %}

Output shape: (batch, {{ output_dims }})
{% if total_params %}
Trainable parameters: {{ total_params }}
{% endif %}
"""
from __future__ import annotations

import torch
import torch.nn as nn
{% if uses_functional %}
import torch.nn.functional as F
{% endif %}
{% for helper in torch_helpers %}


{{ helper }}{% endfor %}


class {{ class_name }}(nn.Module):
    """{{ graph_name }}: (batch, {{ input_dims }}) -> (batch, {{ output_dims }})."""

    def __init__(self) -> None:
        super().__init__()
{% for m in modules %}
        {{ m.torch_module }}
{% endfor %}

    def forward(self, x: torch.Tensor) -> torch.Tensor:
{% for n in nodes %}
        {{ n.torch_expr }}
{% endfor %}
        return {{ output_var }}


def build_model() -> {{ class_name }}:
    """Construct a freshly initialised model."""
    return {{ class_name }}()


if __name__ == "__main__":
    model = build_model()
    print(model)
    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"trainable parameters: {n_params:,}")
{% if int_input %}
    x = torch.randint(0, 2, (2, {{ input_dims }}))
{% else %}
    x = torch.randn(2, {{ input_dims }})
{% endif %}
    model.eval()
    with torch.no_grad():
        y = model(x)
    print("input shape: ", tuple(x.shape))
    print("output shape:", tuple(y.shape))
'''
