"""PyTorch code template. Module-level strings for now; Phase 2 moves these
into loadable template files (enables user-customizable output styles)."""

PYTORCH_TEMPLATE = '''\
"""{{ graph_name }} - generated by AI Made Easy."""
import torch
import torch.nn as nn


class {{ class_name }}(nn.Module):
    def __init__(self):
        super().__init__()
{% for m in modules %}
        {{ m.torch_module }}
{% endfor %}

    def forward(self, x):
{% for n in nodes %}
        {{ n.torch_expr }}
{% endfor %}
        return {{ output_var }}


if __name__ == "__main__":
    model = {{ class_name }}()
    print(model)
    x = torch.randn(1, {{ input_dims }})
    out = model(x)
    print("input shape: ", tuple(x.shape))
    print("output shape:", tuple(out.shape))
'''
