"""Runtime exports: scripts that serialize the designed model to ONNX or
TorchScript. Generated, self-contained, and runnable standalone — the app
also runs them through the training runner for one-click export.
"""
from __future__ import annotations

from ai_made_easy.core.codegen import class_name_for, emit_dag
from ai_made_easy.core.graph import Graph

_ONNX_TEMPLATE = '''\
"""{graph_name} -> ONNX — generated by AI Made Easy."""
from pathlib import Path

import torch
import torch.nn as nn

OUTPUT = Path("{output_path}")


class {class_name}(nn.Module):
    def __init__(self):
        super().__init__()
{modules}

    def forward(self, x):
{forward}
        return {output_var}


def main():
    model = {class_name}().eval()
    dummy = torch.randn(1, {input_dims})
    with torch.no_grad():
        torch.onnx.export(
            model, dummy, str(OUTPUT),
            input_names=["input"], output_names=["output"],
            dynamic_axes={{"input": {{0: "batch"}}, "output": {{0: "batch"}}}},
            opset_version=18,
        )
    print(f"saved {{OUTPUT}}")
    try:
        import onnx

        onnx.checker.check_model(onnx.load(str(OUTPUT)))
        print("onnx checker: OK")
    except ImportError:
        print("(pip install onnx to validate the exported file)")


if __name__ == "__main__":
    main()
'''

_JIT_TEMPLATE = '''\
"""{graph_name} -> TorchScript — generated by AI Made Easy."""
from pathlib import Path

import torch
import torch.nn as nn

OUTPUT = Path("{output_path}")


class {class_name}(nn.Module):
    def __init__(self):
        super().__init__()
{modules}

    def forward(self, x):
{forward}
        return {output_var}


def main():
    model = {class_name}().eval()
    scripted = torch.jit.script(model)
    scripted.save(str(OUTPUT))
    print(f"saved {{OUTPUT}}")

    reloaded = torch.jit.load(str(OUTPUT))
    out = reloaded(torch.randn(1, {input_dims}))
    print(f"reload smoke test OK — output shape {{tuple(out.shape)}}")


if __name__ == "__main__":
    main()
'''


def _model_parts(graph: Graph):
    nodes, input_shape, (out_t, _out_k) = emit_dag(graph)
    modules = "\n".join(f"        {m['torch_module']}" for m in nodes if m["torch_module"]) or "        pass"
    forward = "\n".join(f"        {n['torch_expr']}" for n in nodes)
    return {
        "class_name": class_name_for(graph.name),
        "modules": modules,
        "forward": forward,
        "output_var": out_t,
        "input_dims": ", ".join(str(d) for d in input_shape),
    }


def generate_onnx_export(graph: Graph, output_path: str = "exports/model.onnx") -> str:
    return _ONNX_TEMPLATE.format(graph_name=graph.name,
                                 output_path=output_path,
                                 **_model_parts(graph))


def generate_torchscript_export(graph: Graph,
                                output_path: str = "exports/model_torchscript.pt") -> str:
    return _JIT_TEMPLATE.format(graph_name=graph.name,
                                output_path=output_path,
                                **_model_parts(graph))
