"""Training scripts for time-series forecasting.

Self-contained like every generated script: the model, the series readers and
metrics (``core.forecast.runtime``), per-window scaling, the loss for the
chosen head (point loss, pinball, Student-t or negative-binomial likelihood),
rolling-origin evaluation against a seasonal-naive baseline, forecast plots and
the ``load_predictor`` / ``infer`` functions deploy packages serve.
"""
from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from ai_made_easy.core.codegen import CodegenError, generate, sanitize_identifier
from ai_made_easy.core.forecast import runtime
from ai_made_easy.core.forecast.blocks import quantile_levels
from ai_made_easy.core.forecast.tasks import dataset_of, model_of
from ai_made_easy.core.graph import Graph
from ai_made_easy.core.training import catalog as cat

POINT_LOSSES = {"train.loss_mse": "mse", "train.loss_l1": "mae", "train.loss_huber": "huber",
                "train.loss_smooth_l1": "smooth_l1"}

_env = Environment(trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True,
                   undefined=StrictUndefined)
_env.filters["repr"] = repr

TEMPLATE = r'''"""{{ title }} — time-series forecasting script generated by AI Made Easy.

Data:   {{ data_comment }}
Model:  {{ model_label }} ({{ head }} forecasts, {{ horizon }} steps from {{ window }})
Usage:  python {{ filename }}          train, backtest, save weights + forecast plots
Needs:  {{ requirements }}
{% for note in notes %}
Note:   {{ note }}
{% endfor %}
"""
from __future__ import annotations

import json
import math
import pickle
import random
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from PIL import Image, ImageDraw

DATASET = {{ dataset | repr }}
WINDOW = {{ window }}
HORIZON = {{ horizon }}
STRIDE = {{ stride }}
SEASON = {{ season }}
VAL_WINDOWS = {{ val_windows }}
TEST_WINDOWS = {{ test_windows }}
HEAD = "{{ head }}"
QUANTILES = {{ quantiles | repr }}
POINT_LOSS = "{{ point_loss }}"
INPUT_SHAPE = {{ input_shape | repr }}
EPOCHS = {{ trainer.epochs }}
BATCH_SIZE = {{ batch_size }}
SEED = {{ trainer.seed }}
DEVICE = "{{ trainer.device }}"
EARLY_STOP = {{ trainer.early_stopping_patience }}
GRAD_CLIP = {{ trainer.grad_clip_norm }}
SAMPLES = 200
CHECKPOINT = "{{ name }}_best.pt"
INFERENCE_FILE = "inference_state.pkl"
SAMPLES_DIR = Path("eval_samples")
STATE: dict = {}
# ---------------------------------------------------------------------- model
{{ model_code }}
{{ data_code }}
{{ metrics_code }}
{{ plot_code }}

# ======================================================================== preparation
def fit_covariates(x: np.ndarray) -> None:
    """Covariate statistics from the training windows (channel 0 is the target)."""
    width = x.shape[-1] - 1
    cov = x[..., 1:].reshape(-1, width) if width and x.size else np.zeros((0, width), np.float32)
    STATE["cov_mean"] = cov.mean(0) if len(cov) else np.zeros(width, np.float32)
    STATE["cov_std"] = cov.std(0) + 1e-6 if len(cov) else np.ones(width, np.float32)


def prepare(x: np.ndarray, future: np.ndarray):
    """Scale the target per window (mean absolute value) and standardize covariates."""
    scale = np.abs(x[..., 0]).mean(1) + 1e-3
    x = x.copy()
    x[..., 0] /= scale[:, None]
    if x.shape[-1] > 1:
        x[..., 1:] = (x[..., 1:] - STATE["cov_mean"]) / STATE["cov_std"]
    n_future = future.shape[-1]
    if n_future:
        mean, std = STATE["cov_mean"][-n_future:], STATE["cov_std"][-n_future:]
        future = (future - mean) / std
    return x.astype(np.float32), future.astype(np.float32), scale.astype(np.float32)


def forecaster(model: nn.Module):
    return next((m for m in model.modules() if hasattr(m, "forecast")), None)


def run_model(model: nn.Module, x: torch.Tensor, future: torch.Tensor) -> torch.Tensor:
    head = forecaster(model)
    if head is not None:
        return head.forecast(x, future if future.shape[-1] else None)
    return model(x)


# ======================================================================== losses
def head_loss(out: torch.Tensor, y_scaled: torch.Tensor, y_raw: torch.Tensor,
              scale: torch.Tensor) -> torch.Tensor:
    if HEAD == "point":
        if POINT_LOSS == "mae":
            return (out - y_scaled).abs().mean()
        if POINT_LOSS == "huber":
            return nn.functional.huber_loss(out, y_scaled)
        if POINT_LOSS == "smooth_l1":
            return nn.functional.smooth_l1_loss(out, y_scaled)
        return nn.functional.mse_loss(out, y_scaled)
    if HEAD == "quantile":
        levels = torch.tensor(QUANTILES, device=out.device)
        diff = y_scaled.unsqueeze(-1) - out
        return torch.maximum(levels * diff, (levels - 1) * diff).mean()
    if HEAD == "student_t":
        dist = torch.distributions.StudentT(out[..., 2], out[..., 0], out[..., 1])
        return -dist.log_prob(y_scaled).mean()
    mean = out[..., 0] * scale[:, None]
    alpha = out[..., 1] / scale[:, None].sqrt()
    total = 1.0 / alpha
    dist = torch.distributions.NegativeBinomial(total_count=total,
                                                probs=(mean / (mean + total)).clamp(1e-6, 1 - 1e-6))
    return -dist.log_prob(y_raw.clamp(min=0).round()).mean()


@torch.no_grad()
def describe(out: torch.Tensor, scale: torch.Tensor) -> dict:
    """Point forecast, interval and (when probabilistic) samples in the original units."""
    s = scale[:, None]
    if HEAD == "point":
        point = out * s
        return {"point": point}
    if HEAD == "quantile":
        q = out * s.unsqueeze(-1)
        mid = int(np.argmin(np.abs(np.asarray(QUANTILES) - 0.5)))
        return {"point": q[..., mid], "quantiles": q, "lower": q[..., 0], "upper": q[..., -1]}
    if HEAD == "student_t":
        dist = torch.distributions.StudentT(out[..., 2], out[..., 0], out[..., 1])
        samples = dist.sample((SAMPLES,)) * s
    else:
        mean = out[..., 0] * s
        total = 1.0 / (out[..., 1] / s.sqrt())
        dist = torch.distributions.NegativeBinomial(
            total_count=total, probs=(mean / (mean + total)).clamp(1e-6, 1 - 1e-6))
        samples = dist.sample((SAMPLES,))
    return {"point": samples.median(0).values, "samples": samples,
            "lower": samples.quantile(0.1, dim=0), "upper": samples.quantile(0.9, dim=0)}


# ======================================================================== train / evaluate
def tensors(split: dict, device: torch.device):
    x, future, scale = prepare(split["x"], split["future"])
    return (torch.from_numpy(x).to(device), torch.from_numpy(future).to(device),
            torch.from_numpy(scale).to(device), torch.from_numpy(split["y"]).to(device))


@torch.no_grad()
def evaluate(model: nn.Module, split: dict, device: torch.device, keep: int = 0) -> tuple:
    model.eval()
    if not len(split["y"]):
        return {}, []
    x, future, scale, y = tensors(split, device)
    parts = [describe(run_model(model, x[i:i + 256], future[i:i + 256]), scale[i:i + 256])
             for i in range(0, len(x), 256)]
    merged = {k: torch.cat([p[k] for p in parts], dim=1 if k == "samples" else 0).cpu().numpy()
              for k in parts[0]}
    y_np = split["y"]
    metrics = point_metrics(y_np, merged["point"], split["mase_scale"])
    if "quantiles" in merged:
        metrics["pinball"] = pinball(y_np, merged["quantiles"], QUANTILES)
        metrics["crps"] = crps_from_quantiles(y_np, merged["quantiles"], QUANTILES)
    elif "samples" in merged:
        metrics["crps"] = crps_from_samples(y_np, merged["samples"])
    else:
        metrics["crps"] = metrics["mae"]  # a point forecast's CRPS is its absolute error
    if "lower" in merged:
        metrics["coverage_80"] = coverage(y_np, merged["lower"], merged["upper"])
    metrics["mae_by_step"] = np.abs(merged["point"] - y_np).mean(0).round(4).tolist()
    kept = [{k: v[i] for k, v in merged.items() if k != "samples"} for i in range(min(keep, len(y_np)))]
    return metrics, kept


def naive_mase(split: dict) -> float:
    """MASE of repeating the last season (the baseline a model must beat)."""
    x = split["x"][..., 0]
    m = max(1, SEASON)
    idx = np.arange(HORIZON) % m - m
    pred = x[:, idx] if m <= WINDOW else np.repeat(x[:, -1:], HORIZON, axis=1)
    return point_metrics(split["y"], pred, split["mase_scale"])["mase"]


def pick_device() -> torch.device:
    if DEVICE != "auto":
        return torch.device(DEVICE)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def report_resources(device: torch.device, step_seconds: float) -> None:
    peak = 0.0
    if device.type == "cuda":
        peak = torch.cuda.max_memory_allocated(device) / 2**20
    elif device.type == "mps":
        peak = torch.mps.driver_allocated_memory() / 2**20
    print(f"resources: peak_memory_mb={peak:.1f} step_ms={step_seconds * 1e3:.2f} "
          f"batch_size={BATCH_SIZE} device={device.type}", flush=True)


def fit(model: nn.Module, train: dict, val: dict, device: torch.device) -> nn.Module:
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = {{ optimizer_expr }}
{% if scheduler_expr %}
    scheduler = {{ scheduler_expr }}
{% endif %}
    x, future, scale, y_raw = tensors(train, device)
    y_scaled = y_raw / scale[:, None]
    best, best_state, bad = math.inf, None, 0
    for epoch in range(1, EPOCHS + 1):
        model.train()
        started, running, steps = time.time(), 0.0, 0
        order = torch.randperm(len(x), device=device)
        for start in range(0, len(x), BATCH_SIZE):
            idx = order[start:start + BATCH_SIZE]
            out = run_model(model, x[idx], future[idx])
            loss = head_loss(out, y_scaled[idx], y_raw[idx], scale[idx])
            if not torch.isfinite(loss):
                raise SystemExit(f"the loss became {float(loss)}: lower the learning rate")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            if GRAD_CLIP > 0:
                nn.utils.clip_grad_norm_(params, GRAD_CLIP)
            optimizer.step()
{% if scheduler_step == "batch" %}
            scheduler.step()
{% endif %}
            running += loss.item() * len(idx)
            steps += 1
        if epoch == 1:
            report_resources(device, (time.time() - started) / max(steps, 1))
        metrics, _ = evaluate(model, val, device)
        score = metrics.get("mase", running / max(len(x), 1))
{% if scheduler_step == "epoch" %}
        scheduler.step()
{% elif scheduler_step == "metric" %}
        scheduler.step(score)
{% endif %}
        shown = " ".join(f"val_{k}={v:.4f}" for k, v in metrics.items() if isinstance(v, float))
        print(f"epoch {epoch}/{EPOCHS} train_loss={running / max(len(x), 1):.4f} {shown} "
              f"lr={optimizer.param_groups[0]['lr']:.3g} ({time.time() - started:.1f}s)",
              flush=True)
        if score < best:
            best, bad = score, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            bad += 1
            if EARLY_STOP and bad >= EARLY_STOP:
                print(f"early stopping: no improvement for {EARLY_STOP} epochs")
                break
    if best_state is not None:
        model.load_state_dict(best_state)
    return model


def save_plots(split: dict, kept: list, series: list) -> None:
    SAMPLES_DIR.mkdir(exist_ok=True)
    for i, item in enumerate(kept):
        s = series[int(split["series"][i])]
        origin = int(split["origin"][i])
        history = s["target"][max(0, origin - 2 * HORIZON - WINDOW // 2):origin]
        plot_forecast(history, split["y"][i], item["point"], item.get("lower"),
                      item.get("upper"), f"{s['id']} @ step {origin}").save(
            SAMPLES_DIR / f"sample_{i}.png")


# ======================================================================== serving
_PREDICTOR = None


def load_predictor(folder: str | Path = ".", device: str = "cpu") -> nn.Module:
    global _PREDICTOR
    with open(Path(folder) / INFERENCE_FILE, "rb") as fh:
        STATE.update(pickle.load(fh))
    model = build_model()
    model.load_state_dict(torch.load(Path(folder) / CHECKPOINT, map_location=device))
    _PREDICTOR = model.eval().to(device)
    return _PREDICTOR


@torch.no_grad()
def infer(raw: list) -> list[dict]:
    """Forecasts for series histories: a list of numbers, or a dict with "history",
    "past_covariates" ([T][P]) and "future_covariates" ([T + horizon][F]) rows."""
    if _PREDICTOR is None:
        raise RuntimeError("call load_predictor(folder) first")
    device = next(_PREDICTOR.parameters()).device
    results = []
    for item in raw:
        item = item if isinstance(item, dict) else {"history": item}
        history = np.asarray(item["history"], np.float32)
        if len(history) < WINDOW:
            raise ValueError(f"history needs at least {WINDOW} values, got {len(history)}")
        n_future = int(STATE.get("n_future", 0))
        n_past = len(STATE["cov_mean"]) - n_future
        # covariates the request leaves out are filled with zeros (their "absent" value)
        past = np.asarray(item.get("past_covariates") or np.zeros((len(history), n_past)),
                          np.float32).reshape(len(history), -1)
        fut_all = np.asarray(item.get("future_covariates") or
                             np.zeros((len(history) + HORIZON, n_future)), np.float32)
        fut_all = fut_all.reshape(len(fut_all), -1)
        if past.shape[1] != n_past or fut_all.shape[1] != n_future:
            raise ValueError(f"the model was trained with {n_past} past and {n_future} future "
                             f"covariate(s); got {past.shape[1]} and {fut_all.shape[1]}")
        if len(fut_all) < len(history) + HORIZON:
            raise ValueError(f"future_covariates needs {len(history) + HORIZON} rows (history "
                             f"+ horizon), got {len(fut_all)}")
        x = np.concatenate([history[:, None], past, fut_all[: len(history)]], axis=1)[-WINDOW:]
        future = fut_all[len(history): len(history) + HORIZON].reshape(HORIZON, -1)
        xs, fs, scale = prepare(x[None], future[None])
        out = run_model(_PREDICTOR, torch.from_numpy(xs).to(device),
                        torch.from_numpy(fs).to(device))
        desc = describe(out, torch.from_numpy(scale).to(device))
        result = {"forecast": desc["point"][0].cpu().numpy().astype(float).round(4).tolist()}
        for key in ("lower", "upper"):
            if key in desc:
                result[key] = desc[key][0].cpu().numpy().astype(float).round(4).tolist()
        if "quantiles" in desc:
            q = desc["quantiles"][0].cpu().numpy().astype(float)
            result["quantiles"] = {str(lv): q[:, j].round(4).tolist()
                                   for j, lv in enumerate(QUANTILES)}
        results.append(result)
    return results


def main() -> None:
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    device = pick_device()
    print(f"device: {device}")
    series = load_series(DATASET)
    splits = {name: make_windows(series, WINDOW, HORIZON, VAL_WINDOWS, TEST_WINDOWS, STRIDE,
                                 name, SEASON) for name in ("train", "val", "test")}
    if not len(splits["train"]["y"]):
        raise SystemExit("no training windows: use longer series or a shorter window / horizon")
    print(f"series: {len(series)} windows: train={len(splits['train']['y'])} "
          f"val={len(splits['val']['y'])} test={len(splits['test']['y'])}")
    fit_covariates(splits["train"]["x"])
    STATE["n_future"] = int(splits["train"]["future"].shape[-1])
    if not len(splits["val"]["y"]):
        splits["val"] = splits["train"]
    model = build_model().to(device)
    print(f"parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    model = fit(model, splits["train"], splits["val"], device)
    torch.save(model.state_dict(), CHECKPOINT)
    with open(INFERENCE_FILE, "wb") as fh:
        pickle.dump(dict(STATE), fh)
    print(f"saved best weights to {CHECKPOINT}")
    test = splits["test"] if len(splits["test"]["y"]) else splits["val"]
    metrics, kept = evaluate(model, test, device, keep=6)
    metrics["naive_mase"] = naive_mase(test)
    print("test: " + " ".join(f"{k}={v:.4f}" for k, v in metrics.items()
                              if isinstance(v, float)))
    Path("metrics.json").write_text(json.dumps(metrics, indent=1))
    save_plots(test, kept, series)
    print(f"saved {len(kept)} forecast plots to {SAMPLES_DIR}/")


if __name__ == "__main__":
    main()
'''


def _strip_main(code: str) -> str:
    head, _sep, _tail = code.partition('\n\nif __name__ == "__main__":')
    body = head.split('\nfrom __future__ import annotations\n', 1)[-1]
    lines = [ln for ln in body.splitlines()
             if not ln.startswith(("import torch", "import torch.nn as nn",
                                   "import torch.nn.functional as F"))]
    return "\n".join(lines).strip("\n") + "\n"


def _picked(graph: Graph, ids) -> tuple:
    found = [n for n in graph.nodes.values() if n.type_id in ids]
    return (found[0], dict(found[0].resolved_params())) if found else (None, {})


def _dataset(graph: Graph) -> dict:
    node = dataset_of(graph)
    if node is None:
        return {"block": "data.synthetic_series", "n_series": 30, "length": 400, "trend": 0.2,
                "noise": 0.1, "counts": False, "promotions": False, "seed": 0, "window": 48,
                "horizon": 12, "stride": 1, "season_length": 24, "val_windows": 2,
                "test_windows": 2}
    out = {"block": node.type_id, **dict(node.resolved_params())}
    raw = out.get("path")
    if raw and not str(raw).startswith("~") and not Path(str(raw)).is_absolute():
        candidate = Path.cwd() / str(raw)
        if candidate.exists():
            out["path"] = str(candidate)
    return out


def context(graph: Graph, framework: str) -> dict:
    if framework != "pytorch":
        raise CodegenError("forecasting trains with PyTorch: choose the PyTorch framework")
    notes: list[str] = []
    dataset = _dataset(graph)
    if dataset_of(graph) is None:
        notes.append("no dataset block: training on generated seasonal series")
    model = model_of(graph)
    params = dict(model.resolved_params()) if model is not None else {"head": "point"}
    chain = graph.model_nodes()
    shapes = graph.infer_shapes()
    input_shape = list(shapes[chain[0].instance_id])
    _t, trainer = _picked(graph, ("train.trainer",))
    trainer = cat.resolved("train.trainer", trainer)
    _l, loader = _picked(graph, ("prep.dataloader",))
    loss_node, _lp = _picked(graph, tuple(POINT_LOSSES))
    head = params.get("head", "point")
    if head != "point" and loss_node is not None:
        notes.append(f"{loss_node.definition().display_name} is ignored: the {head} head "
                     "trains with its own loss")
    opt, opt_params = _picked(graph, cat.OPTIMIZER_IDS)
    optimizer = ("torch.optim.Adam(params, lr=0.001)" if opt is None else
                 cat.render(opt.type_id, cat.resolved(opt.type_id, opt_params), "pytorch")
                 .replace("model.parameters()", "params"))
    sched, sched_params = _picked(graph, cat.SCHEDULER_IDS)
    name = sanitize_identifier(graph.name)
    model_code = generate(graph, "pytorch")
    from ai_made_easy.core.training.generate import own_loop_requirements

    return {
        "requirements": own_loop_requirements(
            model_code, ("pandas",) if dataset["block"] == "data.forecast_csv" else ()),
        "title": graph.name, "filename": f"{name}_train_pytorch.py", "name": name,
        "notes": notes, "data_comment": _data_comment(dataset),
        "model_label": model.definition().display_name if model else "custom layers",
        "dataset": dataset, "window": int(dataset["window"]),
        "horizon": int(dataset["horizon"]), "stride": int(dataset["stride"]),
        "season": int(dataset["season_length"]), "val_windows": int(dataset["val_windows"]),
        "test_windows": int(dataset["test_windows"]),
        "head": head, "quantiles": list(quantile_levels(params)) or [0.5],
        "point_loss": POINT_LOSSES.get(loss_node.type_id, "mse") if loss_node else "mse",
        "input_shape": input_shape, "trainer": trainer,
        "batch_size": int(loader.get("batch_size") or 0) or int(trainer["batch_size"]),
        "model_code": _strip_main(model_code),
        "data_code": runtime.DATA_CODE, "metrics_code": runtime.METRICS_CODE,
        "plot_code": runtime.PLOT_CODE, "optimizer_expr": optimizer,
        "scheduler_expr": (cat.render(sched.type_id, cat.resolved(sched.type_id, sched_params),
                                      "pytorch") if sched else None),
        "scheduler_step": cat.COMPONENTS[sched.type_id].meta["step"] if sched else None,
    }


def _data_comment(dataset: dict) -> str:
    if dataset["block"] == "data.synthetic_series":
        return (f"{dataset['n_series']} generated series of {dataset['length']} steps "
                f"(season {dataset['season_length']})")
    return f"{dataset['path']} (target '{dataset['target_column']}')"


def render(graph: Graph, _spec, framework: str) -> str:
    return _env.from_string(TEMPLATE).render(**context(graph, framework))


def register() -> None:
    from ai_made_easy.core.training.generate import register_trainer

    register_trainer("forecasting", render, needs_spec=False)
